### ISSUE TITLE
All commands suggested to default players

### ISSUE THREAD

**Issue by Federe76** [EngineHub/WorldEdit#1260]
I'm starting a server (MCv 1.15.2 on Paper), nad when testing as a default user (alt account) I noticed that the chat input suggests all of WE commands to the player, who doesn't have any permissions regarding WE.

To reproduce:
Just typing a "/" suggests all commands.

Expected behavior:
To show players only commands that they have permissions for. In this case, to not show any.

![image](https://user-images.githubusercontent.com/62208477/76702651-1f127c00-66aa-11ea-8c3c-db567204a5d6.png)

Additional: I don't want to have to tell players to disable chat suggestions client-side, and this would also disable command suggestions that I DO want them to see.

**Comment by wizjany** [comment]
> Just typing a "/" suggests all commands.
no it doesn't, it suggests 3 commands and their aliases there...
> To show players only commands that they have permissions for
that is the behavior you're currently observing

**Comment by Federe76** [comment]
What about the screenshot?

**Comment by wizjany** [comment]
what about the screenshot? please actually try things out before just assuming random conclusions.

**Comment by Federe76** [comment]
To show players only commands that they have permissions for

that is the behavior you're currently observing

But players dont have permission for brush, so why is it showing?

**Comment by Federe76** [comment]
> what about the screenshot? please actually try things out before just assuming random conclusions.

Sorry about this, I was noticing the 3 commands per plugin.
