### ISSUE TITLE
I'm sorry, but I still have this issue

### ISSUE THREAD

**Issue by Federe76** [EngineHub/WorldEdit#1261]
I sincerely apologize, since I replied way quicker than I shoul've, but I still need help with this:

Issue: Default players are shown commands that they don't have permissions for.
MCv1.15.2 Paper
Running LuckPerms (if that helps)
As stated in the previous thread, I wasn't noticing that only three commands are suggested per plugin, but still the player doesn't have permissions for any of WE commands. How can I fix this?

Original thread:
https://github.com/EngineHub/WorldEdit/issues/1260

**Comment by wizjany** [comment]
please stop spamming our tracker with non-issues

**Comment by Federe76** [comment]
I don't intend to spam, but I do have an unintended behavior.

Please.

**Comment by octylFractal** [comment]
It seems you don't understand that those commands have no permissions attached to them. Every user has them suggested because every user can use them. It is not a bug for these to be suggested.
