### ISSUE TITLE
Can't load worldedit

### ISSUE THREAD

**Issue by DevelopmentHigh** [EngineHub/WorldEdit#1262]
**Describe the bug**
Just the plugin can't load

**To Reproduce**
none

**Expected behavior**
none

**Screenshots**
![stawtf](https://user-images.githubusercontent.com/61356848/76917379-86574880-68c3-11ea-993f-5c1d2a32e08c.png)

**Additional context**
My plugins:
![test321123](https://user-images.githubusercontent.com/61356848/76917409-9ec76300-68c3-11ea-882c-5e00ab4e77ec.png)
i try to install async world edit and they does not work, but old version works.. why?

**Comment by me4502** [comment]
AsyncWorldEdit is not supported for compatibility and safety reasons. It's also not our plugin.

**Comment by me4502** [comment]
Also you can't run WorldEdit 7 on 1.8.8, you need to use an old version.
