### ISSUE TITLE
Stair alignment messed up when copy and pasting

### ISSUE THREAD

**Issue by arit123** [EngineHub/WorldEdit#1271]
**Describe the bug**
I copy and pasted a tank including lots of stairs. When i pasted the tank, all the stairs were aligned facing one way
**To Reproduce**

1. Select region that has stairs
2. //copy
3. Move to area I wanted to paste
4. //paste

**Expected behavior**
The stairs should be aligned the same way they were in the original build

**Screenshots**
https://imgur.com/a/hDZFKMt

**Comment by wizjany** [comment]
Please ensure you're using up to date versions of WE etc.
