### ISSUE TITLE
Could not pass event AsyncTabCompleteEvent

### ISSUE THREAD

**Issue by baolam0000** [EngineHub/WorldEdit#1281]
**Versions**

WorldEdit version:
i'am using version WorldEdit 7.1.0 (1.13.2 - 1.15.2) download on bukkit webiste but when i try to use /we version it's say unknow
Platform version:
Bukkit-Official 7.1.0;8e55131
**Describe the bug**
Get random spamming on my console 
**To Reproduce**
Unknown it just randomly spamming
**Expected behavior**
Not spamming this error anymore
**Additional context**
https://pastebin.com/q8b3EV4F

**Comment by wizjany** [comment]
second report of this with protocol hacks...
really starting to think they are sending malformed tab completes.

**Comment by baolam0000** [comment]
Hope you guys could make somethings to block this spam
