### ISSUE TITLE
'/we help' doesn't list only commands the player has permission for

### ISSUE THREAD

**Issue by I-Knight-I** [EngineHub/WorldEdit#1283]
**Versions**
WorldEdit version: Bukkit-Official(7.1.0;8e55131)
Platform version: git-Paper-103 (MC: 1.15.2)

**Describe the bug**
Doing `/we help` should only list commands that the player has permission for. It instead lists all commands. 

**To Reproduce**

0. Use LuckPerms?
1. Give/Remove specific permissions from a player
2. Have the player run /we help
3. Locate the command the permission should otherwise hide

**Expected behavior**
The commands the player does not have access to should not be shown in /we help

**Screenshots**
![image](https://user-images.githubusercontent.com/26165117/78576775-10406480-7825-11ea-8ebf-31c4c6d2ad87.png)

**Additional Info**
Lemme know if anything else is needed.

**Comment by lizzyd710** [comment]
I'd be interested in taking a look if this gets accepted.

**Comment by octylFractal** [comment]
Oops, should've marked this accepted a while ago.
