### ISSUE TITLE
Error copying blocks from Project Red 2

### ISSUE THREAD

**Issue by Harchvertelol** [EngineHub/WorldEdit#1296]
**Versions**

WorldEdit version: worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
Platform version: windows 10 (java 8 update 241)
Forge: 14.23.5.2847.

**Describe the bug**
Complex constructions from wires are copied with errors.

**To Reproduce**

1. Build the construction as in the screenshots.
2. Select.
3. Copy.
4. Paste.

**Expected behavior**

Similarly construction.

**Screenshots**

Mods and versions:
File ChickenASM-1.12-1.0.2.7 and:
![image](https://user-images.githubusercontent.com/63555997/79222825-ead4db80-7e60-11ea-87b3-676c5ea19bdb.png)

By the way, last CUI version WorldEdit+CUI+Forge+Edition+2-2.2.0-mf-1.12.2-14.23.5.2768 dont working (do not understand why).
For show selection I use WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12.2-14.23.5.2768.

Bug:
Copy object:
First side:
![image](https://user-images.githubusercontent.com/63555997/79223043-499a5500-7e61-11ea-85b4-40e3283d3bc7.png)
Second side:
![image](https://user-images.githubusercontent.com/63555997/79223088-5ae36180-7e61-11ea-9da7-80be02edc11a.png)
Selecting:
![image](https://user-images.githubusercontent.com/63555997/79225143-f75b3300-7e64-11ea-8b64-298c08a02f37.png)
Pasting and... incorrect first side.
![image](https://user-images.githubusercontent.com/63555997/79225249-1f4a9680-7e65-11ea-8e64-5eb1997804f1.png)

**Additional context**

**Comment by wizjany** [comment]
1) WorldEdit CUI Forge Edition is an unofficial port containing stolen code from the original WorldEdit CUI project, and has nothing to do with us (not that the actual WE CUI project is ours either).
2) Old versions are no longer receiving support or updates. Copying mod blocks is always tenuous since they store state in odd ways.

**Comment by Harchvertelol** [comment]
Please give a link to the original mod WE CUI for version 1.12.2. Thank you!
