### ISSUE TITLE
Error copying blocks from Project Red 2 1.7.10

### ISSUE THREAD

**Issue by Harchvertelol** [EngineHub/WorldEdit#1297]
**Versions**

WorldEdit version: worldedit-forge-mc1.7.10-6.1.1-dist
Platform version: 10.13.4.1614

**Describe the bug**

When I copy and paste the construction as in the screenshots at this address (https://github.com/EngineHub/WorldEdit/issues/1296), the wires are not placed, wires drop.

**To Reproduce**

1. Create construction.
2. Selection.
3. Copy.
4. Paste.

**Expected behavior**

Similarly construction.

**Screenshots**

Screenshots this: https://github.com/EngineHub/WorldEdit/issues/1296

**Additional context**

This bug is manifested when working only with ProjectRed and WE, there are no other mods installed.

**Comment by wizjany** [comment]
dunno why you think that if a 3 year old version is unsupported, a 6 year old version suddenly will be
