### ISSUE TITLE
problems with saving schematics

### ISSUE THREAD

**Issue by MapperChan** [EngineHub/WorldEdit#1298]
**Versions**
I use WorldEdit on the forge version.
WorldEdit version:
Platform version: 1.14.4

**Describe the bug**
When writing a command "/schematic save train schematic" an error occurs and asks to look at the console. 

**To Reproduce**
/copy 
/schematic save train schematic

**Expected behavior**
I expected the usual save to the config folder

**Screenshots**
![Screenshot_50](https://user-images.githubusercontent.com/63666804/79258443-ce05cb80-7e93-11ea-8e0c-949b9feac571.png)
![Screenshot_51](https://user-images.githubusercontent.com/63666804/79258497-e4ac2280-7e93-11ea-8628-a9e229370b17.png)

**Comment by wizjany** [comment]
`This format does not support saving`

**Comment by MapperChan** [comment]
then what format will work?

**Comment by wizjany** [comment]
just leave out the format arg, the default will work.
