### ISSUE TITLE
Save the binded tools 

### ISSUE THREAD

**Issue by Ziassan** [EngineHub/WorldEdit#1305]
tl;dr Allow a way to save the tools/brushs binded inbetween sessions

Using a lot of different brushs/tools, including "complex" ones like % based spheres with masks and all, it would be very helpful to keep the tools and brushs or allow a way to save the toolbar for next time. Would really made working on big projects easier.

**Comment by wizjany** [comment]
please use the issue templates...

**Comment by Ziassan** [comment]
My bad, somehow I bypassed and didn't see the templates when I created the issue. I'm recreating it.
