### ISSUE TITLE
Error with commands Caused by: java.lang.IllegalStateException: key must be lowercase

### ISSUE THREAD

**Issue by Skiller9090** [EngineHub/WorldEdit#1310]
**Versions**
WorldEdit version: Very lasted build (v7.2.0-SNAPSHOT+4982-df3b373)
Platform version: 1.15.2

**Describe the bug**
One player on my minecraft server runs a worldedit command it it spits out errors.
Error Log: https://pastebin.com/3k3bgWBF

**Expected behavior**
Should execute the command such as //wand but doesn't.

**Comment by wizjany** [comment]
you set an invalid wand item in your config

**Comment by Skiller9090** [comment]
oh?
but this only happens for one person?

**Comment by Skiller9090** [comment]
![image](https://user-images.githubusercontent.com/37740659/80008270-6f59d680-84bf-11ea-9f0d-d282251fd004.png)

**Comment by wizjany** [comment]
somehow an invalid item got into their session file (worldedit/sessions folder).

**Comment by Skiller9090** [comment]
no i checked there too and is what is should be

**Comment by Skiller9090** [comment]
![image](https://user-images.githubusercontent.com/37740659/80008667-f60eb380-84bf-11ea-9860-cee6f077a282.png)
player with the error session

**Comment by wizjany** [comment]
checked the line number - it's the config. https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/session/SessionManager.java#L225
if you're sure your config *file* is correct, that means something is making it invalid after load.

**Comment by Skiller9090** [comment]
ok thank you, not a worldedit bug then, tho it probably should have some kind of way to detect the error and then rewrite config where it isnt right ?

**Comment by wizjany** [comment]
dunno, suppose we could catch that exception and rethrow as invalidtoolbind so you get a "nicer" warning message. wouldn't help figure out why the item is changing though, but will tell you what it's being changed too at least.

**Comment by Skiller9090** [comment]
yeah and then also send it as a warning furthermore you could then set the invalid item to the default wooden_axe and then it would also allow the code to continue on

**Comment by Skiller9090** [comment]
also i dont know if this is caused by the same error, i assumed but it also happens when the player changed game mode ill send the log, (different error)

**Comment by Skiller9090** [comment]
https://pastebin.com/pvdkvQ2H
tho if it is the same error i dont know why the gamemode changed would be effected by this?
that would be something to also fix because errors shouldnt be spat out at non-worldedit commands

**Comment by wizjany** [comment]
what's nav-wand set to in your config? also would you mind joining discord (https://discord.gg/enginehub), easier to discuss there

**Comment by Skiller9090** [comment]
Closed Due to not plugin code error
