### ISSUE TITLE
Bug with Blocks with inventory.

### ISSUE THREAD

**Issue by MaxWarsNicht** [EngineHub/WorldEdit#1312]
Block at -47, 88, 314 is Block{minecraft:stone} but has net.minecraft.server.v1_15_R1.TileEntityDispenser@4ce5b052. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

This happens with all kinds of blocks with Inventory

**Comment by wizjany** [comment]
1) you didn't follow the template
2) you can ignore this, nothing is broken, bukkit just likes making noise
