### ISSUE TITLE
//Regen freezes server after second attempt to regen witch hut during QWH testing. no crash log.

### ISSUE THREAD

**Issue by usafphoenix** [EngineHub/WorldEdit#1313]
**Versions**

WorldEdit version:
Platform version: Forge 31.1.46 for MC 1.15.2

**Describe the bug**
Attempting to build Quad-witch hut in seed: 6546194431633768665, was getting non-witch mob spawns so attempted to revert one platform back to original area and continue debugging the design. I moved the platforms up one....down one...etc....discovered i had to raise all levels of the platform up by one. without restarting the server, i later reverted same area back to witch hut when i i thought i had gotten off the axis by one in ANOTHER direction. area did reset to the witch hut (was small cuboid, only 7x9x8), it did regen the structure, but the server FROZE after. no commands (even /kill) would take. the server had frozen. 

**To Reproduce**

1. ...I'm really not sure. This behavior occured after hours of ingame "Scratching-head" moments trying to work out why i was getting skeletons in a witch hut farm. I'd guess the method to reproduce might be: destroy area around witch hut creating a perimeter, alter witch hut structure blocks into the beginnings of a witch hut farm.... use //regen in cuboid to restore original witch hut... move the platforms up or down by one to see if the correct spawning platforms needed to be raised or lowered to get only witch spawns... discover that didn't work so attempt //regen once again.....and see if the server freezes? but that's basically what's happening. the first time i used //regen it worked fine...after that first regen it freezes the server.

**Expected behavior**
I expected it to delete player placed blocks and regenerate the selected area (wasn't full chunk, was only a small cuboid less than 10x10x10.

**Screenshots**

**Additional context**
I have also since rebooted the server between //regen attempts but it continues to freeze the server on subsequent attempts made on any area that had already had the //regen method used (attempts after the first successful regen) This leads me to the hypothesis that this function may not work correctly after the first time but i can't think of why that may be. 
Unfortunately it isn't "Crashing" so i cant investigate what's actually causing the server to freeze up...only that after the structure (or area) is regenerated the server then freezes. item entities on the ground can't be picked up by a player, commands don't work, and interaction with tile entities don't work (can't open chests, etc).

**Comment by wizjany** [comment]
It's an issue with regen being a huge hack and locking up the structure gen iirc. If you're on a non-singleplayer platform the watchdog will kill the server eventually, but singleplayer doesn't have a watchdog. iirc someone provided the stacktrace where it locked in discord at some point (albeit on bukkit, on which note it doesn't reproduce on paper I think?).
anyway there wasn't any good solution from what I remember, probably best to use delchunks + restart or snapshot restore if you have backups.

**Comment by usafphoenix** [comment]
alright :'( if there was a way for me to provide more info and help look for a solution i'd be willing to if it'd make the mod better.  but other than seeing a crash log myself i don't know where to go from there haha

**Comment by octylFractal** [comment]
I suspect this has been fixed in 7.2.0 dev builds with the regen rewrite. This did not make it to previous versions of the adapters yet, but contributions are welcome to https://github.com/EngineHub/worldedit-adapters to backport the changes, which should be rather effortless besides the name changes.

**Comment by octylFractal** [comment]
Closing as this appears fixed.
