### ISSUE TITLE
Paper anti-xray doesn't update blocks neighboring worldedits

### ISSUE THREAD

**Issue by TorSkiZ** [EngineHub/WorldEdit#1315]
**Versions**
WorldEdit version: worldedit-bukkit-7.1.0
Platform version: git-Paper-211 (MC: 1.15.2)

**Describe the bug**
I have issue with "/br smooth" command. 

**To Reproduce**
1. I really don't know why this is happening, but this issue appeared when I installed some plugins. List of them attached below in "Additional context" section.

**Expected behavior**
Only stone without any ores.

**Screenshots**
https://www.youtube.com/watch?v=sn6lzADzS4k

**Additional context**
AuthMe-5.6.0-SNAPSHOT
EasyWhitelist
EssentialsX-2.17.2.0
EssentialsXChat-2.17.2.0
EssentialsXSpawn-2.17.2.0
LuckPerms-Bukkit-5.0.72
ProtocolLib
SkinsRestorer 13.7.2
Skript 2.4.1
Vault

**Comment by wizjany** [comment]
Are you using Paper's anti-xray?

**Comment by TorSkiZ** [comment]
Yes. On "engine-mode 2".

**Comment by wizjany** [comment]
Yea that's how antixray works. sends fake blocks to the client. Not really sure if we can/want to include forcing updates for that stuff on our end or not. Probably needs some consideration.

**Comment by TorSkiZ** [comment]
I disabled it and it works! Thank You!
