### ISSUE TITLE
CraftScript import io package

### ISSUE THREAD

**Issue by oganexon** [EngineHub/WorldEdit#1317]
**Versions**
WorldEdit version: 1.6
Platform version: Forge 1.12.2

I can import any package but those in `io` produce an error.

**To Reproduce**
```javascript
importPackage(Packages.com.sk89q.worldedit) //works
importPackage(Packages.com.randompackage) //works

importPackage(Packages.io.github.terra121) //doesn't work
importPackage(Packages.io.randompackage) //doesn't work
```

**Expected behavior**
Should import every package

**Screenshots**
console output:
```
Java class
"net.minecraft.network.play.server.SPacketMultiBlockChange"
has no public instance field or method named "github"
```

**Comment by wizjany** [comment]
Old versions are generally unsupported, unless someone else wants to backport https://github.com/EngineHub/WorldEdit/commit/5277f99bf28d57ada505dedfb1c425948bcc1c84 to the 1.12.2 branch

**Comment by octylFractal** [comment]
If someone wants to they can open a PR, but I'm not going to consider this an active issue.
