### ISSUE TITLE
Command /repl or /tool repl doesn't copy/paste completely

### ISSUE THREAD

**Issue by Anonymio** [EngineHub/WorldEdit#1318]
Hello

Version Bukkit-Official(7.2.0-SNAPSHOT+4974-d260185
Server 1.15.2

A little "bug" with /repl or /tool repl
For an example:
If I /repl 1 and copy the "top" of a piston and paste on a bloc it erases the bloc but dont put the top of piston
But if i test it with the bottom of a piston, it kinda works (2-3clics to paste correctly)

Doesn't work anymore with stair (corner), top/bottom of a door..

Can anyone test and confirm ths ?

**Comment by wizjany** [comment]
Doesn't sound like this has anything to do with the repl tool. It's expected for double-blocks to not be able to exist without their other half, and squarely in minecraft code. You can try using fast mode toggles to suppress validation and so on, but that's not really WorldEdit's problem.
Also please use the template.

**Comment by Anonymio** [comment]
It was working this way in the previous version..

**Comment by Anonymio** [comment]
![2020-04-26_15 22 44](https://user-images.githubusercontent.com/54781729/80311695-6af42d00-87e1-11ea-9894-cf3abd83bae7.png)
![2020-04-26_15 23 43](https://user-images.githubusercontent.com/54781729/80311696-6c255a00-87e1-11ea-93f0-b2bbcfa8bbc0.png)
![2020-04-26_17 14 04](https://user-images.githubusercontent.com/54781729/80311698-6cbdf080-87e1-11ea-9d55-bffe709afde4.png)

**Comment by wizjany** [comment]
Did you actually read what I said?
