### ISSUE TITLE
WorldEdit Files 7.0.1 Not Showing Up

### ISSUE THREAD

**Issue by BuggyAl** [EngineHub/WorldEdit#1319]
WorldEdit version: 7.0.1
Platform version: Bukkit

I am trying to install world edit onto my server but when I upload the jar file into the plugins folder, the folder that appears for world edit DOES NOT have any files inside it, which includes the config. Also when I am in-game, the plugin does not show and the commands are not there.

1. Download the file
2. Upload it into the plugins file
3. Restart the server 
*NOTE* I am running the server on CloudNode

The folder that was created for WorldEdit receives all files including the config.yml and the commands show up in-game.

- https://user-images.githubusercontent.com/64368488/80312520-2a79bc80-87ab-11ea-8d88-e5e1f8259a6c.png
-https://user-images.githubusercontent.com/64368488/80312565-690f7700-87ab-11ea-90bf-28ab12d4286e.png
-https://user-images.githubusercontent.com/64368488/80312605-9825e880-87ab-11ea-9839-ad39d6637678.png

**Comment by octylFractal** [comment]
1) You're out of date, try updating to 7.1.0
2) WorldEdit is working fine for many others, so I doubt this is a bug in WorldEdit. If the issue persists after upgrading, come to our Discord instead so we can take a closer look.
