### ISSUE TITLE
Bukkit Blocks set incorrectly when replaced

### ISSUE THREAD

**Issue by harry0198** [EngineHub/WorldEdit#1320]
**Versions**
WorldEdit version: 7.1.0
Platform version: Bukkit-Official(7.1.0;8e55131)
Server Ver: Tuinity - Latest ver as of writing (Fork of Paper), 1.15.2, API version 1.15.2-R0.1-SNAPSHOT

**Describe the bug**
When replacing some blocks, e.g carpet, with entities that can contain items (chest, hopper etc) in the console **and then undo the change**, it produces this in the console: [11:06:24 ERROR]: Block at 76, 72, -2,339 is Block{minecraft:gray_carpet} but has net.minecraft.server.v1_15_R1.TileEntityChest@8700661. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

**To Reproduce**
1. Place carpet on floor
2. Select the carpet with wand
3. //set chest
4. //undo
5. Check console

**Expected behavior**
Console should not log the error in blocks

**Screenshots**

Not applicable

**Additional context**

I am in a multiverse - created world, separate to minecrafts standard.

**Comment by wizjany** [comment]
#1312
