### ISSUE TITLE
Biome brush

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#1322]
**Is your feature request related to a problem? Please describe.**
It's hard to brush biomes with the clipboard brush. It requires a lot of setup for a simple operation.

**Describe the solution you'd like**
`//brush biome forest`

**Describe alternatives you've considered**
See problem above.

**Comment by darius-leong** [comment]
What does the //brush biome command do?

**Comment by octylFractal** [comment]
Use the Discord for questions.

**Comment by octylFractal** [comment]
Nothing, yet. It's a proposed feature.
