### ISSUE TITLE
Categories ignore material blacklist

### ISSUE THREAD

**Issue by MegaNarwhal** [EngineHub/WorldEdit#1323]
**Versions**

WorldEdit version: Tested on release 7.1.0;8e55131 and build 4990 (7.2.0-SNAPSHOT+4990-ba91dff)
Platform version:
------------------ Platforms ------------------
* Bukkit-Official(7.1.0;8e55131)

---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**Describe the bug**

Material categories (e.g. `##portals`) ignore the material blacklist in the config.yml. `//set nether_portal` will be blocked while `//set ##portals` will work despite nether portal being one of the blocks in the category.

**To Reproduce**

1. Add minecraft:nether_portal to limits.disallowed-blocks in the config.yml
2. Make a selection
3. Type `//set ##portals`

**Expected behavior**

The command should be denied, since `//set nether_portal,end_portal,end_gateway` has the same result and is denied.

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
not a bug

**Comment by octylFractal** [comment]
To explain further, disallowed blocks is a simple filter on the input parser to prevent accidentally setting weird blocks. It doesn't work with anything but the basic block pattern, and if you're using categories as a pattern it's assumed you know what you're doing. I don't see it as necessary to prevent accidents.
