### ISSUE TITLE
Max Blocks Changed only 32000

### ISSUE THREAD

**Issue by real1lover** [EngineHub/WorldEdit#1324]
Bukkit..running
WorldEdit version:7.1
Platform version:15.2

HELP, love World edit but this is a problem.

There is no way to change the max block changed. I have changed it in the config and also in world //limit and still nothing. It will only let me do 32000. That is a small house and would take me forever to clear some space. It use to work and I could set it up for a ton of blocks, now only 32000.

Let me set the amount of block and let me do more then 32000->
HELP, your fan MIKE

**Comment by wizjany** [comment]
//limit and the config are the only ways WE limits things. Potentially you have something else imposing limits. Please join the discord for general support questions.
