### ISSUE TITLE
//setbiome not working properly inside biome mask

### ISSUE THREAD

**Issue by Shadow82828** [EngineHub/WorldEdit#1328]
WE Version: tested on 7.1 and 7.2.0-SNAPSHOT-dist.jar
System: Spigot-Bukkit
Minecraft Version: 1.15.2

In order to replace a biome with another, i tried the biome mask.
After making my selection, I used //gmask $taiga to only affect the taiga biome and then //setbiome forest so as to change the entire taiga biome to a forest one.

I left and rejoined the server, to see the effect. In general, the replacing works quite well and most of the taiga biome was replaced by a forest biome. Although, there are also quite  afew spots that remained taiga. It gets worse, when for example a river biome runs through the taiga; many parts of the river get changed into forest as well, although the mask should prevent them from being affected. Interestingly, only some prts of the river are affected, not all.

I tried using the biome mask with //set and //replace. With those two, he can clearly make out the biome borders and places blocks exactly within the specified mask (biome). Every block is matching.

If I somehow misunderstood something, I am sorry to bother. But to me it seems like a bug.

**Comment by me4502** [comment]
Is this on 1.15?

Do note that biomes now do not exist in every chunk, but are stored for 4x4x4 sections of the world. MC then does some mixing to blend the biomes together.

**Comment by Shadow82828** [comment]
> 
> 
> Is this on 1.15?
> 
> Do note that biomes now do not exist in every chunk, but are stored for 4x4x4 sections of the world. MC then does some mixing to blend the biomes together.

Ye I forgot to mention the version... 1.15.2... my bad.
Oh so that means there are no clear biomes for every single blocks anymore ? Meaning that my small river has some spaces where there isnt even a river biome left ?

**Comment by me4502** [comment]
Yeah, basically - biomes aren't as controllable now outside of the 4x4x4 sections. Especially as MC has some weird blending that is based on the seed, making it rather random even inside the 4x4x4 area

**Comment by Shadow82828** [comment]
> 
> 
> Yeah, basically - biomes aren't as controllable now outside of the 4x4x4 sections. Especially as MC has some weird blending that is based on the seed, making it rather random even inside the 4x4x4 area

Oh lord... thank you very much for that (insanely fast) reply. Sorry to bother !
