### ISSUE TITLE
Allow copying of region corner coordinates from //size to clipboard

### ISSUE THREAD

**Issue by Shadow82828** [EngineHub/WorldEdit#1329]
It would be awesome if there were a command, that just pastes the coordinates of the corners of your (cuboid) selection to your cliboard. You basically do your selection, write //xywhatever and then you can use Ctrl + V to paste the corner coordinates into a command block for example.

I hope you can't do this already... but I didnt find something.

**Comment by wizjany** [comment]
//size does this already, albeit not copy-able.

**Comment by octylFractal** [comment]
We could just make that click-to-copy, pretty sure that's a text feature.

https://minecraft.gamepedia.com/Raw_JSON_text_format
> "copy_to_clipboard": Copies  value to the clipboard.

**Comment by wizjany** [comment]
copy_to_clipboard is new to 1.15. unsure what'll happen if that goes to old clients, since WE still supports older versions for now.
suggest_command will put the text in the chat bar though, from where it can be copied. that's what i'm doing atm in WG for copying UUIDs from region info.

**Comment by Shadow82828** [comment]
> 
> 
> //size does this already, albeit not (in-game) copy-able.

Ye this is somehow the issue. It would be very useful especially for command blocks.
