### ISSUE TITLE
Loading schematic from api (doors/blocks mods)

### ISSUE THREAD

**Issue by michalk2k04** [EngineHub/WorldEdit#1331]
Hello :D 

WorldEdit version: WorldEdit 6.1.9 (up to MC 1.12.2)
Platform version: CatServer-5897fa9 (forge 1.12.2 2847)

Loading blocks from schematic via api is a problem. 
 
If it loads the schema via the command, everything is ok and as api it doesn't load properly.

No error in console/chat.

![2020-04-29_12 39 18](https://user-images.githubusercontent.com/35611019/80985883-162f6280-8e30-11ea-8a1f-569cd2408727.png)
![2020-04-29_12 39 20](https://user-images.githubusercontent.com/35611019/80985886-16c7f900-8e30-11ea-92ed-331143c16f95.png) 
![2020-04-29_12 39 25](https://user-images.githubusercontent.com/35611019/80985835-0a43a080-8e30-11ea-8504-06773d072e85.png)
![2020-04-29_12 40 08](https://user-images.githubusercontent.com/35611019/80985837-0b74cd80-8e30-11ea-994d-12c4004a81b2.png)
![2020-04-29_12 40 11](https://user-images.githubusercontent.com/35611019/80985841-0ca5fa80-8e30-11ea-9993-a1a9d66e98a4.png)
![2020-04-29_12 40 14](https://user-images.githubusercontent.com/35611019/80985847-0dd72780-8e30-11ea-87bf-706d726adf0b.png)
![2020-04-29_12 40 16](https://user-images.githubusercontent.com/35611019/80985849-0e6fbe00-8e30-11ea-8748-58ce35284f81.png)
![2020-04-29_12 40 20](https://user-images.githubusercontent.com/35611019/80985851-0f085480-8e30-11ea-99a0-97313244d4fd.png)
![2020-04-28_13 17 05](https://user-images.githubusercontent.com/35611019/80985852-0fa0eb00-8e30-11ea-84ec-573d53e7165f.png)
![2020-04-28_13 17 10](https://user-images.githubusercontent.com/35611019/80985854-10398180-8e30-11ea-8fb9-77341630af75.png)
![2020-04-28_13 17 20](https://user-images.githubusercontent.com/35611019/80985856-10d21800-8e30-11ea-9c7c-59c84443d2c1.png)
![2020-04-28_13 17 25](https://user-images.githubusercontent.com/35611019/80985859-116aae80-8e30-11ea-8d21-29ec5f4779fb.png)
![2020-04-28_13 17 39](https://user-images.githubusercontent.com/35611019/80985861-12034500-8e30-11ea-8670-1f8cefff88af.png)
![2020-04-28_23 07 12](https://user-images.githubusercontent.com/35611019/80985863-129bdb80-8e30-11ea-9e83-7aac366f43b4.png)
![2020-04-28_23 07 13](https://user-images.githubusercontent.com/35611019/80985865-13347200-8e30-11ea-8e8b-51994011451d.png)
![2020-04-28_23 07 15](https://user-images.githubusercontent.com/35611019/80985866-13cd0880-8e30-11ea-90cc-95c91aa6b023.png)
![2020-04-28_23 07 16](https://user-images.githubusercontent.com/35611019/80985869-14659f00-8e30-11ea-981b-aead0370f21e.png)
![2020-04-29_12 39 07](https://user-images.githubusercontent.com/35611019/80985873-14659f00-8e30-11ea-95db-de6c21b6b0c7.png)
![2020-04-29_12 39 10](https://user-images.githubusercontent.com/35611019/80985874-14fe3580-8e30-11ea-9511-b2f7c7de23e2.png)
![2020-04-29_12 39 12](https://user-images.githubusercontent.com/35611019/80985875-1596cc00-8e30-11ea-958a-75e1180c6105.png)
![2020-04-29_12 39 15](https://user-images.githubusercontent.com/35611019/80985878-1596cc00-8e30-11ea-97f3-e9fce67724a9.png)

**Comment by michalk2k04** [comment]
Need more info ?

**Comment by wizjany** [comment]
unsupported version/platform. hybrid servers are known to generally be a broken pain, nor are we interested in supporting old versions anymore.

**Comment by michalk2k04** [comment]
> unsupported version/platform. hybrid servers are known to generally be a broken pain, nor are we interested in supporting old versions anymore.

It's interesting because even on a regular vanilla there is a problem with the door. Old version, how should I understand it? 1.12.2 is not old.As far as I know, you just don't want to fix it. Similar bugs have been reported.Hybrids are broken? Interesting because normally the schema are loaded correctly only api you did not do it correctly would be good documentation: P

**Comment by me4502** [comment]
1.12.2 is definitely old, we only support the latest version of WorldEdit, and the MC versions that it supports.

And yes, hybrid server implementations are known to not implement the Bukkit API correctly. So we don't support them as generally, it's not our issue.

If it works fine when using commands but not through your API usage, it's an issue with your plugin that's using the API.

**Comment by michalk2k04** [comment]
I'd love to wait for someone to move and fix this api. And you won't look for excuses for "hybrid servers are known to generally be a broken pain"



> 1.12.2 is definitely old, we only support the latest version of WorldEdit, and the MC versions that it supports.
> 
> And yes, hybrid server implementations are known to not implement the Bukkit API correctly. So we don't support them as generally, it's not our issue.
> 
> If it works fine when using commands but not through your API usage, it's an issue with your plugin that's using the API.

Worldedit just doesn't load blocks correctly via api.

From what I know, for plugin to load blocks / items from mowdów must do it specifically. The command does it correctly but api does not. Please do not look for excuses because I use a hybrid. On vanilla it is the same but with doors etc.



It's not the hybrid's fault, although I thought so at first.

**Comment by michalk2k04** [comment]
By the way, look how many people use 1.12.2 and how many the latest version of the month.

**Comment by me4502** [comment]
Yep, that affirms what I said. https://bstats.org/global/bukkit

**Comment by me4502** [comment]
As for the API, the commands use the API. If the API didn't work, the commands wouldn't work. Therefore it's an issue with whatever plugin is using the API.

**Comment by michalk2k04** [comment]
I can at least the file responsible for the /paste command
