### ISSUE TITLE
Diamond sword bug with /navwand and I can't disable it.

### ISSUE THREAD

**Issue by Macintosh-Fan** [EngineHub/WorldEdit#1333]
I type: /navwand or /tool navwand and I get this: "worldedit.tool.navwand.equip". How do I disable it?
![image](https://user-images.githubusercontent.com/50642934/81034778-fce8df00-8e4c-11ea-886b-665c936344a8.png)

**Comment by wizjany** [comment]
already fixed in dev

**Comment by Macintosh-Fan** [comment]
What do I do to fix @wizjany?

**Comment by octylFractal** [comment]
Update to a dev/experimental build (same thing, different names), or wait for 7.2.0 to drop.
