### ISSUE TITLE
//setbiome not respecting the set area

### ISSUE THREAD

**Issue by PGMvlaar** [EngineHub/WorldEdit#1334]
**Versions**
WorldEdit version: worldedit-fabric-mc1.15.2-7.1.0
Platform version: Fabric Loader 0.7.9 - 1.15.2

**Describe the bug**
After //setbiome is used, sometimes columns at the edge of the selection are still the old biome, and sometimes columns just outside the selection turned into the new biome.

**To Reproduce**
1. Select a region in any way: //wand, //pos1 and //pos2, or //chunk
2. //setbiome <biome>
3. Relog.
4. With F3 open, check the biomes as you walk over the edge of your selection.

**Expected behavior**
I expect to have all columns in the selection be changed to the new biome, and all columns outside of the selection to not be touched.

**Additional context**
I assume this is to have 'natural' biome borders, but then it would be assumed there is a boolean parameter to turn that on/off, or an integer to select the intensity of this randomness.

**Comment by me4502** [comment]
This isn’t a worldedit issue, that’s just how biomes work in Minecraft
