### ISSUE TITLE
ERROR Could not pass event PlayerMoveEvent to WorldGuard v7.0.2-SNAPSHOT;bf2593e

### ISSUE THREAD

**Issue by GameFreakBaree** [EngineHub/WorldEdit#1336]
07.05 15:51:41 [Server] ERROR Could not pass event PlayerMoveEvent to WorldGuard v7.0.2-SNAPSHOT;bf2593e
07.05 15:51:41 [Server] INFO java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
07.05 15:51:41 [Server] INFO at com.mewin.WGRegionEvents.WGRegionEventsListener.updateRegions(WGRegionEventsListener.java:113) ~[?:?]
07.05 15:51:41 [Server] INFO at com.mewin.WGRegionEvents.WGRegionEventsListener.onPlayerMove(WGRegionEventsListener.java:76) ~[?:?]
07.05 15:51:41 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor456.execute(Unknown Source) ~[?:?]
07.05 15:51:41 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1141) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1047) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-260]
07.05 15:51:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by wizjany** [comment]
1) use the issue template
2) this is the worldedit tracker
3) this isn't even a worldguard issue.
