### ISSUE TITLE
java.lang.ThreadDeath: null in console during server lock

### ISSUE THREAD

**Issue by dodofan** [EngineHub/WorldEdit#1337]
**Versions**

WorldEdit version: * Bukkit-Official(7.1.0;8e55131)
Platform version: Paper version git-Paper-259 (MC: 1.15.2)

**Describe the bug**

I tried //replacenear for 1000 blocks and the server crashed probably due to lag, but right before it closed, I saw the server tell me to "Please report this bug," so here I am.

**To Reproduce**

1. //repleacenear 1000 () ()

**Expected behavior**

I'm unsure. Maybe the blocks to be replaced?

**Screenshots**

I only have a pastebin of the console. https://pastebin.com/JFLKAC29

**Additional context**

None

**Comment by wizjany** [comment]
please use discord for support
