### ISSUE TITLE
Allow block tags with the disallowed-blocks option

### ISSUE THREAD

**Issue by JasonHorkles** [EngineHub/WorldEdit#1340]
**Is your feature request related to a problem? Please describe.**

There are so many blocks like flowers that you'd have to manually add to the list for it to properly block so it's annoying when you have to add each one

**Describe the solution you'd like**

The ability to add block tags would be nice because you can add the single option of #flowers and it will block all flowers

**Describe alternatives you've considered**

Not really considered anything else

**Additional context**

Block tags can be found [here](https://minecraft.gamepedia.com/Tag)

**Comment by wizjany** [comment]
#1323 please use search
