### ISSUE TITLE
CJK characters garbled

### ISSUE THREAD

**Issue by LeonXu98** [EngineHub/WorldEdit#1342]
**Versions**

WorldEdit version: 7.1.0;8e55131
Platform version: Fabric-Official

**Describe the bug**

CJK characters output from WorldEdit is garbled.

**To Reproduce**

1. Set Minecraft Language to a CJK language.
2. Type a WorldEdit command which will output CJK characters, such as `/brush cylinder stone 1 1`
3.You will found CJK characters from WorldEdit is garbled.

**Expected behavior**

CJK characters should display normally.

**Screenshots**

![2020-05-13_16.38.18.png](https://i.loli.net/2020/05/13/753EtBkLK9JnldG.png)

**Additional context**

**Comment by wizjany** [comment]
Already fixed in dev builds.
