### ISSUE TITLE
Command Blocks in a Region

### ISSUE THREAD

**Issue by BeastModeNinja** [EngineHub/WorldEdit#1346]
I am trying to set up a parkour region and have the bottom layer of blocks kill the player once they touch it (with them respawning at the start of the parkour.

When I set all of it up, the command block only kills me and another staff who both have bypass on for the region. It does not kill someone who is not bypassing. Here is the command I am using in the command block. My guess is that it is some flag or something I do not know about which does not allow command blocks to function.

Any help is much appreciated!

Here is the command: /execute as @a at @s if block ~ ~-1 ~ minecraft:end_portal_frame run kill @s

**Comment by octylFractal** [comment]
How is this a WorldEdit question? Looks completely unrelated.

**Comment by BeastModeNinja** [comment]
It is a WorldGuard question but the WorldGuard bukkit page sent me here when I cliked on issues...That is why I closed and reopened it because I noticed it was WorldEdit but this is where the page took me

**Comment by octylFractal** [comment]
Neither of the issue tracker links in the WG Bukkit page link to WorldEdit. Regardless, remake this issue over there, and use the templates this time.
