### ISSUE TITLE
WorldEdit doesn't recognize some blocks.

### ISSUE THREAD

**Issue by ClioBus72** [EngineHub/WorldEdit#1351]
**Versions**
WorldEdit version: 6.1.10
Platform version: Forge 1.12.2 14.23.5.2847

**Describe the bug**
WorldEdit can not figure out what block it is, when it's the exact block.

**To Reproduce**
1. Select a random area.
2. Do //set polished_andesite

**Expected behavior**
The selected area turns into the block.

**Screenshots**
![2020-05-29_20 07 40](https://user-images.githubusercontent.com/66147136/83314402-344a7180-a1e8-11ea-88e3-0b68c24fde8c.png)

**Additional context**
N/A

**Comment by me4502** [comment]
Those blocks don’t exist in 1.12.2, they’re data values on stone and other blocks.
