### ISSUE TITLE
Server crash when using /snow with a parameter

### ISSUE THREAD

**Issue by JasperDre** [EngineHub/WorldEdit#1352]
**Versions**

WorldEdit version: 7.1.0
Platform version: 1.15.2 Spigot

**Describe the bug**
Server crash after using /snow. We were using /pumpkins without issues before that while messing around.

**To Reproduce**

1. Type /snow 39
2. Server crash

**Expected behavior**
Spawn snow around the player.

**Screenshots**

**Additional context**
>.... [15:56:05 ERROR]: Current Thread: Server thread
>.... [15:56:05 ERROR]: PID: 17 | Suspended: false | Native: false | State: TIMED_WAITING
>.... [15:56:05 ERROR]: Stack:
>.... [15:56:05 ERROR]: sun.misc.Unsafe.park(Native Method)
>.... [15:56:05 ERROR]: java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:492)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:332)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:277)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_15_R2.getBlock(Spigot_v1_15_R2.java:300)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:404)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.EditSession.getBlock(EditSession.java:600)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.EditSession.simulateSnow(EditSession.java:1794)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.command.UtilityCommands.snow(UtilityCommands.java:290)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$snow(UtilityCommandsRegistration.java:532)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.command.UtilityCommandsRegistration$$Lambda$2509/917380801.run(Unknown Source)
>.... [15:56:05 ERROR]: org.enginehub.piston.CommandManager.execute(CommandManager.java:158)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486)
>.... [15:56:05 ERROR]: sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>.... [15:56:05 ERROR]: sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>.... [15:56:05 ERROR]: sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [15:56:05 ERROR]: java.lang.reflect.Method.invoke(Method.java:498)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181)
>.... [15:56:05 ERROR]: com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348)
>.... [15:56:05 ERROR]: com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55)
>.... [15:56:05 ERROR]: org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [15:56:05 ERROR]: org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$3712/1680152879.run(Unknown Source)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1224)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
>.... [15:56:05 ERROR]: java.lang.Thread.run(Thread.java:748)
>.... [15:56:05 ERROR]: ------------------------------
>.... [15:56:05 ERROR]: Current Thread: Server Infinisleeper
>.... [15:56:05 ERROR]: PID: 19 | Suspended: false | Native: false | State: TIMED_WAITING
>.... [15:56:05 ERROR]: Stack:
>.... [15:56:05 ERROR]: java.lang.Thread.sleep(Native Method)
>.... [15:56:05 ERROR]: net.minecraft.server.v1_15_R1.DedicatedServer$1.run(DedicatedServer.java:72)
>.... [15:56:05 ERROR]: ------------------------------
>.... [15:56:05 ERROR]: Current Thread: Snooper Timer
>.... [15:56:05 ERROR]: PID: 16 | Suspended: false | Native: false | State: WAITING
>.... [15:56:05 ERROR]: Stack:
>.... [15:56:05 ERROR]: java.lang.Object.wait(Native Method)
>.... [15:56:05 ERROR]: java.lang.Object.wait(Object.java:502)
>.... [15:56:05 ERROR]: java.util.TimerThread.mainLoop(Timer.java:526)
>.... [15:56:05 ERROR]: java.util.TimerThread.run(Timer.java:505)
>.... [15:56:05 ERROR]: ------------------------------
>.... [15:56:05 ERROR]: Current Thread: Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1
>.... [15:56:05 ERROR]: PID: 9 | Suspended: false | Native: false | State: TIMED_WAITING
>.... [15:56:05 ERROR]: Stack:
>.... [15:56:05 ERROR]: sun.misc.Unsafe.park(Native Method)
>.... [15:56:05 ERROR]: java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
>.... [15:56:05 ERROR]: java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
>.... [15:56:05 ERROR]: com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38)
>.... [15:56:05 ERROR]: com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
>.... [15:56:05 ERROR]: com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
>.... [15:56:05 ERROR]: com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
>.... [15:56:05 ERROR]: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [15:56:05 ERROR]: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [15:56:05 ERROR]: java.lang.Thread.run(Thread.java:748)
>.... [15:56:05 ERROR]: ------------------------------
>.... [15:56:05 ERROR]: Current Thread: Signal Dispatcher
>.... [15:56:05 ERROR]: PID: 4 | Suspended: false | Native: false | State: RUNNABLE
>.... [15:56:05 ERROR]: Stack:
>.... [15:56:05 ERROR]: ------------------------------
>.... [15:56:05 ERROR]: Current Thread: Finalizer
>.... [15:56:05 ERROR]: PID: 3 | Suspended: false | Native: false | State: WAITING
>.... [15:56:05 ERROR]: Stack:
>.... [15:56:05 ERROR]: java.lang.Object.wait(Native Method)
>.... [15:56:05 ERROR]: java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
>.... [15:56:05 ERROR]: java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
>.... [15:56:05 ERROR]: java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
>.... [15:56:05 ERROR]: ------------------------------
>.... [15:56:05 ERROR]: Current Thread: Reference Handler
>.... [15:56:05 ERROR]: PID: 2 | Suspended: false | Native: false | State: WAITING
>.... [15:56:05 ERROR]: Stack:
>.... [15:56:05 ERROR]: java.lang.Object.wait(Native Method)
>.... [15:56:05 ERROR]: java.lang.Object.wait(Object.java:502)
>.... [15:56:05 ERROR]: java.lang.ref.Reference.tryHandlePending(Reference.java:191)
>.... [15:56:05 ERROR]: java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
>.... [15:56:05 ERROR]: ------------------------------
>.... [15:56:06 INFO]: Stopping server

**Comment by me4502** [comment]
That's not a WorldEdit crash. It's the server watchdog. 

Either use `/watchdog` or update to the dev builds where it's enabled by default.

**Comment by wizjany** [comment]
You conveniently snipped out the part where it says "THIS IS NOT A BUG OR CRASH". As me4502 said, this is just the server watchdog killing the server.

**Comment by JasperDre** [comment]
Right my bad. I was able to find the actual logs which makes more sense. The console I was using only showed a few lines of the output, so I didn't see that before when a player reported it. Thanks for the quick response though!
>[15:55:05] [Server thread/INFO]: <PlayerName> issued server command: /snow 3999
>[15:55:15] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-327 (MC: 1.15.2) ---
>[15:55:15] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
