### ISSUE TITLE
WorldEdit (worldedit) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by paxjah** [EngineHub/WorldEdit#1355]
Hello, I've been getting this error to appear both server-side and within my Minecraft launcher. This error appears before crashing either.

I'm not too sure what ti is or how to fix it and can find no steps to reproduce, it seems to just randomly occur.

Any help in resolving is greatly appreciated.

**Comment by me4502** [comment]
There’s literally nothing we can say/do without the error

**Comment by wizjany** [comment]
Please use the issue template or come to discord for support questions.
