### ISSUE TITLE
extreme server problems

### ISSUE THREAD

**Issue by Blueeyestar** [EngineHub/WorldEdit#1356]
Hello, we have had huge server crashes due to worldedit. it is enough if you make // fixwater 10 and the server makes a huge error message. What can I do about it?

https://pastebin.com/RmxxBxG3

we are currently using:  WorldEdit_7.2.0-Build5023.jar

 

Paper: Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by wizjany** [comment]
something ran the spread command here. the stacktrace has nothing to do with worldedit
