### ISSUE TITLE
//undo (Number) breaks if number is higher than actions done

### ISSUE THREAD

**Issue by lSherozl** [EngineHub/WorldEdit#1357]
Version 1.15.2(Latest)

I think I found a bug, idk if it's intentional or not, If I use the brush tool, a sphere with air, and I do a bunch of spheres into the ground, then I undo, it works well, say I used the brush 10 times, and I do //undo 5 it will work, but if I go //undo 20 or go over the number of times I used the brush, it will forget what was done, and say "nothing left to undo", and even forget about it if you went //undo only once afterwards

**Comment by me4502** [comment]
That’s not a bug. There’s a limit to the history size that’s configurable in the config. If you want it to be higher, increase it. Do note that it’ll use more memory

**Comment by lSherozl** [comment]
I see so what is the option called in the config to raise the history?

**Comment by me4502** [comment]
history.size, and I don’t understand what you mean?

**Comment by lSherozl** [comment]
For example, if I use the brush 20 times right, //undo 10, it will undo 10 times for me, now I only have 10 actions that I did, but now if I go, //undo 12, it will say "nothing left to undo" which is fine because I went over the amount of actions I did, but as soon as I have went over, and I type even //undo 2, //undo 5 it does not matter how many actions I had left, it will not allow me to undo further as soon as I go over, its as if my 10 actions got erased from the history

**Comment by me4502** [comment]
I still don’t understand, what do you expect it to do once you’ve reached the end of history? If there’s nothing left to undo, there’s nothing left to undo?

**Comment by lSherozl** [comment]
Say I created a giant hole in a mountain with my brush, and it took me 12 brush edits to do that, now if I go //undo 14, it will say "nothing left to undo" because I had gone past the amount of edits, maybe I forgot how many times I used the brush, what I was hoping was to be able to exchange my number afterwards to a smaller one like //undo 10 so it can undo that hole in the mountain, but as soon as you have gone over by mistake, it will give you the "nothing left to undo" no matter how much smaller your number gets to undo, and basically your stuck with the hole in the mountain, are you just saying this is fixed by having a larger history? Sorry if this is confusing

**Comment by lSherozl** [comment]
Sorry I checked you answered my question, raising the history will allow you to undo a higher amount without that error preventing you from undoing further

**Comment by me4502** [comment]
I currently don’t have a desk so can’t check currently, but I’ll double check when I next get to a computer whether progressing the history pointer too far progresses the pointer without actually undoing the entries. I believe that’s what the issue you were experiencing there is

I’ll re-open the issue as a reminder for me to check

**Comment by lSherozl** [comment]
Okay thank you

**Comment by octylFractal** [comment]
I cannot reproduce this bug, with a `history-size=15` in the config, if you do 20 brush actions, WorldEdit correctly remembers only 15 of them, and doing `//undo 10` + `//undo 12` results in the following chat messages:
![Undid Edits Messages](https://url.octyl.net/wlflfteln1y0stz-qjcp)
And it does undo 15 brush actions, as the chat messages say. It will not undo any more actions, because WorldEdit already forgot them -- `//undo 10` doesn't allow WorldEdit to recover more of your previous brush actions. The solution here is to increase `history-size` or whatever the equivalent property is on your platform.

If you find that this is not the case, please send a video that reproduces the issue, as the given instructions are not clear enough.

**Comment by lSherozl** [comment]
I'm using world edit 1.15.2(Latest), if my history size is 15, and I do say 20 brush actions as you said, if I was to go //undo 25, basically any number higher than my actions, it will say "nothing left to undo" and worldedit forgets the 20 actions u did as well, without undoing them. Yes increasing the history-size fixed the solution for me, because now I can undo // a larger number, but the problem I was having in the beginning was not with //undo for a number smaller than my edits, it was for if I did //undo for a number larger than my edits when my history size was smaller, so I dont think its a bug either, I just think you need a larger history size, otherwise doing anything higher than 15 for //undo caused my worldedit to not undo anything, but keep giving the same message of "nothing left to undo."

**Comment by wizjany** [comment]
`world edit 1.15.2(Latest)`
still isn't a version number. 1.15.2 is a minecraft version, not a worldedit version. I think octy already demonstrated that this works fine currently.

**Comment by lSherozl** [comment]
My bad I meant this one here:  And yeah it probably works fine, maybe its just because im new to it, thanks for your time
![image](https://user-images.githubusercontent.com/65663746/84033433-130b2300-a956-11ea-8d01-4bbde7f12d36.png)
