### ISSUE TITLE
Poly Cut <Specific Block> Pastes Instead

### ISSUE THREAD

**Issue by Eniam** [EngineHub/WorldEdit#1360]
Hello,

I used //sel poly to select an area, cut a specific block (in this case, biomesoplenty:dried_sand) in an attempt to then //paste -a so I could lower a riverbed, but instead it pasted 548,912 of that specific block to the entire selection. I took screenshots, if necessary. I am on your Discord if you want more information quickly; name: Sniper_Gecko

**Comment by wizjany** [comment]
please use the template
