### ISSUE TITLE
/sp area/recur/single Some blocks do not drop

### ISSUE THREAD

**Issue by Twister1one** [EngineHub/WorldEdit#1366]
**Versions**

WorldEdit version: Bukkit-Official(7.1.0;8e55131)
Platform version: Paper version git-Paper-325 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Describe the bug**
With the /sp area/recur/single, some blocks do not drop while in the configuration the option "drop-items" and "many-drop-items" are true.
The boards, the concrete powders and many others, drop correctly but the terracota, the diorite etc ... do not drop.

**To Reproduce**
1. /sp area 10
2. destroy diorite, cobblestone...

**Expected behavior**
With the /sp area all block drops

**Additional context**
I tested with a lot of version of worldedit, 7.1, 7.2, the very last ...

**Comment by me4502** [comment]
Try updating Paper, there was a Spigot bug that would likely cause this issue

**Comment by wizjany** [comment]
This is entirely up to the server https://github.com/EngineHub/WorldEdit/blob/57d62b0bf516ad8d5f89e34208a114a5b4c76238/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java#L406
