### ISSUE TITLE
Schematic load hangs gameserver with exceedingly high CPU usage.

### ISSUE THREAD

**Issue by ipaqmaster** [EngineHub/WorldEdit#1367]
**Versions**

Java version: `openjdk version "1.8.0_232"`
Minecraft Version: `1.15.2` via `Paper-365.jar`
WorldEdit version: `worldedit-bukkit-7.1.0.jar`
Platform version: `Bukkit-Official(7.1.0;8e55131)`
Version dump:
```
[19:44:16 INFO]: WorldEdit version (unknown)
[19:44:16 INFO]: https://github.com/EngineHub/WorldEdit/
[19:44:16 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.1.0;8e55131)

[19:44:16 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**Describe the bug / Reproducing steps**

0. All other plugins disabled, `/plugins` only returns (1): WorldEdit

1. Try to load a schematic 

2. Worldedit reports `(Please wait... loading schematic.)`

3. No visual change. Game instantly slows to a crawl (One tick every 20+ seconds) and the java process is maxing out every CPU thread it can get its hands on.

**Expected behavior**
Schematic loads, can be pasted.

**Additional context**
i7 processor maxes out all 4 cores (8 threads) on this java process after starting a schematic load.

`htop` shows this particular Java PID maxing out every single CPU core to 100% as the gameserver becomes unresponsive after a few seconds.

Process must be forcibly SIGKILL'd.

**Comment by me4502** [comment]
What schematic file is this? Schematics are loaded async so this should not at all be possible unless it somehow maxed out IO

**Comment by octylFractal** [comment]
Can you provide the schematic file that's giving you trouble? Many other people load schematics in Paper without issue so I'm not sure what's happening here.

In addition, schematic loading is entirely async, and also single-threaded, so I'm not sure how it could be maxing out the CPU...

**Comment by ipaqmaster** [comment]
That's what I thought also. It makes me feel like this is some other issue.

The two schematic files I've tried are both MCEDIT_SCHEMATIC formatted but are generic uploads found on the front page of www.minecraft-schematics.com.

**Comment by ipaqmaster** [comment]
Well damn.

I copied `paper-365.jar` into a new `test/` directory with `worldedit-bukkit-7.1.0.jar` in it's plugins directory then started it vanilla... and it loaded the same schematics just fine.

I'm going to assume this is some bukkit configuration screwup on my part; sorry to waste your time like that.
