### ISSUE TITLE
Setbiome doesn't work . (WorldEdit 7.1.0)

### ISSUE THREAD

**Issue by JustTimmNL** [EngineHub/WorldEdit#1372]
WorldEdit 7.1.0 / MC 1.15

//Setbiome doesn't work. I leave and join my singleplayer world but it didn't change the biome.

It showed up the biome in 1.14 after rejoining the world but in this version it doesn't.

https://gyazo.com/079f9b00b0929ea2d9aea617b005410b

**Comment by wizjany** [comment]
how did you miss the template *twice*

**Comment by JustTimmNL** [comment]
> how did you miss the template _twice_

I used it.

**Comment by wizjany** [comment]
oh you're right. the labels are there. you just decided to delete the actual text and substitute your own in.

**Comment by JustTimmNL** [comment]
I have followed the steps that are there. Then I don't make a bug report. Find out for yourself.

**Comment by octylFractal** [comment]
Biome math is wrong in older versions. Try again with 7.2.0 dev builds.

**Comment by JustTimmNL** [comment]
Where can i find that?

**Comment by octylFractal** [comment]
builds.enginehub.org/job/worldedit

**Comment by JustTimmNL** [comment]
ty

**Comment by JustTimmNL** [comment]
those don't work either

**Comment by me4502** [comment]
If those don't work, you're doing something wrong

**Comment by JustTimmNL** [comment]
How can I do something wrong? I just download it. Put it in the mods folder, launch the game and use that command. But. It. Doesn't. Work.. It's bugged.

**Comment by me4502** [comment]
It works for literally everyone else

**Comment by JustTimmNL** [comment]
'That's just not possible.. it's the same file?! https://gyazo.com/97e42eb1706a81f6cf91e5748ac40cb1

**Comment by me4502** [comment]
Hence why I said it's probably you doing something wrong

**Comment by octylFractal** [comment]
Apologies for the mishandling of this issue, you will need to use https://builds.enginehub.org/job/worldedit/14576 in order to work with 3D biomes, OR always do `//expand vert` before setting the biomes with the newer builds. 3D biomes don't work properly on Mojang's side.

**Comment by JustTimmNL** [comment]
OMG YES it wokred. Thank you sooo much!
