### ISSUE TITLE
Compass teleport overrides the Lodestone.

### ISSUE THREAD

**Issue by DarkmanBree** [EngineHub/WorldEdit#1394]
**Versions**

**WorldEdit version:** 7.2.0 Beta 1
**Platform version:** CraftBukkit version git-Spigot-16d7899-4ff609e (MC: 1.16.1)

**Describe the bug**
When you have the permission to teleport using the Compass, It is impossible to sign your compass on a Lodestone block to turn it into a Lodestone Compass, Teleporting overrides it instead.

**To Reproduce**
1. Have the Compass teleport permission.
2. Right click a Lodestone Block with a compass.
3. You will teleport instead of signing your Compass on it.

**Expected behavior**
1. The Teleport won't happen and the Compass will become a Lodestone Compass regardless if I have the Compass Teleport permission or not.

**Screenshots**
Screenshots cannot proof this.

**Additional context**
Just a suggestion, what if the WorldEdit Wand and Compass only worked when they have specific item names on them, which you can then spawn with //wand and //compass, giving you a Wooden Axe named "Wand" in gold and Compass named "Compass" in gold while the vanilla compass and wooden axe behave like normal vanilla items?
This would fix it too.

**Comment by wizjany** [comment]
You can simply unbind your compass or change it to something else if you need to use it in a survival setting.
Things like being able to bind custom items are existing feature requests but not in the same vein as the proper solution here.
