### ISSUE TITLE
No air blocks in ravine

### ISSUE THREAD

**Issue by Hrhr77** [EngineHub/WorldEdit#1395]
**Versions**

WorldEdit version: WorldEdit 7.2.0 Beta 1 (1.13.2 - 1.16.1)
Platform version: Craftbukkit 1.16.1

**Describe the bug**

Wanted to replace air with stone in a ravine. No air is found inside ravines for minecraft 1.16.1. Air is found above ground. (screenshot below shows selection of 6 blocks horizontally across ravine but counts no air blocks with .//count air, while there should be 4)

**To Reproduce**

1. Create a world for 1.16.1
2. Go to a ravine and .//count air in a lower section of the ravine.
3. The amount of air is often 0 in ravines and some caves

**Expected behavior**

Expect to find air inside ravines.

**Screenshots**

![2020-06-27_17 25 41](https://user-images.githubusercontent.com/16170755/85925879-a8d20800-b89b-11ea-90a5-c364a61a6a9b.png)

**Additional context**

**Comment by wizjany** [comment]
cave air. please use discord for questions.
