### ISSUE TITLE
The command //setbiome isn't working in 1.16.1

### ISSUE THREAD

**Issue by PeterExec** [EngineHub/WorldEdit#1399]
**Versions**

WorldEdit version: 7.2.0
Platform version: 1.16.1

**Describe the bug**

The //setbiome doesn't work
**To Reproduce**

1. ...  I write the comamand //setbiome plains and restart my game
2. ... The selected area doesn't change, and when i restart only the place i was before left change, and it doesn't change at all, just around a chunk, and when I break a block it disappears.
**Expected behavior**

it was supossd to change de biome.
**Screenshots**

**Additional context**

**Comment by octylFractal** [comment]
Please provide your full logs, found in `logs/latest.log`.

**Comment by octylFractal** [comment]
NVM, found the bug.
