### ISSUE TITLE
Server Crashing Whenever I //set

### ISSUE THREAD

**Issue by CrafterOfArts** [EngineHub/WorldEdit#1401]
When I issue the command //set, even without any selection, the server crashes and gives me the following error message: 

http://pastie.org/p/0DjenRdi4a4uWF8an4xTED

I am currently running on the latest build of Paper 1.15.2 

Any ideas?

**Comment by octylFractal** [comment]
This is probably an issue with WG removing API, or WGRegionEvents using outdated API. Nothing to do with WorldEdit.
