### ISSUE TITLE
Schematic overwriting house1 to house2 while saving and pasting structures

### ISSUE THREAD

**Issue by akara211** [EngineHub/WorldEdit#1405]
**Versions**

WorldEdit version: Fabric-Official(7.1.0;8e55131)
Platform version: I don't know which platform - Win10 Pro?

**Describe the bug**
I have one house and a tower. I save the house as house1.schem and load it and paste it, okay. Then, I save the tower as tower1.schem and paste it and it pastes house instead of the tower.

**To Reproduce**
1. I take pos1 and pos2 for a house and copy
2. Then I type //schematic save house1
3. I use //schematic load house1 and paste it and it's everything alright
4. Then I use pos1 and pos2 for a tower and copy
5. I type //schematic save tower1
6. I use //schematic load tower1 and paste it and it pastes house1 for both of .schem files

**Expected behavior**
I expected to paste house1 as a house which was okay, but I expected to paste tower1 as a tower instead of house1.

**Screenshots**

**Additional context**

**Comment by octylFractal** [comment]
I'm going to require a video reproducing the issue for this one, because there's little chance that WorldEdit has simply become inconsistent with clipboard handling. If you can reproduce with a video, I'll look into it. Otherwise, I'll consider this to be user error.

**Comment by akara211** [comment]
> I'm going to require a video reproducing the issue for this one because there's little chance that WorldEdit has simply become inconsistent with clipboard handling. If you can reproduce with a video, I'll look into it. Otherwise, I'll consider this to be a user error.

Hmmm... I don't know what happened, but after restarting Minecraft it's working. Yesterday, it was as I wrote up there. Doubt it it was my mistake. Thanks for reaching me out!
