### ISSUE TITLE
Path is outside allowable root when saving schematics

### ISSUE THREAD

**Issue by Tom1969** [EngineHub/WorldEdit#1406]
WorldEdit version: WorldEdit 7.2.0 Beta 1
Platform version: Fabric

I try to save some schematics from my local save world, to bring it back to a new world, but if i want to save the schematic the following error comes up:

**Path is outside allowable root**

1. Select the structure 
2. Enter //copy
3. Enter //schematic save name

Don't know if it's a bug, but i'm very happy for al tipps and trickt to solve this issue.

**Comment by wizjany** [comment]
allow-symlinks in config
