### ISSUE TITLE
SuperPickaxe in area mode is not working

### ISSUE THREAD

**Issue by iOshawott** [EngineHub/WorldEdit#1407]
**Versions**

WorldEdit version: Bukkit-Official(7.2.0-SNAPSHOT+5102-732c11c)
Platform version: git-Paper-27 (MC: 1.16.1)

**Describe the bug**

SuperPickaxe in area mode breaks only 1 block (does nothing)

**To Reproduce**

1. Do //
2. Do /sp area 5
3. Break a block - Removes only 1 block

**Expected behavior**

It should breaks blocks in radius

**Screenshots**

Don't think it's needed

**Additional context**

Nothing more to add

**Comment by wizjany** [comment]
can't repro

**Comment by iOshawott** [comment]
Well, I got it. It's not working with netherite pickaxe only! @wizjany

**Comment by wizjany** [comment]
oh yea that's a thing now.
