### ISSUE TITLE
Can't manipulate large area in 1.16.1

### ISSUE THREAD

**Issue by redbrain** [EngineHub/WorldEdit#1417]
I'm using worldedit 7.2.0.beta1 in fabric. When I try to //copy a large area for a schematic (10,194,327 blocks) i get java.lang.illegalArgumentException: Can't convert other of type net.minecraft.class_2501 . The same happened when trying to //set or //replace in that area.
Screenshot:
![image](https://user-images.githubusercontent.com/42494361/86490237-b15f8e00-bd34-11ea-821a-e86ac264680b.png)

**Comment by wizjany** [comment]
please provide your full log and use the issue template
