### ISSUE TITLE
Doors don't paste in 7.2.0 Beta 1 1.16.1

### ISSUE THREAD

**Issue by MattQ012** [EngineHub/WorldEdit#1421]
Worldedit 7.2.0 Beta 1 - Fabric
Platform version: 1.16.1

**Describe the bug**
When you copy and paste doors, the doors are not pasted

**To Reproduce**
1. Copy any door or any area with doors
2. Paste the selection

**Expected behavior**
The doors should get pasted

**Screenshots**
https://imgur.com/a/VZLga5T

**Comment by octylFractal** [comment]
Duplicate of #1396.
