### ISSUE TITLE
Decoration layer doesn't regenerate correctly [1.16.1 beta 2]

### ISSUE THREAD

**Issue by solonovamax** [EngineHub/WorldEdit#1424]
# Decoration layer doesn't regenerate correctly [1.16.1 beta 2]
## Versions
WorldEdit version: 7.2.0-beta-02+d10d7d6
Platform version: Bukkit

## Describe the bug
When running //regen the decoration layer doesn't regenerate correctly.

## To Reproduce
1. Select an area with trees/grass/etc. (Basically any area works since most areas will have things generated in the decoration stage)
2. run `//regen`
3. The trees/grass/flowers/etc. are now different.

## Expected behaviour
The decoration layer doesn't change when regenerating.

**Comment by wizjany** [comment]
https://discordapp.com/channels/80853743897149440/540076527593717760/729801815046226001

**Comment by solonovamax** [comment]
Thanks for that, I didn't have time to upload any images/videos when I did it.

**Comment by me4502** [comment]
That video shows it working fine

**Comment by wizjany** [comment]
thanks for what? this is a counterpoint to your bug report.
as mentioned in discord, it works fine for us so it's on you to somehow show it doesn't work.

**Comment by solonovamax** [comment]
I'm sorry, but your video was showing the bug in action...

The //regen command should've regenerated the tree and not deleted it.

**Comment by me4502** [comment]
It did regenerate the tree?

**Comment by wizjany** [comment]
I used //set 0 to delete part of the tree and then //regen to show that it pops back up exactly as it was...

**Comment by solonovamax** [comment]
Wait, am stupid and only watched first part of gif.

**Comment by solonovamax** [comment]
I'll get some pictures of it now and possibly upload some videos later.

**Comment by solonovamax** [comment]
Before regen:
![2020-07-06_23 17 54](https://user-images.githubusercontent.com/46940694/86700279-fb6b9c80-bfde-11ea-8e8c-b640fa55fbbe.png)
After regen:
![2020-07-06_23 17 50](https://user-images.githubusercontent.com/46940694/86700293-feff2380-bfde-11ea-9d75-2fd1865ac12d.png)

Before regen:
![2020-07-06_23 19 23](https://user-images.githubusercontent.com/46940694/86700498-28b84a80-bfdf-11ea-9264-dd0e70a63bbf.png)
After regen:
![2020-07-06_23 19 20](https://user-images.githubusercontent.com/46940694/86700521-2c4bd180-bfdf-11ea-9f36-44b48958872d.png)

From the minimal amount of testing I did before, it was working on everything, but then again, I only did it on 1 area.

**Comment by me4502** [comment]
What Minecraft version was the world generated in

**Comment by wizjany** [comment]
moreover, do multiple invocations of regen on the same area produce the same results? or are you only comparing to what you believe to be the original world gen.

**Comment by solonovamax** [comment]
I'm pretty sure the world was generated in 1.16, but this also happens in 1.16 only terrain. (I'll attach more images in a second.)

**Comment by wizjany** [comment]
more images don't really help tbh.

**Comment by solonovamax** [comment]
New nether terrain:
Before:
![2020-07-06_23 26 29](https://user-images.githubusercontent.com/46940694/86701628-2efaf680-bfe0-11ea-8b1a-77d3c68e0ccd.png)
After:
![2020-07-06_23 26 33](https://user-images.githubusercontent.com/46940694/86701636-315d5080-bfe0-11ea-8156-3da5f62f2e1b.png)

**Comment by me4502** [comment]
The only "guarantee" that regen makes is that it'll replace the terrain with what the world generator says should go there. 

It being so similar to what was there prior makes me think this is a slight change in the generation algorithm potentially made by Spigot/etc. The only place we could be doing something wrong is passing in the wrong seed, but that would produce vastly different results.

**Comment by solonovamax** [comment]
Fair point.

Though when I was doing some code digging in world edit, it seems you just copy the same world generator as the current world, so I'm not sure why it does this.

From what I understand about seeds, some things like the decoration generation use more bits of the seeds than things like the terrain generation, so it could be something where the upper bits of the seed are off by something, but not the lower ones. /shrug

I'll close the issue now if you want, as nothing major like structures are being changed.

**Comment by me4502** [comment]
Generally seeds are setup in a way that a tiny change produces massive changes, so the upper bits being off would definitely not produce results like this unless there was some ridiculously unlikely coincidence

**Comment by solonovamax** [comment]
I was doing some research a while ago about brute-forcing seeds and how some things can only be used to calculate some of the lower bits of the seed. Like how the obsidian end pillars can be used to calculate something like the lower 8 bits, but I digress.
