### ISSUE TITLE
/replace air glowstone only replaces ~500 blocks of a much larger selected area.

### ISSUE THREAD

**Issue by Barerock** [EngineHub/WorldEdit#1425]
WorldEdit version: 7.1.0 (unknown output from command)
Platform version: MC 1.15.2 Forge 31.2.0

Bug: In this current version and in versions before (notably 1.14.4) I have been unable to replace a large selection area of air (such as cave space) with glowstone. The command replace goes through, but only changes some hundreds of blocks before not changing ANY at all afterwards even with hundreds of thousands left to go in other regions. The command fails every time after the initial execution. Edit: The selection is only 638,144 blocks cubed.

**To Reproduce**
1. Select an area using Cuboid (only way I've tested it), can be anywhere above 510 blocks total it seems
2. initialize command -/replace air glowstone- in any way using IDs or names
3. Continue to execute command and observe

**Expected behavior**
I expect to be able to replace the entire space with whatever block I wish, and I've already set the block limit to 10 million for builds I've copied and pasted in the past ranging from 5,100 blocks to 4,900,000 blocks on the same server.

**Screenshots**
![image](https://user-images.githubusercontent.com/38869993/86709952-75ecea00-bfe8-11ea-8ae5-802741134f33.png)
This includes the entire selection as well as the versions and results of a second execution of the command. The initial execution only replaces 510 blocks, as can be seen in the middle of the screen.

Thanks for the hard work!

**Comment by wizjany** [comment]
cave air isn't air. use `!#existing` if you want to include both (or cave_air,air).

**Comment by Barerock** [comment]
Got it... That makes sense I guess
