### ISSUE TITLE
Index 55 out of bounds for length 55

### ISSUE THREAD

**Issue by tajemniktv** [EngineHub/WorldEdit#1437]
**Versions**

WorldEdit version: 7.2.0 beta-2
Platform version: Forge 1.16.1  32.0.63

**Describe the bug**

Minecraft gives an error when turning on
"Exception caught during firing event: Index 55 out of bounds for length 55"

**To Reproduce**

1. Turn on minecraft w/ WE, other mods and using zulu java

**Expected behavior**

Minecraft turning on properly

**Additional context**

Latest: https://hasteb.in/zowudoxo.md
Debug: https://hasteb.in/jacaraga.md
Mods list: https://imgur.com/a/LIY8hLm 

I'm using zulu 11.39.15 ca jdk11.0.7 as my java

**Comment by octylFractal** [comment]
This is a Forge bug, report to them.
