### ISSUE TITLE
Navwand/Compass left click occurs after right click

### ISSUE THREAD

**Issue by Tashnav** [EngineHub/WorldEdit#1438]
Versions
7.2.0-SNAPSHOT
MC 1.16.1

Describe the bug
When right clicking with the compass, it does /jumpto as well as thru

To Reproduce
Right click with compass

Expected behavior
Should do only /thru, does /jumpto aswell

Additional context

This has  been happening for several versions, was hoping it'd be fixed by now

**Comment by me4502** [comment]
What platform does this occur on

**Comment by Tashnav** [comment]
I've noticed in Forge, Fabric, and in Sponge through FAWE

**Comment by me4502** [comment]
It's a FAWE bug then, don't report it to us.

**Comment by Tashnav** [comment]
> It's a FAWE bug then, don't report it to us.

I mean Sponge has worldedit but only through FAWE, and it's a problem there as well. It's not specific to FAWE.

**Comment by me4502** [comment]
What do you even mean by "Sponge has WorldEdit but only though FAWE".

If you can show it being reproduced without FAWE, show us on the Discord.

**Comment by Tashnav** [comment]
Ok, I can do that, I have Fabric 1.16.1 running with it, if you don't mind may I ask how I can share it with you?

**Comment by me4502** [comment]
Join the Discord and provide details there
