### ISSUE TITLE
Rework event handling

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#1439]
Right click handlers are broken in Fabric/Forge, and because I think it is due to how Mojang now sends the packets, it will not be fixed without changes from Mojang. Right clicking a block fires twice, once as "right click block" and once as "right click item". We could use a raytrace to see if a RCI is really a RCB, and ignore it. We could implement the occasionally discussed timer system. Not sure what we really want to do here.

Left click air is also broken right now, needs a more consistent solution on all platforms, or an official notice that it simply doesn't work.

**Comment by wizjany** [comment]
I think this affects bukkit as well to some extent.

**Comment by octylFractal** [comment]
Fixed long ago by #2153
