### ISSUE TITLE
Errors on pasting and attempting to //undo a build with spawners and gold pressure plates from a 1.15.2 nether world to a 1.16.1 one.

### ISSUE THREAD

**Issue by Momshroom** [EngineHub/WorldEdit#1440]
**Versions**

WorldEdit version: 
> we version
[05:02:19 INFO]: WorldEdit version 7.2.0-SNAPSHOT
[05:02:19 INFO]: https://github.com/EngineHub/WorldEdit/
[05:02:19 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.2.0-SNAPSHOT+5170-a0b4f93)

[05:02:19 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

Platform version:
Paper 92 (1.16.1)
[05:02:49 INFO]: This server is running Paper version git-Paper-92 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[05:02:49 INFO]: Checking version, please wait...
[05:02:49 INFO]: Previous version: git-Paper-89 (MC: 1.16.1)
[05:02:49 INFO]: You are running the latest version

**Describe the bug**

Pasting an older nether build into a 1.16.1 nether world gives errors both on //paste and on //undo.
 The errors are: 
https://paste.gg/p/Momshroom/c82df4110a434c7daf18267daa018d3d

**To Reproduce**

I //copied a nether build from our old nether, which included spawners and pressure plates.  It seems to have copied fine, but when pasting it into our new 1.16.1 nether it pastes mostly fine (no spawner or gold pressure plates), but gives a console error.  When I attempt to //undo it I get both a console error and an ingame error telling me to report it and nothing appears undone. 

This was reproducible on multiple versions of worldedit and paper (I updated both to see if they would fix it).

**Expected behavior**

Build would paste with all parts, including the spawner and pressure plates and there would be no errors.

**Screenshots**

spawner portion of the build before copying and pasting: https://prnt.sc/tip709
same area after pasting: https://prnt.sc/tip7tz

**Additional context**

**Comment by me4502** [comment]
CoreProtect issue, not WorldEdit.

**Comment by Momshroom** [comment]
Ty, updating CoreProtect to yesterday's release candidate fixed it.
