### ISSUE TITLE
Failing unit test when building from a path with a symlink in it

### ISSUE THREAD

**Issue by Pieter12345** [EngineHub/WorldEdit#1444]
**Versions**

WorldEdit version: Build 5183
Platform version: Irrelevant
OS version: Windows 10

**Describe the bug**

Unit test `com.sk89q.worldedit.world.snapshot.experimental.fs.FileSystemSnapshotDatabaseTest.rootIsAbsoluteDir(FileSystemSnapshotDatabaseTest.java:148)` fails when building WorldEdit from a command prompt with a symlink in the path to the WorldEdit source directory. The failure is caused by an assert comparing the path with the symlink in it with the path without the symlink in it. The target directories are the same, but the path comparison doesn't support resolving symlinks.

**To Reproduce**

1. Open a command prompt.
2. Use `cd C:\...\some_symlink\...\worldedit` to nativate to the WorldEdit source directory.
3. Run `gradlew install`.

**Expected behavior**

No failing unit tests.

**Screenshots**

**Additional context**

**Comment by octylFractal** [comment]
Cannot reproduce on Linux, so probably a Windows bug (again @.@)
