### ISSUE TITLE
Allow regen to output to other Extents, such as the clipboard

### ISSUE THREAD

**Issue by me4502** [EngineHub/WorldEdit#1445]
**Is your feature request related to a problem? Please describe.**
Add the ability to regen to clipboard. This could allow for making modifications such as rotation, flips, etc before pasting. Also allows for pasting it in other places.

**Describe the solution you'd like**
Make the method on World take an extent rather than using the editsession. And adding a flag (`-c`?) to the regen command to pass in the clipboard.

**Describe alternatives you've considered**
Regen, copy, undo :P

**Additional Context**
PlotSquared want an API to regen to a custom extent. This also achieves that while adding a potentially useful feature.

**Comment by wizjany** [comment]
technically already doable since you can pass whatever `World` impl you want to the editsession being written into. "generifying" the signature from EditSession -> Extent just saves a step of indirection I guess (and skips the whole ES extent stack, which might be good or bad depending).

**Comment by me4502** [comment]
I'm going to close this as it's now possible via the API
