### ISSUE TITLE
Grass remains grey after snow layer removed via //thaw , //replace or //set air

### ISSUE THREAD

**Issue by moosecovite** [EngineHub/WorldEdit#1446]
**Versions**

WorldEdit version: 7.2.0 Beta 02 _(MC 1.16.1)_
Platform version: Forge 32.0.70 _(MC 1.16.1)_

**Describe the bug**

Grass colour remains grey and side texture of grass also remains snowed-over after //thaw or snow-removal commands. Issue persists even after rejoining or reloading of world.

**To Reproduce**

1. Go to snowed-over grassy area
2. Use **//thaw** or **//replacenear X snow air**
3. Restart or rejoin world

**Expected behavior**

Grass colour will be green/appropriate to present biome after snow layer is removed.

**Screenshots**

![2020-07-19_21 37 20](https://user-images.githubusercontent.com/68504958/87876157-b72dc280-ca08-11ea-952a-f081a4e5e2f4.png)
![2020-07-19_21 37 27](https://user-images.githubusercontent.com/68504958/87876159-b8f78600-ca08-11ea-9682-17095f2d9cf2.png)

**Additional context**

**//fast** was disabled. No additional mods were installed.

**Comment by me4502** [comment]
As far as I can tell, this was working fine on Forge always. You do need to have "validations" turned on in `//perf` for this to happen though.

It was actually broken on Bukkit on 1.16 due to some horrible namings in Spigot, but that is now resolved.
