### ISSUE TITLE
//undo with use-inventory returns one item of all materials used when all materials should be consumed.

### ISSUE THREAD

**Issue by CHduckie** [EngineHub/WorldEdit#1450]
Version: worldedit-7.2.0-beta-02 (bukkit)

To reproduce:
1. Set use-inventory flag to true in config.
2. Select and replace any block with another, ensure that the block to be replaced is not available in the inventory.
3. After replacing and successfully acquiring the replaced block, undo the operation.

**Comment by wizjany** [comment]
fyi as mentioned on the docs the use-inventory option isn't supported or recommended.

also you missed the issue template.

**Comment by CHduckie** [comment]
Sorry, I must've missed the issue template, I couldn't find it.

Alright, so no inventory support, got it.

**Comment by retep998** [comment]
I do wish the use-inventory option was supported. It's such a useful middle ground between creative and survival.

**Comment by octylFractal** [comment]
WorldEdit is designed to be an administrative tool, not a building wand. We are even considering dropping the feature, as it is out-of-line with the rest of WorldEdit. If you wish to have that sort of option, find or create an alternative survival-oriented WorldEdit plugin.
