### ISSUE TITLE
Empty strings for most translatable components in command feedback

### ISSUE THREAD

**Issue by Pieter12345** [EngineHub/WorldEdit#1451]
**Versions**

WorldEdit version: Bug is present in build 5015 to 5187, and is NOT present in build 4965.
Platform version: Bukkit 1.16.1.

**Describe the bug**

Command feedback is partially missing. It looks like some materials/arguments/... are translated to empty strings. See image with the result of `//distr` without printed material names and `//set`/`//replace` with missing argument descriptors:
![afbeelding](https://user-images.githubusercontent.com/9693840/88186075-03f5e100-cc35-11ea-88c4-042cc8cf7d49.png)

**To Reproduce**

1. Start a Bukkit 1.16.1 server with an affected WorldEdit build.
2. Run the mentioned commands and notice the missing feedback.

**Expected behavior**

The feedback should contain the strings as printed in the mentioned unaffected build instead of being empty strings.

**Screenshots**

See above.

**Additional context**

**Comment by wizjany** [comment]
Bukkit is not server software, it's an api. Please actually give the output of /version.
also like
![](https://i.imgur.com/97Sk4jv.png)
works fine so yea. gonna need actual repro.

**Comment by Pieter12345** [comment]
The issue occurs on CraftBukkit 1.16.1, and not on Spigot 1.16.1. But as this is the Bukkit version of WorldEdit, it should work on both.

**Comment by wizjany** [comment]
Turns out bukkit has 0 api for any of the text component stuff mojang has added in the past 6 years (surprise, bukkit has been dead for 6 years), so the distinction between craftbukkit and spigot is extremely meaningful. Not sure why you decided to just omit that.

**Comment by Pieter12345** [comment]
If Bukkit doesn't have the API required, then which calls are made to what to send the feedback? Since this bug is also present on Spigot 1.16.1 consoles, I'm guessing that a translation fallback there would also be fitting to solve the bug for CraftBukkit players and console.
