### ISSUE TITLE
Could not pass event PlayerMoveEvent to FastAsyncWorldEdit

### ISSUE THREAD

**Issue by Darkethereal** [EngineHub/WorldEdit#1452]
**Versions**

WorldEdit version: WorldEdit 7.2.0 Beta 2 (1.13.2 - 1.16.1)
Platform version: Paper Spigot 1.16.1 #108

Constantly have this flooding my console, preventing me from using world edit or a few other plugins.  I've tried re'installing it a few times.. checking configs but I can't seem to get it working.

Console:
22.07 14:03:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
22.07 14:03:05 [Server] ERROR Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v19.07.12-5cc5ce5-1277-22.3.0
22.07 14:03:05 [Server] INFO java.lang.NoClassDefFoundError: com/boydti/fawe/wrappers/FakePlayer
22.07 14:03:05 [Server] INFO at com.boydti.fawe.object.FawePlayer.wrap(FawePlayer.java:87) ~[?:?]
22.07 14:03:05 [Server] INFO at com.boydti.fawe.bukkit.listener.BrushListener.onPlayerMove(BrushListener.java:70) ~[?:?]
22.07 14:03:05 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor535.execute(Unknown Source) ~[?:?]

Not sure what's up...  Thank you in advance

**Comment by me4502** [comment]
We don’t support forks of WorldEdit. If you can reproduce without FAWE, fix up the issue and reopen it.
