### ISSUE TITLE
Dispensers face the wrong way after pasting - Sponge

### ISSUE THREAD

**Issue by Pulverizer** [EngineHub/WorldEdit#1454]
**Versions**

WorldEdit version: 6.1.10-SNAPSHOT
Platform version: SpongeVanilla latest - I'm running it from the IDE.

**Describe the bug**

Dispensers face the wrong way after pasting

**To Reproduce**

1. `//copy` a tnt cannon that utilises dispensers.
2. `//paste` it at a new location.
3. Notice that some dispensers have changed their orientation.

**Expected behavior**

Dispensers should maintain their orientation.

**Screenshots**

**Additional context**

**Comment by octylFractal** [comment]
Old versions aren't supported. When Sponge updates to modern Minecraft, it will be supported again. As for now, we will not be fixing any bugs in Sponge.
