### ISSUE TITLE
WorldEdit can be used on a region without access

### ISSUE THREAD

**Issue by Ziomkeee** [EngineHub/WorldEdit#1455]
**Versions**
WorldEdit version: Bukkit-Official(7.1.0;8e55131)
Platform version: This server is running Tuinity version git-Tuinity-"18fdc0c" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
WorldGuard version: WorldGuard version 7.0.2-SNAPSHOT;bf2593e

**Describe the bug**
I created a new world, added flags on it, including blockade of building / placing and destroying blocks. I added all the flags to __global__ and yet players who can use worldedit on their plots (PlotSquared) can use worldedit in that region where they shouldn't be able to build anything.

**To Reproduce**
1. /mv create spawn normal
2. rg flag __global__ build deny, rg flag __global__ block-break deny, rg flag __global__ block-place deny
3. player with worldedit perms; //pos1, //pos2, next //set 0
4. player removes spawn

**Expected behavior**
It should block the player's actions.

**Comment by wizjany** [comment]
that's not an intended feature so not sure why you think it should do that.

**Comment by Ziomkeee** [comment]
I do not understand you. I believe it is a mistake that a player who has not been added to a region can remove buildings there because he has perms to use // set

**Comment by wizjany** [comment]
Correct.
