### ISSUE TITLE
query, queryRel and queryAbs not working with //g

### ISSUE THREAD

**Issue by Memz-idk** [EngineHub/WorldEdit#1456]
**Versions**

WorldEdit version: 7.1.0
Platform version: Paper 1.14.4

**Describe the bug**

Basically when you use query/queryRel/queryAbs on //g either the server crashes or the message "Evaluation error: 0 blocks changed. X blocks took too long to evaluate (increase with //timeout)" appears, depends on the selection size. No relevant errors in the console.
(If I had to guess probably it's because query still uses legacy id but idk)

**To Reproduce**

1. Make a selection
2. Do //g with any expression that has query/queryRel/queryAbs (ex: //g -o stone query(x,y,z,0,0))
3. Profit

**Expected behavior**

The command working / The server not crashing

**Screenshots**

http://prntscr.com/toy6pt

**Additional context**

Yes, it happens even when selecting only 1.12- blocks.

**Comment by wizjany** [comment]
try a dev build, i feel like this was fixed months ago.

**Comment by Memz-idk** [comment]
It worked, thanks!
