### ISSUE TITLE
New flag suggestion

### ISSUE THREAD

**Issue by zasnaz** [EngineHub/WorldEdit#1457]
Hello,
I have a suggestion which is adding a new flag called "rebuild".
What this flag does is saving the selected buildings and every thing inside the region as it is and auto rebuilding it after a specific minutes, By this feature we can allow the players to build and break but they can't grief for a long time. 
For example :
/region flag spawn rebuild 10m.
Thank you.

**Comment by me4502** [comment]
This is the worldedit tracker, not WorldGuard

**Comment by zasnaz** [comment]
ooh sorry I didn't realize
