### ISSUE TITLE
//setbiome changes random blocks

### ISSUE THREAD

**Issue by LordTelchar** [EngineHub/WorldEdit#1463]
**Versions**
WorldEdit version: WorldEdit 7.2.0 Beta 2 (Forge for MC 1.16.1):
Platform version: Forge 1.16.1 32.0.98

**Describe the bug**
When changing the biome of a block with //setbiome, several other random blocks within a range of approximately 10 blocks around the selected area also change. Sometimes, especially when changing a small amount of blocks, the selected blocks themselves are not even changed, but a random area in its vicinity. This phenomenon occurs since WorldEdit 7.1.0. 

**Expected behavior**
Only the blocks selected should change the biome.

**Screenshots**
![2020-07-30_12 05 21](https://user-images.githubusercontent.com/68993137/88910684-20110800-d25d-11ea-9a2b-7ed09b0db099.png)
The areas supposed to change are marked with redstone; the blocks were changed from _plains_ to _mountains_.

**Additional context**
This may be a feature, if so, I plead for it to be reverted back to what it was. I use a resource pack with biomespecific textures, the ability to change the biome of single blocks is incredibly useful.

**Comment by me4502** [comment]
This is due to a Minecraft change. There is nothing WorldEdit can do to change how this behaviour works.

To get this reverted, you'd have to request Mojang to change Minecraft to make biomes work in 1x1 space on the x/z axis like they used to.
