### ISSUE TITLE
Set Biome Issue Continues

### ISSUE THREAD

**Issue by NYBluff** [EngineHub/WorldEdit#1464]
Hello, 

I am using  version: master | #5190 | 
I saw previous threads that set biome was fixed. It still does not work. I've tried //setbiome 'Biome name here' and //setbiome minecraft:'Biome name here'.
World edit processes the change, but I relog, and restart the server the biome still turns out to be the original one that I wanted to change. I am I missing something or is this still an ongoing issue?

**Comment by wizjany** [comment]
please join discord for support.
