### ISSUE TITLE
'cuboid' selection outline/visualisation 

### ISSUE THREAD

**Issue by Zwangi** [EngineHub/WorldEdit#1467]
Since minecraft is capable of drawing an outline with an structure block feature, i think its possible to use that in World Edit as well. I would love to see that outline of an region u selected or the selection of position 1 and position 2.

Iam not sure if other shapes are possible this way, but square selections are most common to my knowledge.

visualisation:
https://i.imgur.com/gbyOWbG.jpg

**Comment by wizjany** [comment]
//drawsel
