### ISSUE TITLE
Add the ability to download schematics from a remote server.

### ISSUE THREAD

**Issue by aboutDavid** [EngineHub/WorldEdit#1473]
**Is your feature request related to a problem? Please describe.**
Somewhat. I don't want to keep having to go to the Server Control Panel to upload schematics from sites like [Minecraft Schematics](minecraft-schematics.com) or from my personal server.

**Describe the solution you'd like**
A command like /schem download [URL] (Save as name) (-f).

**Describe alternatives you've considered**
None.

**Additional context**

I found this on how to download files in Java: [https://www.stackabuse.com/how-to-download-a-file-from-a-url-in-java/](https://www.stackabuse.com/how-to-download-a-file-from-a-url-in-java/)

**Comment by me4502** [comment]
Our main reason for not having added this is the security implications of having a feature like this. 

Servers will provide the feature to players even when we recommend against it, some gzip security vulnerability will be found that impacts Java, and suddenly people will be downloading malicious schematics to servers. Then we get blamed for it.

**Comment by aboutDavid** [comment]
Oh, ok
