### ISSUE TITLE
Piston are in the wrong orientation and deleting blocks

### ISSUE THREAD

**Issue by Assassin4b** [EngineHub/WorldEdit#1477]
7.2.0 beta-01 1.16.1, spigot

pistons are always facing down and delete the block under them because the retract for some reason.

1. place a piston (and a block under it for the deleting part)
2. select it
3. stack or copy/paste

piston should be clone with the right direction and block under them

**Comment by wizjany** [comment]
please reproduce with a current build

**Comment by Assassin4b** [comment]
didnt see beta 3 yesterday, sry
