### ISSUE TITLE
Cannot remove liquid when use_inventory is enabled

### ISSUE THREAD

**Issue by Ink-33** [EngineHub/WorldEdit#1478]
**Versions**

WorldEdit version:  7.2.0.-beta-02
Platform version: Bukkit-Official(7.2.0-beta-02+d10d7d6)

**Describe the bug**

Players who are in survivial mode cannot remove liquid when use_inventory is enabled.

**To Reproduce**

1. Enable use_inventory
2. Execute //replace minecraft:water(or lava) minecraft:air(or others)
3. Nothing will happen  

**Expected behavior**

The liquid will be replace by the given block
**Screenshots**

**Additional context**

It seems that this bug has existed for a long time.

**Comment by wizjany** [comment]
#1450
