### ISSUE TITLE
/regen crashes the server in 1.16.2

### ISSUE THREAD

**Issue by Blueeyestar** [EngineHub/WorldEdit#1496]
Spigot-Version:CraftBukkit version git-Spigot-379750e-9a9c223 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

Worldedit: worldedit-bukkit-7.2.0-SNAPSHOT-dist.jar #5280

Unfortunately, in 1.16.2 with the latest version, I can no longer make rain without the server crashing.

https://pastebin.com/mUZpSXUS

**Comment by me4502** [comment]
As all of the threads in the server are stuck, this looks unlikely to be an issue with WorldEdit.

This is most likely either a bug in Spigot/Paper, or a potential extension of a vanilla Minecraft stuck chunk bug (where every so often chunk loads never finish and crash the server).

**Comment by me4502** [comment]
After some extensive testing, this definitely doesn't look like it's a WorldEdit issue. 

My initial guess is the most likely cause, either a bug in Spigot/Paper or an instance of Minecraft's stuck chunk bugs.

**Comment by petittitouan** [comment]
Same problem in 1.19
