### ISSUE TITLE
//regen compatibility with EpicWorldGenerator

### ISSUE THREAD

**Issue by R4zzerYT** [EngineHub/WorldEdit#1498]
**Is your feature request related to a problem? Please describe.**

The //regen command generates a normal vanilla chunk and not the real chunk from my world generator. That's a problem obviously

**Describe the solution you'd like**

//regen should work with the 35€ World-Generator. 

**Describe alternatives you've considered**

idk.

**Additional context**

EpicWorldGenerator: https://www.spigotmc.org/login/two-step?redirect=%2Fresources%2Fepicworldgenerator-1-15-1-16-1-support-all-update-aquatic-features.8067%2F&remember=1

**Comment by wizjany** [comment]
As mentioned in discord, this has been tested to work with free custom world gens. We're not going to buy a $35 premium plugin to fix it for them.
