### ISSUE TITLE
use world edit on unmodded using setblock fill and clone

### ISSUE THREAD

**Issue by dallytaur** [EngineHub/WorldEdit#1510]
you need a modded sever for world edit making it hard MP/temp need world world edit

my idea is you could parse the world edit command into string of setblock fill and clone commands e.g.

//cyl set block a circle and clone it downwards
//set fill command using the cords of axe
//copy //paste clone command or set block

Only other way to allow this is a modded server

I could see this to be laggy or slow but if world edit is used commonly you could install the world edit mod to the server

**Comment by me4502** [comment]
WorldEdit isn't a client mod, it only runs on the server (either dedicated server or integrated server on the client).

I feel this is fairly out of scope for WorldEdit

**Comment by dallytaur** [comment]
> WorldEdit isn't a client mod, it only runs on the server (either dedicated server or integrated server on the client).
> 
> I feel this is fairly out of scope for WorldEdit

It is both a client mod and a server mod if on the client the not on the server you can only you use it in SPC with this parser it would allow the client to run worldedit on any server assuming you have OP commands abit slower.

**Comment by octylFractal** [comment]
This is way out of scope for WorldEdit, even if we wanted to add it we would need to majorly restructure the internals of WorldEdit _and_ it would not work great for placing blocks in general, as there would be no control over any side-effects such as lighting or neighbor updates. It's just way too much work for nearly no benefit. Learn how to setup a modded server, it is really no harder than vanilla.
