### ISSUE TITLE
//setbiome does not set entire selection

### ISSUE THREAD

**Issue by tedders5** [EngineHub/WorldEdit#1512]
**Versions**
WorldEdit version: 7.2.0-beta-04
Platform version: Bukkit-Official(7.2.0-beta)

**Describe the bug**
The //setbiome command does not set the entire selected region. Instead, only a few chunks are set. I have switched worlds and unloaded / reloaded chunks and the original biomes are still there.

**To Reproduce**
1. Select a region.
2. do the //setbiome command.

**Expected behavior**
The entire selection would be set.

**Comment by octylFractal** [comment]
Can you provide your full startup logs (restart and copy `logs/latest.log` to https://paste.enginehub.org/)? As far as I know, any issues with setting biomes on Bukkit fall squarely into the Bukkit implementation's bugs, not ours.

**Comment by octylFractal** [comment]
Determined to be a 3D biome mixup.
