### ISSUE TITLE
Can't running after used server reload command

### ISSUE THREAD

**Issue by Creepercdn** [EngineHub/WorldEdit#1515]
**Versions**

WorldEdit version: `worldedit-forge-mc1.12-6.1.8-dist`
Platform version: `This server is running Mohist version 1.12.2-3a8f576 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2854)`

**Describe the bug**

When used `/reload`, WorldEdit isn't exec any command.
But Region Tool can set region.

**To Reproduce**

1. Run command `/reload`

**Expected behavior**

WorldEdit can running expected, exec all correct command.

**Screenshots**

**Additional context**

This bug only can reproduce on Forge server.

**Comment by wizjany** [comment]
unsupported version and environment. that's not even a forge server.

**Comment by Creepercdn** [comment]
Forge and Spigot server.
