### ISSUE TITLE
Language Broken Issue

### ISSUE THREAD

**Issue by d0nghan** [EngineHub/WorldEdit#1517]
**Versions**

WorldEdit version:  7.1.0
Platform version: 1.15.2 / Paper / Bukkit Official 7.1.0;8e55131

**Describe the bug**
Hi, this is a Korean user.
If the default setting is English, the language does not look broken. But If the default setting is Korean, the language appears broken.
Can you set US language as the default setting even when it's Korean?

**Comment by octylFractal** [comment]
This issue has already been fixed in the dev builds, we do not support older versions but 7.2.0 beta 04 should still function on 1.15.2 Bukkit.

**Comment by octylFractal** [comment]
The secondary issue here, being able to override the language selection, is something we have considered but not yet implemented.
