### ISSUE TITLE
"-e" does not work in 1.16.2 Fabric

### ISSUE THREAD

**Issue by Haoshuiganlong** [EngineHub/WorldEdit#1520]
**Versions**

WorldEdit version: 7.2.0 Beta 4
Platform version: Minecraft 1.16.2 with Fabric

**Describe the bug**

-e does not work

**To Reproduce**

1. select a region and place an entity within it, eg, item frame or armour stand
2. run //move 1 -e, //stack 1 -e, or //copy 1 -e for it, and the entity will not change.

**Expected behavior**

As described in the descriotion of -e

**Comment by octylFractal** [comment]
Cannot reproduce, make sure you're using `//paste -e` as well, and note that paintings seem to sit one block higher than they actually are (potentially a bug but might just be Mojank again).

**Comment by octylFractal** [comment]
There is a related bug, I have opened #1522.

**Comment by Haoshuiganlong** [comment]
Pasting is with "-e". Can reproduce, but normal occasionally. Vanilla structure blocks seem to have the same problem.

https://i.loli.net/2020/09/08/vAEITpHcQod4aOt.png
https://i.loli.net/2020/09/08/FPmeKLgfz7MZQ2w.png
In the two cases, I typed //stack with a "-e".

**Comment by octylFractal** [comment]
Did you try with the latest dev build? As I mentioned, there is a related issue that I fixed.

**Comment by Haoshuiganlong** [comment]
I didn't see your update in CurseForge.
