### ISSUE TITLE
new brush: splatter

### ISSUE THREAD

**Issue by PeterDorvay** [EngineHub/WorldEdit#1524]
**Is your feature request related to a problem? Please describe.**
Currently, there is no simple way to create a splatter design over a large surface that I am aware of. You can slowly do it by creating different brushes, but it's slow and painful to do.

**Describe the solution you'd like**
A brush that essentially does this:
![image](https://user-images.githubusercontent.com/21300105/92533315-0ca37600-f1e7-11ea-8e6a-e235f8d85510.png)

It's parameters would be a **block**, **radius**, and **fall-off** strength. A higher fall-off strength would create a sphere brush pattern. A lower fall-off strength would create a messier pattern.

![image](https://user-images.githubusercontent.com/21300105/92533535-8b98ae80-f1e7-11ea-8858-596368a4ba26.png)
The left would be high fall-off, the right would be low fall-off.

**Describe alternatives you've considered**
Alternative solutions are to use GoPaint (which offers this brush) however that plugin requires FAWE which is completely unusable. Another alternative is to create different brushes with percentage patterns to slowly create this effect. Emphasis on slowly.

**Additional context**
I believe that everything. If you have any questions let me know.

**Comment by octylFractal** [comment]
Done in #1657
