### ISSUE TITLE
Measure Distance using Wordedit?

### ISSUE THREAD

**Issue by thatoneXman** [EngineHub/WorldEdit#1529]
I'm making a Minecraft Schematic so I can Import a Build Into another world. But I don't know how long and Tall my Build is. so then I thought: "Does worldedit have a Measure Distance Feature?"

Solution (If it isn't in the mod already): a Measure Distance Feature!

Works maybe something like this: a Player places Points A & B using Wand, then types in "//Measure" or something like that, and it tells you how tall, Long, and Wide the Selection is.

 keep in mind, this is just a small suggestion, and I have no idea if it's already in the game or not.

Have a Nice day!

**Comment by wizjany** [comment]
`//size`
please direct Q&A to discord.
