### ISSUE TITLE
1.12.2 //setbiome doesn't work

### ISSUE THREAD

**Issue by Jacubus2345678923456781234678912345** [EngineHub/WorldEdit#1530]
**Versions**
WorldEdit version: worldedit-forge-mc1.12.2-6.1.10-dist
Platform version: Forge 14.25.3.2838

**Describe the bug**
//setbiome doesn' work, after execute this command by enter message on chat writed about change biome but nothing happen.

I have a world edit in modpack, maybe it's reason? List of mods:
[http://prntscr.com/uiyq94](http://prntscr.com/uiyq94)
[http://prntscr.com/uiyqzz](http://prntscr.com/uiyqzz)
[http://prntscr.com/uiyrjb](http://prntscr.com/uiyrjb)
[http://prntscr.com/uiyrxu](http://prntscr.com/uiyrxu)
[http://prntscr.com/uiysd9](http://prntscr.com/uiysd9)
[http://prntscr.com/uiysyy](http://prntscr.com/uiysyy)

**Comment by wizjany** [comment]
Old versions are unsupported. iirc the forge version had a bug where setting biomes wouldn't mark the chunk dirty so it wouldn't be saved unless you also change some blocks or otherwise update the chunk.
