### ISSUE TITLE
None of the tree commands work like they're supposed to.

### ISSUE THREAD

**Issue by ggilost** [EngineHub/WorldEdit#1532]
Here, I was using the command shown but, the trees just refused to go anywhere further than about 10 blocks from 0, 0. The brush command also seemed to only work around the same 10 block radius around 0. Even forest gen doesn't work like it's supposed to. I'm on the latest version of spigot(as of this message, sorry I'm not sure which one exactly), on 1.16.3. Any help would be appreciated. If you need any extra info just ask. Thank you and have a nice day.
![Screenshot (90)](https://user-images.githubusercontent.com/60539157/93622818-96312000-f9ff-11ea-852b-7ed0cbf8e185.png)

**Comment by wizjany** [comment]
please follow the issue template. also can't reproduce at all.
