### ISSUE TITLE
worldedit doesn't work in some worlds but it does in others (in the same version)

### ISSUE THREAD

**Issue by xdperez** [EngineHub/WorldEdit#1537]
version of game: 1.6.3

version of worldedit: worldedit-forge-mc1.16.3-7.2.0-beta-05

I can't use "//wand" and other commands in a world from 1.5.2, but in other worlds they do.

1. world that i can't use worldedit
![image](https://user-images.githubusercontent.com/71753776/93979714-4de96900-fd43-11ea-9810-1ac958f1d35c.png)

2. world that i can use worldedit
![image](https://user-images.githubusercontent.com/71753776/93979853-7709f980-fd43-11ea-9357-4208b1de6fd0.png)

**Comment by me4502** [comment]
Sounds like your permissions setup

**Comment by octylFractal** [comment]
WorldEdit requires cheats enabled or the appropriate configuration setting set to true, probably not a bug.
