### ISSUE TITLE
Having wands as modname:item instead of #IDs

### ISSUE THREAD

**Issue by Goldninja100gn** [EngineHub/WorldEdit#1552]
**Versions**

WorldEdit version: worldedit-forge-mc1.12.2-6.1.10-dist.jar
Platform version: MC: 1.12.2 (modded) forge-14.23.5.2854

**Describe the bug**

Wand items only work with #IDs and not with modname:item

**To Reproduce**

1. set the wand item in the config file as an id that is in the formate modname:item
2. run Minecraft, when you do //wand it will give you the wooden wand
3. set the wand item to the #ID of modname:item
4. run Minecraft, when you do //wand you will get the modname:item
5. the problem with this is #IDs change when new items/blocks are added from new mods or updating mods, unlike modname:item which stays a consistent

**Expected behavior**

when the wand is set to modname:item, the wand should be set to modname:item 

**Screenshots**

**Additional context**

I haven't found a way to force an #ID to never change, the only #IDs that never change are ones from Minecraft. My research has brought me to learn that FML creates the #IDs for each mod where mod creators can't actual force the #ID to stay the same unlike modname:item formated IDs. All the other mods in this modpack use modname:item except for worldedit when calling on an item/block. I believe it is plausible to fix. Thank you for reading this issue <3

**Comment by octylFractal** [comment]
This should be fixed in 1.13+, we do not support older versions.

**Comment by Goldninja100gn** [comment]
wait, 1.12.2 is unsupported when that is the most recent release version? 
![image](https://user-images.githubusercontent.com/12952449/95133839-87e54280-0727-11eb-802d-d255040a8663.png)
anyways Thank You, I'll just have to always update the IDs for every modpack update then <3

**Comment by octylFractal** [comment]
It's the most recently published build simply because we had not published the final version. We do not support anything but the latest release.
