### ISSUE TITLE
Problème avec un brush

### ISSUE THREAD

**Issue by TeddyR88** [EngineHub/WorldEdit#1553]
Bonjour,

Je vous écris pour vous dire que j'ai rencontré un problème curieux. J'utilise  WorldEdit sur un serveur en multi (version 7.2.0) mais quand j'utilise /br sphere 13%20,80%0 4 la commande fonctionne mais, je ne sais pas pourquoi dans certaine zone et à certaines hauteurs dans cette zone, la commande ne pose pas les blocs. J'espère que vous aurez une solution pour moi.

Merci d'avance !

**Comment by wizjany** [comment]
1) please use the issue template
2) please use english
3) questions go on discord
