### ISSUE TITLE
Build 5457 not working

### ISSUE THREAD

**Issue by OGRaft18** [EngineHub/WorldEdit#1556]
https://builds.enginehub.org/job/worldedit?branch=master

Build 5445 works properly for us.

However, Build 5457 shoots errors all over: https://pastebin.com/raw/YgScdWjY

The issue, if I'm not mistaken, would appear to be this commit: https://github.com/EngineHub/WorldEdit/commit/bc64990e7ecfc829d8d18da98df027f831d91f78

Thanks in advance for looking over this.

**Comment by octylFractal** [comment]
please use the template next time though

**Comment by OGRaft18** [comment]
> please use the template next time though

No, stop breaking things.

**Comment by octylFractal** [comment]
Fixed in c2d818245e88ee03a2da2d911cbc6936ffa224b9.
