### ISSUE TITLE
//setbiome not working Version 7.2.0 on MC 1.16.1

### ISSUE THREAD

**Issue by caesar-oculus** [EngineHub/WorldEdit#1557]
**Versions**

WorldEdit version:
Platform version:

**Describe the bug**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by me4502** [comment]
You're going to need to provide more information than absolutely nothing.

But use the Discord for support.

**Comment by caesar-oculus** [comment]
Original post updated

**Comment by me4502** [comment]
You still haven't really provided enough information. For example, the version you gave does not exist yet.

But this definitely works, so use the Discord for support.
