### ISSUE TITLE
//setbiome not working 7.2.0 on Paper 1.16.1

### ISSUE THREAD

**Issue by caesar-oculus** [EngineHub/WorldEdit#1558]
Versions

WorldEdit version: Bukkit 7.2.0
Platform version: Paper 1.16.1

Describe the bug

I select an area (low and high points) with wooden axe tool, and enter //setbiome sunflower_plains or //setbiome forest and then log out, restart server, log back in, and the biome is still a savanna.

To Reproduce

... select block at bottom of ocean coastline.
...second selection point 30 blocks above ground level and far to the right of first slection
...enter command "//setbiome sunflower_plains"
... restart server
Expected behavior

I expect the biome to change to the sunflower_plains biome

Screenshots

Additional context

**Comment by octylFractal** [comment]
resolved in discord
