### ISSUE TITLE
Worldedit no longer accepts layman

### ISSUE THREAD

**Issue by GormAuslander** [EngineHub/WorldEdit#1565]
Updated from 1.12 to 1.15, worldedit is now less dynamic and only accepts 100% accurate block ID

Eg;
1.12.2 
//set stonebrick (sets stone_bricks)
//set stainedglasspane (sets stained_glass_pane)
//set gras (auto corrects to grass)

1.15.2 demands that every item be spelled minecraft:full_exhausting_item_name

**Comment by wizjany** [comment]
not sure if this is a question or what, but yes that's intended. we have no intention of manually maintaining a database of aliases, and tab completions make finding the correct block id quite trivial tbqh.

**Comment by me4502** [comment]
Also worth noting that the minecraft: part at the start is not required
