### ISSUE TITLE
Languages unpack despite already existing on Windows

### ISSUE THREAD

**Issue by ShiftingKill** [EngineHub/WorldEdit#1567]
**Versions**
WorldEdit version: v7.2.0-SNAPSHOT+5470
Platform version: Paper Build #240

**Describe the bug**
A few exceptions when the server starts up, as well as when I am right/left clicking.

**To Reproduce**
1. Start server
2. Join and interact/click

**Server Log**
https://pastebin.com/5yh9MsEF

**Comment by wizjany** [comment]
Seems to be caused by an unpack not finishing at some point for whatever reason (or the unpack_finished marker getting deleted). To ensure integrity we should probably re-create all files when re-unpacking to an existing hash-directory without the finished marker.
