### ISSUE TITLE
Regeneration of a chunk isnt working in version 7.1.0

### ISSUE THREAD

**Issue by Alzucard** [EngineHub/WorldEdit#1570]
**Versions**
7.1.0 - Latest Bukkit Version

**Describe the bug**
Whenever i try ti use //regen i get this error in the console
"java.lang.UnsupportedOperationException: Missing BukkitImplAdapater for this version."
**To Reproduce**
1. Try to regen a region

**Expected behavior**
Regenerate the area

**Comment by wizjany** [comment]
latest isn't a version, nor is bukkit even a server software, it's an api.
