### ISSUE TITLE
Blocks breakdown on //paste

### ISSUE THREAD

**Issue by Sonlein** [EngineHub/WorldEdit#1571]
**Versions**
WorldEdit version: 7.2.0-rc2
Platform version: CraftBukkit Spigot 1.16.1-R0.1 and CraftBukkit Spigot 1.16.3-R0.1

**Describe the bug**
When you //paste dead corals (and other blocks that cannot exist in the air, such as torches or carpets), some of them are destroyed. This does not depend on RandomTickSpeed, because even with a value of 0, blocks break. On version 7.2.0 beta 3, such blocks could be easily inserted into the air without breaking. Also, the remaining blocks form a wave pattern, and the bottom layer of inserted blocks is always intact

**To Reproduce**
1. Allocate some space in the air
2. //set dead_fire_coral_fan[waterlogged=false]

**Expected behavior**
The inserted blocks should not break, regardless of whether they can exist in the air or not

**Screenshots**
![image](https://user-images.githubusercontent.com/61748957/96934252-97f07680-14ca-11eb-8ced-235de78e4450.png)

**Additional context**
We use the modified texture of corals on trees as leaves, but when inserting a schematic, a lot of leaves break

**Comment by wizjany** [comment]
various block placement settings can be toggled in //perf. this isn't a bug though.
