### ISSUE TITLE
No Commands From WorldEdit

### ISSUE THREAD

**Issue by Gordae** [EngineHub/WorldEdit#1572]
**Versions**

WorldEdit version: 6.1.9
Platform version: 1.12.2

**Describe the bug**

All WorldEdit Commands Are Not Registered, When I Type In /help worldedit, I see this.
```
Commands From WorldEdit:
```

**To Reproduce**

1. Run A Spigot 1.12.2 Server.

**Expected behavior**

I Expected Commands From WorldEdit.

**Screenshots**

![image](https://user-images.githubusercontent.com/49623720/97377273-e2804300-187c-11eb-81e3-f4a0c36adea2.png)

**Comment by me4502** [comment]
Old versions are unsupported.

Sounds like you've got a permissions issue there though. This is a bug tracker, not a support forum.
