### ISSUE TITLE
High CPU usage and low fps in areas I use world edit, goes back to normal when you leave the area.

### ISSUE THREAD

**Issue by eVisper** [EngineHub/WorldEdit#1573]
So I started using world edit to level some terrain in a plains biome to build and within the first minute of starting to flatten the terrain with brushes and //set I noticed my CPU usage would go from 15% to 50% and my FPS would go from 500 to 100 or less. This happens for all my friends that also join and go around the area I used world edit in.
Any help is appreciated, thank you.

Server PC:
Xeon E5-1630v3 @ 3.7Ghz
16GB DDR4 ECC
1TB SSD

My PC:
I7-7700k @ 4.5Ghz
16GB DDR4 @ 3200Mhz
Aorus 2080 Super Waterforce Edition
1TB M.2

**Comment by me4502** [comment]
WorldEdit does nothing after setting the blocks. If you're having performance issues in the area afterwards, it's due to the blocks that have been placed in the area rather than WorldEdit itself.
