### ISSUE TITLE
Furnace orientation misplacement

### ISSUE THREAD

**Issue by TeeSee64** [EngineHub/WorldEdit#1575]
WorldEdit version: Worldedit-bukkit-7.1.0
Platform version: Spigot Paper 1.16.3

Copy and paste a line of furnaces will place the furnaces not as the original

**To Reproduce**

1. place a line of furnaces and select, copy this.
2. at another postition (few blocks away) paste the copied furnaces and you will see the furnaces are turned arround.

**Screenshots**
<a href="https://ibb.co/vqqX91v"><img src="https://i.ibb.co/QQQD09j/2020-10-29-13-15-46.png" alt="2020-10-29-13-15-46" border="0"></a>
<a href="https://ibb.co/3f05YCc"><img src="https://i.ibb.co/hXKx1mV/2020-10-29-13-16-06.png" alt="2020-10-29-13-16-06" border="0"></a>
<a href="https://ibb.co/mXbXgkV"><img src="https://i.ibb.co/4YKY3zn/2020-10-29-13-16-16.png" alt="2020-10-29-13-16-16" border="0"></a>

**Comment by GMpet** [comment]
Update worldedit to version 7.2 since 7.1 is outdated

**Comment by TeeSee64** [comment]
7.2 is not a R version but RC

**Comment by TeeSee64** [comment]
Sorry me bad, 7.2 RC version did solve the problem. My apologies for this
