### ISSUE TITLE
//Undo Fails to restore sign text or chest contents

### ISSUE THREAD

**Issue by Mintaka3a** [EngineHub/WorldEdit#1577]
**Versions**

WorldEdit version: worldedit-bukkit-7.2.0-rc2-dist.jar
Platform version: Paper 1.16.3

**Describe the bug**
Using the //undo command to restore a region works and restores chest and sign blocks, but the contents of any containers are empty and signs have lost their text.

**To Reproduce**

1. Place a chest and put some items inside it.
2. Place a sign with text nearby.
3. Select a region cuboid which encompasses the chest and sign.
4. //set stone
5. //undo
6. The chest and sign are back but the chest is empty and the sign is blank.

**Expected behavior**

Container contents should be restored and sign text preserved when rolling back with //undo.

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
you're either missing permissions to set nbt, or some other plugin is breaking things. in general you should probably join discord for support since this is likely not a WE bug.
