### ISSUE TITLE
This WorldEdit version does not fully support your version of Bukkit?..

### ISSUE THREAD

**Issue by molor** [EngineHub/WorldEdit#1578]
**Versions**

WorldEdit version: WorldEdit v7.3.0-SNAPSHOT+5491-5ae691a
Platform version: Paper version git-Paper-"a4129244" (MC: 1.16.4; Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Describe the bug**
```
[11:18:02]
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

```

**To Reproduce**

1. Download last build
2. Run the server

**Expected behavior**

No warning message.

**Comment by me4502** [comment]
Momentary spigot issue, update Paper.

**Comment by molor** [comment]
> Momentary spigot issue, update Paper.

@me4502, I'm already run `./paper jar` and got latest build, see `platform version` :/

**Comment by me4502** [comment]
That's not the latest

**Comment by molor** [comment]
Oh, they updated it again 13 minutes ago.. OK, I rebuild again, thanks
