### ISSUE TITLE
Blocks drop additionally when placed

### ISSUE THREAD

**Issue by RobZenTL** [EngineHub/WorldEdit#1579]
Hi guys, with latest versions of worldedit we have the problem that after setting some blocks, the same blocks that were placed occur additional as dropped items. So the blocks are set, but they also are dropped as items.
Example: We are doing '//set stone' (or '1') and 9 cobblestone are dropped. But the 9 stone are also placed as cleanstone.
Is it a false config? Thanks for your help!

Paper 1.13.2
worldedit-bukkit-7.2.0-dist (also since worldedit-bukkit-7.2.0-beta-05)

**Comment by wizjany** [comment]
1) use the template
2) sounds very much like not a worldedit issue
