### ISSUE TITLE
World Crashes when and enderman spawns in or is spawned in.

### ISSUE THREAD

**Issue by NebulaVY** [EngineHub/WorldEdit#1581]
**Versions**

WorldEdit version: 1.16.4
Platform version:1.16.4

**Describe the bug**

From my experiences the bug occurs when an enderman spawns in or is spawned in a single player world. Which then causes the world to crash. 
**To Reproduce**

1. Load single player world
2. Spawn enderman

**Expected behavior**

World crashes
**Screenshots**

![Capture](https://user-images.githubusercontent.com/74324508/98860037-efbe3580-2417-11eb-928d-e5b8c453f59f.PNG)

![Capture2](https://user-images.githubusercontent.com/74324508/98860069-f9e03400-2417-11eb-912a-763d5d49da53.PNG)

**Additional context**

That is the only issue that has happened so far

**Comment by wizjany** [comment]
WE doesn't even touch rendering, nor does anything there point to WE being an issue.

**Comment by NebulaVY** [comment]
> 
> 
> WE doesn't even touch rendering, nor does anything there point to WE being an issue.

Oh, I thought it had something to do with WE since the issue only happens when I use WE, thank you.
