### ISSUE TITLE
//regen error

### ISSUE THREAD

**Issue by ballhammer** [EngineHub/WorldEdit#1583]
**Versions**
WorldEdit version: v7.2.0
Platform version: Fabric for MC 1.16.4

**Describe the bug**
Error when attempting to regen biome.

**To Reproduce**
1. //chunk
2. //regen -b

**Expected behavior**
Biome regen.

**Screenshots**
![2020-11-11_16 02 48](https://user-images.githubusercontent.com/49887495/98864253-9239e100-2437-11eb-9fdb-057fd3d7aa14.png)

**Additional context**
N/A

**Comment by wizjany** [comment]
provide the log at least...?

**Comment by ballhammer** [comment]
Forget about this. I'm just assuming it was my fault because the biome was listed as null.
