### ISSUE TITLE
fill command stops working

### ISSUE THREAD

**Issue by frazzlesticks** [EngineHub/WorldEdit#1584]
I am trying to fill in sections without placing all the blacks with the fill command, but after about an hour of doing so, i tried to fill, but it said 'Missing argument for radius' and I hadn't been using it before, and i couldnt fill anything and had to place the blocks by hand. Please help.

**Comment by wizjany** [comment]
a) use the template
b) yes, the command needs a radius? not sure what the question is. `//help fill` or the docs will give you the usage.
