### ISSUE TITLE
Tree tool triggers invalid position message yet the position is valid

### ISSUE THREAD

**Issue by N0tMyFaultOG** [EngineHub/WorldEdit#1585]
**Versions**

WorldEdit version:  7.2.0+a51fa43
Platform version: git-Paper-279 (MC: 1.16.4)

**Describe the bug**

The tree tool triggers the invalid position message regardless the location is valid or not.

**To Reproduce**

1. `/tool tree <type, if desired>`
2. See the result

**Expected behavior**

The message should only pop up if the location is actually invalid.

**Screenshots**

https://i.gyazo.com/37a6f8e13c3b0738d08cc31cda593d8a.mp4

**Additional context**

/

**Comment by wizjany** [comment]
99% sure this is the same as #1439

**Comment by N0tMyFaultOG** [comment]
Oic, looks familiar. I searched for duplicated issues but that one clearly didn't pop up. Thanks for clarification 👍
