### ISSUE TITLE
My residence plugin is not working with world edit.

### ISSUE THREAD

**Issue by ExodusCW** [EngineHub/WorldEdit#1588]
Good morning can you help me solve this problem my residence plugin is working perfectly till I add worldedit. then it stopped working.

**Comment by ExodusCW** [comment]
![image](https://user-images.githubusercontent.com/74600830/99387607-9309c180-28d4-11eb-976c-41e3cb65049c.png)
It is writing this and I can not even select first and second point

**Comment by me4502** [comment]
Almost definitely not caused by worldedit.

That plugin likely enabled additional functionality when worldedit is detected, which breaks it.

Report it to that plugin.

**Comment by ExodusCW** [comment]
It is writing this and I can not even select first and second point
![image](https://user-images.githubusercontent.com/74600830/99387690-b7659e00-28d4-11eb-9041-4e142c66ebc8.png)
