### ISSUE TITLE
WorldEdit MOD not loading 

### ISSUE THREAD

**Issue by Frostash** [EngineHub/WorldEdit#1590]
WE Mod is not loading/detected by fabric loader for 1.16.4 , rest mods work fine
what to doo

other mods :
Voxel map
optifine
optifabric
fabric api

PC specs : 
OS : Ubuntu 20.04
Ram : 4 GiB

what can be the reasons for this ?

**Comment by me4502** [comment]
Use the Discord for support

**Comment by Frostash** [comment]
> Use the Discord for support

i am limited to minecraft and discord , 
i can play minecraft in singleplayer only
and discord account is disabled till april 2021

idk why
