### ISSUE TITLE
Player_heads attached to the side are not recognized in //distr //replace ........

### ISSUE THREAD

**Issue by Blueeyestar** [EngineHub/WorldEdit#1592]
I discovered a general problem with Worldedit that affects all versions. I don't know if he's known but I'll report him about it.

We are currently decorating a Christmas world with decorative heads.

since we had installed so many, we want to make a rate event out of it. where users can guess how many decorative heads are installed.

with the worldedit command // distr i wanted to determine the number of decorative heads.

Now I have noticed that the heads that stand on the ground are counted. Heads that are attached to the side are ignored. Should it be like that or is there a mistake in //distr?

![head](https://user-images.githubusercontent.com/35557302/100203072-6e2fd280-2f02-11eb-9ded-9004ea8d5361.png)

accordingly, you cannot use //replace to specifically remove or delete the heads. Because these are not recognized by Worldedit

**Comment by me4502** [comment]
Those are a different block to the ones that are on the ground. (player_wall_head)

**Comment by Blueeyestar** [comment]
> 
> 
> Those are a different block to the ones that are on the ground. (player_wall_head)

o.k many thanks for the info :) And a Merry Christmas
