### ISSUE TITLE
When I use world edit 7.2.0, it changes itself back to 7.1.0

### ISSUE THREAD

**Issue by Fredashay** [EngineHub/WorldEdit#1593]
**Versions**

WorldEdit version: worldedit-bukkit-7.2.0-dist.jar
Platform version: Spigot

**Describe the bug**

I download worldedit-bukkit-7.2.0-dist.jar and placed it in my /plugins folder.
I'm running Minecraft 1.16.4
When I issue the /COPY command in Minecraft, it gives me the following message: This WorldEdit version does not fully support...
I go back to my /plugins folder and WorldEdit has changed back to worldedit-bukkit-7.1.0.jar

**To Reproduce**

1. ... Download the latest Build Tools
2. ... Build the server and copy the server jar to your server's folder
3. ... Download worldedit-bukkit-7.2.0-dist.jar from https://dev.bukkit.org/projects/worldedit/files/3100517
4. ... Copy worldedit-bukkit-7.2.0-dist.jar to the server /plugins folder
5. ... Launch the server, make sure it is 1.16.4
6. ... Launch the Minecraft launcher.
7. ... Set the launcher to 1.16.4
8. ... Play the game
9. ... Join the server
10. . Get the wand tool. 
11. . Select a block to copy with the wand tool
12. . /COPY the block.
13. . Observe the message in chat which says: This WorldEdit version does not fully support...
14. . Go to your server /plugins folder where you previously placed  worldedit-bukkit-7.2.0-dist.jar
15. . Observe that it is now worldedit-bukkit-7.1.0.jar

**Expected behavior**

1. ... I expect to not get an message in chat saying that my version of WorldEdit is out of date.
2. ... I expect that WorldEdit will NOT revert worldedit-bukkit-7.2.0-dist.jar to worldedit-bukkit-7.1.0.jar in the /plugins folder

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
this is 100% not on us lol
either you forgot to delete the old jar, or your host is installing jars for you

**Comment by Fredashay** [comment]
Okay.  
I'll contact my hosting service tomorrow and yell at them instead of you :-p  
But if they say it's not them, well then, I'll be baaaaaaack...
Thanks!
