### ISSUE TITLE
Biom reset

### ISSUE THREAD

**Issue by Blueeyestar** [EngineHub/WorldEdit#1599]
This is not a bug but I can't find where I can classify this question. I would know can I undo biomes that I have changed with Worldedit? Unfortunately, you can see very clearly biomes that have been changed. Is there a way to bring them back to normal?

![biome](https://user-images.githubusercontent.com/35557302/100550506-aa549180-327a-11eb-91db-70f8d638c2d5.png)

**Comment by wizjany** [comment]
not sure how you missed it
![](https://i.imgur.com/KITjWqb.png)
assuming you can no longer undo, your only option would be to regen.
