### ISSUE TITLE
//repleace command don't work with %

### ISSUE THREAD

**Issue by ArAmc** [EngineHub/WorldEdit#1602]
**1.16.4**

**Describe the bug**
Hi, I saw a problem with command //replecace beacuse every time when i want to change block with % (//repleace stone 20%stone_brick) the problem shows up and i don't know how to do it right :(

**Screenshots**
1 ![image](https://user-images.githubusercontent.com/75588652/101294408-6bdd4a80-3817-11eb-8cc6-5338331c7e0c.png) 
2 ![image](https://user-images.githubusercontent.com/75588652/101294433-8b747300-3817-11eb-941d-01416b5d5a2b.png)

**Comment by octylFractal** [comment]
Please read the note here: https://worldedit.enginehub.org/en/latest/usage/general/patterns/#random-pattern

Use `"%20 stone_bricks"` as your mask instead.
