### ISSUE TITLE
/toggleeditwand not disabling the wand when used.

### ISSUE THREAD

**Issue by OpalPanda** [EngineHub/WorldEdit#1603]
**Versions**

WorldEdit version: 7.2.0
Platform version: Bukkit-Official(7.2.0)

**Describe the bug**

Whenever I go to use the /toggleeditwand command to disable the wands editing ability so that I can use the wooden axe as a normal axe it gives me this message. worldedit.wand.selwand.now.tool and when I go to use the axe it is still an edit tool and i cant use it like a normal axe.
**To Reproduce**

1. Use the /toggleeditwand command 
2. 

**Expected behavior**

I expected for the wand to be disabled and be able to use the axe like normal. 
**Screenshots**

https://gyazo.com/e0d2f98da592bb68e0991e2bcefe4ddc

**Additional context**

**Comment by wizjany** [comment]
the message was a missing translation which has since been fixed, it's just telling you that the wand is a bindable tool so that command no longer functions.

**Comment by OpalPanda** [comment]
So how do i got about disabling the edit wand? or can i not anymore??

**Comment by octylFractal** [comment]
`/tool none` to get equivalent functionality, `//wand` (gives a new one) or `/tool selwand` (binds to current item) when you want it back.
