### ISSUE TITLE
blocks not stacking right

### ISSUE THREAD

**Issue by ATLANTICFIVE** [EngineHub/WorldEdit#1607]
**Versions**

WorldEdit version:1.16.4
Platform version:bukket

**Describe the bug** walls and iron bars along with fences do not connect to surrounding blocks when stacked in world edit, stairs also do not stack properly

**To Reproduce**
fix the block behaviors 

**Expected behavior** the blocks should connect the the blocks around them when stacked horizontally and vertically and the stairs should be facing the same direction as they were placed

**Screenshots**
![2020-12-10_14 21 56](https://user-images.githubusercontent.com/75813358/101837185-89e6cb80-3af3-11eb-8bdb-f5030ba9d850.png)

![2020-12-10_14 15 24](https://user-images.githubusercontent.com/75813358/101837445-ec3fcc00-3af3-11eb-80cf-b34b574a936e.png)
![2020-12-10_14 25 54](https://user-images.githubusercontent.com/75813358/101837465-f2ce4380-3af3-11eb-91a4-6cd4696b07e0.png)

**Additional context**

**Comment by wizjany** [comment]
please stop spamming the issue tracker. you can edit the original issue if you manage to provide proper details, like...the version.
