### ISSUE TITLE
Conflict with Library of Exile

### ISSUE THREAD

**Issue by RDKRACZ** [EngineHub/WorldEdit#1608]
Weird, I can run Carpet and WorldEdit mod without crash **but** when I add Library of Exile to mods then mc crashes.
Running Library of Exile with WorldEdit without Carpet doesn't crash.

_Originally posted by @RDKRACZ in https://github.com/EngineHub/WorldEdit/issues/1605#issuecomment-743127410_

**Comment by RDKRACZ** [comment]
https://github.com/gnembon/fabric-carpet/issues/625

**Comment by RDKRACZ** [comment]
https://github.com/RobertSkalko/Library-of-Exile/issues/1

**Comment by wizjany** [comment]
no reason to make a new issue, please keep new information in the existing issue.
