### ISSUE TITLE
[Fabric Version] Potential conflicts with Litematica and MaLiLib library mod.

### ISSUE THREAD

**Issue by Lava444** [EngineHub/WorldEdit#1610]
[All the version names I list are the names on their respective CurseForge pages. Fabric's version name is the name of the version it creates in the Minecraft launcher.]
**Versions**

WorldEdit version: WorldEdit 7.2.1 (Fabric for MC 1.16.3/1.16.4)
Platform version: 1.16.4 [Fabric Version: fabric-loader-0.10.8-1.16.4]

**Describe the bug**
The game is launchable, but you can't generate a world or enter an old one. When you create a world, it just crashes, and if you try to load one it gets stuck at 0%. I speculate that it conflicts with Litematica and the MaLiLib library mod used to save its schematics.

**To Reproduce**

1. Go to Litematica's CurseForge page and download the file called: [litematica-fabric-1.16.4-0.0.0-dev.20201103.184101.jar]. Next, go onto the MaLiLib CurseForge page and download the file called: [malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar]
2. Run the game with these two mods plus the WorldEdit version I specified in the folder and attempt to create/load a world.

**Expected behavior**
Worlds can be created and loaded when this mod is used with Litematica and the MaLiLib library mod.

**Additional Things**
I also have the Carpet mod running. The file on its CurseForge page is called: [fabric-carpet-1.16.4-1.4.20+v201202.jar]. If there are any confirmed compatibility issues then you should fix that whenever you can. I'm just afraid to remove the mod from my folder because it could mess up a couple of my worlds that have used Carpet the last time they were loaded.

**Comment by wizjany** [comment]
#1605
