### ISSUE TITLE
use-inventory doesn't work on Fabric version

### ISSUE THREAD

**Issue by arnohovhannisyan** [EngineHub/WorldEdit#1615]
**Versions**

WorldEdit version: 7.2.1
Platform version: Fabric 1.16.4

**Describe the bug**

The `use-inventory` option doesn't do anything.

**To Reproduce**

1. Install WorldEdit on Fabric
2. Enable `use-inventory` option
3. Create a new creative world and use WorldEdit

**Expected behavior**

WorldEdit should use items from the player's inventory.

**Comment by wizjany** [comment]
correct, it's only present on bukkit and it's not supported at all anymore on any platform.
