### ISSUE TITLE
Can't paste in World Edit

### ISSUE THREAD

**Issue by FarkieBear** [EngineHub/WorldEdit#1616]
**Versions**

WorldEdit version: bukkit-7.2.0
Platform version: Bukkit/Spigot

**Describe the bug**

When I try paste a copied item, I get the error An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null

Here is 2 Logs with the error as well as my plugin files/folders/.jar.

https://pastebin.com/3unkepA2
https://pastebin.com/nAV8E56
https://pastebin.com/07SrBeCv

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
prism issue
