### ISSUE TITLE
Offset masks do not recognize blocks of the same type

### ISSUE THREAD

**Issue by Heliostorm** [EngineHub/WorldEdit#1625]
**Versions**

WorldEdit version: 7.2.1 and 7.2.0
Platform version: Fabric-Official (7.2.1+299386a)

**Describe the bug**

The overlay and underlay masks (< and >) do not apply to blocks of the same type that is being used for the overlay or underlay.

**To Reproduce**

1. Build a tower of dirt. 
2. Select any block(s) except the one on the bottom.
3. Use //replace >dirt stone

**Expected behavior**
Dirt blocks that are on top of another dirt block should be changed to stone, the same as if they were any other type of block.

**Screenshots**

![2020-12-23_10 18 20](https://user-images.githubusercontent.com/1365299/103011627-3ff4e100-4508-11eb-8142-b3a0eea7ba33.png)
![2020-12-23_10 18 36](https://user-images.githubusercontent.com/1365299/103011631-408d7780-4508-11eb-9e00-c3a33e9025d8.png)
![2020-12-23_10 18 42](https://user-images.githubusercontent.com/1365299/103011636-41bea480-4508-11eb-996a-d58080c609cc.png)

**Additional context**
I have a project made from gravity-enabled blocks, i.e. sand and gravel, and I need to be able to remove them top down so that none of the blocks fall. I thought I would be able to do this with the overlay/underlay masks but they do not apply to blocks of the same type.

**Comment by wizjany** [comment]
This has been discussed before and is due to a negation in the parser, but seems no one made an issue at the time so it went forgotten.

That said this is an xy problem in your case as you can just use the update side-effect as on 7.2.1 on fabric to prevent block updates when you work with your sand/gravel/whatever. (`//perf`)
