### ISSUE TITLE
Crash with Java15 when copying

### ISSUE THREAD

**Issue by tommasobenatti** [EngineHub/WorldEdit#1628]
**Versions**
WorldEdit version: 7.2.1 Bukkit-Official(7.2.1+299386a)
Platform version: Minecraft Server 1.16.4 Yatopia (paper fork)

**Describe the bug**
With java 15 when i try to copy something even little (70 blocks) the server crashes
https://pastebin.ubuntu.com/p/yTx2vbWpts/

**To Reproduce**
1. Use OpenJDK15 and Yatopia (or paper) 
2. Copy a little thing (I copied a fountain)

**Expected behavior**
After some seconds 10/20 in the server console you will see the crash and after a minute the server will stop

**Screenshots**
I have no screenshots but these are the log of the console https://pastebin.ubuntu.com/p/yTx2vbWpts/

**Additional context**
^^^^

**Comment by me4502** [comment]
This is more likely due to Yatopia. Yatopia is known to be rather broken, WorldEdit works fine on Java 15.

**Comment by tommasobenatti** [comment]
Sorry, but if I use Java 11 and yatopia I can copy just fine... It seems strange to me that is a yatopia problem

**Comment by octylFractal** [comment]
Looking at that crash it seems unlikely to be a WorldEdit issue as it's just getting blocks. I would also agree that it's a Yatopia issue.
