### ISSUE TITLE
An error is reported during loading with the fabric carpet mod

### ISSUE THREAD

**Issue by acaciachan** [EngineHub/WorldEdit#1630]
[latest.log](https://github.com/EngineHub/WorldEdit/files/5745992/latest.log)
carpet mod 1.4.21：https://github.com/gnembon/fabric-carpet/releases
The mods I loaded also have "carpet extra","TIS carpet" mod that you can found on GitHub Or Courseforge

**Comment by wizjany** [comment]
https://i.imgur.com/LJ61jl9.png
