### ISSUE TITLE
Using a schematic makes a world un-openable again

### ISSUE THREAD

**Issue by guythatlikespuns** [EngineHub/WorldEdit#1631]
I used the schematics in a test world now I can't reopen the test world after save quiting. I can still load in to worlds that I have not used the commands in.

**Comment by octylFractal** [comment]
1) Use the template, I know github likes to not give it to you when you make an account in the New Issue flow but it's important
2) Please include your `logs/latest.log` file contents, preferably in a spoiler or separate link.
