### ISSUE TITLE
WorldEdit Permission Denied

### ISSUE THREAD

**Issue by endopvp** [EngineHub/WorldEdit#1634]
**Versions**

WorldEdit version: 6.1
Platform version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

**Describe the bug**
hello, I got strike practice yesterday, decided to set it up today and it came with some schematics. the world edit file was like a blank file, no extensions on, and wasn't a directory. so I deleted that file and changed it to a file directory. I put the schematics in and restarted and got this console error. https://hastebin.com/fazijekajo.properties Also got this in chat. "There was an error handling a FAWE command: [See console] java.lang.NullPointerException: null" <----- that was FAWE. When I switched over to world edit it gave me more information that showed that there the permission was denied. I use revivenode, use SpigotMC. This may not be a world edit issue but I need advice or help on what to do.

**To Reproduce**

1. Use revivenode
2. Use spigotmc
3. Use 1.8.8
4. (not sure if it will be able to reproduce, its just my guess.

**Expected behavior**

I expected the schematics to load and be able to paste them and not get the Permission Denied error.

**Screenshots**

![image](https://user-images.githubusercontent.com/68488081/103447152-ea79ac00-4c4c-11eb-9b11-c7daf154f2b0.png)

**Additional context**

**Comment by wizjany** [comment]
old versions aren't supported.

**Comment by endopvp** [comment]
I get that it is older but if you read a bit, I removed FAWE and still got the same error. It isn't FAWE. But thanks for your help.

**Comment by endopvp** [comment]
*isn't about FAWE and isn't FAWE
