### ISSUE TITLE
WorldEdit:version:7.2.1 Minecraft:Fabric Mod Loader

### ISSUE THREAD

**Issue by rxfj** [EngineHub/WorldEdit#1640]
**Versions**

WorldEdit version:7.2.1
Platform version:1.16.4 Fabric everything l have installed is the lateest version

**Describe the bug**

**To Reproduce**

1.not working
2.cuases the game to crash

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by octylFractal** [comment]
https://github.com/EngineHub/WorldEdit/issues/1639#issuecomment-756464099
**provide logs**

there is literally nothing we can say about why it might be crashing without that.

**Comment by rxfj** [comment]
what do l do then?

**Comment by octylFractal** [comment]
Get the `logs/latest.log` file from your `.minecraft` folder, toss it on https://paste.enginehub.org/ or similar, provide it here.

**Comment by seeruk** [comment]
I'm experiencing this issue too - I get crashes if I try to use WorldEdit 7.2.1 with Carpet. WorldEdit 7.2.0 doesn't have any issues so I've just been using that for now. On 7.2.1, single player just gets stuck loading into the world and stays at 0%, multiplayer crashes.

Here's a latest.log from the crash: https://paste.enginehub.org/vpV7_FJCV

**Comment by me4502** [comment]
> I'm experiencing this issue too - I get crashes if I try to use WorldEdit 7.2.1 with Carpet. WorldEdit 7.2.0 doesn't have any issues so I've just been using that for now. On 7.2.1, single player just gets stuck loading into the world and stays at 0%, multiplayer crashes.
> 
> Here's a latest.log from the crash: https://paste.enginehub.org/vpV7_FJCV

https://github.com/EngineHub/WorldEdit/issues/1605
