### ISSUE TITLE
WorldEdit First Position Issue

### ISSUE THREAD

**Issue by PresidentClutch** [EngineHub/WorldEdit#1642]
WorldEdit version: 7.1.0 (Forge for MC 1.15.2)

Every time I right-click to set my first position, it sets it to the block I clicked but then right after, it sets the position to -1 -1 -1 even though I only clicked one time. Please help me.

https://user-images.githubusercontent.com/77213878/104110123-7e2d2700-52a2-11eb-9982-bd7dac0dc62c.png

**Comment by wizjany** [comment]
https://worldedit.enginehub.org/en/latest/faq/#when-i-select-worldedit-also-selects-1-1-1

**Comment by PresidentClutch** [comment]
Thank you!
