### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KanekiK3n** [EngineHub/WorldEdit#1644]
**Versions**

WorldEdit version: WorldEdit 7.2.1+299386a bukkit
Platform version: paper 1.16.4

**To Reproduce**

1. Use the //br smooth on any tool

**Expected behavior**

Get major spam in terminal

**Additional context**

Been busy upgrading my personal server but I have no idea at all why this happens.

[21:00:23] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.extent.EditSessionEvent@6f75357e to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
https://pastebin.com/YXAX8RPg

**Comment by wizjany** [comment]
whatever plugin this is: `net.sothatsit.blockstore`
