### ISSUE TITLE
Version 1.16 Server and a lot is not copy+paste

### ISSUE THREAD

**Issue by ShadowSamara** [EngineHub/WorldEdit#1646]
**Versions**

WorldEdit version: worldedit-bukkit-7.2.1-dist.jar
Platform version: Spigot_Latest_1.16.5.jar (Server hostet by shockbyte)

**Describe the bug**

Regardless of whether it is copying and pasting or as a schematic, only half of it is copied "correctly".
Stairs all only look in one direction, slabs are placed on the lower half of the block, boxes are only copied empty and in general the deco such as banners, for example, are copied like the stairs and are blank.
Is there a fix for this or is it really due to the mc version?

**To Reproduce**

1. copy paste somethink like a chest with items in it

**Comment by octylFractal** [comment]
You need a dev build from https://builds.enginehub.org/job/worldedit?branch=version/7.2.x for 1.16.5 right now.

**Comment by ShadowSamara** [comment]
Thx
