### ISSUE TITLE
Not saving any block data with pasting (e.g. stair rotation)

### ISSUE THREAD

**Issue by Ceeserxx** [EngineHub/WorldEdit#1647]
**WorldEdit version:** worldedit-bukkit-7.2.1-dist
**Platform version:** PaperMC Server 1.16.4 & 1.16.5

**Describe the bug**
If you copy and paste areas or schematics worldedit is currently not saving any block data like state, direction, inventory etc. For example if we take a look on repeaters, if you copy&paste them they will all be facing the same direction with default delay.

**To Reproduce**
Just mark any area with blocks with different states and copy-paste it.

**Comment by Toni300096** [comment]
Hello. Not sure why this issue was marked as invalid, but I've been having the same problem on my server, and I would really like to fix it. If anyone has any info, pls tell me

**Comment by me4502** [comment]
The version they were using did not support their Minecraft version

**Comment by Toni300096** [comment]
ah okay thanks, I'll look into that.
