### ISSUE TITLE
Raise/lower brushes possibly broken

### ISSUE THREAD

**Issue by wizjany** [EngineHub/WorldEdit#1648]
**Versions**

WorldEdit version: 7.2.0
Platform version: Fabric, MC 1.16.4

**Describe the bug**

Reportedly the behavior of these deform-based brushes have changed, and eg lowering a sphere now lowers all the way to the bottom of the sphere instead of just lowering one layer at a time.

**To Reproduce**

1. `/br lower sphere 5`
2. Use the brush on a hill.
3. All blocks within the sphere radius will be air, with the uppermost layer before the brush ending on the bottom.

**Expected behavior**

provided screenshots of apparent supposed function: (only 1 layer lower)
Before: https://cdn.discordapp.com/attachments/421260739970334720/800788664384225280/screenshot_1.JPG
After: https://cdn.discordapp.com/attachments/421260739970334720/800788680523382824/screenshot_3.JPG

**Screenshots**

Actual behavior:
before: https://cdn.discordapp.com/attachments/421260739970334720/800789284872388632/2021-01-18_18.10.33.png
after: https://cdn.discordapp.com/attachments/421260739970334720/800789176269275156/2021-01-18_18.10.04.png

**Additional context**

Unsure if/when this broke, user reported that the behavior changed.

**Comment by me4502** [comment]
After a quick investigation, I believe this is a bug in deform, not the brushes. I can replicate with a selection
