### ISSUE TITLE
//Setbiome bug

### ISSUE THREAD

**Issue by ISurvivor007** [EngineHub/WorldEdit#1649]
**Versions**
WorldEdit version: 7.2.1
Platform version: Bukkit 1.16.4

**Describe the bug**
//Setbiome command does not change every block in a given chunk, leaving some blocks such in original state.

**To Reproduce**

1. use //wand to select a large given area
2. use //setbiome to a different biome

**Expected behavior**
All grass blocks would change into a uniform color

**Screenshots**

![2021-01-22_12 53 01](https://user-images.githubusercontent.com/77853225/105526790-dc99d280-5cb0-11eb-9eed-7a8d8c461441.png)

**Additional context**

**Comment by octylFractal** [comment]
Are you only selecting the surface? https://worldedit.enginehub.org/en/latest/usage/regions/regionops/#setting-biomes

**Comment by ISurvivor007** [comment]
Yes. //expand vert fixed it

Thank you!
