### ISSUE TITLE
Placing sponge next to a chest clears the contents when using obsolete Simulation setting (7.2.2 with WG) 

### ISSUE THREAD

**Issue by crashdemons** [EngineHub/WorldEdit#1650]
**Versions**

WorldGuard version: WorldGuard version 7.0.4+f7ff984
WorldEdit version: WorldEdit version 7.2.2+fc3c499
Platform version:  This server is running Paper version git-Paper-427 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) - can also reproduce on other server versions.

I'm not sure if this is a WE or a WG issue, but only WE was updated which triggered the break.

Plugin configs attached.
[plugins-configs.zip](https://github.com/EngineHub/WorldEdit/files/5861275/plugins-configs.zip)

**Describe the bug**

With our current config - after updating from WorldEdit 7.2.0 to 7.2.2 (with WorldGuard 7.0.4), when players place a dry sponge next to a chest, the contents of the chest is deleted.

I was able to reproduce on a local test server with only WG/WE and our config.
The issue does not occur if I downgrade to WorldEdit 7.2.0.

**To Reproduce**

1. configure a paper server with WG 7.0.4 WE 7.2.2 and the provided plugin configs
2. start the server
3. place a chest and put an item inside
4. place dry sponge in the block next to the chest

**Expected behavior**

the chest should retain all of its contents

**Actual behavior**
the chest loses all of its contents

**Screenshots**

![2021-01-23_16 58 53](https://user-images.githubusercontent.com/3233238/105616438-80ac7800-5d9c-11eb-99ed-fc9b211339bb.png)
![2021-01-23_16 58 59](https://user-images.githubusercontent.com/3233238/105616444-83a76880-5d9c-11eb-9769-27ca3fb9c45c.png)

**Additional context**

the issue does NOT occur with a fresh config and is dependent on a particular obsolete setting.

Disabling `simulation.sponge.enable` solves the issue for the user - and we don't actually need the setting on (as far as I know), but I wouldn't expect it to delete chest contents either.

While this may seem like a nonissue, I imagine if other users leave this obsolete setting on by accident they would rather it just didn't work at all rather than start deleting container contents without explanation.

Potential fixes to this issue might be:
- fix sponge simulation to not clear contents
- just remove sponge simulation entirely since it is marked obsolete
- migrated outdated configs to ignore/remove the option when updating

**Comment by wizjany** [comment]
this is on WG's end and has been fixed there for a while. there's no WE changes here at all.

**Comment by crashdemons** [comment]
is there an actual release for this fix, or only a dev build? 7.0.4 is the newest posted release
