### ISSUE TITLE
Towny Regions Support - Feature Request

### ISSUE THREAD

**Issue by SoraShiunin** [EngineHub/WorldEdit#1655]
**Is your feature request related to a problem? Please describe.**

For the longest time I wish normal players could use World Edit withouth breaking the server builds or others. The solution:
To allow normal players to use world edit in their towny regions as to not break other users builds. 

**Describe the solution you'd like**

I'd like to have a new config option limiting world edit to plot owned areas only. Possibly by detecting if they are in their town and can build(In towny api).
 With a permission to bypass this.

Here is the towny api:
https://github.com/TownyAdvanced/Towny/wiki/TownyAPI#getting-started-with-towny-and-your-ide

**Comment by wizjany** [comment]
We don't ever recommend giving WE to untrusted users. They or someone else can use our api to accomplish this, but we certainly won't be.

**Comment by SoraShiunin** [comment]
> We don't ever recommend giving WE to untrusted users. They or someone else can use our api to accomplish this, but we certainly won't be.

Well yes but permissions would be managed to only allow eg: set command.

**Comment by wizjany** [comment]
k. doesn't change the answer.
