### ISSUE TITLE
use //copy throw Exception

### ISSUE THREAD

**Issue by 3269199948** [EngineHub/WorldEdit#1661]
**Versions**

WorldEdit version: 7.2.2-dist
Platform version: Forge 1.16.4-Mohist

**Describe the bug**

**To Reproduce**

1. Use //cpoy, and then throw an exception

**Expected behavior**
success

**Screenshots**
![image](https://user-images.githubusercontent.com/41908013/106567399-b86da980-656c-11eb-94c7-458f8f38c788.png)

**Additional context**
https://paste.ubuntu.com/p/JvyZ5QXt33/

**Comment by octylFractal** [comment]
We don't support hybrids, try using both the forge and bukkit versions, otherwise tough luck. Hybrids break a lot of assumptions about these platforms.
