### ISSUE TITLE
Conflict with QuickCarpet

### ISSUE THREAD

**Issue by skyrising** [EngineHub/WorldEdit#1662]
This is basically the same issue as #1605 as [QuickCarpet](https://github.com/DeadlyMC/QuickCarpet114) also wants to redirect `onAdded()`, but the fix (#1654, 56c8919) specifically checks for the presence of "carpet".

QuickCarpet currently contains a workaround for this, but it would be nicer if a more general solution could be found.

**Comment by octylFractal** [comment]
top ten reasons this should be fabric api

**Comment by octylFractal** [comment]
8a46670
