### ISSUE TITLE
My worlds will not load up at all with WorldEdit installed?

### ISSUE THREAD

**Issue by soulqveen** [EngineHub/WorldEdit#1663]
I've been using WorldEdit since...well, forever! Never had a problem with it and I've never had to post on github for any problems, so I'm sorry if I do this wrong. But, I am so confused. I'm using 1.16.4, Forge Edition. About three days, I realized that none of my worlds were loading up. I do use over 100 mods, so I went through the task of going through ONE BY ONE to figure out which one wasn't working. Which in the end, resulted in me needing to delete a few worlds because I accidentally deleted my backups folder (I always move my backups away from the saves folder for some reason, I don't know why).  After going through that process, I came to the conclusion that WorldEdit was the culprit. Nothing changed except the fact that I updated BiomesOPlenty and I updated Quark and a few other mods that I already was using. I can have the WorldEdit CUI 3 installed (which I know is separate) with no problems. I have tried all 3 of the 1.16.4 versions available on the Curseforge website and none of them worked. All of them result in me sitting for thirty minutes waiting for my world to load up (which used to only take a minute because of all of my mods). The other night I downloaded a mod to tell me how long my load-up time was just to get an idea and then I went to bed. When I woke up, the world was still loading. And I got a full 10 hours of sleep. I'm not sure what's happened? I can run the world easily without WorldEdit. But, when WorldEdit is on, I can't even play.

For now, I've given up on using WorldEdit, which I suppose isn't too bad because it's nice to go back to my "roots" and plant a block one by one, but...I miss it! I don't know what's happened but if anyone has any idea how I could fix it? I don't know how to post my crash-report or if a crash report would even help. I know how to read my crash-reports a little bit only because I have so many mods and I know there are mods that aren't compatible with each other. But I can't really tell what's going on when it comes to this situation. I always have to force close Minecraft whenever I try and use WorldEdit. It loads to the menu screen, allows me to select my world, and then after that I'm sat hoping that it'll work and it never does.

Any help with this would be greatly appreciated? I don't know if this is the right place to post this or the right formatting or whatever, but hopefully someone understands what I mean?

**Comment by me4502** [comment]
Please follow the template.

We can't really say anything at all without logs, etc. But WorldEdit does not do anything on the Forge side that should really cause this. It's likely that mod using the WorldEdit API and doing it incorrectly.
