### ISSUE TITLE
Right-click action on wand & changing the wand item defunct

### ISSUE THREAD

**Issue by ChipWolf** [EngineHub/WorldEdit#1665]
**Versions**
WorldEdit version: Fabric-Official(7.2.3-SNAPSHOT+5468-7185bcc)

**Describe the bug**
The right-click action on the wand to set the second position doesn't seem to do anything.
Also, changing the wand item in the config doesn't seem to change the wand item.

**To Reproduce**
1. Right-click with a wooden axe
2. Note the second position is not set

> and

1. Set `wand-item=minecraft\:diamond_axe`
2. Restart server
3. Note the wooden axe is still the wand

**Additional context**
We're also using the latest version of [cardboard](https://github.com/CardboardPowered/cardboard) with a single plugin; [voxel-sniper-flattened-backward](https://github.com/mcparkournet/voxel-sniper-flattened)

**Comment by wizjany** [comment]
repro without cardboard?

**Comment by octylFractal** [comment]
also `wand-item=minecraft\:diamond_axe` I don't think that's right, I think the backslash will kill the `:` because the reader already got the `=` separator, just write it without the backslash and see if that works.

**Comment by ChipWolf** [comment]
@octylFractal I assumed a backslash b/c the default value is `wand-item=minecraft\:diamond_axe`

**Comment by ChipWolf** [comment]
> repro without cardboard?
Just checked: in this environment, right-click action works without cardboard. We ended up removing cardboard either way due to a Velocity/FabricProxy conflict.
The issue with changing the wand-item is still present.



> 
> 
> also `wand-item=minecraft\:diamond_axe` I don't think that's right, I think the backslash will kill the `:` because the reader already got the `=` separator, just write it without the backslash and see if that works.
I assumed the slash should stay b/c the default value is `wand-item=minecraft\:wooden_axe`, but I've just tried without and I can still replicate the same  issue

**Comment by octylFractal** [comment]
You might need to just manually rebind it then, just do `/tool none` while holding the wand, then `//wand`, and it should rebind. I can't reproduce the issue in Fabric, I had a wooden axe, changed it in the config, `/we reload`ed, rejoined the world and it was now diamond axe.
