### ISSUE TITLE
Minor issue with //regen

### ISSUE THREAD

**Issue by ProClifo** [EngineHub/WorldEdit#1667]
**Versions**

WorldEdit version: 7.2.2
Platform version: Paper 1.16.5

**Describe the bug**
When using //regen in a different world than the default worlds (overworld, the_nether, the_end), it may regenerate wrong terrain if that world has a different property like seed or world type (default, flat, largeBiomes, etc.)

My main overworld uses the seed 5269245539006863647 with the "largeBiomes" world type. Regenerating in this world works perfectly. My second world uses the seed 5797705914173781750 with the "default" world type. When I use //regen in this second world, it produces terrain as if it were my main overworld.

I'm going to guess that WorldEdit uses information from the server.properties file to determine how the area should be regenerated. If you want regeneration to match additional worlds, it should use the properties that are stored in the level.dat files for each world.

**To Reproduce**

1. Create a world that has a different seed or world type than the server's main worlds
2. Use //regen

**Expected behavior**
I expected the terrain to regenerate according to the properties of the world I was present in.

**Screenshots**
https://i.imgur.com/jOd9Mlf.jpg

In this image, I used //regen to create a cube of forest in the middle of a cold ocean biome.

**Additional context**
This problem is only relevant if you have custom worlds created with Multiverse (or any other world creation plugin) that differ from the properties of your default overworld, nether and end dimension.

**Comment by wizjany** [comment]
Can't reproduce. Your assumptions are wrong, WE doesn't touch files (neither server.properties nor level.dat) at all, it copies the settings from the existing world in memory (which are generally read from level.dat originally, but could in theory be changed at runtime).

I would note that the large biome generator doesn't seem to be deterministic. While the biome was always the same when I regen'ed, I'd get different actual terrains frequently.

There was definitely no crossover between worlds though.
