### ISSUE TITLE
Conflict with CoreProtect & CreeperHeal

### ISSUE THREAD

**Issue by FireController1847** [EngineHub/WorldEdit#1669]
Hello, CoreProtect, WorldEdit, and CreeperHeal developers. I have found a joint issue when using all three plugins together that I'm hoping we can work together to solve.

The issue is that CoreProtect does not log blocks that are broken by fire, water, or lava when all three plugins are installed.

My versions include:
PaperMC 1.16.5 Build 466
CoreProtect 19.4
CreeperHeal 7.0.5 (Jikoo Fork, Release 3) 
WorldEdit 7.2.2

The issue occurs using default configurations. Steps to reproduce are:
1. Create a new server with the corresponding plugins
2. Place a 4x4x1 area of wood planks (or any other burnable substance)
3. Burn it
4. Run `/co rollback radius:10 time:5m user:#fire`
5. Confirm with `/co near` that there are no reports of `#fire broke oak_planks`

I have absolutely no clue what could be causing the issue. At a complete guess, possibly two plugins are blocking some sort of block break event, causing the third (cp) to not detect it. But that's just a guess.

Here are the corresponding issues for the other two plugins:
CoreProtect: https://discord.gg/NvndZ7xM9p (#bugs)
CreeperHeal: https://github.com/Jikoo/CreeperHeal/issues/1

**Comment by wizjany** [comment]
WE doesn't really touch anything in bukkit api outside of player interaction events. If simply being installed is causing this it'd be up to one of those plugins using our API in some weird way.

**Comment by FireController1847** [comment]
I would presume this is primarily a CoreProtect issue, but I figured I'd report it to all three plugins. I find it very strange that the issue does not occur with two plugins specifically, which is what was confusing me. It *must* be all three plugins for the issue to occur

**Comment by wizjany** [comment]
I know coreprotect has WE integration but given that it's closed source I can't offer any insight as to why that would cause other parts of its logging to not work. Perhaps try turning that integration off? Though again can't say if even that is implemented correctly so it might still happen.
