### ISSUE TITLE
1.17 Update Needs

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#1670]
This is a tracking issue for all the stuff that needs to be changed in order to update a platform to 1.17. For details, please see the Fabric platform, where all of this is discovered.

- [ ] Adjust tree types, needs some unwrapping logic
- [ ] Add getMinY implementation in all worlds, maybe to Clipboard as well, possibly remove clamping from Regions as well, maybe change default getMinY and getMaxY of AbstractWorld to min/max integer values.
- [ ] Redo TE sets as fromTag + markDirty, not setLocation + fromTag
- I'm sure there'll be more...

**Comment by AgentLoneStar007** [comment]
Any idea on how long it will be till WorldEdit support for 1.17 drops?

**Comment by octylFractal** [comment]
already did, see discord for dev builds

**Comment by AgentLoneStar007** [comment]
K.
