### ISSUE TITLE
Fabric/Forge Adapter methods for BlockState are inefficient

### ISSUE THREAD

**Issue by wizjany** [EngineHub/WorldEdit#1671]
The `adapter.adapt(BlockState)` methods in Fabric/Forge currently re-apply properties each time instead of using internal ID like bukkit does. Properties should be calculated on first use (possibly in a different place - eg in the platform/using registry events/etc.) and then the mappings from WE<->Native should be stored for use in the `adapt` method.

https://github.com/EngineHub/WorldEdit/blob/7.2.2/worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricAdapter.java#L201
https://github.com/EngineHub/WorldEdit/blob/7.2.2/worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeAdapter.java#L197

_Originally posted by @wizjany in https://github.com/EngineHub/WorldEdit/issues/556#issuecomment-699531987_

**Comment by octylFractal** [comment]
This was merged in 3c161db9a409dd1ee38301eaa32987f24b69b5e2
