### ISSUE TITLE
Commands Missing in Aternos Server

### ISSUE THREAD

**Issue by Awerty16** [EngineHub/WorldEdit#1683]
**1.16.5**
The ax does not work and commands are missing like //cut and commands like that

WorldEdit version:
Platform version:

**Describe the bug**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Awerty16** [comment]
Why did you close?

**Comment by wizjany** [comment]
no info

**Comment by octylFractal** [comment]
also this still isn't a bug, so you'd be better served by following the link to the discord for support
