### ISSUE TITLE
Error trying to move cuboid selection

### ISSUE THREAD

**Issue by Nick2bad4u** [EngineHub/WorldEdit#1684]
**Versions**
22.02 16:47:56 [Server] INFO WorldEdit version 7.3.0-SNAPSHOT
22.02 16:47:56 [Server] INFO https://github.com/EngineHub/WorldEdit/
22.02 16:47:56 [Server] INFO ------------------ Platforms ------------------
22.02 16:47:56 [Server] INFO * Bukkit-Official(7.3.0-SNAPSHOT+5669-2c7ac3d)
22.02 16:47:56 [Server] INFO ---------------- Capabilities ----------------
22.02 16:47:56 [Server] INFO GAME_HOOKS: Bukkit-Official
22.02 16:47:56 [Server] INFO CONFIGURATION: Bukkit-Official
22.02 16:47:56 [Server] INFO USER_COMMANDS: Bukkit-Official
22.02 16:47:56 [Server] INFO PERMISSIONS: Bukkit-Official
22.02 16:47:56 [Server] INFO WORLDEDIT_CUI: Bukkit-Official
22.02 16:47:56 [Server] INFO WORLD_EDITING: Bukkit-Official

**Describe the bug**
Trying to move a building with a chest inside, 1 block north and get: 
Please report this error: [See console]
java.lang.Illegal5tateException: Class
com.sk89q.uorldedit.world.block.BlockState must override com.sk89q.worldedit.uorld.block.BlockStateHolder.toBaseBlockCLazyReference)

**To Reproduce**
Only seems to be affecting selections with chests.

**Expected behavior**
Should move all blocks 1 block unit north.

**Comment by wizjany** [comment]
did you manually type the error in here instead of copying it? please provide the actual server log file

**Comment by octylFractal** [comment]
You're using an outdated dev build, this was already fixed 4 days ago. Please ensure you are running the latest dev build before reporting issues in them.
