### ISSUE TITLE
WE 7.2.3 drops items from containers

### ISSUE THREAD

**Issue by x1p** [EngineHub/WorldEdit#1686]
**Versions**

WorldEdit version: 7.2.3
Platform version: Paper 1.16.5

**Describe the bug**

When deleting chests, the contents drops on the ground.
Causing lag and the possibility that players pick up items when they should not be able to do that.

**To Reproduce**

1. Place a chest with some items
2. Select chest with the wand
3. //set 0
4. check ground

**Expected behavior**

Not drop items from containers

**Screenshots**
![WE-1](https://user-images.githubusercontent.com/28690790/109185605-75c87700-7790-11eb-9f0b-0687b26479e1.png)
![WE-2](https://user-images.githubusercontent.com/28690790/109185607-76610d80-7790-11eb-999b-fe0e5becb49f.png)
![WE-3](https://user-images.githubusercontent.com/28690790/109185609-76610d80-7790-11eb-86f2-663af5448a9a.png)

**Additional context**

Until WE 7.2.2 it worked fine

**Comment by wizjany** [comment]
should be fixed tho I can't test right now, if someone can confirm I can close.

**Comment by x1p** [comment]
I'm not used to building WE and I can't get this build sorted. So perhaps someone familiar building this can give it a small test.

**Comment by RedNesto** [comment]
Hi, I encountered this issue and can confirm @wizjany's fix is working correctly, block entities no longer drop their items.
