### ISSUE TITLE
Allow //setbiome to accept biome IDs in the <target> parameter

### ISSUE THREAD

**Issue by UnIockables** [EngineHub/WorldEdit#1693]
When editing colormaps for resourcepacks with Optifine, the grid format translates each pixels' x coordinate into biome IDs (and the y coordinate refers to the height of the block in the world). It would be beneficial to have the //setbiome command accept biome IDs as well as the biome names for quick testing of colormap changes.

I get that it would be a niche use, but if the current build still supports the old block IDs then I would guess the biome IDs would be possible too?

The biome IDs can be found on the official Minecraft Wiki:
https://minecraft.gamepedia.com/Biome#Biome_IDs

PS thank you all for your hard work and dedication :)

**Comment by wizjany** [comment]
no thanks, we're looking to remove legacy things, not add them.

**Comment by UnIockables** [comment]
Fair enough, thought I'd try anyways. Thanks anyways :)
