### ISSUE TITLE
Make //brush clipboard support a higher radius

### ISSUE THREAD

**Issue by dr-atuti** [EngineHub/WorldEdit#1694]
Today I attempted to copy and paste custom trees I made, using the //brush clipboard command, but it said that I couldn't paste a selection larger than 6... This means that I will have to manually go around doing //paste in areas I want the trees. And I want A LOT of trees. Potentially hundreds.
  Because of this, I think that it would be very useful if this brush supported a much higher radius. 20 minimum, I would say. This would make it much easier to paste custom trees, and even other types of objects in a much shorter amount of time.
  Thinking about this solution, however, made me wonder if it would be possible to actually implement something more like "//brush schematic" or something. This way people could just save their objects (trees in my case) as schematics and just go all around the map pasting the schematics quickly. You wouldn't need to go back to a tree and copy it each time in order to start pasting again, but rather just load the schematic wherever you are and paste the stuff with the brush!
  I hope you understand what I mean by this.
 I would very much prefer a "//brush schematic" over an improved "//brush clipboard", but I imagine the schematic one will be more difficult to make.
 Thanks :)

**Comment by JOO200** [comment]
You can change the max brush radius in the config.
https://worldedit.enginehub.org/en/latest/config/#settings

By default it's limited to 6, but you can take the number you want.

**Comment by dr-atuti** [comment]
How would I edit the config file? Which program would I need to use? I tried it some time ago and it wouldn't open.

**Comment by wizjany** [comment]
You should really read the docs that were linked. Further questions should be directed to discord as this is an issue tracker and not a support board.

**Comment by dr-atuti** [comment]
I have, and it doesn't seem to have anything about opening .properties files. I have searched for this before, but nothing seems to have worked.
