### ISSUE TITLE
Grand failure on Spigot start-up

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldEdit#1700]
### WorldEdit Version

WorldEdit-bukkit-7.3.0-SNAPSHOT-dist  b5707 or b5708

### Platform Version

3019-Spigot-bff5261-ee5006d (MC: 1.16.5)

### Bug Description

WorldEdit triggers spectacular start-up failure on Spigot 1.16.5-3019. It loads fine on Paper 1.16.5-542. WE build 5705 loads fine. Basically, plugins that depend on WE fail, and server start-up fails overall.

Log available on request.

### Expected Behavior

Not that. :)

### Reproduction Steps

1. Update WE to b5707 (or b5708)
2. Start server

**Comment by octylFractal** [comment]
yea a log would be nice, otherwise I've got no clue what could be happening

**Comment by SlimeDog** [comment]
AFK for a few hours, but will do.

**Comment by wizjany** [comment]
yea can't repro on given versions.

**Comment by SlimeDog** [comment]
http://blackdog.straight8.com/drops/WE-5707.log
after which the server is dead. Please let me know when you've got it, so I can delete it. And good hunting.

**Comment by wizjany** [comment]
`nl.zandervdm.stayput` is blocking main thread with DB queries on startup. nothing to do with WE here.

**Comment by SlimeDog** [comment]
I removed StayPut. Then the same sorts of errors were reported in Residence.
I removed Residence. Then the same sorts of errors were reported in BiomeFinder.
I removed BiomeFinder. Then the same sorts of errors were reported in Residence.
I could go on, but you get the idea.

If I revert to WE build 5705, with everything else back in place, there are no issues. Please help me understand.

**Comment by SlimeDog** [comment]
I appreciate that I'm seeing some kind of interaction effect. If I remove all plugins except WE, the server starts up. I will run more isolations.
