### ISSUE TITLE
Auto tab complete error

### ISSUE THREAD

**Issue by Henriiig** [EngineHub/WorldEdit#1701]
### WorldEdit Version

Bukkit-Official(7.3.0-SNAPSHOT+5599-c4efc8b)

### Platform Version

git-Paper-545

### Bug Description

When trying to set a block such as white stained glass pane with the following command:
//set white_stained_glass_pane[west=True]
The chat is spammed with "An internal error occurred wile attempting to tab-complete this command". This only happens when some of the letters in the command are capitalized.

Pastebin:
https://pastebin.com/7TJcQdwg

### Expected Behavior

The chat should not be spammed and the capitalized letter should be ignored

### Reproduction Steps

Type the following command //set white_stained_glass_pane[west=true] (or probably also similar ones) and try editing fx. the word "true" to "True", "trUe" etc.

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/WorldEdit/commit/4cd7dc4bcdfaddf4efc5261a917068022c9b1658
