### ISSUE TITLE
Worldedit conflicts with McMMO /inspect command

### ISSUE THREAD

**Issue by Pabsb** [EngineHub/WorldEdit#1703]
### WorldEdit Version

7.2.3

### Platform Version

Paper-545

### Bug Description

World edit conflicts with McMMO inspect command

### Expected Behavior

When inspecting a player with /inspect it should show their McMMO stats and not bring up world edit

### Reproduction Steps

1. Install World Edit
2. Install McMMO
3. Try to /inspect a player

Option to disable /inspect WE command or compatibility to recognize if McMMO is enabled and don't intercept the command for WE

**Comment by wizjany** [comment]
we don't have an inspect command, so not sure what you're talking about.

**Comment by kashike** [comment]
This is a command added by [FastAsyncWorldEdit](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolCommands.java#L209-L217).

**Comment by octylFractal** [comment]
Thanks for the confirmation kashike.
