### ISSUE TITLE
Cylindrical selector: Unable to use 0,0,0 as center

### ISSUE THREAD

**Issue by JOO200** [EngineHub/WorldEdit#1706]
### WorldEdit Version

7.2.4

### Platform Version

Paper 1.16.5

### Bug Description

I'm unable to use 0,0,0 as center for cylindrical selections.

### Expected Behavior

Working cylindrical selection

### Reproduction Steps

1. //sel cyl
2. //pos1 0,0,0
3. //pos2 1,0,0
--> Error message

![grafik](https://user-images.githubusercontent.com/15250323/111444490-b3bf1800-870a-11eb-9191-8422a55c23a6.png)

**Comment by octylFractal** [comment]
Done in #1734
