### ISSUE TITLE
worldedit-core pom is not deployed

### ISSUE THREAD

**Issue by wizjany** [EngineHub/WorldEdit#1708]
### WorldEdit Version

7.2.4-SNAPSHOT, 7.2.4, 7.2.5-SNAPSHOT, 7.3.0-SNAPSHOT

### Platform Version

Maven Repo

### Bug Description

The `worldedit-core-<version>.pom` file is not deployed to the maven repository for the worldedit-core artifact via the TeamCity deployment build.

### Expected Behavior

The pom file is present in the maven repository.

### Reproduction Steps

1. https://maven.enginehub.org/repo/com/sk89q/worldedit/worldedit-core/7.2.4-SNAPSHOT/ (as of Mar 10th builds)
2. https://maven.enginehub.org/repo/com/sk89q/worldedit/worldedit-core/7.2.4/
3. https://maven.enginehub.org/repo/com/sk89q/worldedit/worldedit-core/7.2.5-SNAPSHOT/
4. Also affects master, likely as of being merged from the 7.2.x branch: https://maven.enginehub.org/repo/com/sk89q/worldedit/worldedit-core/7.3.0-SNAPSHOT/

Suspect commit is https://github.com/EngineHub/WorldEdit/commit/0b2d992a5d30fa1efc35c7fca5421a28f03502be
This is the first commit which did not deploy a pom file with the build.

**Comment by octylFractal** [comment]
Fixed with #1718
