### ISSUE TITLE
WorldEdit 7.2.4 and 7.2.3 crashes when loading world

### ISSUE THREAD

**Issue by mikkolukas** [EngineHub/WorldEdit#1709]
### WorldEdit Version

7.2.4+5723-e3bfc64 and 7.2.3+5680-135941e

### Platform Version

Forge 36.1.1 and 36.1.0

### Bug Description

WorldEdit 7.2.4 and 7.2.3 crashes when loading world.
WorldEdit 7.2.2 does not crash.

* Windows 10, updated.
* AdoptOpenJDK Hotspot 1.8 (jdk8u282-b08)
* Updated MultiMC
* Minecraft 1.16.5
* Freshly downloaded WorldEdit .jar-files from curseforge

I am using MultiMC, ~~and have not tested the behaviour with the vanilla launcher as this probably wouldn't make a difference.~~
_EDIT: It turns out that it indeed **is** a conflict when using MultiMC.
But I don't know if it is MultiMC that fails or it is MultiMC that trips over an error induced by WorldEdit._

All combinations of above mentioned configurations have been tested separately on clean Minecraft instances, as to make sure no old data was lingering and no other mods were to blame.

A combination of Forge 36.0.63 and WorldEdit 7.2.4 has also been done and does also crash.

Log for the combination of Forge 36.1.1 and  WorldEdit 7.2.4 is available at:
https://paste.ee/p/uwfKT

### Expected Behavior

Loading world without crash.

### Reproduction Steps

1. Create a new Minecraft 1.16.5. instance
2. Add Forge 36.1.1 or 36.1.0
3. Add WorldEdit 7.2.4 or 7.2.3
4. Launch the Minecraft instance
5. Create a new world or load an existing one.
6. Watch the loading percentage reach 100%
7. Game crashes to desktop.

**Comment by me4502** [comment]
This error has only ever been seen with MultiMC, so it's quite possible it's a MultiMC bug.

**Comment by mikkolukas** [comment]
> This error has only ever been seen with MultiMC, so it's quite possible it's a MultiMC bug.

oh, I had no idea that it actually made a difference o.O

**Comment by octylFractal** [comment]
Please try the following JAR to see if it resolves your issues.

https://ipfs.octyl.net/ipfs/QmTtgrHtW6HsKN8ZKGyKeqMoVie2E6u4tUNDySUR2GNhRq?filename=worldedit-mod-7.2.5-SNAPSHOT-dist.jar

If so, I will consider this fixed when #1715 is merged.

**Comment by mikkolukas** [comment]
> If so, I will consider this fixed when #1715 is merged.

The linked jar works :)
(tested with Forge 36.1.1 and 36.1.2)

Thank you for a fast reply and fix - and for this excellent mod. You guys are really great! :)

**Comment by octylFractal** [comment]
(leaving this open until PR merges)

**Comment by Godlycreations** [comment]
I am getting this same error while using PaperMC builds 611, 612, and 613. I have tried all WE versions from 7.2.2 to 7.2.5 including the snapshot version posted above and I am still having this issue occur on all 12 of our MC servers. While I was troubleshooting this issue on our network, I came across the following and thought that it may assist you as well. I am not sure what version you are calling in your dependencies, but it may be worth looking into. If there is anything else that you need from me, please let me know.

https://stackoverflow.com/questions/52700803/im-getting-noclassdeffounderror-org-apache-logging-log4j-util-reflectionutil

**Comment by wizjany** [comment]
I mean, this issue won't occur with the current versions of WE. Either you're not actually using an up-to-date version, or your issue is not this issue.

**Comment by Godlycreations** [comment]
I downloaded the jar files directly from this site, 7.2.2 - 7.2.3 - 7.2.4 - and 7.2.5

**Comment by wizjany** [comment]
"this" site does not host downloads, only source code. There is no mistake here. Please use discord for further questions.
