### ISSUE TITLE
calling a function and immediately reloading causes all worledit commands to disappear

### ISSUE THREAD

**Issue by Ronezkj15** [EngineHub/WorldEdit#1710]
### WorldEdit Version

7.2.3

### Platform Version

1.16.5-Forge-36.0.46

### Bug Description

when /reload is entered after immediately calling a function, all world edit commands disappear. Typing anything related to any worldedit command shows an unknown command, and if you use it as it would, it will treat it as an unknown command. The only way to work around this is to re-enter the world.

### Expected Behavior

/reload should not be able to affect commands from what I know, so nothing should have changed when /reload was entered.

### Reproduction Steps

1. Log into any world and get any datapack that has runnable functions. Run it and quickly type in /reload and hit enter.
2. attempt to do a world edit command, or just simply type in //.

**Comment by wizjany** [comment]
#1626
