### ISSUE TITLE
I have 2 selwands

### ISSUE THREAD

**Issue by enderson0** [EngineHub/WorldEdit#1717]
### WorldEdit Version

7.2.0

### Platform Version

Paper

### Bug Description

I have 2 selwands for some reason, 2 different texts.
I bound selwand to a Carrot on a Stick, but the iron axe i bound it to earlier still works, but it doesnt. I cant use worldedit commands with the axe, but it still blocks me out of mining or stripping logs.

### Expected Behavior

I SHOULD only have 1 selwand, and the second one shouldn't exist

### Reproduction Steps

Not sure

https://ibb.co/m0w4v1c

**Comment by octylFractal** [comment]
That other one is not a WorldEdit selwand, no idea what it is but it is definitely not WorldEdit.
