### ISSUE TITLE
WE conflicts with /cs carpet script

### ISSUE THREAD

**Issue by Syntro42** [EngineHub/WorldEdit#1719]
### WorldEdit Version

7.2.0-7.2.4

### Platform Version

Fabric 0.11.0

### Bug Description

The /cs command from Worldedit does not allow a /cs carpet script command to function. 

### Expected Behavior

/cs command from a carpet script to function instead of the /cs from worldedit

### Reproduction Steps

1. Go into a singleplayer world while having WE 7.2.4 and Fabric-Carpet 1.4.29 in your mods list as well as a carpet script that uses the /cs command to function (such as: https://github.com/gnembon/fabric-carpet/wiki/Cam-app; rename the script to cs) in your world save folder
2. Type '/script load cs'. Log out. Type '/cs' and observe that the script does not stay loaded (even with /carpet scriptsAutoload true)

**Comment by octylFractal** [comment]
Solution: don't name it a conflicting name. WorldEdit is not going to move out of the way for every random script people might have, especially if you can freely rename it.

**Comment by me4502** [comment]
I don't exactly understand this issue? It sounds like you chose to cause a conflict here?

Fabric does not include a way of mitigating command collisions, so there's nothing we can really do here.
