### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by Meiscool125** [EngineHub/WorldEdit#1720]
### WorldEdit Version

Minecraft 1.16.5 Java

### Platform Version

Forge

### Bug Description

Whenever I try to use it, the commands dont work. They dont show up. When I type //wand, it gives me the normal error message from Vanilla MC.

### Expected Behavior

I wanted the commands to work

### Reproduction Steps

1. Open world
2. WorldEdit not working

**Comment by wizjany** [comment]
use discord for support
