### ISSUE TITLE
WorldEdit is dropping Blocks

### ISSUE THREAD

**Issue by Deaclya** [EngineHub/WorldEdit#1724]
### WorldEdit Version

 7.2.4

### Platform Version

Paper 1.13.2

### Bug Description

I dont know how to explain, so i made a Video:

https://youtu.be/fQQaie-G0TI

please watch it, i think you guys can see the Problem.

My Server is on the 1.13.2 Paper Version

Pluginlist:

 EssentialsXChat-2.18.2.0.jar | 08.04.2021 16:23:10
EssentialsXProtect-2.18.2.0.jar | 08.04.2021 16:23:10
 EssentialsXSpawn-2.18.2.0.jar | 08.04.2021 16:23:11
 Expansion-PowerRanks.jar | 08.04.2021 18:44:33
 Multiverse-Core-4.2.2.jar | 08.04.2021 17:22:56
 PlaceholderAPI-2.10.9.jar | 09.04.2021 23:05:49
PlotSquared-Bukkit-5.13.11-Premium.jar | 08.04.2021 17:58:46
PowerRanks.jar | 08.04.2021 16:25:21
Scoreboard-revision.jar | 08.04.2021 18:22:22
Vault.jar | 08.04.2021 16:24:58
ViaVersion-3.2.1.jar | 08.04.2021 16:21:41
  worldedit-bukkit-7.2.4.jar | 09.04.2021 22:57:29
  worldguard-bukkit-7.0.0.jar

### Expected Behavior

Not this xD

### Reproduction Steps

Watch the Video

**Comment by wizjany** [comment]
#1586 ?
it was definitely fixed so you're either not on the version you say you are or something else broke in which case i'm definitely not gonna go back and figure out what since as mentioned you're on an unsupported version.

**Comment by Deaclya** [comment]
> #1586 ?
> it was definitely fixed so you're either not on the version you say you are or something else broke in which case i'm definitely not gonna go back and figure out what since as mentioned you're on an unsupported version.

https://prnt.sc/11933it

Its 100% paper 1.13.2

**Comment by Deaclya** [comment]
Bad Support

**Comment by octylFractal** [comment]
As stated on the linked issue, "Going to close this as we only support the latest version of Minecraft." It is not "bad support" to declare versions from years ago unsupported, it is us managing the resources we have.
