### ISSUE TITLE
copy and paste bug 

### ISSUE THREAD

**Issue by monmonmonika** [EngineHub/WorldEdit#1726]
### WorldEdit Version

6.1.10

### Platform Version

forge 1.12.2

### Bug Description

trying 2 copy and paste a house from one world to another, when the schematic is loaded and pasted in the world i want it is only loaded halfway? not sure how else to describe that part, but when it is pasted in another world it loads fine. any ideas on what is causing this? 

### Expected Behavior

i expected the entire thing to be pasted yknow? sorry this isnt very professional HAHAH

### Reproduction Steps

1. i copy the house
2. saved the schematic 
3. pasted into the desired world
4. ended up glitched and halfway pasted
5. pasted in another world
6. worked out fine

**Comment by wizjany** [comment]
unsupported version
