### ISSUE TITLE
Will you please make it so that we can copy, paste, and stack entities in forge 1.12.2?

### ISSUE THREAD

**Issue by mrgallop** [EngineHub/WorldEdit#1728]
### The Problem

    I am making this building of an apartment complex, and I'm using maps in item frames to use as custom paintings. I'm making wallpapers, a/c units, and wall tiles. I can't stack, copy, or paste item frames because they are entities, so I have to add them all individually which is annoying, especially when placing wallpaper. I used the 1.16.3 version which did have the feature   for entity clip boarding. But I also use this furniture mod that loses a ton of features for 1.16.3, and I can't seem to find any more mods that have some of the missing features. So I went back to 1.12.2, and I'm kind of stuck here. 

### A Solution

    WorldEdit 6.1.10 doesn't have the feature for entity clip boarding, so in the meantime I'll have to add them all individually by hand. When you get the chance, will you please make it so that we can copy, paste, and stack entities in forge 1.12.2?
Thank you for your time.

**Comment by me4502** [comment]
This is firstly not true, it does.

Either way. We do not provide support for archaic versions of the game nor WorldEdit.
