### ISSUE TITLE
Removing a WorldEdit's player entity raises an UnsupportedOperationException

### ISSUE THREAD

**Issue by JOO200** [EngineHub/WorldEdit#1729]
### WorldEdit Version

7.2.4

### Platform Version

Spigot and Paper

### Bug Description

Removing an entity of type player doesn't work. Spigot is unable to remove a player for obvious reasons.

WorldEdit's [Entity.remove()](https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/entity/Entity.java#L55) will create a UnsupportedOperationException for player types.

### Expected Behavior

As discussed in the discord removing players should return "false" instead of raising an exception.

### Reproduction Steps

Use the following snippet in some bukkit plugin:
```java
BukkitAdapter.adapt(player).remove();
```

**Comment by orrinpants** [comment]
WTF I CANNOT ADD AN ISSUE
