### ISSUE TITLE
WE Crashed the game

### ISSUE THREAD

**Issue by Vojlas** [EngineHub/WorldEdit#1732]
### WorldEdit Version

7.2.4. Forge

### Platform Version

Forge 36.1.4.

### Bug Description

Well... I made a modpack for myself with few mods (47 total). I run the game everything was fine until I created new world. It reached 100% and then crashed I coud see in console that was some kind of error with WE.

### Expected Behavior

Normaly create new word withou crashing the game.

### Reproduction Steps

Create new word. With these mods (shown in screenshot):
![Snímek obrazovky (13)](https://user-images.githubusercontent.com/59581113/115160154-09366e00-a097-11eb-90a3-5233c7b3ecc9.png)

**Comment by wizjany** [comment]
provide error logs. we're not going to recreate your modpack just to figure out what might be wrong.

**Comment by Vojlas** [comment]
Sorry for not provide any logs I noticed that immediately after I post the Issue. 
Log from multi MC:
[logMultiMC.txt](https://github.com/EngineHub/WorldEdit/files/6332169/logMultiMC.txt)

Crash report that was generated:
[crash-2021-04-18_22.33.22-server.txt](https://github.com/EngineHub/WorldEdit/files/6332175/crash-2021-04-18_22.33.22-server.txt)

**Comment by wizjany** [comment]
#1709

**Comment by Vojlas** [comment]
Thanks for help and sorry for duplicate
