### ISSUE TITLE
Crashed Upon World Generation

### ISSUE THREAD

**Issue by TheRealAtrocities** [EngineHub/WorldEdit#1733]
### WorldEdit Version

1.16.5

### Platform Version

Forge 36.1.0 to 36.1.4

### Bug Description

Fresh install of Minecraft 1.16.5 using MultiMC with Forge 36.1.0 installed.  Game launches and worlds can be generated no issue.  Install WorldEdit version WorldEdit 7.2.4 (Forge/Fabric for MC 1.16.3/1.16.4/1.16.5 into mod folder and run.  Minecraft loads just fine. However, when trying to enter any world results in crash once the world generation hits 100%.  Same issue for creating new worlds.  

### Expected Behavior

The world to load or be generated and then loaded.

### Reproduction Steps

1. Using MultiMC - or Vanilla Minecraft Launcher 
2. Create new Instance of Minecraft 1.16.5
3. Enable or install Forge (36.1.0 or later)
4. Run Minecraft
5. Open Mods Folder
6. Place WorldEdit 7.2.4 (Forge/Fabric for MC 1.16.3/1.16.4/1.16.5) into mods folder
7. Exit Minecraft
8. Restart Minecraft
9. Select Single Player
10. load world or Create New world

**Comment by TheRealAtrocities** [comment]
SOLVED -  Version conflict.  Used version WorldEdit 7.2.2 (Forge for MC 1.16.3/1.16.4/1.16.5) and no more crashes

**Comment by wizjany** [comment]
prob 1709
