### ISSUE TITLE
Server lags

### ISSUE THREAD

**Issue by epserv** [EngineHub/WorldEdit#1737]
### WorldEdit Version

Bukkit-Official(7.2.4+5723-e3bfc64)

### Platform Version

git-Yatopia-ver/1.16.5-79

### Bug Description

Sometimes WorldEdit (according to timings WorldEdit causes lag) starts causing huge lags. Nobody/nothing uses it when it starts lagging. `/plugman reload WorldEdit` helps.

### Expected Behavior

WorldEdit works perfectly without any server lag.

### Reproduction Steps

I don't know why it happens and how to reproduce it.

### Anything Else?

Timings: https://timings.aikar.co/?id=8e43fb7a3c884d99a3a3021f894e4409
Spark report: https://spark.lucko.me/#L88QRcWKGo

Tested on paper today, it happens.

Ask me if more info is needed.

**Comment by wizjany** [comment]
#1722

**Comment by octylFractal** [comment]
This is just #1722 but tbh it seems like Brigadier is causing more lag that WorldEdit here. Can you provide the full details of the JDK you're on, your GC flags, and the OS you're running on?
