### ISSUE TITLE
Regen IllegalStateException on 1.16.5 

### ISSUE THREAD

**Issue by timepieces141** [EngineHub/WorldEdit#1739]
### WorldEdit Version

7.2.4

### Platform Version

Forge 1.16.5-36.1.0

### Bug Description

I tried to do a `\\regen` in the Nether and received an `IllegalStateException.: Regen Failed`. I found the bug report  for an older version that said it might be a mod conflict, so I removed the few other mods I had and tried again. Same issue. The mods that I used in the world were:

- architectury-1.12.145-forge
- cloth-config-4.11.19-forge
- light-overlay-5.8.0
- WorldEdit-CUI-FE3-1.16.5-3.0.9
- worldedit-mod-7.2.4

... just in case one of those "contaminated" the world previously and the conflict still existed regardless of the mods being removed. Also, this line in the log:
`Caused by: java.lang.IllegalStateException: Unable to map GeneratorOptions: Unknown tag: net.minecraft.tags.Tag@e795a1d; Unknown tag: net.minecraft.tags.Tag@e795a1d; Unknown tag: net.minecraft.tags.Tag@e795a1d; Unknown tag: net.minecraft.tags.Tag@e795a1d; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e; Unknown tag: net.minecraft.tags.Tag@5e24592e`
... made me thing there were unknown blocks the mod did not know how to replace/regenerate.

### Expected Behavior

Select the region, run the regen command, see the "air" region return to the originally generated terrain.

### Reproduction Steps

1. Load up a world
2. Travel to the Nether
3. Select a region
4. Set the region as a block or set of blocks distinguishable from the original terrain
5. Using the same region, use the regen command

**Comment by wizjany** [comment]
soooo you found the issue and made a duplicate anyway?

**Comment by timepieces141** [comment]
> soooo you found the issue and made a duplicate anyway?

No? It's for a different version _and_ I ruled out the collision with other mods.

**Comment by octylFractal** [comment]
> just in case one of those "contaminated" the world previously and the conflict still existed regardless of the mods being removed

probably this

**Comment by wizjany** [comment]
Not sure why being a different version matters given that the original issue wasn't fixed. At *most* you could comment on the original that you still get the issue on a newer version, but since it was never fixed that's the expected result...

And yes as octy said, you didn't rule out a mod conflict. You would need to make a new world with only WE installed and then try regen to rule out mod conflicts due to the way data is stored in worlds.
