### ISSUE TITLE
World Edit Plugin Won’t Load

### ISSUE THREAD

**Issue by MysteryTimeTrav** [EngineHub/WorldEdit#1740]
### WorldEdit Version

7.2.2

### Platform Version

Paper 629

### Bug Description

The plugin doesn’t appear to start as it says “Could not load”

paste for the error 
https://pastebin.com/h3T7MeCf

### Expected Behavior

Plugin should start up

### Reproduction Steps

1. Load server

### Anything Else?

Add any additional context you can provide below.

**Comment by JOO200** [comment]
Worldedit 7.2.2 is outdated, you should update to 7.2.5
