### ISSUE TITLE
The maximum selection area of the structure blocks is outdated

### ISSUE THREAD

**Issue by SolrzING** [EngineHub/WorldEdit#1741]
### WorldEdit Version

7.2.5

### Platform Version

Fabric

### Bug Description

Since the version of **Minecraft 1.16**, the **maximum limit** of **structure blocks** has been increased, going from **32x32x32** to **48x48x48**, however when a selection greater than 32 blocks is made, it is not indicated as it should

### Expected Behavior

Selections greater than 32 blocks and less than or equal to 48 blocks should be marked with the structure blocks in any of the axes.

### Reproduction Steps

1. Run the command **//drawsel**
2. Make a selection greater than 32 blocks

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
this is currently intended since we somewhat-maintain compat for 1.13/1.14/1.15. we either need to split sizes based on platform version or make the decision to make it non-functional on older versions.

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/WorldEdit/commit/8b38f6fbc00619b9f7deeb211b6f429857c0e8a1
