### ISSUE TITLE
Exception when executing most of worldedit command

### ISSUE THREAD

**Issue by RiccardoBarbieri** [EngineHub/WorldEdit#1743]
### WorldEdit Version

Forge-Official 6.1.8

### Platform Version

Forge 1.12.2-14.23.5.2854

### Bug Description

When executing commands like `/biomelist` or `//setbiome PLAINS` I get this message:
Please report this error: [See console]
java.lang.reflect.InvocationTargetException: null
When looking at the server console I didn't notice anything related to this message.

### Expected Behavior

Expected the list of biomes.

### Reproduction Steps

1. Install worldedit for Forge 1.12.2-14.23.5.2854 server
2. Select region
3. Prompt `//setbiome  PLAINS` command

**Comment by wizjany** [comment]
old versions aren't supported

**Comment by RiccardoBarbieri** [comment]
Where can I get newer version's .jar files?
