### ISSUE TITLE
latest forge release has no commands available

### ISSUE THREAD

**Issue by joeyjumper94** [EngineHub/WorldEdit#1744]
### WorldEdit Version

version 7.2.5+57d5ac9

### Platform Version

forge-36.1.0

### Bug Description

no commands are available at all, even with operator status on the server

### Expected Behavior

i would expect the regular world edit commands to become available when the mod is installed.
commands like //pos1 or /we

### Reproduction Steps

1. download world edit mod version 7.2.5+57d5ac9 from https://www.curseforge.com/minecraft/mc-mods/worldedit/download/3283693
2. start your forge server

### Anything Else?

i had to look through the latest.log to find out what version it was since i could not run "/we version"

**Comment by wizjany** [comment]
please join discord for support.

**Comment by joeyjumper94** [comment]
you want to hear something funny? it seems that it somehow refused to load the commands when it was initally added, but after a restart it was working.
