### ISSUE TITLE
//undo does not work on tool tree

### ISSUE THREAD

**Issue by SecretlyJealous** [EngineHub/WorldEdit#1745]
### WorldEdit Version

Bukkit-Official(7.2.5+57d5ac9)

### Platform Version

paper-1.16.5-652

### Bug Description

When using `/tool tree` I cannot use `//undo`
![2021-05-09_16 44 04](https://user-images.githubusercontent.com/10485646/117578337-c7bd3f80-b0e5-11eb-8f31-2a27e829761b.png)

I'm also unsure why it says "A tree can't go there" but does the edit anyway.

### Expected Behavior

//undo should undo the edit

### Reproduction Steps

1. Do /tool tree
2. Do //undo

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
the tree can't go there message is unrelated, it's due to the client sending a second interact after the tree is already placed.

that said can't repro, undo works fine on trees from the tool, forest, and forestgen...can only guess there's something else going on you didn't cover in your report.

**Comment by SecretlyJealous** [comment]
My current plugins are:
Plugins (4): BungeeGuard, LuckPerms, spark, WorldEdit
I've deleted the WorldEdit folder to generate new default configs but I'm still unable to //undo on /tool tree - do you have any advice on how I can better debug this issue?

**Comment by wizjany** [comment]
potentially a bug in spigot/paper? i tend to not update my test server very often. working fine in paper 588 anyway.

**Comment by wizjany** [comment]
yup, looks like spigot just removed the delegate usage, nice.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/28d72c4bd8c22f568384560459d0d703c2d0fefe

**Comment by Louisover** [comment]
but this bug also appeared on Forge_WorldEdit，not only on spigot or paper🤔

**Comment by me4502** [comment]
Forge never supported this. Spigot used to, but they broke support for it.
