### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by hjhyhg** [EngineHub/WorldEdit#1748]
### WorldEdit Version

latest

### Platform Version

fabric

### Bug Description

i got like 0 fps

### Expected Behavior

when i downloaded the mod i got 0 fps when i loaded minecraft up even on the main menu

### Reproduction Steps

1. ...
2. ...

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
this isn't even close to being a bug report never mind that worldedit doesn't even do anything until you at least load into a world

**Comment by hjhyhg** [comment]
> this isn't even close to being a bug report never mind that worldedit doesn't even do anything until you at least load into a world

i think it is another mod then interfering with world edit

**Comment by hjhyhg** [comment]
> this isn't even close to being a bug report never mind that worldedit doesn't even do anything until you at least load into a world

then it is another mod messing with world edit
