### ISSUE TITLE
//regen acts different depending on the chunk the selection is in.

### ISSUE THREAD

**Issue by helpimnotdrowning** [EngineHub/WorldEdit#1751]
### WorldEdit Version

7.2.5

### Platform Version

Fabric-Official(7.2.5+57d5ac9)

### Bug Description

//regen regenerates differently depending on wether the selection is contained entirely within one chunk or not, but only on some chunks.

### Expected Behavior

//regen should act the same no matter where the selection is in.

### Reproduction Steps

1. Make Superflat world using "overworld" preset
2. Find lake
3. `//regen`, but keep the selection inside of a single chunk
4. 
![image](https://user-images.githubusercontent.com/35247379/118896461-eaadd780-b8cd-11eb-906f-2f1ec690fcdb.png)
becomes
![image](https://user-images.githubusercontent.com/35247379/118896479-f39ea900-b8cd-11eb-8c26-bbbbe45c968c.png)
, but expanding the selection 1 block to the left regens the lake like normal.
![image](https://user-images.githubusercontent.com/35247379/118896560-22b51a80-b8ce-11eb-9499-7a3173a0cd16.png)

 

### Anything Else?

It only work in certain chunks, but I have no idea how to tell those apart.

**Comment by wizjany** [comment]
pretty sure this is just a consequence of how world gen/feature placement works. we really don't make any guarantees as to how regen will behave since it's entirely up to the underlying world generator.
