### ISSUE TITLE
Data universal ?

### ISSUE THREAD

**Issue by Pantyhose-X** [EngineHub/WorldEdit#1753]
### The Problem

Minecraft WorldEdit to [Minetest-WorldEdit](https://github.com/Uberi/Minetest-WorldEdit) Data universal ?

### A Solution

https://forum.minetest.net/viewtopic.php?f=11&t=572

### Anything Else?

Add any additional context you can provide below.

**Comment by octylFractal** [comment]
I'm not sure what you're asking for here.

**Comment by Pantyhose-X** [comment]
> I'm not sure what you're asking for here.

Minecraft Building Numerical Reconstruction in [MineTest](https://forum.minetest.net/viewtopic.php?f=11&t=572)

**Comment by wizjany** [comment]
that project has nothing to do with us, they just stole our name.
