### ISSUE TITLE
schematic light bug (45 degree paste)

### ISSUE THREAD

**Issue by iElijahx** [EngineHub/WorldEdit#1754]
### WorldEdit Version

Bukkit-Official(7.3.0-SNAPSHOT+5775-ec2fb07)

### Platform Version

git-Paper-685

### Bug Description

[https://www.youtube.com/watch?v=F0cSjvObGfE](url)
this video shows an odd light bug when pasting a loaded tree schematic. the light issue only occurs when pasted at a 45 degree angle. anything like 90 or 180 degrees is normal and doesn't have this issue. tried to use /paper fixlight and /cleanlight  with light cleaner plugin, but nothing has fixed this.

here's the schematic file : [https://www.dropbox.com/s/52mz6s93gokeab0/smalltree.schem?dl=1](https://www.dropbox.com/s/52mz6s93gokeab0/smalltree.schem?dl=1)

### Expected Behavior

On paste at a 45 degree angle there should show some shadows

### Reproduction Steps

1. ...install worldedit dev build7.3.0-SNAPSHOT+5775-ec2fb07 + schem to server
2. ...startup server and login
3. ...use //schem load smalltree
4. ...//paste as normal on an empty space
5. ...then move over to a new spot and //rotate 45 then //paste
6. ...shadows should not appear
7. 
![2021-05-20_10 35 42](https://user-images.githubusercontent.com/65664977/119029894-14164400-b95e-11eb-9430-7201369dc4d3.png)

**Comment by wizjany** [comment]
lighting is being updated fine, it's just not very visible here due to gaps in the foliage due to the rotation.

![](https://i.imgur.com/LDEsnRE.png)

also since the leaves aren't persistent the holes get worse and worse (on *both* rotated and non-rotated trees) so there is progressively less shadow.
