### ISSUE TITLE
World Edit is causing items to have the same ID and crashing 

### ISSUE THREAD

**Issue by no82133** [EngineHub/WorldEdit#1755]
### WorldEdit Version

7.2.5-dist

### Platform Version

Forge

### Bug Description

The server crashes at random points with an IllegalStateException.  This can happen with our without players online.  I talked to the biomes o plenty creators and they informed me that this is not a bop error but an issue with something overwriting their items and putting "minecraft" in front.  World edit is found in the crash report and is the only mod on the server that seems to know that these problematic items exist.  How do I change the ID names to prevent this?  

https://pastebin.com/5zr3TZVW
https://pastebin.com/6MDg1A83

### Expected Behavior

No crashing.  The crash causes the entire server to shut down until we restart it manually.  

### Reproduction Steps

1. cannot be reproduced because it happens whenever the server tries to access these items with worldedit.  I have seen it happen with no one online.  

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
we don't touch items or blocks whatsoever. we literally only ever read from the registry.

**Comment by octylFractal** [comment]
You're running mohist, hybrids aren't supported and likely the cause of this issue.
