### ISSUE TITLE
//setbiome does not work

### ISSUE THREAD

**Issue by mineland-0066** [EngineHub/WorldEdit#1756]
### WorldEdit Version

7.2.5

### Platform Version

Fabric 0.11.3

### Bug Description

The //setbiome command does not work. It shows an error in chat when trying to use it (java.lang.NullPointerException)

### Expected Behavior

The biome was supposed to change to the one specified.

### Reproduction Steps

1. Select an area to change biome
2. use the //setbiome command
3. see the error

### Anything Else?

[latest.log](https://github.com/EngineHub/WorldEdit/files/6529011/latest.log)
(ignore the big ammount of missingno sprite errors at the start, those are from another mod)

![2021-05-23_17 39 08](https://user-images.githubusercontent.com/60583383/119278896-dcbdc680-bbed-11eb-9929-09fe28ee4d5e.png)
screenshot of the fail

[mod list.txt](https://github.com/EngineHub/WorldEdit/files/6529039/mod.list.txt)
list of mods installed

**Comment by octylFractal** [comment]
To my knowledge, that field literally cannot be `null` in normal Minecraft, so one of your mods is conflicting. No idea which one it could be, possibly carpet.

**Comment by mineland-0066** [comment]
hm, got to try it again without carpet, same result, same error. going to be trying it on a fabric server with only world edit now

**Comment by mineland-0066** [comment]
tried it on a server with only world edit and it seems that it was indeed some conflicting mod. Not carpet tho, moved it out and the error still happened on my local world. Gotta check which mod was it now then...
