### ISSUE TITLE
My axe, is always a wand

### ISSUE THREAD

**Issue by yentdevries1270** [EngineHub/WorldEdit#1757]
### WorldEdit Version

7.2.4

### Platform Version

Fabric 1.16.5

### Bug Description

when i'm in survival, and i craft an axe, when i left click it will do the same behaviour as a wand. how do i fix this? 

### Expected Behavior

when i hit a block with an axe it wont select it as position 1, even in survival

### Reproduction Steps

1. ...
2. ...

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
unbind the tool? I mean despite being in survival you obviously had permission to use it as an axe, so this is more an issue with your setup.
