### ISSUE TITLE
Game does not launch with WorldEdit/ModernIndustrialization installed

### ISSUE THREAD

**Issue by Snowolf2001** [EngineHub/WorldEdit#1759]
### WorldEdit Version

7.2.5

### Platform Version

Fabric 0.11.3

### Bug Description

I have a good 180-something mods on my minecraft fabric installation and worldedit definitely worked in the past but i uninstalled it. upon reinstallation my game refuses to launch and it claims that the crash is caused by these other mods, so i removed all the mods and left world edit in, and it worked. i added the mods back in one by one. as soon as I added Modern Industrialization it crashed, but MI works fine with all the other mods. its only when I add in WE when issues start to happen. there is no crash log generated, only this: 
![image](https://user-images.githubusercontent.com/43156914/119580948-613b5100-bd76-11eb-949b-28ad6ccc5c2c.png)

### Expected Behavior

The expected behavior is that the game would run as intended

### Reproduction Steps

1. add Modern Industrialization, fabric api, and worldedit to your mods folder.
2. try to launch the game
3. crash

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
provide the log

**Comment by Snowolf2001** [comment]
> provide the log

there is no log, i said in the description. no crashlog is generated in the .minecraft folder

**Comment by wizjany** [comment]
i didn't ask for a crash report, we need the actual game log.

**Comment by Snowolf2001** [comment]
> i didn't ask for a crash report, we need the actual game log.

oh like latest.log? here:
[latest.log](https://github.com/EngineHub/WorldEdit/files/6542945/latest.log)

**Comment by wizjany** [comment]
nothing to do with worldedit.

**Comment by Snowolf2001** [comment]
> nothing to do with worldedit. I highly doubt that this setup works without worldedit, since modern industrialization is specifically telling you what's wrong there in the log.

i dont understand how it works fine when i remove worldedit then

**Comment by wizjany** [comment]
would probably be better if you actually just tried reproducing with the two mods. also the version you haven't installed doesn't even match the version you said you're using.
there's definitely something else wrong with your setup though. even if there was something like a mixin conflict with worldedit it would show in the log, which it's not.

**Comment by Snowolf2001** [comment]
> would probably be better if you actually just tried reproducing with the two mods. also the version you haven't installed doesn't even match the version you said you're using.
> there's definitely something else wrong with your setup though. even if there was something like a mixin conflict with worldedit it would show in the log, which it's not.

alright thank you, ill try to see if i can fix it that way! :D
