### ISSUE TITLE
Time Lock Bug

### ISSUE THREAD

**Issue by KolakZ** [EngineHub/WorldEdit#1760]
### WorldEdit Version

WorldEdit 7.2.5

### Platform Version

git-Purpur-1132 (MC: 1.16.5)

### Bug Description

I have a time-lock of 1000 set at spawn but sometimes when players exit spawn, it's still at 1000 even though it's nighttime. This only gets fixed when they relog.

### Expected Behavior

I expect the time to revert to the real time when players exit spawn.

### Reproduction Steps

1. Set a time-lock of 1000 in a region
2. Set the time of day to night
3. Exit out of spawn

### Anything Else?

If you have any questions, leave a comment and I'll be happy to answer it.

**Comment by wizjany** [comment]
if you changed the flag while players are in the region, this is expected and you need to flushstates.
