### ISSUE TITLE
Documentation for //stack command does not mention [direction]

### ISSUE THREAD

**Issue by PhoenixIV** [EngineHub/WorldEdit#1762]
### WorldEdit Version

Online

### Platform Version

Web

### Bug Description

The command //stack is allowing to mention the direction in which to stack, but that does not show in the docs nor ingame.
Example: `//stack 3 up` is valid.

### Expected Behavior

[direction] is a listed argument at https://worldedit.enginehub.org/en/latest/commands/ and ingame

### Reproduction Steps

-

### Anything Else?

If anyone could provide me with an example of how to use the offset argument that would be a fabulous addition.

**Comment by PhoenixIV** [comment]
Nevermind: Joo200 on Discord explained to me how to use [offset], which lead me to understand that "[direction]" is a variation of [offset], just that [offset] is more broad.

This leaves me to ask you to improve your documentation. Maybe put some extra explanation how to use [offset] with x,y,z

**Comment by wizjany** [comment]
https://github.com/EngineHub/WorldEditDocs/issues/31
