### ISSUE TITLE
//paste, //set, or //move blocks into a position that has a smoker or jukebox gives error

### ISSUE THREAD

**Issue by Momshroom** [EngineHub/WorldEdit#1764]
### WorldEdit Version

* Bukkit-Official(7.3.0-SNAPSHOT+5790-67c99be)

### Platform Version

Paper version git-Paper-756 (MC: 1.16.5)

### Bug Description

When //move ing, //set ing, or //paste ing blocks over a jukebox or smoker
I consistently get this error:
https://paste.gg/p/Momshroom/dba6deecd41f491ea93c0ae10522e8e4

### Expected Behavior

Not get map errors

### Reproduction Steps

1. select a jukebox or smoker
2. //set stone

OR
paste or move blocks over where a jukebox or smoker was

### Anything Else?

Add any additional context you can provide below.

**Comment by me4502** [comment]
This is a Bukkit issue, not WorldEdit
