### ISSUE TITLE
//update command

### ISSUE THREAD

**Issue by QuickWrite** [EngineHub/WorldEdit#1765]
### The Problem

When someone does something that does not update these things need to be updated. This must (to my knowledge) be done manually and can take a long time and some things can be missed.
These things can be redstone as well as other WorldEdit commands.

### A Solution

A command that updates all of the blocks in a specific region. (I would call it `//update`) This command could have extra features like masks as well.

### Alternatives

* Update all of the blocks by hand (placing/ breaking blocks for example). - This is really tedious and I don't think anyone enjoys this.
* Use another plugin. - It is easier if it is in WorldEdit directly, but can be helpful if this should be splitted.

### Anything Else?

Note that something like `//update` could be very laggy with big structures. Especially with long redstone wires as they update extreme amounts of things.

This could break some contraptions as well as some rely on the BUD-Switch, but this could be undone with a mask that does not update pistons/ droppers.

**Comment by wizjany** [comment]
literally already exists

**Comment by QuickWrite** [comment]
> literally already exists

I haven't found it. So when you are saying this could you please tell me the command? It would be very helpful.

**Comment by octylFractal** [comment]
It's in the 7.3.0 snapshots, and had the exact name you gave.

**Comment by QuickWrite** [comment]
Ok, thanks. I was really confused with the answer of @wizjany as I couldn't find anything anywhere in any documentation.

Just a little tip: When you say that it already exists, please tell the one who made the issue where it is so that the person has learned something and can use that. It helps the user and sounds way better.
