### ISSUE TITLE
Client side version

### ISSUE THREAD

**Issue by AlexTheDolphin0** [EngineHub/WorldEdit#1767]
### The Problem

I've always loved this mod/plugin. I usually end up using the plugin. But there is one thing I believe this is missing. I think a client-side version would be good. I always find myself messing up /fill in stupid ways.

### A Solution

It could /fill or /setblock a bunch of different commands to do what you want it to I guess? and it would be entirely client-side so therefore no cheating on servers.

### Anything Else?

Add any additional context you can provide below.

**Comment by octylFractal** [comment]
I think this is pretty out-of-scope for WorldEdit. It would lack a ton of important features and be a big pain to actually make it work properly or quickly. In general, I think you should probably just install WorldEdit on the server if you can. Unfortunately, this isn't a great solution for Realms, but that's really something Mojang would need to change.

The general concept of macro'ing setblock or fill isn't that difficult to set up, and certainly doesn't need WorldEdit's massive set of commands to be quite useful. It's probably a cool thing for someone else to tackle.
