### ISSUE TITLE
WorledEdit acting up With mohist maybe

### ISSUE THREAD

**Issue by InfernoGamingYT** [EngineHub/WorldEdit#1768]
### WorldEdit Version

worldedit-bukkit-7.2.5-dist

### Platform Version

Forge 1.16.5

### Bug Description

I'm using Mohist to run both plugins and mods, and world edit is acting up, world guard is fine(as far as I'm aware). I cant make simple cuts or replacements, it's like the whole mod just breaks, I'm also using fawe, if don't, world edit doesn't even work(like the wooden axe doesn't even do anything). This is what it was says when I select a block(selecting works) "FAWE java.lang.NoClass.DefFoundError: Could not initialize class com.sk89q.worldedit.world.block.blocktypes". I'm not sure if I should be putting this in world edit or fawe's issues. Sometimes it will only be whenever I do //undo. ill screen record a bit of what it does. https://streamable.com/mjk5um 

### Expected Behavior

For me to be able to do the basics of world edit atleast.

### Reproduction Steps

1. Download Mohist 1.16.5
2. make a self-hosted server
3. download some mods and plugins(including fawe, world guard, and world edit)
4. try selecting an area and doing something simple like //cut

### Anything Else?

if you need my ful modlist(which is 75 mods) and plugin list (which is 15 plugins) i will send screenshots

**Comment by me4502** [comment]
FAWE is not supported

**Comment by InfernoGamingYT** [comment]
> FAWE is not supported

by you guys? or by mohist?

**Comment by me4502** [comment]
By us

**Comment by InfernoGamingYT** [comment]
> By us
should i go to mohist? or fawe's issues thing?

**Comment by octylFractal** [comment]
Doubt FAWE wants to support Mohist, so probably ask Mohist.

**Comment by InfernoGamingYT** [comment]
> Doubt FAWE wants to support Mohist, so probably ask Mohist.

gotcha
