### ISSUE TITLE
//brush paint does not paint under blocks

### ISSUE THREAD

**Issue by ArcticRaven** [EngineHub/WorldEdit#1769]
### WorldEdit Version

7.3.0-SNAPSHOT

### Platform Version

PurPur 1.16.5-1144

### Bug Description

Using a cylinder based paint brush, it does not paint under blocks that are already placed. This is especially noticeable under transparent or non-full sized blocks (16px) 

![image](https://user-images.githubusercontent.com/43667891/120855175-268ea100-c54c-11eb-81c4-b073ea5c482a.png)

### Expected Behavior

I would expect a cylinder to paint the full cylinder so I can continue to be extra lazy. 

### Reproduction Steps

1. Build a structure where you can see blocks underneath - ie trapdoor walls, glass, etc. 
2. Try to paint blocks underneath it with a wide radius paint brush
3. Cry because you now have to manually place those blocks. 

### Anything Else?

:)

**Comment by wizjany** [comment]
that's the point

**Comment by ArcticRaven** [comment]
The point is to paint the blocks that are located underneath others in the event the block above isn't a full block or transparent.

**Comment by wizjany** [comment]
then use a general sphere/cyl brush and define your own masks.
this is like an artist putting painters tape on their canvas and then being surprised that the canvas under the tape doesn't have paint on it.

**Comment by ArcticRaven** [comment]
If I wanted to make new blocks then by all means - yes I would use a standard cylinder brush - however if I **dont** want to make edit to the shape of the land then most people would probably stick to painting. There's not any clear documentation that defines how to use "masks" in a cylinder tool either which makes your solution obsolete. Kind of like having and instruction manual that requires a tool that doesn't exist.

**Comment by wizjany** [comment]
there's an entire page on the documentation that covers all the mask types. anyway, this isn't a bug as mentioned. support questions go to discord, not the issue tracker.
