### ISSUE TITLE
Paste Command Not Working As Expected

### ISSUE THREAD

**Issue by KingOwnageXV** [EngineHub/WorldEdit#1773]
### WorldEdit Version

1.12.2

### Platform Version

Latest

### Bug Description

When I copy a section, and select the pos 1 and pos 2 I want to paste it to afterwards it paste it near the player position and not where I selected

### Expected Behavior

It should paste to the section / place I selected unless dictated otherwise

### Reproduction Steps

1. ...
2. ...

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
unsupported version

**Comment by KingOwnageXV** [comment]
1.12.2 is the latest version of minecraft that has stable performance, which is why 90% of minecraft servers run on it so what do you mean "unsupported version"? You mean you choose latest versions over popularity? So you'd rather update world edit for an update that less servers are running on it? This is all backwards. Explain the logi

**Comment by wizjany** [comment]
I thought 90% of servers run 1.8?
[*oh wait*](https://bstats.org/global/bukkit#minecraftVersion)
this isn't up for debate. thanks.
