### ISSUE TITLE
1.17 Snapshot Build (Can't use anything besides //wand)

### ISSUE THREAD

**Issue by Harrsn** [EngineHub/WorldEdit#1776]
### WorldEdit Version

Build #5810 snapshot-testing 1.17

### Platform Version

Latest BuildTools (Spigot 1.17) Build #128

### Bug Description

Hey! Not entirely sure if this has been posted before, but I thought I might as well report it! Just got Spigot working for 1.17 and I installed some essential plugins, one of them being WorldEdit. I downloaded the latest snapshot testing build, restarted my server, and I can receive the wand with //wand but anything besides that does not work. I tried //cut, //copy, //sphere, etc. I tried deleting the .jar and folder that was made, shut down my server, and reinstalled the plugin. Tried again and I got the same result. The code below is after a fresh restart and I only tried the //cut command. If there's any fix to this issue, please let me know! Thanks!

```
11.06 13:42:40 [Server] Server thread/ERROR An unexpected error while handling a WorldEdit command
11.06 13:42:40 [Server] INFO java.lang.IllegalStateException: Currently invalid
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.lifecycle.Lifecycled.lambda$valueOrThrow$0(Lifecycled.java:99) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.lifecycle.Lifecycled.valueOrThrow(Lifecycled.java:99) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitServerInterface.getWatchdog(BukkitServerInterface.java:128) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.EditSession.<init>(EditSession.java:249) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1048) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:249) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Optional.map(Optional.java:260) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:248) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.command.ClipboardCommandsRegistration.extract$editSession(ClipboardCommandsRegistration.java:324) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_cut(ClipboardCommandsRegistration.java:245) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[?:?]
11.06 13:42:40 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
11.06 13:42:40 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
11.06 13:42:40 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
11.06 13:42:40 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
```

### Expected Behavior

Being able to use WorldEdit as it's intended to. (i.e. //cut, //replace, etc)

### Reproduction Steps

1. Uninstalled the plugin entirely, deleting the folder that was made as well.
2. Reinstalled and restarted my server, same thing happens.

### Anything Else?

I apologize if there's something in the code that clearly shows the error in what's happening, I'm not very savvy with these types of things. Any help would be appreciated!

**Comment by wizjany** [comment]
full log please

**Comment by Harrsn** [comment]
`11.06 13:41:55 [Multicraft] Starting server!
11.06 13:41:55 [Multicraft] Loaded config for "Snapshot (Latest)"
11.06 13:41:55 [Multicraft] Updating eula.txt file
11.06 13:41:56 [Server] INFO Loading libraries, please wait...
11.06 13:42:00 [Server] main/INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
11.06 13:42:01 [Server] main/INFO Reloading ResourceManager: Default, bukkit
11.06 13:42:02 [Server] Worker-Main-12/INFO Loaded 7 recipes
11.06 13:42:03 [Server] main/INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
11.06 13:42:03 [Server] main/INFO Reloading ResourceManager: Default, bukkit
11.06 13:42:03 [Server] Worker-Main-12/INFO Loaded 7 recipes
11.06 13:42:03 [Server] Server thread/INFO Starting minecraft server version 1.17
11.06 13:42:03 [Server] Server thread/INFO Loading properties
11.06 13:42:03 [Server] Server thread/INFO This server is running CraftBukkit version 3111-Spigot-66f9d3c-cbf2f67 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
11.06 13:42:03 [Server] Server thread/INFO Debug logging is disabled
11.06 13:42:03 [Server] Server thread/INFO Server Ping Player Sample Count: 12
11.06 13:42:03 [Server] Server thread/INFO Using 4 threads for Netty based IO
11.06 13:42:03 [Server] Server thread/INFO Default game type: SURVIVAL
11.06 13:42:03 [Server] Server thread/INFO Generating keypair
11.06 13:42:04 [Server] Server thread/INFO Starting Minecraft server on 192.99.18.198:25599
11.06 13:42:04 [Server] Server thread/INFO Using epoll channel type
11.06 13:42:05 [Server] Server thread/INFO [SMPBank] Loading SMPBank v0.1
11.06 13:42:05 [Server] Server thread/INFO [AureliumSkills] Loading AureliumSkills vBeta 1.0.6
11.06 13:42:05 [Server] Server thread/INFO [Troll] Loading Troll v1.2
11.06 13:42:05 [Server] Server thread/INFO [WorldEdit] Loading WorldEdit v7.2.6-SNAPSHOT+5810-7217a71
11.06 13:42:05 [Server] Server thread/INFO Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@2f2c3650]
11.06 13:42:05 [Server] Server thread/INFO [SmartCore] Loading SmartCore v1.0.2
11.06 13:42:05 [Server] Server thread/INFO [WorldEdit] Enabling WorldEdit v7.2.6-SNAPSHOT+5810-7217a71
11.06 13:42:05 [Server] Server thread/INFO Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
11.06 13:42:06 [Server] Server thread/INFO WEPIF: Using the Bukkit Permissions API.
11.06 13:42:06 [Server] INFO **********************************************
11.06 13:42:06 [Server] INFO ** This WorldEdit version does not fully support your version of Bukkit.
11.06 13:42:06 [Server] INFO **
11.06 13:42:06 [Server] INFO ** When working with blocks or undoing, chests will be empty, signs
11.06 13:42:06 [Server] INFO ** will be blank, and so on. There will be no support for entity
11.06 13:42:06 [Server] INFO ** and block property-related functions.
11.06 13:42:06 [Server] INFO **
11.06 13:42:06 [Server] INFO ** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
11.06 13:42:06 [Server] INFO **********************************************
11.06 13:42:06 [Server] Server thread/WARN Failed to load the built-in legacy id registry
11.06 13:42:06 [Server] INFO java.lang.IllegalStateException: Currently invalid
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.util.lifecycle.Lifecycled.lambda$valueOrThrow$0(Lifecycled.java:99) ~[?:?]
11.06 13:42:06 [Server] INFO at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.util.lifecycle.Lifecycled.valueOrThrow(Lifecycled.java:99) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitServerInterface.getWatchdog(BukkitServerInterface.java:128) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.block.BlockState.generateStateMap(BlockState.java:120) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.block.BlockType.lambda$new$3(BlockType.java:61) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.block.BlockType.getBlockStatesMap(BlockType.java:91) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:83) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:101) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:117) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:70) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:191) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:408) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:198) ~[?:?]
11.06 13:42:06 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:177) ~[?:?]
11.06 13:42:06 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[snapshot-latest.jar:3111-Spigot-66f9d3c-cbf2f67]
11.06 13:42:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[snapshot-latest.jar:3111-Spigot-66f9d3c-cbf2f67]
11.06 13:42:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[snapshot-latest.jar:3111-Spigot-66f9d3c-cbf2f67]
11.06 13:42:06 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[snapshot-latest.jar:3111-Spigot-66f9d3c-cbf2f67]
11.06 13:42:06 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[snapshot-latest.jar:3111-Spigot-66f9d3c-cbf2f67]
11.06 13:42:06 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) ~[snapshot-latest.jar:3111-Spigot-66f9d3c-cbf2f67]
11.06 13:42:07 [Multicraft] Skipped 201 lines due to rate limit (40/s)
11.06 13:42:07 [Server] Worker-Main-12/INFO Preparing spawn area: 0%
11.06 13:42:08 [Server] Worker-Main-8/INFO Preparing spawn area: 0%
11.06 13:42:08 [Server] Worker-Main-13/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-13/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-10/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-8/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-13/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-8/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-13/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-13/INFO Preparing spawn area: 9%
11.06 13:42:12 [Server] Worker-Main-11/INFO Preparing spawn area: 9%
11.06 13:42:13 [Server] Worker-Main-10/INFO Preparing spawn area: 54%
11.06 13:42:13 [Server] Server thread/INFO Time elapsed: 6792 ms
11.06 13:42:13 [Server] Server thread/INFO Preparing start region for dimension minecraft:the_nether
11.06 13:42:13 [Server] Worker-Main-10/INFO Preparing spawn area: 0%
11.06 13:42:14 [Server] Worker-Main-11/INFO Preparing spawn area: 0%
11.06 13:42:14 [Server] Worker-Main-11/INFO Preparing spawn area: 5%
11.06 13:42:15 [Server] Worker-Main-14/INFO Preparing spawn area: 44%
11.06 13:42:15 [Server] Worker-Main-12/INFO Preparing spawn area: 68%
11.06 13:42:16 [Server] Worker-Main-12/INFO Preparing spawn area: 69%
11.06 13:42:16 [Server] Worker-Main-8/INFO Preparing spawn area: 75%
11.06 13:42:17 [Server] Worker-Main-8/INFO Preparing spawn area: 83%
11.06 13:42:17 [Server] Worker-Main-10/INFO Preparing spawn area: 83%
11.06 13:42:18 [Server] Worker-Main-10/INFO Preparing spawn area: 87%
11.06 13:42:18 [Server] Worker-Main-14/INFO Preparing spawn area: 90%
11.06 13:42:19 [Server] Worker-Main-11/INFO Preparing spawn area: 95%
11.06 13:42:19 [Server] Worker-Main-12/INFO Preparing spawn area: 99%
11.06 13:42:19 [Server] Server thread/INFO Time elapsed: 6139 ms
11.06 13:42:19 [Server] Server thread/INFO Preparing start region for dimension minecraft:the_end
11.06 13:42:19 [Server] Worker-Main-8/INFO Preparing spawn area: 0%
11.06 13:42:20 [Server] Worker-Main-9/INFO Preparing spawn area: 0%
11.06 13:42:20 [Server] Worker-Main-8/INFO Preparing spawn area: 39%
11.06 13:42:21 [Server] Worker-Main-11/INFO Preparing spawn area: 68%
11.06 13:42:21 [Server] Worker-Main-13/INFO Preparing spawn area: 69%
11.06 13:42:22 [Server] Worker-Main-11/INFO Preparing spawn area: 73%
11.06 13:42:22 [Server] Worker-Main-8/INFO Preparing spawn area: 76%
11.06 13:42:23 [Server] Worker-Main-14/INFO Preparing spawn area: 81%
11.06 13:42:23 [Server] Worker-Main-8/INFO Preparing spawn area: 84%
11.06 13:42:24 [Server] Worker-Main-9/INFO Preparing spawn area: 85%
11.06 13:42:24 [Server] Worker-Main-14/INFO Preparing spawn area: 92%
11.06 13:42:25 [Server] Worker-Main-11/INFO Preparing spawn area: 96%
11.06 13:42:25 [Server] Server thread/INFO Time elapsed: 5912 ms
11.06 13:42:25 [Server] Server thread/INFO [SMPBank] Enabling SMPBank v0.1
11.06 13:42:25 [Server] Server thread/INFO [AureliumSkills] Enabling AureliumSkills vBeta 1.0.6
11.06 13:42:25 [Server] Server thread/INFO [AureliumSkills] Loaded 156 config options in 1 ms
11.06 13:42:25 [Server] Server thread/INFO [AureliumSkills] Loaded 284 sources and 9 tags in 30ms
11.06 13:42:26 [Server] Server thread/INFO [AureliumSkills] Loading languages...
11.06 13:42:26 [Server] Server thread/INFO [AureliumSkills] Loaded 11 languages in 671ms
11.06 13:42:27 [Server] Server thread/INFO [AureliumSkills] Loaded 3 menus, 9 items, and 5 templates in 255 ms
11.06 13:42:27 [Server] Server thread/INFO [AureliumSkills] Loaded 77 Ability Options in 4ms
11.06 13:42:27 [Server] Server thread/INFO [AureliumSkills] Loaded 23 items and 0 commands in 4 loot tables.
11.06 13:42:27 [Server] Server thread/INFO [AureliumSkills] Loaded 3 blocked worlds.
11.06 13:42:27 [Server] Server thread/INFO [AureliumSkills] Aurelium Skills has been enabled
11.06 13:42:27 [Server] Server thread/INFO [Troll] Enabling Troll v1.2
11.06 13:42:27 [Server] Server thread/INFO [Troll] Config was loaded successfully
11.06 13:42:27 [Server] Server thread/INFO [SmartCore] Enabling SmartCore v1.0.2
11.06 13:42:27 [Server] Server thread/INFO ──────────────────────────────────
11.06 13:42:27 [Server] Server thread/INFO SmartCore v1.0.2
11.06 13:42:27 [Server] Server thread/INFO Version: 1.0.2
11.06 13:42:27 [Server] Server thread/INFO Author: Northy
11.06 13:42:27 [Server] Server thread/INFO Server: 1.16
11.06 13:42:27 [Server] Server thread/INFO Enabling the plugin...
11.06 13:42:27 [Server] Server thread/INFO ──────────────────────────────────
11.06 13:42:27 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it
11.06 13:42:27 [Server] Startup Done (20.920s)! For help, type "help"
11.06 13:42:29 [Server] User Authenticator #1/INFO UUID of player harrsn is 5fed7853-a34e-4961-b7b3-e2c308725b1e
11.06 13:42:31 [Connect] User harrsn, IP 75.109.39.195
11.06 13:42:31 [Multicraft] harrsn ran command Message of the Day
11.06 13:42:31 [Server] Server thread/INFO [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
11.06 13:42:31 [Server] Server thread/INFO [NBTAPI] NMS support 'MC1_17_R1' loaded!
11.06 13:42:31 [Server] Server thread/INFO [NBTAPI] Found Gson: class com.google.gson.Gson
11.06 13:42:36 [Server] Server thread/INFO harrsn issued server command: //wand
11.06 13:42:40 [Server] Server thread/INFO harrsn issued server command: //cut
11.06 13:42:40 [Server] Server thread/ERROR An unexpected error while handling a WorldEdit command
11.06 13:42:40 [Server] INFO java.lang.IllegalStateException: Currently invalid
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.lifecycle.Lifecycled.lambda$valueOrThrow$0(Lifecycled.java:99) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.lifecycle.Lifecycled.valueOrThrow(Lifecycled.java:99) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitServerInterface.getWatchdog(BukkitServerInterface.java:128) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.EditSession.<init>(EditSession.java:249) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1048) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:249) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Optional.map(Optional.java:260) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:248) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
11.06 13:42:40 [Server] INFO at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.command.ClipboardCommandsRegistration.extract$editSession(ClipboardCommandsRegistration.java:324) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_cut(ClipboardCommandsRegistration.java:245) ~[?:?]
11.06 13:42:40 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[?:?]
11.06 13:42:40 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
11.06 13:42:40 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
11.06 13:42:40 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
11.06 13:42:40 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
11.06 13:42:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]`

**Comment by JOO200** [comment]
Update worldedit, your worldedit version doesn't support 1.17

**Comment by octylFractal** [comment]
specifically, you want the bukkit 1.17 branch, not snapshot testing.

**Comment by Harrsn** [comment]
> specifically, you want the bukkit 1.17 branch, not snapshot testing.

Thank you!
