### ISSUE TITLE
Leaves placed with //set decay

### ISSUE THREAD

**Issue by whydoineedgithub** [EngineHub/WorldEdit#1777]
### WorldEdit Version

7.2.5

### Platform Version

fabric 0.7.3

### Bug Description

When leaves are placed using //set they decay. I do not know if this happens with other commands.

### Expected Behavior

Leaves placed with //set would act like leaves placed by hand and not decay. 

### Reproduction Steps

1. Select area
2. //set oak_leaves 

### Anything Else?

It would be more useful if leaves placed using the //set command would act like leaves placed by hand instead of leaves that naturally spawn on trees. On the left is leaves placed with //set, on the right is leaves placed by hand. 
![worldeditleaves](https://user-images.githubusercontent.com/85765112/121744047-2a27a800-cab7-11eb-9fc7-f2b93beab8eb.PNG)

**Comment by wizjany** [comment]
https://minecraft.fandom.com/wiki/Leaves#Data_values

**Comment by savagematt** [comment]
To turn the comment above into something actionable:

```
//set oak_leaves[persistent=true]
```
