### ISSUE TITLE
Commands not working after reload

### ISSUE THREAD

**Issue by SeraphJACK** [EngineHub/WorldEdit#1780]
### WorldEdit Version

7.2.5

### Platform Version

forge-1.16.5-36.1.24

### Bug Description

When `/reload` executes, the CommandDispatcher will be reset, and World Edit needs to register all the commands again to continue functioning. In the current version, WorldEdit won't do that, and therefore `/reload` leads to `//xxx` commands stop working.

Quoted from Forge `net.minecraftforge.event.RegisterCommandsEvent` Javadoc:

> Commands are rebuilt whenever DataPackRegistries is recreated. You can use this event to register your commands whenever the Commands class in constructed. The event is fired on the MinecraftForge.EVENT_BUS

### Expected Behavior

Commands should be registered by subscribing `net.minecraftforge.event.RegisterCommandsEvent`.

### Reproduction Steps

1. Start a Forge server with World Edit
2. `//xxx` commands working properly
3. Execute `/reload`
4. `//xxx` commands disappear

### Anything Else?

Nope.

**Comment by wizjany** [comment]
1626
