### ISSUE TITLE
Upwards to 1.17

### ISSUE THREAD

**Issue by MrKiller01** [EngineHub/WorldEdit#1784]
### The Problem

I can put a wall with glass panes two or any blocks in any direction and the glass panes are broken. Same goes with restoring from backup with fences and rails.
I thought this was taken care of....
I hope with the next update these problems do disappear.

### A Solution

All of the above being either moved or restored, being as it should be when it was built in the first place.

### Alternatives

there is no alternative, the only plugin who says that it can do this, is Worldedit. So I really hope that the future build has been taken care of this, I sincerely hope it.... 

### Anything Else?

Add any additional context you can provide below.I
Am I the only one who experiences this? or did I just made a boo-boo in question, that this is already been asked?
In that case, throw this one out of the window and Hell YEAH! Bring it on baby!! We love your work!!!!!!!!!!!!!!!

So much thanks people for all your kind, honest and hard work!

**Comment by wizjany** [comment]
prob need to turn on validation in //perf. please use search or at least discord for questions.

**Comment by Jarynnnn** [comment]
> @wizjany: I need to turn on what now? I am doing this action since the first time I met Worldedit, and now you tell me that I need to turn something on? in order to move a thing? and since when is posting here a request, nicely formulated, friendly asking with a wink, Invalid?
> You do understand that not everybody has the need to go to different platforms to lay down their problem or question. That you point me in the direction of this Discord, just to get more replies from people who don't have any tether to the program, Hell, my neighbor could be joining and sell me all this nonsense..... You think it is fun going to such social media platform if you HATE these kind of chit-chat? That is why I post here, it is kinda direct, until you make it near seconds after my posting invalid, very sharp though......
> And now I am here, maybe the devs can think of a way to make people more aware of changes (radical) in the plugin by console messages, or only at admin rights holding persons in chat.... That way this kind of me trying to talk to the developers is not needed: e.g. non-use chit-chat.
> 
> But thanks for reacting.... (and why can I not find any smiley's around this editor?????) (:

Just turn on validation like he said, no need to write a novel

**Comment by wizjany** [comment]
this is an issue tracker, not social media.
