### ISSUE TITLE
schematic with other mods places random blocks instead of the previus ones

### ISSUE THREAD

**Issue by TheRealA77** [EngineHub/WorldEdit#1785]
### WorldEdit Version

6.1.10

### Platform Version

Forge 1.12.2 - 14.23.5.2854

### Bug Description

when creating a schematic of a building containing blocks from other mods, the blocks change to random blocks from other mods during the pasting process in another world

### Expected Behavior

I expected to just see the schematic paste correctly

### Reproduction Steps

1. create a building with modded blocks
2. create a schematic with the blocks
3. paste the schematic in another world with the same mods

### Anything Else?

Add any additional context you can provide below.

**Comment by wizjany** [comment]
old version

**Comment by wizjany** [comment]
no, update to 1.16+ if you want support
