### ISSUE TITLE
"Nothing Selected" when using //set  (im sure i selected pos1 and pos2)

### ISSUE THREAD

**Issue by Makces** [EngineHub/WorldEdit#1788]
### WorldEdit Version

7.2.5+57d5ac9

### Platform Version

Forge 36.1.1

### Bug Description

i selected pos1 and pos2 and used //set command but it says nothing selected

### Expected Behavior

it should placed blocks that i said in //set command

### Reproduction Steps

have a forge and world edit with said versions
even though i had some other mods installed but idk
![image](https://user-images.githubusercontent.com/86025981/122298954-57051080-cf38-11eb-9386-4f69a6eab2b1.png)
mods i had installed 

### Anything Else?

there was no error log in latest.log

**Comment by wizjany** [comment]
reproduce without mods probably.

**Comment by Makces** [comment]
sorry, i was not able to reproduce bug i mentioned earlier.
i think its some incompatibility caused by other mods,
