### ISSUE TITLE
//regen command does not work and returns an error

### ISSUE THREAD

**Issue by Qunato** [EngineHub/WorldEdit#1791]
### WorldEdit Version

7.3.0-SNAPSHOT+#5835-b8a9c00

### Platform Version

git-Paper-"bc4b23e"

### Bug Description

The //regen command doesn't work and returns a console error.

Here is a link to the console error: https://mcpaste.io/75ae9d33473ef554

### Expected Behavior

The selection is reset to its original terrain.

### Reproduction Steps

1. Open a server on with the stated versions of Paper and WorldEdit.
2. Make a selection.
3. Execute the command //regen.

### Anything Else?

Nope.

**Comment by octylFractal** [comment]
This is an upstream bug with Paper: https://github.com/PaperMC/paperweight/issues/24

**Comment by MiniDigger** [comment]
please try with latest paper build

**Comment by wizjany** [comment]
`java.lang.NoSuchMethodError: 'net.minecraft.world.level.storage.SaveData net.minecraft.server.dedicated.DedicatedServer.getSaveData()'`
paper-13

**Comment by smplfy** [comment]
> please try with latest paper build

Tried with Paper version b59165a. Still getting the following error when issuing the '//regen' command:

java.lang.NoSuchMethodError:
'net.minecraft.world.level.storage.SaveData
net.minecraft.server.dedicated.DedicatedServer.getSaveData()'

**Comment by wizjany** [comment]
Please read the previous comment before making a new one.

**Comment by wizjany** [comment]
should in theory be fixed with https://github.com/PaperMC/Paper/commit/a7cddc41532ee01067ea9b9b08e9ff7e63f21f27
...unless there's some other missing mappings.

**Comment by phemmer** [comment]
Can confirm `//regen` is now working with Paper build # 43
