### ISSUE TITLE
Crash when pasting certain schematics or builds

### ISSUE THREAD

**Issue by Desynq** [EngineHub/WorldEdit#1792]
### WorldEdit Version

7.30-SNAPSHOT+5835-b8a9c00

### Platform Version

Fabric Loader 0.11.6

### Bug Description

Whenever pasting a schematic of a particular size or shape, the game ends up CTD'ing.

I haven't been able to find a noteable pattern of what would cause it to crash.

### Expected Behavior

The schematic should paste correctly without causing a CTD.

### Reproduction Steps

[schematic.zip](https://github.com/EngineHub/WorldEdit/files/6683164/schematic.zip)
1. Load schematic `mountain`
2. Paste schematic
3. Crash occurs a couple of seconds later
[crash-2021-06-20_18.06.07-server.txt](https://github.com/EngineHub/WorldEdit/files/6683152/crash-2021-06-20_18.06.07-server.txt)

### Anything Else?

The crash seems to occur both on singleplayer and multiplayer.

**Comment by Desynq** [comment]
[schematic.zip](https://github.com/EngineHub/WorldEdit/files/6683163/schematic.zip)

**Comment by octylFractal** [comment]
AFAIK this is a mod conflict, try with just WorldEdit.

**Comment by Desynq** [comment]
> AFAIK this is a mod conflict, try with just WorldEdit.

Which mod do you think could be causing the issue?

**Comment by Desynq** [comment]
> AFAIK this is a mod conflict, try with just WorldEdit.
I tried it with only WorldEdit, same issue.

[crash-2021-06-20_18.40.17-server.txt](https://github.com/EngineHub/WorldEdit/files/6683189/crash-2021-06-20_18.40.17-server.txt)

**Comment by octylFractal** [comment]
Please try https://builds.enginehub.org/job/worldedit/18193.
