### ISSUE TITLE
Spawning anvil drop

### ISSUE THREAD

**Issue by MCstrijder** [EngineHub/WorldEdit#1795]
### The Problem

If I spawn an anvil or multiple like with the //replace air 87%air,13%anvil (or sand), it will float, I can't use the floating anvils for my minigame, please help!

### A Solution

Maybe the solution is to get a new update for WorldEdit, because as far as I know, there is no WorldEdit 1.17 and al my builds are with 1.17 blocks.

### Anything Else?

Add any additional context you can provide below.

**Comment by octylFractal** [comment]
This would be a bug, not a feature request. You also didn't specify if you're on Bukkit or Fabric, so can't test to reproduce. Finally, there is a 1.17 update, please see the Discord for a direct link to the current dev builds that support 1.17.

**Comment by me4502** [comment]
I can't reproduce this on either Bukkit or Fabric - This is presumably an issue with Spigot's setBlock function, which we fallback to when a version of WorldEdit that doesn't support your MC version is installed.
