### ISSUE TITLE
//wand error

### ISSUE THREAD

**Issue by ZayanPlayz** [EngineHub/WorldEdit#1797]
### WorldEdit Version

1.13.2

### Platform Version

PaperMC 1.17

### Bug Description

I can't do //wand

### Expected Behavior

every time when I start the server and do //wand error always comes every time I do that.

paste: https://paste.gg/p/anonymous/dcaa4ce8dd6246e68a981c247904da76

### Reproduction Steps

1. login in world
2. do //wand
3. error comes

**Comment by JOO200** [comment]
Your zip file is somehow invalid. Either you changed / deleted the .jar-file while the server was online or you have some problems with the upload of the plugin.

And WorldEdit 1.13.2 is no valid version.

**Comment by ZayanPlayz** [comment]
thanks it worked
