### ISSUE TITLE
Add "lit" state to signs

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1799]
### The Problem

Settings signs only accept the waterlogged and rotation as state. 1.17 added the lit state declaring whether text on the sign is lit or not.

### A Solution

Add a lit when setting signs.

### Alternatives

None.

### Anything Else?

None.

**Comment by wizjany** [comment]
properties are retrieved dynamically from the server, you can use whatever mojang (or modders, for modded platforms) declares to be a valid property.
