### ISSUE TITLE
Axes acting like wand

### ISSUE THREAD

**Issue by idkimanerd** [EngineHub/WorldEdit#1801]
### WorldEdit Version

7.2.5-dist

### Platform Version

fabric-0.11.3-1.16.5

### Bug Description

When in survival with cheats, some axes act like the wand.

Note* amplified world

### Expected Behavior

To act like a normal axe

### Reproduction Steps

1. Make survival world with cheats and amplified world
2. Make axe
3. Use 1 time
4. All future uses will act like wand

**Comment by wizjany** [comment]
cheats prob off or sth, use discord for questions
