### ISSUE TITLE
Fix tab complete for people without permissions

### ISSUE THREAD

**Issue by Alejandro-Sosa** [EngineHub/WorldEdit#1802]
### WorldEdit Version

(7.3.0-SNAPSHOT+5835-b8a9c00)

### Platform Version

git-Purpur-1190

### Bug Description

Commands players don't have access to still show up in tab complete. 
![image](https://user-images.githubusercontent.com/60317441/123407408-3da13b80-d5ac-11eb-80a0-52a123e01170.png)

### Expected Behavior

When you don't have permission to these commands you won't be using them. So they shouldn't show up in tab complete.

### Reproduction Steps

1. Open chat using the key T or /
2. Press the tab key

### Anything Else?

No

**Comment by me4502** [comment]
https://github.com/EngineHub/WorldEdit/issues/1691
