### ISSUE TITLE
How to get a selection (1.16.5/1.17)

### ISSUE THREAD

**Issue by FireSpirit15** [EngineHub/WorldEdit#1805]
### WorldEdit Version

7.2.5

### Platform Version

Spigot

### Bug Description

I'm currently not able to get the selection of a player by using the plugin as API.
Selection cannot be imported correctly, so I can just import it as internal annotation and the code won't work.

Here is my code: https://pastebin.com/hc5WiRQH

### Expected Behavior

In older versions this code worked without problems. There were no errors. What do I have to do to fix that?

### Reproduction Steps

Just paste the code into eclipse

### Anything Else?

None

**Comment by wizjany** [comment]
this isn't a bug. use discord for questions
