### ISSUE TITLE
plugin stopped working and I dont know how

### ISSUE THREAD

**Issue by meatjr** [EngineHub/WorldEdit#1806]
### WorldEdit Version

worldedit-bukkit-7.2.5-dist.jar

### Platform Version

Spigot 1.16.5

### Bug Description

On my server I used Worldedit and WorldGuard and they were working just fine. I had then saw that there was a new version for both Worldedit and Worldguard so I updated them both, restarted the server and now my server just thinks that they dont exist anymore. It is as if Worldedit plugin is not there and Worldguard wont work becasue Worldedit wont work even tho they clearly show up in the files with there version up to date. I had a similar issue with another plugin that I cant seem to fix but I really need help with this. the error message in the console was " [Server thread/ERROR]: Could not load 'plugins/worldedit-bukkit-7.2.5-dist.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml"

### Expected Behavior

I expected both plugins to update because they appeard in the files and the .yml seemed to be the same so it should have worked. 

### Reproduction Steps

1. Download the new version of worldedit from 7.2.4 to 7.2.5 
2. delete the old version and restart the server.

### Anything Else?

I am not sure if this may be a issue with the plugin but something else. I had the exact same issue with dynamp (another plugin) but all my other plugins work fine. I know I did update them wrong because I updated other plugin with no issues. One other thing to note is that my server changed locations after this error but I don't think that could effect it.

**Comment by wizjany** [comment]
likely issue with your download, can't say more without a log. use discord for questions.
