### ISSUE TITLE
No BlockUpdate after set or brush

### ISSUE THREAD

**Issue by MisterIch2000** [EngineHub/WorldEdit#1812]
### WorldEdit Version

7.2.5 dist

### Platform Version

Spigot 1.17

### Bug Description

When I use a brush (sphere or smooth for example) or set an area to for example air there is no Block Update sent to the bordering blocks.

### Expected Behavior

After I set an gravel sphere on an ocean field I expect that it falls down because of the blockupdate trigers the gravels gravitation.
When I smooth a snowed montain I expect snow without a block under it to disappear.
After I replaced the gras_blocks of an forrest with cobblestone I expect that all grass ontop of them get destroyed by the block update.

### Reproduction Steps

Brush Example:
Given an item an gravel brush (for example sphere) and creat one in air or on top of water.

Replace Example:
Mark the bottom area of any natural forrest an replace it by non dirt blocks; so that all flowers ands grass blocks should be destoryed.

### Anything Else?

I case this is not an issue but a feature - how can I switch it back? This is really anyoing to me as I am terraforming larger forrest, snowmontains and ocean bioms at the moment and this half cut tall_grass or flying flowers and snow is really *******.
In the last WorldEdit version I've used (around the 1.16.3 release date - don't know the exact version number anymore) this wasn't a problem because all blocks got an block update...

**Comment by me4502** [comment]
Use a version that actually supports 1.17
