### ISSUE TITLE
Rotating error

### ISSUE THREAD

**Issue by N13lSs** [EngineHub/WorldEdit#1814]
### WorldEdit Version

1.17-36;aa3ae63

### Platform Version

Purpur-1199

### Bug Description

Rotating a big selection to a rotation other than the one it started out at and pasting does not work. 

### Expected Behavior

Just a normal paste, instead i get an error ( https://hastebin.com/caleluraro.md ) 

### Reproduction Steps

1. //copy -e
2. //rotate 90 0 0
3. //paste -a -e
4. (selection size: 4327680, 109 entities, armourstands and item frames) 

### Anything Else?

Add any additional context you can provide below.

**Comment by me4502** [comment]
FAWE is not supported for compatibility and safety reasons. If you want support, use WorldEdit.
