### ISSUE TITLE
Could not dispatch event 1.17.1

### ISSUE THREAD

**Issue by ErythroCraft** [EngineHub/WorldEdit#1817]
### WorldEdit Version

7.2.6 Beta

### Platform Version

3172-Spigot-610a8c0-99561c2 (MC: 1.17.1)

### Bug Description

After update to spigot 1.17.1 the console the console say
"Could not dispatch event ..."

Bug: https://pastebin.com/rTYGgLDm

Report: https://pastebin.com/syyVkSLt

### Expected Behavior

The Expected Behavior is loading the server is normally.

### Reproduction Steps

1. Install plugin
2. start server

### Anything Else?

Plugins I use:

XItemsRemover, AdvancedRedstone, AutoRestart, CubCustomDrops, UltimateTimber, BeehivesPro, youTrade, AutoShulker, Vault, ChestSort, WorldEdit, AsyncWorldEdit, CommandPanels, WorldGuard, Citizens, AngelChest, WorldGuard-Towny, WolfyUtilities, CMILib, CustomCrafting, BottledExp

**Comment by octylFractal** [comment]
AsyncWorldEdit is not WorldEdit, remove it or report to them.

**Comment by ErythroCraft** [comment]
I have now uninstalled AsyncWorldEdit and the problem still exists.

**Comment by octylFractal** [comment]
Please provide the new logs without AWE.

**Comment by ErythroCraft** [comment]
Now I started an test server with WorldEdit only.

This is the latest.log without all plugins

https://pastebin.com/dcPgz79c

**Comment by octylFractal** [comment]
5814 is heavily outdated, please use the beta published to dev.bukkit.org recently or the latest build from the builds site, on the version/7.2.x branch.

**Comment by ErythroCraft** [comment]
Fixed.

Thank you.
