### ISSUE TITLE
Sync problem in custom dimensions

### ISSUE THREAD

**Issue by Londiuh** [EngineHub/WorldEdit#1818]
### WorldEdit Version

7.2.6-SNAPSHOT

### Platform Version

Fabric 0.7.4

### Bug Description

When you use WE commands in custom dimensions, the server won't send block updates and the client desyncs. This is so annoying, I have to reload the affected chunks.

### Expected Behavior

Server sends block updates.

### Reproduction Steps

1. Create a data pack custom dimension
2. Go to your custom dimension
3. Use a WE command (for example //set)

**Comment by me4502** [comment]
Provide the actual version, not just “SNAPSHOT”

**Comment by Londiuh** [comment]
> Provide the actual version, not just “SNAPSHOT”

I provided "7.2.6-SNAPSHOT"

**Comment by me4502** [comment]
Yes, that's not the complete version

**Comment by Londiuh** [comment]
`/we version` says "Fabric-Official(7.2.6-SNAPSHOT+5855-40ded93)"

**Comment by me4502** [comment]
The version you're using pre-dates support for your MC version. Update
