### ISSUE TITLE
Changing biomes does not work with the 1.18 preview world generation

### ISSUE THREAD

**Issue by alenga-dura** [EngineHub/WorldEdit#1819]
### WorldEdit Version

7.2.6 Beta

### Platform Version

Fabric 1.17

### Bug Description

The feature of changing biomes does not work in worlds generated with the experimental generation datapack (officially provided by mojang).

### Expected Behavior

Expected to change the biomes like it always did

### Reproduction Steps

1. Generate a world using the experimental generation datapack
2. Use the setbiome or the brush commands to try and changing the biome anywere.
3. Exit and re-enter the world to check if it worked
4. It did not work

**Comment by wizjany** [comment]
Marking this as forge+fabric since I'm fairly sure we use the same (incorrect) math for both, likely need to offset for the height diff.
