### ISSUE TITLE
An unexpected error while handling a WorldEdit command

### ISSUE THREAD

**Issue by yjamestnt** [EngineHub/WorldEdit#1822]
### WorldEdit Version

WorldEdit 7.2.6 Beta 1

### Platform Version

paper-1.17.1-97

### Bug Description

<html>
<body>

[Server thread/ERROR]: An unexpected error while handling a WorldEdit command
200 | java.lang.AbstractMethodError: Receiver class net.coreprotect.worldedit.CoreProtectLogger does not define or inherit an implementation of the resolved method 'com.sk89q.worldedit.world.block.BaseBlock getFullBlock(com.sk89q.worldedit.math.BlockVector3)' of interface com.sk89q.worldedit.extent.Extent.
201 | at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
202 | at com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[?:?]
203 | at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
204 | at com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[?:?]
205 | at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
206 | at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getFullBlock(WatchdogTickingExtent.java:108) ~[?:?]
207 | at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
208 | at com.sk89q.worldedit.extent.ChangeSetExtent.setBlock(ChangeSetExtent.java:64) ~[?:?]
209 | at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
210 | at com.sk89q.worldedit.extent.MaskingExtent.setBlock(MaskingExtent.java:69) ~[?:?]
211 | at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
212 | at com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:87) ~[?:?]
213 | at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
214 | at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:64) ~[?:?]
215 | at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:737) ~[?:?]
216 | at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:780) ~[?:?]
217 | at com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53) ~[?:?]
218 | at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
219 | at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
220 | at com.sk89q.worldedit.command.RegionCommands.set(RegionCommands.java:106) ~[?:?]
221 | at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:408) ~[?:?]
222 | at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
223 | at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
224 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
225 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
226 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
227 | at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
228 | at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
229 | at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
230 | at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
231 | at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
232 | at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
233 | at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
234 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[minecraft_server.jar:git-Paper-97]
235 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[minecraft_server.jar:git-Paper-97]
236 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
237 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
238 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
239 | at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
240 | at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
241 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
242 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft_server.jar:git-Paper-97]
243 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
244 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
245 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[minecraft_server.jar:git-Paper-97]
246 | at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[minecraft_server.jar:git-Paper-97]
247 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
248 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[minecraft_server.jar:git-Paper-97]
249 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[minecraft_server.jar:git-Paper-97]
250 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
251 | at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[minecraft_server.jar:git-Paper-97]
252 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[minecraft_server.jar:git-Paper-97]
253 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[minecraft_server.jar:git-Paper-97]
254 | at java.lang.Thread.run(Thread.java:831) [?:?]
255

<br class="Apple-interchange-newline">
</body>
</html>

### Expected Behavior

//set

### Reproduction Steps

1. //hpos1
2. //hpos2
3. //set0

**Comment by JOO200** [comment]
CoreProtect issue. Update CoreProtect or talk to them.

**Comment by yjamestnt** [comment]
> CoreProtect

Oh~Thanks^^
