### ISSUE TITLE
//copy & //paste result in stairs facing the incorrect direction

### ISSUE THREAD

**Issue by ASchneider-GitHub** [EngineHub/WorldEdit#1823]
### WorldEdit Version

7.2.6-SNAPSHOT+5852-0790e6e

### Platform Version

Paper-1.17.1-100

### Bug Description

When using //copy to copy a build, using //paste results in any stairs in the clipboard facing the wrong direction. The stairs always face south, and the orientation (be it direction, whether or not they're upside down, or connected to other stairs) is lost.

### Expected Behavior

Stairs should //paste with the same blockstates as from where they were //copy'd

### Reproduction Steps

1. Place down stairs in various orientations
2. Select the area and do //copy
3. Go somewhere else and run //paste
4. Stairs are now all facing south, and don't preserve original blockstate

### Images:

Original build that was copied: 
![2021-07-11_13 57 00](https://user-images.githubusercontent.com/65742424/125209795-43577c00-e250-11eb-8d8b-a5d286ce92d5.png)
![2021-07-11_13 57 39](https://user-images.githubusercontent.com/65742424/125209797-43f01280-e250-11eb-9fd9-be80cb28354a.png)

Build after pasting:
![2021-07-11_13 58 10](https://user-images.githubusercontent.com/65742424/125209800-4fdbd480-e250-11eb-8a5b-d7174242aed7.png)
![2021-07-11_13 58 21](https://user-images.githubusercontent.com/65742424/125209802-50746b00-e250-11eb-97bc-860a4c57d67b.png)

**Comment by ASchneider-GitHub** [comment]
@wizjany Why was this marked as invalid? Does something need to be added?

**Comment by octylFractal** [comment]
> Please ensure you are running up to date software before making a bug report.
You are on an old version before 1.17.1 was released. Please update.

**Comment by ASchneider-GitHub** [comment]
It looks like the 7.2.6 beta is the newest version available for Bukkit (as listed on https://enginehub.org/worldedit/#downloads). Is there another version that can be downloaded?
This is the newest version that shows up on DevBukkit: https://dev.bukkit.org/projects/worldedit/files/3379705

**Comment by octylFractal** [comment]
Correct, that is the newest release. You are not running that.

**Comment by ASchneider-GitHub** [comment]
Ah I was unaware that the `7.2.6 beta` isn't the same as `/we version` returning `7.2.6-SNAPSHOT+5852-0790e6e`. Not sure where that version came from then since I don't see it listed. I'll go ahead and look at updating
