### ISSUE TITLE
Unknown property 'facing' for block minecraft:ladder

### ISSUE THREAD

**Issue by Agentomega** [EngineHub/WorldEdit#1824]
### WorldEdit Version

worldedit-bukkit-7.2.5-dist

### Platform Version

paper-1.17.1-100

### Bug Description

When attempting to place ladders against a set of bunkbeds, I found I was unable to specify the facing property.

### Expected Behavior

When //set or //replace used with facing specified, ladders facing appropriate direction.

### Reproduction Steps

1. Place two beds on top of each other.
2. //wand
3. Set point 1 to ground adjacent to bed (beds facing=south in example)
4. Set point 2 to upper bunk, foot of bed (northernmost block)
5. //replace air ladder[facing=east]
![2021-07-12_01 30 18](https://user-images.githubusercontent.com/599494/125235797-040d4780-e2b1-11eb-832c-5d3d7ecbae0c.png)
![2021-07-12_01 30 25](https://user-images.githubusercontent.com/599494/125235805-08396500-e2b1-11eb-8144-344b744118d9.png)

### Anything Else?

I originally did this with the forge version before uploading the world to paper, but some villagers updated the beds and broke the ladders, thus needing to do it again with the Bukkit/Paper version.

**Comment by me4502** [comment]
Use a version that supports 1.17

**Comment by Agentomega** [comment]
Fair enough, totally didn't notice the beta version on bukkit, will give that a test.
