### ISSUE TITLE
Waterlog Command

### ISSUE THREAD

**Issue by DonniesAlt** [EngineHub/WorldEdit#1825]
### The Problem

With the current way world edit works, whenever you are doing a build underwater you have to constantly waterlog the blocks manually.

### A Solution

What if there was a way to select an area and run a command along the lines of //waterlog or something like that. It would take into account all the blocks in the selected area and determine whether the block has a waterlog option and then set the block data to include it. I'm not a coder so I'm not sure if this would even work but it would be cool as hell if you could somehow get it to work!

**Comment by me4502** [comment]
You can already do this with the state applying pattern, adding a specific command doesn't make too much sense as it's too limited
