### ISSUE TITLE
Worldeditaxe rightclick candle

### ISSUE THREAD

**Issue by Jan9103** [EngineHub/WorldEdit#1829]
### WorldEdit Version

7.2.6-beta

### Platform Version

Spigot

### Bug Description

you can still rightclick candles with the wooden axe (it dosn't mark, but instead interacts)

### Expected Behavior

mark the position

### Reproduction Steps

1. Place a candle
2. get a wooden axe
3. right click the candle

**Comment by wizjany** [comment]
can't repro? https://i.imgur.com/44XuQOq.png
