### ISSUE TITLE
The fabric-networking-api included in the Mod is not compatible with 1.17.1

### ISSUE THREAD

**Issue by Sanluli36li** [EngineHub/WorldEdit#1830]
### WorldEdit Version

worldedit-fabric-mc1.17-7.2.6-beta-01.jar

### Platform Version

Fabric 0.11.6-1.17.1

### Bug Description

Since the fabric-networking-api of 1.17 is not compatible with 1.17.1, when fabric-api is not installed separately in 1.17.1, the server cannot be accessed

### Expected Behavior

Join the game normally

### Reproduction Steps

1. put WE into server mods folder and folder without fabric-api (use 1.17.1)
2. open server, and try join game
3. can not join server

### Anything Else?

Although this is not a problem of we in essence, I don't want to install a fabric api separately for this problem (my other mods do not depend on this)

**Comment by octylFractal** [comment]
Already fixed.
