### ISSUE TITLE
Nothing Loaded

### ISSUE THREAD

**Issue by dogevspenguin** [EngineHub/WorldEdit#1834]
### WorldEdit Version

WorldEdit 7.2.5

### Platform Version

1.16.5Forge-36.1.0

### Bug Description

Nothing load.There're few command but there're useless.No //wand no //set and the axe dont work.No error in the console of minecraft

### Expected Behavior

I expect to see command,And I expect to see the block that i've destroyed using wooden axe reappear

### Reproduction Steps

1.Download World edit
2. Test

### Anything Else?

I have 16 mod which are Mowzie Mob,Biome o' Plenty,Pam harvest craft(3 of them),MR crayfish Furniture mod,Pehkui,Marvel Mod,Nukes,Mantle,Create,JEI,Flywheel and my own mod which i created in mcreator.

**Comment by dogevspenguin** [comment]
Look like without biome o' plenty generation.Everything was fine

**Comment by dogevspenguin** [comment]
When i create another world it's fine

**Comment by wizjany** [comment]
prob need cheats on
