### ISSUE TITLE
SPAM ERROR CONSOLE.

### ISSUE THREAD

**Issue by MaxiiARG** [EngineHub/WorldEdit#1836]
### WorldEdit Version

7.2.5

### Platform Version

Spigot (Mohist 1.16.5)

### Bug Description

com.sk89q.worldedit.event.platform.BlockInteractEvent@60e7bce9 to handler EventHandler{priority=NORMAL}
14.07 22:24:40 [Server] INFO java.lang.reflect.InvocationTargetException: null
14.07 22:24:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
14.07 22:24:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
14.07 22:24:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
14.07 22:24:40 [Server] INFO at com.sk89q.worldedit.WorldEdit.handleBlockRightClick(WorldEdit.java:665) ~[?:?]
14.07 22:24:40 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:136) ~[?:?]
14.07 22:24:40 [Server] INFO at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source) ~[?:?]
14.07 22:24:40 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
14.07 22:24:40 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
14.07 22:24:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
14.07 22:24:40 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
14.07 22:24:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
14.07 22:24:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
14.07 22:24:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
14.07 22:24:40 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[forge:?]
14.07 22:24:40 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1478) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
14.07 22:24:40 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:113) ~[?:?]
14.07 22:24:56 [Multicraft] Skipped 120 lines due to rate limit (30/s)
14.07 22:24:56 [Server] ERROR Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@348ad7ca to handler EventHandler{priority=NORMAL}
14.07 22:24:56 [Server] INFO java.lang.reflect.InvocationTargetException: null
14.07 22:24:56 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
14.07 22:24:56 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
14.07 22:24:56 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
14.07 22:24:56 [Server] INFO at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:639) ~[?:?]
14.07 22:24:56 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:144) ~[?:?]
14.07 22:24:56 [Server] INFO at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source) ~[?:?]
14.07 22:24:56 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
14.07 22:24:56 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
14.07 22:24:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
14.07 22:24:56 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
14.07 22:24:56 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
14.07 22:24:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
14.07 22:24:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
14.07 22:24:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[forge:?]
14.07 22:24:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:465) ~[forge:?]
14.07 22:24:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:461) ~[forge:?]
14.07 22:24:56 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:1523) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:30) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:9) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
14.07 22:24:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
14.07 22:24:57 [Multicraft] Skipped 664 lines due to rate limit (30/s)
14.07 22:24:57 [Server] ERROR Could not dispatch event: com.sk89q.worldedit.event.platform.BlockInteractEvent@6855b31 to handler EventHandler{priority=NORMAL}
14.07 22:24:57 [Server] INFO java.lang.reflect.InvocationTargetException: null
14.07 22:24:57 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
14.07 22:24:57 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
14.07 22:24:57 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
14.07 22:24:57 [Server] INFO at com.sk89q.worldedit.WorldEdit.handleBlockRightClick(WorldEdit.java:665) ~[?:?]
14.07 22:24:57 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:136) ~[?:?]
14.07 22:24:57 [Server] INFO at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source) ~[?:?]
14.07 22:24:57 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
14.07 22:24:57 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
14.07 22:24:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
14.07 22:24:57 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
14.07 22:24:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
14.07 22:24:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
14.07 22:24:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
14.07 22:24:57 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[forge:?]
14.07 22:24:57 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1478) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
14.07 22:24:57 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:113) ~[?:?]

### Expected Behavior

a

### Reproduction Steps

1. ...
2. ...
3

**Comment by octylFractal** [comment]
Hybrids aren't supported.
