### ISSUE TITLE
//forest can't undo

### ISSUE THREAD

**Issue by Louisover** [EngineHub/WorldEdit#1841]
### WorldEdit Version

7.2.5

### Platform Version

Spigot (Mohist 1.16.5) or Forge (Arclight 1.16.5)

### Bug Description

When I use "//forest", the trees were generated,
then I ues "//undo", It said "Nothing left to undo."

### Expected Behavior

use "//forest" , the trees were generated,
and ues "//undo", the trees were cleared

### Reproduction Steps

1. Selection range
2. use "//forest"
3. use "undo"

**Comment by me4502** [comment]
This is a Spigot bug - https://github.com/EngineHub/WorldEdit/issues/1745

But hybrids are not supported.
