### ISSUE TITLE
Cannot connect to my server - unhandled exception

### ISSUE THREAD

**Issue by ip0her** [EngineHub/WorldEdit#1848]
### WorldEdit Version

7.2.6 Beta 1 (Fabric for MC 1.17/1.17.1)

### Platform Version

fabric 0.7.4 Minecraft 1.17.1

### Bug Description

When I am connecting to my fabric server without this mod everything is ok. When I am shutting it down, placing "worldedit-fabric-mc1.17-7.2.6-beta-01.jar" in the empty "mods" folder, and run it again, I cannot connect to the server anymore.

[latest.log](https://github.com/EngineHub/WorldEdit/files/6872546/latest.log)

### Expected Behavior

I can connect to the modded server and use the mod.

### Reproduction Steps

1. Install the latest fabric server.
2. Connect to it.
3. Shut it down, install the mod, run it again.
4. Try to connect to it once again.

**Comment by wizjany** [comment]
#1830
