### ISSUE TITLE
Observers paste the wrongway

### ISSUE THREAD

**Issue by productionnerd** [EngineHub/WorldEdit#1849]
### WorldEdit Version

7.2.5

### Platform Version

Spigot

### Bug Description

When I copy observers facing down, and paste it, it pastes like this:
![2021-07-25_10 19 22](https://user-images.githubusercontent.com/87790274/126906139-adc16d14-1eb5-498c-8e22-b47b59f3f4fa.png)
In terms, the left is the observer that i copied, and the right is that i pasted.

### Expected Behavior

I expected it to paste the observers in the format that I copied them.

### Reproduction Steps

1. ... Copy observer facing down
2. ... Paste it.

**Comment by octylFractal** [comment]
Is this 1.17 or...? You didn't really provide any platform info.

**Comment by productionnerd** [comment]
My apologies. It’s 1.17. It was difficult for me to understand the platform info

**Comment by octylFractal** [comment]
Then you're outdated, use the beta from DBO.

**Comment by productionnerd** [comment]
Okay. Thanks, but what exactly is DBO

**Comment by octylFractal** [comment]
dev.bukkit.org, where we host the releases for Bukkit.

**Comment by productionnerd** [comment]
Oh
. Thank you.

**Comment by productionnerd** [comment]
But I use it on a spigot server

**Comment by octylFractal** [comment]
Spigot is bukkit.
