### ISSUE TITLE
Large schematic won't load

### ISSUE THREAD

**Issue by RasputanTheMad** [EngineHub/WorldEdit#1854]
### WorldEdit Version

7.2.5

### Platform Version

Forge 36.1.13

### Bug Description

I am trying to load a fairly large schematic and it crashes my game, even if I set it to a void creative game with no mobs or structures spawning. I have even set my ram to 32GB with no success. I have tried with multiple types of worlds all with no success.

### Expected Behavior

I was hoping to load this schematic.

### Reproduction Steps

1. ...
2. ...

**Comment by octylFractal** [comment]
Please provide the schematic, and the crash log.

**Comment by RasputanTheMad** [comment]
[steampunk-e1270.zip](https://github.com/EngineHub/WorldEdit/files/6911384/steampunk-e1270.zip)

This is not on a server but a single player world so I don't have a crash log.

**Comment by wizjany** [comment]
single player still has crash logs.

**Comment by octylFractal** [comment]
As this is a legacy schematic and on 7.2.5, I'm going to tentatively call this fixed via #1808. Unfortunately for you, we don't backport fixes to older versions, so you'll have to update to 1.17.1 if you want this fixed.
