### ISSUE TITLE
Can't place not connected ironbars

### ISSUE THREAD

**Issue by noahterpe** [EngineHub/WorldEdit#1858]
### WorldEdit Version

7.2.6-beta

### Platform Version

git-paper-138

### Bug Description

After I updated to the newest WorldEdit version. I can no longer place iron-bars that are not connected. It automatically connects them to each other, and i have no way of disabling it.

### Expected Behavior

The iron bars should look like when you have a single "iron-bars".

### Reproduction Steps

1. Select the 2 points
2. //set iron_bars or //set iron_bars[east=false,south=false,north=false,west=false]

**Comment by octylFractal** [comment]
`//perf neighbors off` should fix this, unless they also connect on self update in which case you also need `//perf update off`.
