### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by MojoNut** [EngineHub/WorldEdit#1860]
### WorldEdit Version

7.2.6

### Platform Version

Curse Forge 1.17.1

### Bug Description

I recently made a server with mods that me and my friends can play on and i decided i wanted to add world edit but when i load up the server and load up mc and join the server it says failed to connect and the server is up and world edit works on single player but i am unsure how to fix this as when i remove world edit from the mods folder i can connect to the server please any help would be appreciated and asap so i can get going on some projects i have planned, Thank you.

### Expected Behavior

I expected to be able to join once i added world edit and use it once oped.

### Reproduction Steps

.

**Comment by octylFractal** [comment]
"Curse Forge" is not a platform, do you mean Forge? Can you reproduce without any other mods on the server or client?

**Comment by octylFractal** [comment]
Also, "7.2.6" is not a version, please provide the full version number from `/we version`.

**Comment by nrliii** [comment]
I have the same problem the server starts properly but you cannot connect.

**Comment by wizjany** [comment]
please don't bump issues if you have nothing to add.
