### ISSUE TITLE
Cycler tool issues

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1867]
### WorldEdit Version

WorldEdit version 7.2.6-SNAPSHOT+5898-b9f0416

### Platform Version

git-Paper-165 (MC: 1.17.1)

### Bug Description

I encountered two issues using /tool cycler
1. Using the cycler to cycle the face and type of a chest deletes the content
2. The cycler dupes vines and deletes vine chains instead of cycling the location

### Expected Behavior

1. Don't delete items from chests
2. Don't dupe vines

### Reproduction Steps

1.1 Put some items in the chest
1.2 Select the cycler to cycle thru the face and type of a chest
1.3 see the result

2. https://gyazo.com/ceeb0c9f7f303b15e88edef2fc64f828

**Comment by me4502** [comment]
I just put up a PR to fix the chest content loss issue.

The other part just sounds like your current side effect status, which you can change in the //perf settings

**Comment by octylFractal** [comment]
Fixed by #1868
