### ISSUE TITLE
biome change error

### ISSUE THREAD

**Issue by LazyMnr** [EngineHub/WorldEdit#1871]
### WorldEdit Version

7.2.3

### Platform Version

Fabric 1.17.1

### Bug Description

I am on a multiplayer server with my friends. When trying to change a big area to a different biome, it shows many small patches that did not respond to the command. When I tried to change one of those patches individually, it still won't respond to the command. The problem seems to be present only in the multiplayer server as the command worked just fine in my single player world.

### Expected Behavior

Please fix this bug as we want to change the biome of a big area in our server.

### Reproduction Steps

1. look into the problem
2. fix it

**Comment by me4502** [comment]
Use a version of WorldEdit that support 1.17.1, instead of one for 1.15?
