### ISSUE TITLE
/delchunks w/ polygon selection error

### ISSUE THREAD

**Issue by delbertina** [EngineHub/WorldEdit#1873]
### WorldEdit Version

7.2.6-SNAPSHOT+5908-9de6b87

### Platform Version

git-Paper-195 1.17.1

### Bug Description

When using the /delchunks command while having a polygon selection selected, it throws an error. 
[Full Log](https://pastebin.com/NMnYv60s)
[Region](https://pastebin.com/AGquxEvk)

### Expected Behavior

I would expect the command to successfully mark the chunks for deletion on next startup.

### Reproduction Steps

1. Select a polygon selection
2. Execute the command /delchunks

### Anything Else?

Tested with cuboid selections and that does not throw an error. Tested the same polygon regions with /listchunks and that does not throw an error. I have a couple polygon regions that all throw the same error so I don't really think it's specifically about the selection, but included one in the bug description for reproduction purposes. 

I initially came across this issue while using WE 7.2.6 Beta 2 & paper-175 1.17.1. So can at least say this isn't a bug introduced between then and now.

**Comment by octylFractal** [comment]
Show bug & log without AWE.

**Comment by delbertina** [comment]
[Full Log w/o AWE](https://pastebin.com/yRhmyCXQ)

**Comment by me4502** [comment]
Fixed by ed280896280a7af6deedd33006d700e82f07c6ed
