### ISSUE TITLE
Add -a for loading schematics

### ISSUE THREAD

**Issue by Hypnotic0celot** [EngineHub/WorldEdit#1878]
### The Problem

Unable to load a schem.

https://user-images.githubusercontent.com/30245629/130325627-d16597a8-842d-4711-bcd8-50c4d26c2a93.mp4

### A Solution

Allow users to //schem load {schem name} {filetype} -a so it doesn't add air blocks and any unnecessary strain

**Comment by wizjany** [comment]
that's not how anything works. there needs to be some block at every position in a clipboard. the time taken to load a schematic is roughly linear based on the number of blocks in the schematic, cutting air out won't make a significant difference since we still need to read over them all.

**Comment by Hypnotic0celot** [comment]
ok thanks
