### ISSUE TITLE
Curseforge intergration issue

### ISSUE THREAD

**Issue by I0u0I** [EngineHub/WorldEdit#1879]
### WorldEdit Version

7.2.6

### Platform Version

Fabric 0.7.1

### Bug Description

***This is an issue with curseforge intergration not world edit directly, but can only be dealt with by whomever is uploading the files on curseforge.***

Fabric projects are getting rejected for including WorldEdit due to the questionable logic in automoderation not recognising the single file is forge & fabric compatible.

> "Found non-Fabric file WorldEdit 7.2.6 (Forge/Fabric for MC 1.17.1)(3433990) from project WorldEdit(225608) in Fabric modpack"

### Expected Behavior

Not to be auto-modded to death by curseforge.

### Reproduction Steps

1. Create a Fabric Project including Worldedit
2. Upload to Curseforge.
3. Wait for automod to yell at you...

### Anything Else?

While this issue is not on your team, the response from curseforge is just a workaround that you are required to implement, (rather than fixing their own system). 

> The system doesn't handle shared files well due to them being very low use and the entire everything not set up the most ideal way.
> They should upload two of the same file with an extra little edit to bypass the duplicate upload filter. Then mark one for forge and one for fabric.

Sorry for wasting your time on trivial stuff guys, but it's def a QoL thing for us users.

**Comment by me4502** [comment]
CurseForge does not allow additional files to specify a different platform, and uploading them as separate releases causes the sidebar to not work correctly

**Comment by I0u0I** [comment]
That's fair, obvs you know far more than me, I was just quoting verbatim the response I got from Curseforge support, guess the option is currently between sidebar not working correctly, and people not being able to include worldedit in fabric projects.

Again sorry for wasting time on something you aren't responsible for.

**Comment by wizjany** [comment]
going to close as it's not a bug with WE anyway.
ultimately all we get is https://i.imgur.com/JKGB0Ly.png and this wouldn't be an issue if we could just select multiple things. presumably it doesn't make things any better if we leave it blank? no clue how CF modpacks/automod/whatever work and it's not really a discussion for this bugtracker anyway tbh.
