### ISSUE TITLE
the survival also work w/ this mod.

### ISSUE THREAD

**Issue by alwaysJackinn** [EngineHub/WorldEdit#1886]
### The Problem

the one I think that quite crucial, if you're in survival w/ this mod is activating
in any reason I accident for playing survival then I crafted wood axe, 
then yes it appeared those purple text that I don't want to.

### A Solution

So There's my suggestion.
if you could create a "//optionhelp" + "//option"(for later need to toggles more laws and things) commands- 
like similar display Layout like "//help" command lists. Inside "//option" command to set it like, for example: toggle display
purple text in survival/adventure gamemode.

### Anything Else?

Thanks for take time to seen my *suggestion.
‏‏‎ ‎
‏‏‎ ‎
‏‏‎ ‎
‏‏‎ ‎
Best regards,
By alwaysJackinn_

**Comment by octylFractal** [comment]
Or you could just do `/tool none`.
