### ISSUE TITLE
Log4J MRJAR broken

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1890]
### WorldEdit Version

WorldEdit CLI (version 7.2.7-SNAPSHOT)

### Platform Version

None

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If I launch the command line interface I get the following message:
````
java -jar worldedit-cli-7.2.7-SNAPSHOT-dist.jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
````

### Expected Behavior

No performance issues or no message.

### Reproduction Steps

1. java -jar worldedit-cli-7.2.7-SNAPSHOT-dist.jar

2. See the warning

**Comment by octylFractal** [comment]
Fixed in 6c08b68244c1cea5dbd90839af5a13f0136d0f23.
