### ISSUE TITLE
WorldEdit crash server when try mixing with fawe?

### ISSUE THREAD

**Issue by Broascaa** [EngineHub/WorldEdit#1891]
### WorldEdit Version

WorldEdit 6.1.10 (For MC 1.12.2)

### Platform Version

Forge 1.12.2 using SpongeForge 1.12.2

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [ ] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The server simply crash on startup because of Fast Async World Edit, which is strange.. (more details on attached file)

[crash-2021-09-07_10.45.07-server.txt](https://github.com/EngineHub/WorldEdit/files/7119849/crash-2021-09-07_10.45.07-server.txt)

### Expected Behavior

I expected that WorldEdit will mix with FAWE, but instead of that i got a big crash.

### Reproduction Steps

Adding WorldEdit into mods folder, then FAWE, start the server and almost the complition of startup the server crash.

### Anything Else?

Can i get unban from discord? I have been banned by wizjany_ for trying to help a random dude (also deleted our messages) :| ID: Brosky (Vlad)#4823

**Comment by me4502** [comment]
Very unsupported

**Comment by Broascaa** [comment]
I can't use latest version 'cause SpongeForge is not updated :|
