### ISSUE TITLE
Unable to use JavaAdapter in CraftScripts

### ISSUE THREAD

**Issue by Snownee** [EngineHub/WorldEdit#1895]
### WorldEdit Version

7.2.5

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Due to the current implementation of `MinecraftHidingClassShutter`, run the script below will show `Access to Java class "adapter1" is prohibited`

https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/scripting/MinecraftHidingClassShutter.java#L30

Which means you can't extend any class by CraftScripts

### Expected Behavior

ability to use JavaAdapter in CraftScripts

### Reproduction Steps

Use this script:
```js
// $Id$
/*
 * Test CraftScript for WorldEdit
 * Copyright (C) 2021 Snownee
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

let we = com.sk89q.worldedit.WorldEdit.getInstance()
let factory = we.getBlockFactory()
let parser = new JavaAdapter(com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser, {
	parseFromInput: function(input, context) {
		return null
	}
}, we)

```

**Comment by octylFractal** [comment]
Why do you need to extend `DefaultBlockParser`? That's not really an intended usage of the API, if you need to parse stuff there are helpers to do that already [ref](https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/scripting/CraftScriptContext.java#L208).

**Comment by Snownee** [comment]
I want to register my own parser to the the BlockFactory

**Comment by wizjany** [comment]
you should be making a custom SimpleInputParser (or any InputParser), not extending DefaultBlockParser

and i'm like 95% sure you can just do that with java's "anonymous class syntax", e.g.
```js
parser = new SimpleInputParser(we) {
  getMatchedAliases: function() { return ImmutableList.of("#mypattern")}
  parseFromSimpleInput: function(input, context) { return MyPattern(...) };
}
we.getBlockFactory().register(parser)
```

**Comment by octylFractal** [comment]
Why a different _block_ parser? Are you sure you're not looking to add a _pattern_ parser and add it to the existing pattern factory?

**Comment by Snownee** [comment]
> you should be making a custom SimpleInputParser (or any InputParser), not extending DefaultBlockParser
> 
> and i'm like 95% sure you can just do that with java's "anonymous class syntax", e.g.
> 
> ```js
> parser = new SimpleInputParser(we) {
>   getMatchedAliases: function() { return ImmutableList.of("#mypattern")}
>   parseFromSimpleInput: function(input, context) { return MyPattern(...) };
> }
> we.getPatternFactory().register(parser)
> ```

I thought that was a very simple need. So I don't want to import GPL codes or writing a dedicated mod for it. Also I am having some trouble extending abstract class in Rhino.

**Comment by octylFractal** [comment]
What do you mean by "GPL codes"? All of worldedit is GPL, you can't _not_ use it.

**Comment by Snownee** [comment]
> What do you mean by "GPL codes"? All of worldedit is GPL, you can't _not_ use it.

I don't want my entire project to become under GPL.

**Comment by octylFractal** [comment]
Unfortunately using CraftScript won't let you avoid that. You must still use a GPL-compatible license even if you write a craftscript, as that is still linking against WorldEdit.

**Comment by Snownee** [comment]
So is it a bug?

**Comment by octylFractal** [comment]
Not being able to use JavaAdapter may be a bug, I'm looking in to it. However, you do not need it to implement a single interface as you need here, so this isn't a blocker.

**Comment by octylFractal** [comment]
Fixes by https://github.com/EngineHub/WorldEdit/commit/6008fe7333fb236b38b2f6e9cddabff555987209.
