### ISSUE TITLE
Publish releases to GitHub

### ISSUE THREAD

**Issue by TwoLeggedCat** [EngineHub/WorldEdit#1896]
### The Problem

The WorldEdit releases on Bukkit cannot be (easily) downloaded directly from the command line. Additionally, the Bukkit website has stability issues and goes down fairly often.

### A Solution

Release new WorldEdit versions on GitHub in addition to Bukkit.

### Alternatives

Downloading builds directly from the CI or just continuing to download them and copy them via SCP. The former is sub-optimal as it required finding the exact build considered stable, if it's even on the CI at all. The latter works, but is slow.

**Comment by octylFractal** [comment]
Alternative: You can grab the URL from the last redirect when downloading in browser and it works fine.

**Comment by octylFractal** [comment]
It seems like `wget --content-disposition https://dev.bukkit.org/projects/worldedit/files/3433988/download` works for me, at least right now. Are you experiencing an error currently?

**Comment by TwoLeggedCat** [comment]
That's... strange. I swear that didn't work last time 😅
