### ISSUE TITLE
Post 2 in gamemode spectator

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1898]
### WorldEdit Version

WorldEdit version 7.2.7-SNAPSHOT+5938-6008fe7

### Platform Version

git-Paper-262 (MC: 1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If you are in gamemode spectator and hold the selection wand, a right click selects a position.

### Expected Behavior

Don't select position two in spectator mode, position one isn't selected either. Very inconvenient if you want to check a player's chest and select it accidentally.

### Reproduction Steps

1. //wand
2. /gamemode spectator
3. Rightclick something

**Comment by octylFractal** [comment]
Is `/tool none` not sufficient for fixing this? I don't see any reason to add gamemode-specific state.

**Comment by octylFractal** [comment]
Or, even better, you could just configure your permissions plugin to drop the permission when in spectator mode.

**Comment by wizjany** [comment]
yea not sure how this is a bug. and due to the many ways around it as mentioned, we won't be offering additional behavior for this.
