### ISSUE TITLE
GUI's

### ISSUE THREAD

**Issue by AngerminecraftYT** [EngineHub/WorldEdit#1901]
### The Problem

An GUI where you can click on the axe (as example) to copy and on the slime to paste and the barrier to undo

in there with all worldedit features so its not only commands anymore

### A Solution

Please add it, there is no plugin that support that

**Comment by octylFractal** [comment]
WorldEdit will never have GUIs as it is not a client-side mod.

Also, opening some sort of "inventory GUI" [probably via a command...] and using items to manipulate stuff is a _lot_ slower than just typing the commands.
