### ISSUE TITLE
Move javadocs in one directory

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1902]
### The Problem

The javadocs published at https://docs.enginehub.org/javadoc/com.sk89q.worldedit/worldedit-core/version/ are sorted by module.

### A Solution

Publish an additional directory where you have all modules in one directory. So if you browse javadocs, you can find all modules in one spot instead of switching tabs if you work with the bukkit, core and fabric module like in my case, which often is hard if you only have on screen.

**Comment by josephjthomas** [comment]
Yes, you can't use a lot but some methods in bukkit are handy. I prefer using javadocs that contain all of a project xD

**Comment by wizjany** [comment]
There's literally only one class per platform that falls under the API and I'd rather not bundle them all together or give the impression they are part of core or part of API. Any competent IDE setup will pull all the javadocs from the repo on a per-artifact basis anyway.
