### ISSUE TITLE
Cannot set Pos 1 at all.

### ISSUE THREAD

**Issue by nightdroideka** [EngineHub/WorldEdit#1903]
### WorldEdit Version

Forge Official 7.2.5+57d5ac9

### Platform Version

1.16.5 Forge-36.2.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using a wand or a command to set the positions of blocks to change the selection for position 1 always resorts to [ -1, -1, -1 ]. It doesn't matter what I select it as or how far away I am from the location. Position 2 sets up normally, but position 1 will always choose [ -1, -1, -1 ]. 

### Expected Behavior

When using the want or Pos command, Position 1 is supposed to be set to the location I choose.

### Reproduction Steps

1. Either Using the wand or pos command, Select position 1 
2. Position 1 gets selected, then immediately after it gets changed to [ -1, -1, -1 ]

**Comment by me4502** [comment]
This is an issue with Enchantable, not WorldEdit.
