### ISSUE TITLE
//regen showing jar error

### ISSUE THREAD

**Issue by AwesomeFinster09** [EngineHub/WorldEdit#1904]
### WorldEdit Version

7.2.6 August 22 2021

### Platform Version

Spigot 1.17.1

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i use worldedit command //regen it shows error: java.langNoSuchMethodError: 'voidnet.meanecraft.server.level,WorldServer,<init> (net.minecraft.server.MinecraftServer, java.util.concurrent.Executer, net.minecraft,world.level.storage.Convertable$ConversionSession, net.minecraft.world.level.storage.]WorldDataServer,net.minecraft.resources.ResourceKey,net.minecraft.world.level.dimension.DimensionManager,net.minecraft.server.level.progress.WorldLoadListener,net.minecraft.world.level.chunk.ChunkGenerator, boolean, long,java.util.list, boolean. org.bukkit.world$environment, org.bukkit.generator.ChunkGenerator)' and i need help

### Expected Behavior

Regeneration of a selected region with the worldedit wand

### Reproduction Steps

resets chunk data

**Comment by JOO200** [comment]
Duplicate: https://github.com/EngineHub/WorldEdit/issues/1872
