### ISSUE TITLE
//copy //stack not proper directions, connections and items

### ISSUE THREAD

**Issue by Winpooh498** [EngineHub/WorldEdit#1905]
### WorldEdit Version

worldedit-mod-7.2.6

### Platform Version

Spigotmc-1.17.1-882dc

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I copy and paste or stack, chests don't stay combined, things change directions and items in chests disappear. 

### Expected Behavior

double chests to stay double, item to copy in them, 
hoppers, pistons etc to stay in the original direction

### Reproduction Steps

1. ...
2. ...

**Comment by JOO200** [comment]
Probably outdated, worldedit-mod is not for spigot, Make sure to use an current bukkit version.
