### ISSUE TITLE
An unexpected error while handling a WorldEdit command

### ISSUE THREAD

**Issue by ErythroCraft** [EngineHub/WorldEdit#1908]
### WorldEdit Version

7.2.6+4b2d1e7

### Platform Version

(MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Would like using //regen after //paste an edited build.
It is a single installation without FAWE or AWE.

Watch out the picture:
![want_to_fill](https://user-images.githubusercontent.com/76217862/135415581-bb947ee1-82b6-4bb2-a28c-256ee567b451.png))

The latest server log here:
[latest.log](https://github.com/EngineHub/WorldEdit/files/7257803/latest.log

### Expected Behavior

Filling in missing blocks between the build and the world blocks with //regen.

### Reproduction Steps

1. installed WorldEdit 
2. joined world1

3. //pos1
4. //pos2
5. //copy
6. //past in world2
7. editiing the build

8. /mv regen world1

9. //pos1 cutted build
10. //pos2 cutted build
11. //copy cutted build world 2
12. //paste cutted build in regenerated world1 on same place

13. //pos1 [a little part of emtys]
14. //pos2 [a little part of emtys]

BUG BY
15. //regen

**Comment by ErythroCraft** [comment]
[Minecraft 1.17.1 An unexpected error while handling a WorldEdit command](https://youtu.be/h0BOKGYtAC8)

**Comment by me4502** [comment]
See pinned issue, you need to update.

**Comment by ErythroCraft** [comment]
@me4502 
I do not understand. After the issue on SBPrime I uninstalled AWE and recreated the server build.
Watch out the video on youtube.

**Comment by JOO200** [comment]
Update Worldedit to a dev build

**Comment by ErythroCraft** [comment]
> Update Worldedit to a dev build

worldedit-bukkit-7.2.7-SNAPSHOT-dist.jar ?

**Comment by ErythroCraft** [comment]
Perfect work. 
Thanks so much for helpings.

**Comment by ErythroCraft** [comment]
25 per month.
I hope your plugin will never ending.
