### ISSUE TITLE
Problems with dynmap

### ISSUE THREAD

**Issue by ErythroCraft** [EngineHub/WorldEdit#1912]
### WorldEdit Version

3242-Spigot-6c1c1b2-d3cc412 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Platform Version

7.2.7-SNAPSHOT

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

After insttalling dynmap the server console say "Regen failed" .
Caused by: java.lang.IllegalStateException: Unregistered dimension type: net.minecraft.world.level.dimension.DimensionManager@67c59b2e

**Befor I installed dynmap the command //regen was working.**

### Expected Behavior

Regenerate parts of chunks.

### Reproduction Steps

1. stopping server
2. installing Dynmap version: core=3.2-beta-3-514, plugin=3.2-beta-3-514
3. using //regen

### Anything Else?

**Please also explain how it can be fixed.
If I can fix it myself.**

Installed Plugins on this server are
1. Vault
2. Multiverse-Core
3. ProtocolLib
4. dynmap
5. WorldEdit
6. Multiverse-Inventories

latest log here
[latest.log](https://github.com/EngineHub/WorldEdit/files/7271161/latest.log)

**Comment by octylFractal** [comment]
Are you sure this is dynmap-related and not Multiverse? I don't understand what dynmap would be doing to cause this.

**Comment by ErythroCraft** [comment]
Yes. I had to install it because I was lost and no longer knew where I was.
I did that a few minutes ago.
It is the only thing that I have additionally installed.

**Comment by octylFractal** [comment]
Well, I can't reproduce on latest Paper, so I'm going to assume it's _not_ dynmap. Try removing Multiverse and see if it helps. Or if you're going to _insist_ it's dynmap, try removing it and see if it fixes the problem.

**Comment by ErythroCraft** [comment]
I test it now.

**Comment by ErythroCraft** [comment]
It works without Multiverse, but I do not understand.
Without dynmap and installed Multiverse it is functionaly fine.

So
Worldedit + MV = ✅
Worldedit + dynmap = ✅
Worldedit + MV + dynmap = ❎

**Comment by octylFractal** [comment]
Well that sounds more like a problem between MV + dynmap, then. Not sure there's much for us to fix.

**Comment by ErythroCraft** [comment]
I test it with the new 4.3.2-SNAPSHOT-b862 of Multiverse.
But the same.

Can I link this issue to MV and Dynmap ?
Maybe they can help to understand.

**Comment by ErythroCraft** [comment]
import person 
@sk89q

**Comment by me4502** [comment]
Please don't randomly tag people

**Comment by ErythroCraft** [comment]
> Please don't randomly tag people
I deleted

**Comment by ErythroCraft** [comment]
Maybe it's the Caves And Cliffs preview? (datpack)

**Comment by me4502** [comment]
Spigot does not work properly with datapacks, so that's very possible - Using datapacks with Spigot is known to irreparably corrupt worlds.

**Comment by ErythroCraft** [comment]
Indeed! I've been using this since it came out.

**Comment by ErythroCraft** [comment]
![Screenshot 2021-10-02 123745](https://user-images.githubusercontent.com/76217862/135712765-41e7a8d8-8bf9-444e-b902-4232d2bb8c39.png)

**Comment by ErythroCraft** [comment]
The bukkit folder is created by spigot.

**Comment by ErythroCraft** [comment]
//regen is going without the caves and cliffs datapack. I regenerated the world by Minecraft and loaded it in the server build.

I've already shared it with the creator of Multiverse.
