### ISSUE TITLE
Curseforge does NOT recognize WE as a Fabric Mod.

### ISSUE THREAD

**Issue by StevenG5** [EngineHub/WorldEdit#1913]
### WorldEdit Version

7.2.6

### Platform Version

Fabric-0.11.6

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I am using the correct version of WE for my modpack version (1.17). When I tried to upload/update my modpack to curseforge I get this error: 

_The status of the file [My Modpack] has been changed to Rejected.
Found non-Fabric file WorldEdit 7.2.6 (Forge/Fabric for MC 1.17.1)(3433990) from project WorldEdit(225608) in Fabric modpack(3484148)_

Also got this message as well: 

_The status of the file Stevorium 1.0 (Steve5's Origins Plus Pack) has been changed to Rejected.
File 3433990 is invalid for modpack 3484148 with mod loader Fabric._

It appears that curseforge does not recognize the (Forge/Fabric) WE classification as a functional fabric mod. I can not speak for the forge implications. **I also tested this on my other modpack which runs MC version 1.17.1, same issue.**

All I know, is if you want to use this version of WE for the fabric launcher and upload the pack to curseforge, it will be detected and rejected. It also works perfectly fine in singleplayer and on a multiplayer server. It just does not pass curseforge's modpack verification process. 

### Expected Behavior

I expected the mod to be a valid fabric mod when uploading a modpack to curseforge. Instead it was classified as "something else" and not allowed to be in the pack due to it being classified as a "non-fabric" mod.

### Reproduction Steps

1. Put WorldEdit 7.2.6 (Forge/Fabric for MC 1.17.1) into a regular fabric modpack (1.17 OR 1.17.1)
2. Try to upload said modpack to curseforge with the WE Mod included.
3. Wait for the short verification period, and check your inbox. It will have been rejected by curseforge for not being a "fabric mod".

### Anything Else?

Really great mod and useful tool. Hope this bug gets fixed for all my brothers out there trying to create a fabric modpack on Minecraft 1.17 or 1.17.1

**Comment by me4502** [comment]
There isn't anything we can do about this, it's a CurseForge issue

**Comment by octylFractal** [comment]
To be more explicit, CurseForge does not let you set a mod as both Forge and Fabric, as ours is. They need to allow that, and are already aware of this issue. Leaving this open until they fix that.

**Comment by wizjany** [comment]
seems CF has added this recently, so the files (at least on the site) are marked as supporting both modloaders now.
