### ISSUE TITLE
/reload makes all commands disappear

### ISSUE THREAD

**Issue by NighthowlerStudios** [EngineHub/WorldEdit#1916]
### WorldEdit Version

7.2.5-dist

### Platform Version

Forge 36.2.8 (1.16.5)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When you use /reload, this causes all commands to unregister.  It's extremely reproducible.

### Expected Behavior

let all commands remain without unloading them at all when /reload-ing

### Reproduction Steps

1. install mc 1.16.5 and forge 36.2.8, then install worldedit 7.2.5
2. open a world then /reload
3. try using a command

### Anything Else?

https://github.com/EngineHub/WorldEdit/pull/1766

regression from the above issue.  was this fixed merged into 7.2.5 or are we awaiting it to arrive still?

**Comment by Kaleidio** [comment]
seems the branch is waiting to merge on 7.2.6, my bad.  will it be backported to 1.16.5 or no?
