### ISSUE TITLE
Superpickaxe doesn't drop chest items

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1924]
### WorldEdit Version

7.2.8-SNAPSHOT+5955-3ba0890

### Platform Version

git-Paper-353 (MC: 1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If I use the superpickaxe in single mode and break items with them, they drop. If I put items in a chest and break the chest, only the chest drops and the items in the chest get deleted.
In config I set
super-pickaxe:
    drop-items: true
    many-drop-items: true
but no change.

### Expected Behavior

Don't delete items in chests and drop them like a player breaks the chest. So in the same way the superpickaxe acts on every other block.

### Reproduction Steps

1. /superpickaxe single
2. Break chest with items
3. See items gone

**Comment by wizjany** [comment]
fairly sure this isn't on us as we just call the bukkit api method to break the block naturally.

**Comment by octylFractal** [comment]
Yes, this is an upstream bug in Spigot/Paper, please report to them.
