### ISSUE TITLE
DeepCode AI found potential high risk vulnerability

### ISSUE THREAD

**Issue by Strahilchu** [EngineHub/WorldEdit#1925]
### WorldEdit Version

7.2.7

### Platform Version

git-Paper-358 (MC: 1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

![WeDeepCode](https://user-images.githubusercontent.com/69178324/139775532-fc637e0a-9300-4be5-9cd0-8d2709cfd4f5.JPG)

### Expected Behavior

For DeepCode AI to not detect anything I suppose?

### Reproduction Steps

Google DeepCode AI and import the WorldEdit repository to it to view.

### Anything Else?

I don't know much about code but this AI found an issue and I felt the need to report it here.

It could be nothing, or it could help fix something. Either way I hope it's helpful in some way!

**Comment by wizjany** [comment]
please stop spamming our repos with automatically "found" "vulnerabilities"

**Comment by Strahilchu** [comment]
I posted one for WG in its respective github and one for WE.

Not spamming, just thought it was something I should report.

**Comment by wizjany** [comment]
if you want to discuss things, use discord. by your own admission you have no idea what this stuff means, so you shouldn't be reporting bugs.
