### ISSUE TITLE
Selection bug with item frames and paintings

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1933]
### WorldEdit Version

7.2.8-SNAPSHOT+5955-3ba0890

### Platform Version

Paper version git-Paper-377

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If you use the selection wand on a painting or item frame, it removes the item instead of selecting the position.

### Expected Behavior

Select the position and don't remove the item.

### Reproduction Steps

1. Use the selection wand on a painting
2. See it be gone

**Comment by wizjany** [comment]
item frames and paintings are entities, not blocks. you can't select them. #1018
