### ISSUE TITLE
Brushes in sky where no blocks are

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1941]
### WorldEdit Version

7.2.8-SNAPSHOT+5960-bd87665

### Platform Version

git-Paper-381

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Brushes spawn in at the max world height if you brush in the air.

### Expected Behavior

No brushes in the air if there is no target block to wrap around.

### Reproduction Steps

1. //br sphere 5 5
2. Rightclick in air without target block
3. See blocks

That's the video I recorded https://streamable.com/ewb3iw
You can see, the brushes cut off at 255, the max world height in my world

**Comment by wizjany** [comment]
fixed by #1942
