### ISSUE TITLE
Show warnings when the operation is too big

### ISSUE THREAD

**Issue by Toshimichi0915** [EngineHub/WorldEdit#1944]
### The Problem

I wrongly did //set instead of //wall, then the server crashed.
Unfortunately, doing //undo didn't help because //undo //redo doesn't work after server restarting/crashing.
As a result, the whole map disappeared.

### A Solution

I believe that an warning should be sent before the operation when the number of blocks about to be modified is too big, and the server is going to crash anyway.

### Anything Else?

We might want a command to suppress a warning

**Comment by wizjany** [comment]
duplicates #1500
