### ISSUE TITLE
Mods for Minecraft 1.17.x require additional changes for compatibility

### ISSUE THREAD

**Issue by smmmadden** [EngineHub/WorldEdit#1946]
### WorldEdit Version

7.2.7

### Platform Version

Forge 1.17.1 - 37.0.109

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

**FYI:** Mostly a reminder than issue since these files are often forgotten to be updated.  There are files to change for 1.17.1 to work.
**mods.toml**, ***mixins*** and **pack.mcmeta** need updating for every major release of Minecraft depending on what is included.
Minecraft 1.17.x - Minimum Java Level Supported: 16.0.1
pack.mcmeta files Pack Format=7 for 1.17.x release, 6 for 1.16 and 5 for 1.15, etc.
Minecraft Vanilla Launcher (new one from Microsoft Store) has loading issues that require additional changes to our mods and modpacks.  Read conversation towards the bottom on Forge Support: https://forums.minecraftforge.net/topic/105079-forge-1171-not-launching/?_fromLogin=1
This describes how to workaround the breaking change Microsoft made with the new Vanilla Minecraft launcher.  I'm posting here as I've looked at this 1.17.x version of the mod and found one or both issues exist.  It wasn't an easy process figuring out why mods were not working properly so I've provided the data so you don't have to waste time trying to figure out why.

### Expected Behavior

internal files of the JAR should contain minimum requirements that match Minecraft itself.  Pack Formats are often forgotten about and 1.17.x has an explicit requirement now for Java 16 only.

### Reproduction Steps

1. ...
2. ...

**Comment by wizjany** [comment]
I'm not sure what the bug here is. Are you trying to say WE doesn't run with the new launcher? that should have absolutely 0 bearing on the MC instance itself barring some major bug in the launcher (or possibly forge).
