### ISSUE TITLE
//setbiome not working 1.16.5

### ISSUE THREAD

**Issue by skicek** [EngineHub/WorldEdit#1951]
### WorldEdit Version

worldedit-mod-7.2.5-dist

### Platform Version

forge-1.16.5-36.2.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

cant change biome with command //setbiom 
on server and on single

### Expected Behavior

expecting to change biome 

### Reproduction Steps

1. set region
2. set biome to some other then it is
3. information popup that relog or restart is required
4. after either of them login see no changes

### Anything Else?

I tried to use it on server side and then copy world to single and then change both ways didnt work

**Comment by octylFractal** [comment]
Read the checkboxes you checked next time.

**Comment by skicek** [comment]
oh I see next forge "friendly" developer who dont fix bugs in LTS forge for 1.16.5?
No one is gonna use 1.17.1 in long term...

**Comment by wizjany** [comment]
correct. we're already starting to update to 1.18. unless you'd like to find the issue and PR it to the archive branch, we don't have the time or motivation to support every old version.
