### ISSUE TITLE
Question! How to disable Version checking

### ISSUE THREAD

**Issue by myxxmikeyxx** [EngineHub/WorldEdit#1958]
### WorldEdit Version

7.2.7

### Platform Version

Paper 1.18

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Editing on unsupported versions is disabled. 

### Expected Behavior

Have a way to override this in config.yaml

### Reproduction Steps

Download version 1.18 server
Download worldedit 7.2.7

### Anything Else?

If we can disabled this check in the config what do I need to add?
Also every checkbox is required even though I am not using the version of world edit that supports my mc version

**Comment by octylFractal** [comment]
There is an intentionally undocumented way to disable this check. If you're willing to accept the risk, you can find it in the code yourself. Or you could just use the updated version on our builds site which is more likely to do what you want.

**Comment by myxxmikeyxx** [comment]
I dont know where to look and you dont have dev builds for 1.18

**Comment by octylFractal** [comment]
They're on builds.enginehub.org.
