### ISSUE TITLE
Feature: Brush and Bone_meal

### ISSUE THREAD

**Issue by instantout** [EngineHub/WorldEdit#1962]
### The Problem

So, there is a Feature that World Edit could Possibly Improve on and this is the Bone_meal item for Brush Command goes as follows.
`/brush apply cyl item bone_meal`
so, We are all aware that bone_meal is used not just for farms but also decoration since we can use it on new blocks like Mossy block. but it covers all the Area which is 100% by default and each block.

### A Solution

The solutions I was thinking how blocks have the `10%stone,90%grass_block` for example. that only bonemeal or other blocks that you right click with can have a % added to them.
this would give it a more natural look, since you can make it 50% or 1% depending on how you like it.|

### Alternatives

Other solution is doing it Via hand or using the Blocks under and changing the style.
but this would require more steps.

### Anything Else?

I'm also aware that bone meal works under the water, so this also gives it an extra chance.
I don't know if World Edit has Alternatives, but //flora is a region and you need to find Pos1 and pos2 and lets not forget World edit does not support //flora for the Mossy blocks. while bone_meal is part of the game.

another thing I was thinking was... Small schematics (like custom Trees) added in a way that you can make a bigger bone meal that generates the trees like World Painter (Just an Idea)

**Comment by me4502** [comment]
From what I can tell everything you've asked for already exists?

You can just use a noise mask to reduce quantity

And there's the schematic brush

**Comment by instantout** [comment]
I'll do some more Research into it then, what would the noise command look like for example?
