### ISSUE TITLE
Saving schematic not storying items in chest when copying into new world.

### ISSUE THREAD

**Issue by DSAH1997** [EngineHub/WorldEdit#1971]
### WorldEdit Version

7.2.8+6008-1246d61

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When copy a build with chests that have items in them and then saving it as a schematic to paste into a new world, the items are no longer in the chests. Copying and pasting in the same world keeps the items in the chest but not the schematic command. Also if I try pasting the schematic in the same world I get the same problem.

### Expected Behavior

The Items should be stored in the schematic when copying. I've done on prior Minecraft version, I think 1.16.5 and it worked fine.

### Reproduction Steps

select the region to copy
//copy
//schematic save (Name)
load into new world or same world
//schematic load (Name)
//paste

### Anything Else?

Could of waited for me to respond before closing the issue I had as it clearly isn't working.

**Comment by wizjany** [comment]
don't create duplicate issues.
