### ISSUE TITLE
//setbiome command does not appear to work correctly (v7.2.8, MC v1.18.1, Fabric v0.12.12)

### ISSUE THREAD

**Issue by Terra-Fabrico** [EngineHub/WorldEdit#1976]
### WorldEdit Version

v7.2.8

### Platform Version

Fabric v0.12.12

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

![Screenshot (163)](https://user-images.githubusercontent.com/84546057/146475853-ae47b241-327f-44ad-a69f-985d9c530faf.png)

After selecting the grassy region shown, and entering in the command/reloading the world, the region's biome did not change.

The flat grass blocks signify the biome as 'desert'; they where successfully converted on a previous attempt.

In this previous instance; it appears that only the two points where the first/second pos of the selection where converted.

### Expected Behavior

I'm aware that chunks are stored in a 4x4 format, so some funky behaviour is unavoidable. But the issue is that it's almost impossible to get the command to work.

### Reproduction Steps

1. Select a 2D region
2. Enter in the command //setbiome desert

**Comment by wizjany** [comment]
you're going to need to select a larger region due to the way blending and such works. not a bug.

**Comment by Terra-Fabrico** [comment]
> you're going to need to select a larger region due to the way blending and such works. not a bug.

![InkedScreenshot (164)_LI](https://user-images.githubusercontent.com/84546057/146476740-ee4e557b-5c7d-4f20-b242-13c5f68f1c1d.jpg)

Here I selected a much larger region. The circles denote the few areas that where converted.

**Comment by wizjany** [comment]
as long as you select a 2d region (or anything less than covering a half-chunk boundary), you're going to get blending from the cubes above and below your selection.

**Comment by me4502** [comment]
Then you didn't select all the areas that it's blending from. It'll blend in a 4x4x4 cube, there's nothing we can do about that
