### ISSUE TITLE
worldedit.limit.unrestricted permision doesnt work

### ISSUE THREAD

**Issue by jokbon** [EngineHub/WorldEdit#1977]
### WorldEdit Version

worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar

### Platform Version

purpur1443 https://purpurmc.org/downloads/

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

_worldedit.limit.unrestricted_ permision doesnt work
using luckperms, other permisions from same group iam in do work.

### Expected Behavior

-.-

### Reproduction Steps

-.-

**Comment by wizjany** [comment]
"doesnt work" is not a bug report. dont leave the template empty.

**Comment by jokbon** [comment]
updated

**Comment by wizjany** [comment]
try `//limit -1` before copying, or change the default/max in the config. the perm just lets you bypass the max, it doesn't change the base limits.
