### ISSUE TITLE
Replacenear function

### ISSUE THREAD

**Issue by JustPixels159** [EngineHub/WorldEdit#1979]
### The Problem

I wrote "//replacenear 10 air tnt " and 10 hours of my life exploded into my face. It gave me severe sadness.

### A Solution

 Pls make a difference between activated and unactivated tnt. So people are happier.

**Comment by wizjany** [comment]
that's...not a thing? did you maybe have redstone nearby that would have activated the tnt?

**Comment by JustPixels159** [comment]
I have no idea. It could very well be possible. Sorry if I am wrong. I just wanted to tell it to someone so I feal better.
