### ISSUE TITLE
Smooth is non-functional below y = 0

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#1983]
### WorldEdit Version

7.2.9

### Platform Version

All Platforms

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Smoothing is breaking below y = 0 for some reason. Needs a look at how the kernel is computed.

### Expected Behavior

Smooth should work the same above and below y = 0.

### Reproduction Steps

1. Go down.
2. Select
3. //smooth

**Comment by octylFractal** [comment]
Fixed by #1986 / #1989.

**Comment by rreeoo** [comment]
Is it fixed ?
I can't still use "/br smoorh" below y=0 prorerly in 1.18.1
