### ISSUE TITLE
Most world edit commands won't work

### ISSUE THREAD

**Issue by Snappydoodle** [EngineHub/WorldEdit#1984]
### WorldEdit Version

7.2.8

### Platform Version

CraftBuikkit

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I try to use a command such as //set, it brings up the error
java.lang.NoSuchMethodError: 'long
net.minecraft.SystemUtils.b()'
I noticed that it doesn't affect all commands, as /biomelist works.

### Expected Behavior

Usually the //set command runs.

### Reproduction Steps

1. select two areas with the axe
2. type //set stone

**Comment by wizjany** [comment]
#1978 #1969 #1972
