### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by Ecorous** [EngineHub/WorldEdit#1985]
### The Problem

I don't really like curseforge and it's owner (Overwolf) and I much prefer to use [Modrinth](https://modrinth.com) instead

### A Solution

Post WorldEdit on [Modrinth](https://modrinth.com)

**Comment by gmankab** [comment]
still actual

**Comment by testmeup3** [comment]
I second this, but there's a very **real reason** why people _should_ upload their mods to Modrinth.

On CurseForge, it's impossible to search for, specifically, updated mods for a specific modloader.
This makes it very hard to find... well, anything really.

Before Overwolf bought Curse, there was a Fabric category you would do some URL magic to remedy this problem. But now there isn't, and it wasn't a good solution either.

So yes, please upload to Modrinth.

**Comment by QuillDev** [comment]
Hey wondering if this is still in consideration? Modrinth plugins is open now for uploads.

**Comment by octylFractal** [comment]
Yes, but I personally haven't had any time to work on or think about anything EngineHub. Not sure what's happening with the rest of the team though, or how they feel about this.

**Comment by gmankab** [comment]
still actual

**Comment by me4502** [comment]
We now have a Modrinth page; https://modrinth.com/plugin/worldedit
