### ISSUE TITLE
item_frame(s) not part of cut/copy/paste operations

### ISSUE THREAD

**Issue by Jahfry** [EngineHub/WorldEdit#1987]
### WorldEdit Version

7.2.8-SNAPSHOT+6004-bfef996

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

item_frame(s) placed in selection area (made sure by placing extra regular stone block next to frame to make sure frame's square was included) are not included in the buffer when copy/pasting to a new area. 

### Expected Behavior

*assuming* this isn't a technological limitation (ie, frames aren't blocks):

include frame in buffer when copying, remove existing frame when cutting. 

### Reproduction Steps

1. Place blocks like:
   [stone][stone]
   [stone][item_frame]

2. Use wand to select bottom-left and top-right [stone]

3. //cut the selection (notice frame remains)

4. //paste selection in a new location (notice no frame)

### Anything Else?

I'm not assuming this is possible, but it would be extremely useful if it is. Am aware frames are not normal blocks. 

Close if considered and simply not doable.

**Comment by octylFractal** [comment]
Use -e on copy and paste.
