### ISSUE TITLE
java.lang.NoSuchMethodError: 'long net.Minecraft.SystemUtils.b()'

### ISSUE THREAD

**Issue by GaldorTelperien** [EngineHub/WorldEdit#1988]
### WorldEdit Version

7.2.8+6008-1246d61

### Platform Version

Craftbukkit

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When trying to use Worldedit i get this error message

java.lang.NoSuchMethodError: 'long net.Minecraft.SystemUtils.b()'

with the request to report this.

### Expected Behavior

Worldedit should work normally

### Reproduction Steps

1. //hcyl stone 1
2. java.lang.NoSuchMethodError: 'long net.Minecraft.SystemUtils.b()'

**Comment by octylFractal** [comment]
use the search bar plz thx

**Comment by GaldorTelperien** [comment]
i did, and the only thing i found is: do not use craftbukkit. is that the answer?

**Comment by octylFractal** [comment]
yes

**Comment by GaldorTelperien** [comment]
:/

**Comment by GaldorTelperien** [comment]
All good i fixed it it works now in craftbukkit

**Comment by GaldorTelperien** [comment]
quick question: where can i ask general questions?

**Comment by octylFractal** [comment]
discord, which has been mentioned both in the issue submission form and in the docs themselves

**Comment by ValouIka** [comment]
> All good i fixed it it works now in craftbukkit

Would be great if you explained how :)

**Comment by GaldorTelperien** [comment]
Not really a fix. I just used the old WorldEdit version. Works like a charm. 
Get the 1.16 worldedit version that one still works.
Find it strange that its not supported by craftbukkit.
Says on the main page: Compatible with Forge, Fabric, Bukkit, Spigot, Paper, and Sponge.

**Comment by me4502** [comment]
CraftBukkit itself is not supported, it's literally an interim build artefact of Spigot that's not published. It shouldn't be used by anyone, and not even Spigot recommends using it. This has been the case for many years.

See https://madelinemiller.dev/blog/paper-vs-spigot/#a-note-about-craftbukkit
