### ISSUE TITLE
World edit does not support your version of Bukkit

### ISSUE THREAD

**Issue by Boatcoats** [EngineHub/WorldEdit#1990]
### WorldEdit Version

7.28

### Platform Version

Paper 1.18.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

even though the server is updated to 1.18.1 and the most recent version of world edit it also updated to 7.28 which supports 1.18.1, world edit gives me an error message when i try to execute any commands. We are fully updated with both paper and world edit.
![2222](https://user-images.githubusercontent.com/96803863/147620042-0c4a5543-56d9-44ee-bc09-31c3b90adb2a.png)
 

### Expected Behavior

The commands will work as intended.

### Reproduction Steps

1. I type //copy (or any editing command)
2. it gives me the above error message
3. any continued attemps respond "editing on unsupported versions is disabled"

### Anything Else?

i really dont know what im missing here. if paper is updated and worldedit is updated, is there any reason it wont execute commands? is another plugin interfering with it?

**Comment by octylFractal** [comment]
highly doubt you are actually using 7.2.8. Please provide your logs.

**Comment by Boatcoats** [comment]
![thing](https://user-images.githubusercontent.com/96803863/147621071-f3e5b3ce-67d5-452f-afe6-4d8792753c08.PNG)
line next to 7.2.8, right is the same error message

**Comment by me4502** [comment]
Those aren't your logs

**Comment by Boatcoats** [comment]
![world edit](https://user-images.githubusercontent.com/96803863/147621827-f4067894-ea7f-4663-be7f-5f227f4ef6b7.PNG)
you are correct that it is not world edit when shown in logs, but in the server jar files this is the most recent version from the forge page
is there somewhere else i can get 7.2.8?

**Comment by me4502** [comment]
You're using Bukkit so you shouldn't be getting it from a forge page? The latest download on BukkitDev is correct.

**Comment by Boatcoats** [comment]
https://dev.bukkit.org/projects/worldedit/files
I got it from this website, I said forge because it says forge in the top left.

**Comment by me4502** [comment]
This really looks like user error tbh, there's nothing wrong with that jar file. Either you didn't restart after updating the version or you downloaded the wrong one and renamed it

**Comment by octylFractal** [comment]
It works for everyone else, so I assume you messed up uploading it along the way. Additionally, you're not even looking at the latest logs, but a specific date. 7.2.8 works fine on latest Paper (108), I literally just tested it right now.
