### ISSUE TITLE
Redstone components pop off block when //replace-ing blocks

### ISSUE THREAD

**Issue by Fireheart318** [EngineHub/WorldEdit#1993]
### WorldEdit Version

Fabric-Official(7.2.8+6008-1246d61)

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I use /replace on a block with a redstone component, plant, etc. on top, said component pops off and turns into an item.

### Expected Behavior

Replacing a block with a redstone component, plant, etc. on top should keep said thing on the block.

### Reproduction Steps

//replace or //set a block with a piece of redstone, comparator, flower, etc. on top

### Anything Else?

Context - I'm trying to change the colored wool/concrete in a redstone build into stone bricks in the process of designing a farm to build in a survival world.

**Comment by octylFractal** [comment]
Try with `//perf update off` and `//perf neighbors off`.
