### ISSUE TITLE
Incorrect Smoothing at Negative Y Values

### ISSUE THREAD

**Issue by homiedion** [EngineHub/WorldEdit#1994]
### WorldEdit Version

7.2.8+60008-1246d61

### Platform Version

3384-Spigot-78a14d9-b8a25cb

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Smoothing behavior fails when operating on terrain whose y coordinate is negative.

Instead of performing the standard behavior the resulting terrain will raise itself towards y=0 performing some smoothing along the way.

### Expected Behavior

Standard smoothing behavior

### Reproduction Steps

1. Create a server with "level-type: FLAT"
2. Attempt to smooth the terrain using either a /brush smooth or /smooth command on a target who's y<0.

If **/br smooth 0 1** is used on a single flat point it will grow a 1 block tower. Repeated uses on the same point continues to grow the tower roughly 10 blocks tall. If one were to raise their aim along the tower this behavior will repeat until it creates/reaches y=0.

**Comment by octylFractal** [comment]
you could bother to read the pinned issues before posting.
