### ISSUE TITLE
[WorldEdit API] Missing artifact io.papermc:paperlib:jar

### ISSUE THREAD

**Issue by rhystedstone** [EngineHub/WorldEdit#1995]
### WorldEdit Version

API v7.2.x

### Platform Version

Maven 3.8.4

### Bug Description

Maven complains about missing bstats (v7.2.0 - v7.2.2) and paper (v7.2.3+).

### Expected Behavior

I expect the API to require no other dependencies, since none are mentioned on the API's documentation.

### Reproduction Steps

Use the WorldEdit API with a maven-built project.

### Anything Else?

This is apparently a weirdness with gradle projects and maven: https://github.com/EssentialsX/Essentials/issues/4554#issuecomment-932811798
I've followed their guide and appended the following to my pom.xml (API v7.2.8):
```xml

<exclusions>
      <exclusion>
	      <groupId>io.papermc</groupId>
	      <artifactId>paperlib</artifactId>
      </exclusion>
</exclusions>
```

**Comment by octylFractal** [comment]
I'm going to agree with Essentials here. We declare it as something that downstream projects don't need, so Maven shouldn't resolve it (theoretically). However, due to Maven's age, it doesn't really have a way to declare that, so you'll have to manually exclude it.

**Comment by octylFractal** [comment]
Also, alternatively, you could just add the PaperMC repository, and it would work out fine.
