### ISSUE TITLE
Full failure with Paper (paper-1.18.1-132) and worldedit-bukkit-7.2.8.jar

### ISSUE THREAD

**Issue by Dave-Redisfa** [EngineHub/WorldEdit#1997]
### WorldEdit Version

worldedit-bukkit-7.2.8

### Platform Version

Paper-1.18.1-132 

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Complete failure with repeated reinstalls and fresh downloads. This only showed up when upgrading Paper to the newest build. As the error code is several pages long, I don't feel the need to paste it here. This is the start:
[WorldEdit] Enabling WorldEdit v7.2.8+6008-1246d61
[16:42:58 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformsRegisteredEvent@601359ed to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-7.2.8.jar:?]

---- Then it fails to load built in registries and provides this ominous warning:

[16:42:58 WARN]: Failed to load the built-in block registry
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting WORLD_EDITING

I have researched solutions, but the easiest one is to avoid MC 1.18.1, apparently. I am just sharing this to ask if anyone else has experienced this issue and if you've found a solution.
This is the first time Worldedit has ever failed on me, except when running an OOD version, which has always been an instant download fix. Not this time. :-( 

### Expected Behavior

Normal load and functionality, as usual.

### Reproduction Steps

1. Set up 1.18.1 MC server with the most recent paper build.
2. Install worldedit jar to plugins folder (worldedit-bukkit-7.2.8.jar)
3. Start server.
4. Server starts, but worldedit plugin crashes.

**Comment by wizjany** [comment]
use discord for support.

**Comment by Dave-Redisfa** [comment]
That was a report. I'm not requesting support.

**Comment by octylFractal** [comment]
It's a poor report then.

> As the error code is several pages long, I don't feel the need to paste it here. 

You should always include full detail. Please provide your _entire_ server log, preferably uploaded to something like https://paste.enginehub.org/.
