### ISSUE TITLE
Commands //setbiome doesn't work properly

### ISSUE THREAD

**Issue by ProXx21** [EngineHub/WorldEdit#1998]
### WorldEdit Version

WE VERSION : Forge-Official(7.2.5+57d5ac9)

### Platform Version

FORGE : 1.16.5-forge-36.2.22

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hello, 

I'm on 1.16.5 Forge (36.2.22) and I'm use worldedit on 7.2.5 version from curseforge. 
When i'm try to use the //setbiome commands on my selected region and I relaunch my game, somes blocks changes to the biome I want but somes block stay at the "default" biome (the_void). 
When I try to change the only block who stay on the wrong biomes, it wont change after multiple try. 

This bug comes from worldedit or by the way Minecraft manages the biomes ? 
Someones have any issus ?

PS: Sorry for my basic english. (baguette) 

Sincerrely, ProXx. 

### Expected Behavior

I want to be able to change the biome on whatever block/region I selected. (100% of the region.)

### Reproduction Steps

1. Make a selection of 5x5 block of grass. 
2. Try to change the biome to jungle or other biome (just to see the changes) 
3. Look at the result, somes block stay on the "default" biomes. Somes changes.

**Comment by wizjany** [comment]
5x5 blocks is at most one chunk section of biome cubes. keep in mind that biomes since 1.15 are set in 4x4x4 cubes and not entire columns, and that there's a good amount of blending in between those cubes.

aside from that, old versions won't get updates so unless this is an actual issue in current versions, invalid issue.
