### ISSUE TITLE
Replacing at an angle in higher versions doesn't seem to work./

### ISSUE THREAD

**Issue by Scrypto510** [EngineHub/WorldEdit#2001]
### WorldEdit Version

7.2.7

### Platform Version

Fabric-Official(7.2.7+9f3e795)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I'm not sure if it got removed but replacing some blocks in a specific angle doesn't work in my Version (1.17.1)
For example: //replace /0d:45d 1 Should replace every selcted block from the angle 0-45 degrees with stone.
It worked like that in older versions like 1.12.2 and I tried multiple varients like /mask /0d:45d 1 or //replace /[0d][45d] 
and everything in between. Nothing seems to work and I couldn't find any information online.
Thanks for the help
Scrypto510

### Expected Behavior

Replacing <block> from an angle <a> to <b> with <block>
Replacing a block from at an angle a to b with another block.

### Reproduction Steps

1. //replace /0d:45d 1 (Version 1.12.2 as far as I know)
2. //replace /0d:45d 1 (In Version 1.17.1 doesn't work)

**Comment by octylFractal** [comment]
This isn't a WorldEdit feature.
