### ISSUE TITLE
Rotate command bug

### ISSUE THREAD

**Issue by zReport02** [EngineHub/WorldEdit#2005]
### WorldEdit Version

6.1.10-dist

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The rotate command does not work as it should.
Blocks like stairs etc. they are all buggy, they don't rotate ..

### Expected Behavior

That all blocks with the command rotate rotated well

### Reproduction Steps

1. Start server forge 1.12.2
2. Put worldedit as mod
3. Make a selection and rotate them

**Comment by JOO200** [comment]
Your version is not supported. Update Minecraft and WorldEdit.

**Comment by wizjany** [comment]
![](https://i.imgur.com/t5B7Xym.png) hilarious
