### ISSUE TITLE
//restore is replacing terrain with Papers anti X-ray blocks!

### ISSUE THREAD

**Issue by TomLewis** [EngineHub/WorldEdit#2007]
### WorldEdit Version

7.2.9-SNAPSHOT+6053-512a07e

### Platform Version

PurPur 1.18.1 #1502

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Corker here, setup your snapshots, make a selection and //restore when you are using Papers Anti-xray and the restore will replace the blocks with the Anti-Xray blocks! 

I got a bit of a shock doing this in the nether and all the netherite that generated!

Boring normal terrain in the nether
![2022-01-12_22 00 02](https://user-images.githubusercontent.com/144046/149230580-93ef232d-d9e7-4855-8ae5-5e04a79a317a.png)

After a //restore then changes it to the anti-xray blocks! infinite free netherite for staff!

![2022-01-12_21 53 26](https://user-images.githubusercontent.com/144046/149230669-91c7fbe4-3606-4bbf-9955-ff0358f5d04b.png)

I use Engine-mode 2 from to re-produce.
https://gist.github.com/stonar96/ba18568bd91e5afd590e8038d14e245e

### Expected Behavior

Not generate new blocks based off the Anti-xray.

### Reproduction Steps

1. Setup your snapshots
2. make a selection over terrain and //restore
3. Voila!

**Comment by octylFractal** [comment]
Confirmed not actually occurring in Discord.

**Comment by TomLewis** [comment]
Edit, looks like this is a visual bug only. trying to mine the blocks they get put back to normal, and logging out and in-again fixes it.
