### ISSUE TITLE
Command usage not being sent properly

### ISSUE THREAD

**Issue by u9g** [EngineHub/WorldEdit#2010]
### WorldEdit Version

Bukkit-Official(7.2.8+6008-1246d61)

### Platform Version

git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Running `Bukkit.getCommandMap().getKnownCommands().get("brush").getUsage()` (on paper) results in duplicated usage output (with any worldedit command). It always looks like this: `/brush /brush <forest|butcher|paint|none|clipboard|gravity|heightmap|extinguish|sphere|raise|smooth|cylinder|set|apply|deform|lower|snow|biome>`, showing the command, then the command with args.

### Expected Behavior

I'd expect only the command with args to be shown as is done with every other native command like from spigot/paper/etc.

### Reproduction Steps

Run 
```java
        String usage = Bukkit.getCommandMap().getKnownCommands().get("brush").getUsage();
        cs.sendMessage("Usage: " + usage);
```
on Paper, and watch the output be: `Usage: /brush /brush <forest|butcher|paint|none|clipboard|gravity|heightmap|extinguish|sphere|raise|smooth|cylinder|set|apply|deform|lower|snow|biome>`

**Comment by wizjany** [comment]
er, to be clear on that title, this is about whatever is stored in the bukkit api and not anything about what's sent to the client yes? does that string actually get used anywhere?

**Comment by u9g** [comment]
> er, to be clear on that title, this is about whatever is stored in the bukkit api and not anything about what's sent to the client yes? does that string actually get used anywhere?

I was going to use it for my plugin hence the problem, but yeah, this is a problem with what's being stored in the bukkit api, hence the title change.

**Comment by wizjany** [comment]
0ad3ab14d9aba383996e539d23d28b60e4d1e610
