### ISSUE TITLE
//drain doesn't drain waterlogged fences

### ISSUE THREAD

**Issue by u9g** [EngineHub/WorldEdit#2011]
### WorldEdit Version

7.2.8

### Platform Version

git-Paper-155

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

//drain doesn't drain waterlogged fences

### Expected Behavior

It should drain waterlogged blocks too

### Reproduction Steps

1. Waterlog a fence
2. //drain 5

**Comment by me4502** [comment]
Use the `-w` flag with drain, such as `//drain -w`. This isn't a bug.
