### ISSUE TITLE
//regen seed with datapack writes bad chunk data

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#2013]
### WorldEdit Version

WorldEdit version 7.2.9-SNAPSHOT+6064-0ad3ab1

### Platform Version

git-Paper-155 (MC: 1.18.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

On my server I use the [Terralith](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/) datapack.

If you use //regen seed "5631573288712153026" on my testing case, WorldEdit throws the following exception and the server crashes:
https://paste.gg/p/anonymous/1a7b0aea05c143b0904e22e18f40b23d/files/367f654b7b274128946d4bd42894fd68/raw

Luckily I had a backup to restore from, but it writes some faulty chunk data or something the server does not like, 

### Expected Behavior

No crashes and faulty data, it should regenerate my world.

### Reproduction Steps

1. Get the Terralith datapack
2. //chunk
3. //set 0
4. Try to regenerate the area with //regen seed

**Comment by me4502** [comment]
Spigot doesn't properly support world generation from data packs

**Comment by josephjthomas** [comment]
Does Paper offer a suitable API for it?

**Comment by me4502** [comment]
I'm not referring to APIs. If you use custom worldgen or biomes with spigot, it corrupts the world slowly. Any plugins that interact with the API will also get invalid values - but that's not an API issue but an issue with the underlying world. Paper doesn't resolve it

**Comment by wizjany** [comment]
at least as of 1.18.2 I can't reproduce this.
