### ISSUE TITLE
Keep Blockstates when replacing with a similar block

### ISSUE THREAD

**Issue by hexszeug** [EngineHub/WorldEdit#2014]
### The Problem

When you want to replace things like stairs and slabs with other variants (stone stairs with oak stairs), which have rotations or other block state properties you can't keep the old block states.

### A Solution

When replacing keep all block states, the new block has too, unless you are defining specific block states for the new block.

### Alternatives

Have something like
//replace stone_slab[#] with oak_slab[#]
to tell world edit, it shold keep the old block states.

**Comment by me4502** [comment]
Check the docs before making feature requests - this has existed for years
