### ISSUE TITLE
//replace slab ^%slab,%slab etc

### ISSUE THREAD

**Issue by RaulMihai1** [EngineHub/WorldEdit#2015]
### WorldEdit Version

7.2.7+9f3e795

### Platform Version

Bukkity

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I am trying to replace slabs, but I want to replace them with a certain % of different slabs so I run the below command: 

//replace stone_brick_slab ^60%stone_brick_slab,10%stone_slab,10%mossy_stone_slab,10%

but it says "Invalid value for <to> (Block name '60%stone_brick_slab' was not recognised.), acceptable values are any pattern" 

### Expected Behavior

Based on the wiki I should be able to use the ^ version of replacing command in order to replace the slabs but keep their data, am I doing something wrong or is there a specific command I need to run in order to randomize the slabs as well? 

### Reproduction Steps

//replace stone_brick_slab ^60%stone_brick_slab,10%stone_slab,10%mossy_stone_slab,10%

**Comment by wizjany** [comment]
use discord for support. this isn't a bug.
