### ISSUE TITLE
Basic //fill Command

### ISSUE THREAD

**Issue by TornadoGamer10** [EngineHub/WorldEdit#2017]
### The Problem

There is a vanilla /fill command, but it has a limited number of blocks that it can be used for and you have to type in the coords of the corner blocks.

### A Solution

A //fill command that would function as a better version of the /fill command. You could use the wand to designate coordinates and it wouldn't have the block limit that the vanilla command has. The command would be //fill (block) [nbt]

### Alternatives

The //replace command does work, but you need to replace every block type in order to get a consistent area.

**Comment by wizjany** [comment]
you should at least like, read the quick start on the docs. this is the most basic stuff in the plugin.
