### ISSUE TITLE
Crash: Mod incompatibility.

### ISSUE THREAD

**Issue by Atlantispy** [EngineHub/WorldEdit#2026]
### WorldEdit Version

7.2.9

### Platform Version

Forge 30.0.59

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Crash on Launch updating from Worldedit 7.2.8 to 7.2.9.

### Expected Behavior

Expected not to crash.

### Reproduction Steps

1. Using the AtlanSMP modpack. https://www.curseforge.com/minecraft/modpacks/atlan-smp
2. Remove Worldedit 7.2.8 and place 7.2.9 JAR in mods folder.
3. Launch game.

### Anything Else?

[crash-2022-02-01_10.59.35-fml.txt](https://github.com/EngineHub/WorldEdit/files/7979839/crash-2022-02-01_10.59.35-fml.txt)

It seems to be a crash relating to the mod:

https://www.curseforge.com/minecraft/mc-mods/architectury-forge

**Comment by wizjany** [comment]
Not sure what this has to do with WorldEdit, nor are you even using 7.2.9 according to the crash report provided.
Please comment with proper versions and reproduction if you can pin this down to being even related (never mind caused by) worldedit and we can re-open this.

**Comment by jarocajavi** [comment]
i think was happen to me the same problem, but with fabric instead, im going to create a new issue for this
