### ISSUE TITLE
UPDATE is not triggered with applySideEffects

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#2027]
### WorldEdit Version

7.2.x, 7.3.0-SNAPSHOT

### Platform Version

All Platforms

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

UPDATE side-effect does not get applied when using `applySideEffects`. For fast reorder to work properly, this _must_ occur.

### Expected Behavior

UPDATE is triggered on the block.

### Reproduction Steps

1. `//reorder fast`
2. Set a single sand block in the air.
3. It doesn't fall. Oops.

**Comment by me4502** [comment]
Fixed in 30e1601489b3ed4a416a21de0595f444dad2c945
