### ISSUE TITLE
Invalid blocks and tags in patterns

### ISSUE THREAD

**Issue by 777-Scorpion-777** [EngineHub/WorldEdit#2030]
### WorldEdit Version

7.2.7

### Platform Version

Forge 37.1.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

It's impossoble to use some blocks and tags in copy/paste filters, namely, flowing_water, flowing_lava, #minecraft:water, #minecraft:lava, as well as all tags from custom datapacks.

### Expected Behavior

It should be possible to use  all block IDs and tags in the filters.

### Reproduction Steps

1. Select and copy any region.
2. Try writing this command: "//paste -om ##water". You can see that auto-completion does not work and the game throws an error when using this command.

**Comment by wizjany** [comment]
water and lava aren't tags, and flowing_water and flowing_lava aren't blocks. not quite sure what you're trying to say the issue is.
