### ISSUE TITLE
Flag parsing terminator

### ISSUE THREAD

**Issue by KainGross** [EngineHub/WorldEdit#2031]
### WorldEdit Version

Any

### Platform Version

Spigot/Paper all versions, maybe others too

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Flag parsing terminator "--" doesn't works because String#equals check is after flag pattern check. (Pattern is not allowed two minuses)
Problem is in CommandContext class. (https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/minecraft/util/commands/CommandContext.java)
Screen of bugged place in sources: https://prnt.sc/26sdnhn

### Expected Behavior

Don't parse flags after --

### Reproduction Steps

Use any command with terminator

**Comment by octylFractal** [comment]
That part of the command lib isn't even used anymore and is deprecated for removal. Why is this an issue?

**Comment by KainGross** [comment]
WorldGuard's last version using it, if i understand correctly.

**Comment by octylFractal** [comment]
Yes, but realistically WG should be switched to use Piston rather than spending time fixing this bug, and also this doesn't explain why it is an issue in context. Is there some command you were trying that you were unable to execute because of this?

**Comment by wizjany** [comment]
this is documented in WG's tracker already. I agree that there's no use fixing it here, WG just needs to be migrated at some point.

**Comment by KainGross** [comment]
Was an problem to use command with arg starts with minus, terminator would help with it.

**Comment by KainGross** [comment]
Fine, I have understand  u. Then, I'm just close it.
