### ISSUE TITLE
Biome commands not working through the console

### ISSUE THREAD

**Issue by Maroon28** [EngineHub/WorldEdit#2032]
### WorldEdit Version

7.2.8

### Platform Version

git-Purpur-1537

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When trying to do `//setbiome` through the console, an error message is sent as follows:
```
This command must be used with a player.
```

This also extends further to other biome commands, not just setbiome

### Expected Behavior

The command should work normally from the console, like all the other commands

### Reproduction Steps

1. Make a region selection through the console
2. Try doing //setbiome plains, for example.
3. Recieve the error message.

**Comment by wizjany** [comment]
fyi you are not in fact using the latest WE >.>

**Comment by me4502** [comment]
Fixed in 76ec878eb20677ea5507f96ceacb73487b19026f
