### ISSUE TITLE
Compass movement not working below y coordinate 0

### ISSUE THREAD

**Issue by GeumyiTV** [EngineHub/WorldEdit#2036]
### WorldEdit Version

7.2.9

### Platform Version

Spigot

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WorldEdit Compass does not work properly when holding the compass and going below the y-coordinate of 0

### Expected Behavior

..

### Reproduction Steps

1. ...
2. ...

### Anything Else?

Change the compass to be usable even at the y-coordinate of 0 or less

**Comment by wizjany** [comment]
can't repro
