### ISSUE TITLE
//chunk only selects to y=0 in 1.18

### ISSUE THREAD

**Issue by nymda** [EngineHub/WorldEdit#2038]
### WorldEdit Version

7.2.9+e20e013

### Platform Version

Forge 7.2.9

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Running //chunk only selects the current chunk to y=0, ingame y level in the overworld can now be as low as -64 since the caves and cliffs update.

### Expected Behavior

//chunk should select the entire chunk down to y=-64

### Reproduction Steps

1. Enter overworld
2. Run //chunk
3. Run //set 0
4. Blocks will be left at the bottom of the created hole from y=0 down to y=-64

**Comment by JOO200** [comment]
And the description of the //chunk command claims to select only 256 block tall areas

https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java#L259

**Comment by nymda** [comment]
invalid? why?

**Comment by wizjany** [comment]
did you read the comment above?

**Comment by nymda** [comment]
ah i thought that was also a bug report, considering //chunk logically would select the entire chunk and not just half of it
