### ISSUE TITLE
Help me with WE and permissions on a server

### ISSUE THREAD

**Issue by FNAFman201** [EngineHub/WorldEdit#2046]
### WorldEdit Version

1.16.5

### Platform Version

paper

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

People joining my server have been able to use superpickaxe and i dont know why.  i have a permissions plugin installed and dont know what the permission to make people not able use it is.

### Expected Behavior

i thought someone would just join and not be able to use world edit and they couldnt except for superpickaxe

### Reproduction Steps

make a server with world edit and a permissions plugin.
let people join.

### Anything Else?

i really need help here

**Comment by FNAFman201** [comment]
please

**Comment by wizjany** [comment]
this is neither a place for support nor do we appreciate you lying on the template and editing to get around the confirmations.
