### ISSUE TITLE
WorldEdit doesn't start on Fabric 1.18.2

### ISSUE THREAD

**Issue by WerySkok** [EngineHub/WorldEdit#2048]
### WorldEdit Version

7.2.9+e20e013

### Platform Version

Fabric Loader 0.13.3, Fabric API 0.47.10+1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Minecraft with Fabric modloader doesn't start with WorldEdit 7.2.9.

MultiMC log:
https://paste.ee/p/D3gIJ

### Expected Behavior

Minecraft should start.

### Reproduction Steps

1. Install Minecraft 1.18.2.
2. Install Fabric Loader 0.13.3.
3. Install Fabric API 0.47.10+1.18.2.
4. Install WorldEdit 7.2.9+e20e013.
5. Start Minecraft

**Comment by JOO200** [comment]
Use a dev build from https://builds.enginehub.org/job/worldedit/last-successful?branch=version/7.2.x

**Comment by WerySkok** [comment]
Thanks for the advice. Dev build works.
