### ISSUE TITLE
World Edit and PaperMC for 1.18.2

### ISSUE THREAD

**Issue by JBar2K** [EngineHub/WorldEdit#2050]
### WorldEdit Version

7.2.9

### Platform Version

Paper 1.18.2-232

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When attempting to edit an area, a message is displayed alerting me that world edit is not compatible with minecraft 1.18.2

### Expected Behavior

no alerts, just editing.

### Reproduction Steps

1. select coordinate 1 with wooden axe
2. select coordinate 2
3. enter any command; //walls stone
4. receive error

**Comment by clareiscool** [comment]
Wait so what was the fix?

**Comment by wizjany** [comment]
![](https://i.imgur.com/u27DFo0.png)

not lying on issue templates

**Comment by octylFractal** [comment]
consider asking on discord about updates, it is not a bug that it breaks
