### ISSUE TITLE
Architectury compatibility 

### ISSUE THREAD

**Issue by jarocajavi** [EngineHub/WorldEdit#2051]
### WorldEdit Version

7.2.9

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If this issue is consider duplicate please make me know and close
I think [this](url=https://github.com/EngineHub/WorldEdit/issues/2026) is other problem because in his cause is with forge.

The client crash when i try start fabric 1.18.2 with 3 mods (fabric-api,worldedit and architectury)

In the first time i have more mods, but i was remove slowly to find the problem's root

[crash-2022-03-08_21.20.55-client.txt](https://github.com/EngineHub/WorldEdit/files/8209362/crash-2022-03-08_21.20.55-client.txt)

### Expected Behavior

Just i try update my server since 1.18.1 to ..2
With previous version both of mods works fine together, i used two without any problem.

### Reproduction Steps

1. Install 1.18.2 version of fabric in the client
2. Copy to the mod folder WorldEdit 7.2.9, architectury 4.0.30 & fabric 0.47.10+
3. Start
4. Crash

**Comment by wizjany** [comment]
no clue about architectury but you're not even using a 1.18.2 WE so invalid

**Comment by jarocajavi** [comment]
Yes, i am.... oh, wait. I am ninny, im sorry, some of my modpacks i know are in 1.18.1 version yet...

So, i wait to the update, thanks for the speed.
