### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by 1Euro7Cent** [EngineHub/WorldEdit#2061]
### WorldEdit Version

7.2.9

### Platform Version

forge:1.18.1-39.1.0

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

On startup the client crashes with that error in title.

### Expected Behavior

Start client (not crash)

### Reproduction Steps

1. have a forge development enviroment 
2. add mod to mods folder
3. client does not start

### Anything Else?

I am developing my own mod and I want world edit to test things.
Putting that mod in the mods folder causes the client to not start.

optifine is working. So it's not a general mod loading problem.

crash report:
[crash-2022-03-15_11.19.37-fml.txt](https://github.com/EngineHub/WorldEdit/files/8252241/crash-2022-03-15_11.19.37-fml.txt)

debug log:
[debug.log](https://github.com/EngineHub/WorldEdit/files/8252268/debug.log)

latest log:
[latest.log](https://github.com/EngineHub/WorldEdit/files/8252269/latest.log)

**Comment by wizjany** [comment]
you cant throw "runtime-compiled" mods into a dev environment.
Forgegradle has specific mechanisms for depending on mods and remapping them for your dev workspace, ypu should go look at that.
