### ISSUE TITLE
Worldedit for 1.18.2

### ISSUE THREAD

**Issue by Bombyx08** [EngineHub/WorldEdit#2064]
### The Problem

Please Update Worldedit to 1.18.2.

### A Solution

Update Worldedit to 1.18.2

### Alternatives

Just try to update worldedit to 1.18.2.

**Comment by octylFractal** [comment]
The Problem
You think we haven't made WorldEdit for 1.18.2.

A Solution
Check the `#announcments` channel on Discord, or the commits, or the dev builds site linked from the EngineHub WorldEdit page.

Alternatives
Ask us on Discord, where we'll redirect you to `#announcments` as well.

Anything Else
We already made WorldEdit compatible with 1.18.2.
