### ISSUE TITLE
//snow, but only in snowy biomes

### ISSUE THREAD

**Issue by oskarkk** [EngineHub/WorldEdit#2070]
### The Problem

On my server I had some problems with biomes which left me with terrains like this:

![image](https://user-images.githubusercontent.com/16339637/159126488-ed7d658c-dc20-4a08-a8db-50efb78879ef.png)

I could just wait for it to snow, but I would have to wait for snow in every place like that. And I also have a plugin which greatly decreases frequency of rain/snow, so it won't fix itself fast without intervention.

I could use a brush, but that would be much work.

### A Solution

Make a new flag for //snow command, which would place snow on blocks only if they're in a snowy biome.

**Comment by wizjany** [comment]
just use a biome mask.

**Comment by oskarkk** [comment]
Oh, thanks, that's a great solution.
