### ISSUE TITLE
Carpets not placing correctly

### ISSUE THREAD

**Issue by jamesxr23** [EngineHub/WorldEdit#2073]
### WorldEdit Version

7.2.10

### Platform Version

Forge 1.18.2 - 40.0.32

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when using //set, //replace, or the //copy and //paste commands, carpets do not place correctly when multiple layers of carpet and other blocks are placed.

some of the carpets break and drop their items, while others do not. it appears random which carpets do and do not break. a screenshot has been included. on the left, the 2 layers were created separately, on the right, multiple layers were created at once.
![image](https://user-images.githubusercontent.com/98563429/160254671-ce3f1ab4-716a-4e16-aade-2652fba572fc.png)

### Expected Behavior

carpets should place as expected

### Reproduction Steps

1. use //set to fill a space with carpet. any space taller than 1 will reproduce this bug.

Can also be recreated with //replace, //stack, as well as the copy and paste commands. most likely can be created with other commands too.

**Comment by wizjany** [comment]
looks correct to me. that's how carpets work in minecraft, if you want to prevent physics there's options in //perf

**Comment by jamesxr23** [comment]
> looks correct to me. that's how carpets work in minecraft, if you want to prevent physics there's options in //perf

carpets are able to be placed on top of other carpets, when placed by hand - carpets are able to stack

**Comment by wizjany** [comment]
does suppressing self- and neighbor- updates in //perf fix the issue?

**Comment by jamesxr23** [comment]
unsure what you mean by supressing self-, but it seems that setting neighbor to off works. surely this will affect other things though?

**Comment by wizjany** [comment]
> looks correct to me. that's how carpets work in minecraft, if you want to prevent physics there's options in //perf

this stands then.
