### ISSUE TITLE
when pasting rotate according to the direction the user is facing

### ISSUE THREAD

**Issue by drwoops** [EngineHub/WorldEdit#2075]
### The Problem

having to use //rotate in between //paste is difficult and error prone.

### A Solution

I would love a //paste -r option to rotate the selection in the direction the user is facing.

**Comment by wizjany** [comment]
the only way that makes sense is if you consider the direction you're facing when you load the schematic to be "forward", but that's extremely ambiguous and is specific to the player context. this is far more difficult and error prone than specifying an exact rotation in degrees.

**Comment by octylFractal** [comment]
I think this is not something we would want to implement, it wouldn't work very well in practice unless we locked the rotations, but then it could get really janky if you didn't start aligned.
