### ISSUE TITLE
Replacing with WorldEdit, but keep the stair rotation.

### ISSUE THREAD

**Issue by ezdrial** [EngineHub/WorldEdit#2076]
### The Problem

So I was building a real cool castle with slabs, stairs, blocks etc but now I want to use a different kind of block for them. I want to replace it but some slabs and stairs get the wrong rotation. So is there any way to replace and just keep the block data and position? Some of them are faced differently so I cant do it with adding the rotation thing in the command....

### A Solution

Making it so that the stairs and slabs stay the same way as before.

**Comment by wizjany** [comment]
type applying pattern. read the docs.
