### ISSUE TITLE
When a RegionSelector is loaded via the WE API, it does not update the visual selection

### ISSUE THREAD

**Issue by seb303** [EngineHub/WorldEdit#2081]
### WorldEditCUI Version

1.18.2+01

### Fabric Version

Fabric 0.13.3

### Fabric API Version

Fabric API 0.51.1+1.18.2

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

When a selection is loaded using Denizen/Depenizen (which uses the WE API), the WorldEdit CUI visualisation does not update.  The area is selected properly (confirmed by filling with blocks), just the visualisation does not show - it keeps showing whatever it was showing before.

If the player disconnects and reconnects, or changes worlds, or modifies the selection using a WE command (e.g. //expand 0) then the visualisation updates and shows correctly.

### Expected Behavior

The WorldEdit CUI visualisation should immediately show the loaded selection.

### Reproduction Steps

1. Install Denizen, Depenizen & WorldEdit on server, and WorldEditCUI on client.
https://ci.citizensnpcs.co/job/Denizen_Developmental/
https://ci.citizensnpcs.co/job/Depenizen/
2. Make a cuboid selection using the WE wand.
3. Save the selection as a Denizen cuboid.
/ex note <player.we_selection> as:my_noted_cuboid
4. Make a different selection using the wand.
5. Load the original selection from the Denizen cuboid
/ex adjust <player> we_selection:<cuboid[my_noted_cuboid]>
6. The selection visualisation does not update, even though the selection has actually been loaded (can be confirmed by setting the blocks).

### Anything Else?

Depenizen is calling setRegionSelector in the WE API.

This is the relevant bit in the Depenizen source:
https://github.com/DenizenScript/Depenizen/blob/5ec7cbb56aff08f7d08ddfc60ab6fdfab6274ada/src/main/java/com/denizenscript/depenizen/bukkit/properties/worldedit/WorldEditPlayerProperties.java#L193

**Comment by zml2008** [comment]
If this is a valid issue, it would be on the WorldEdit side, since it's protocol level -- transferring

**Comment by me4502** [comment]
This is more likely those plugins incorrectly using the API by not dispatching CUI updates

**Comment by wizjany** [comment]
yea this is specifically covered in the api docs. setting selections and updating the client are separate methods.
