### ISSUE TITLE
1.18.2 //setbiome Command is Not Working Properly

### ISSUE THREAD

**Issue by Axelotles** [EngineHub/WorldEdit#2086]
### WorldEdit Version

WorldEdit 7.2.10+1742f98

### Platform Version

Forge 40.1.0

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The //setbiome command is incorrectly set from the selected region. Whether it exaggerates the biome placement, scatters it around, or takes no effect whatsoever //setbiome is totally unpredictable, ultimately ruining the neighboring regions.

### Expected Behavior

The //setbiome command is expected to overwrite biomes to the specified biome within the selected area, (i.e., '//setbiome swamp' in a savanna) via the wooden axe/ wand, then rejoining the game.

### Reproduction Steps

1. Use the command //wand for the wooden axe tool.
2. Choose a region to overwrite (preferably a grassy area) by selecting the first point or block with a left-click.
3. Select the final point by right-clicking a new block. (5x5 selected area minimum.)
4. Use the command //setbiome following it with one of these options, (desert, swamp, taiga, jungle, savanna, snowy_plains, etc.)
5. Example: //setbiome jungle
6. Rejoin the world; alternatively, use /kill to quickly reload the biomes. 
7. You will notice one of the few outcomes: larger area affected than the selection, patches scattered around, or little to no effect.

**Comment by octylFractal** [comment]
This is working correctly, read the docs.

**Comment by wizjany** [comment]
see note https://worldedit.enginehub.org/en/latest/usage/regions/regionops/#setting-biomes

**Comment by Axelotles** [comment]
![2022-04-24_21 49 11](https://user-images.githubusercontent.com/104329461/165007811-3c6d8833-f556-480f-8bbb-f456ec81cbf6.png)

//expand vert relieved my stress a bit. Unfortunately, //setbiome still lacks precision compared to 1.13 and below even with the help of //expand vert. The screenshot shows snowy plains, jungle, and desert grass types surrounded by plains grass. The jungle part was only selected in a 3x3 area then I used //expand vert and yet it somehow contaminated a portion of the snowy plains grass with a small patch.

I was hoping for precision, in order to work on a smaller scale rather than having to distance each biome on a greater scale. Hopefully this made sense.

**Comment by wizjany** [comment]
ok, and this is a worldedit bug why? was some part of the note on the docs unclear?

**Comment by Axelotles** [comment]
Well, I initially thought of it as a bug since it's inconsistent. Otherwise, it's was just my misinterpretation, my apologies.

**Comment by octylFractal** [comment]
If you want more precision, go complain to Mojang.
