### ISSUE TITLE
stack with parameter 0 causing error

### ISSUE THREAD

**Issue by starve-l** [EngineHub/WorldEdit#2088]
### WorldEdit Version

7.2.10

### Platform Version

git-Paper-283 MC 1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when you run the command `//stack 0`, we throws an error. when doing the same with //move, worldedit catches that error

### Expected Behavior

//stack should check for a valid integer

### Reproduction Steps

1. run //stack 0

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/WorldEdit/commit/31e5298f39d5b70419078b77735798ec93951b32
