### ISSUE TITLE
Block state mask doesn't work at all

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#2089]
### WorldEdit Version

7.2.10

### Platform Version

Forge 40.1.0

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The block state mask doesn't work at all, it simply doesn't match anything in strict mode, and doesn't match what it should in fuzzy mode.

### Expected Behavior

e.g. `^=[axis=y]` should match y-axis logs.

### Reproduction Steps

1. Select some logs with `[axis=y]`.
2. `//replace ^=[axis=y] stone`
3. 0 blocks replaced.

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/WorldEdit/commit/3eefaa29ddc1bcf9ff40a68bac80462e8b7560f3
