### ISSUE TITLE
Choosing First Position

### ISSUE THREAD

**Issue by Feriousgamer1** [EngineHub/WorldEdit#2090]
### WorldEdit Version

7.2.5

### Platform Version

1.16.5-forge-36.2.34

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I am selecting the first point it selects the coordinates of the block then auto changes to (-1, -1, -1).

### Expected Behavior

It is supposed to just choose the coordinates of the block I clicked on.

### Reproduction Steps

I just left click on a block

**Comment by wizjany** [comment]
https://worldedit.enginehub.org/en/latest/faq/#when-i-select-worldedit-also-selects-1-1-1
