### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by HDAboba** [EngineHub/WorldEdit#2092]
### WorldEdit Version

7.2.10

### Platform Version

Mohist 1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I installed WorldEdit's latest version (7.2.10), joined my Minecraft server, typed //wand and then it said: "This version of WorldEdit is not supporting your Bukkit version. Update WorldEdit, so everything will work."
And then it said: "Wand item is mis-configured or disabled."

### Expected Behavior

It have to gave me Wand, but it didn't.

### Reproduction Steps

1. Minecraft version 1.18.2
2. I typed  //wand
3. It said "This version of WorldEdit is not supporting your Bukkit version. Update WorldEdit, so everything will work."
4. It also said "Wand item is mis-configured or disabled."

### Anything Else?

Note: I have latest version of WorldEdit.

**Comment by wizjany** [comment]
dont lie on the template

**Comment by HDAboba** [comment]
wdym
