### ISSUE TITLE
//chunk selects only to y:0 and not y:-64 on 1.18

### ISSUE THREAD

**Issue by xar55** [EngineHub/WorldEdit#2093]
### WorldEdit Version

7.2.11-SNAPSHOT+6155-3eefaa2

### Platform Version

git-Paper-318

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

as in title
//chunk selects only to y:0 and not y:-64 on 1.18

### Expected Behavior

//chunk should select the whole chunk

### Reproduction Steps

1. //chunk
2. for e.g. //cut
3. see that worldedit is broken and go cry into the corner ;(

### Anything Else?

no

**Comment by wizjany** [comment]
#2038, #2040, etc
