### ISSUE TITLE
Secondary held block is place when using wand

### ISSUE THREAD

**Issue by Josh-65** [EngineHub/WorldEdit#2094]
### WorldEdit Version

7.2.10

### Platform Version

Paper 1.18.2 #329

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If i have a block then use the axes left click to set first position it will place the block in the secondary hand

### Expected Behavior

Block should not be placed or removed after placed

### Reproduction Steps

Hold a block in the second hand
set first position with wand

**Comment by wizjany** [comment]
#1255
