### ISSUE TITLE
move/copy looses servos and cable config for industrial revolution

### ISSUE THREAD

**Issue by Seegras** [EngineHub/WorldEdit#2097]
### WorldEdit Version

7.2.10

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If you select and move any of the "Industrial Revolution"-mod item or fluid pipes, if you copy or move them, the result will have lost all config (blacklist/whitelist) and all servos that were on them.

Undo doesn't restore the original state either. 

### Expected Behavior

copying, pasting, moving and undoing keeps the information associated with these pipes. 

### Reproduction Steps

You can test this by adding worldedit to a modpack containing Industrial Revolution, All of Fabric 5 for instance.

**Comment by me4502** [comment]
This doesn't sound like a WorldEdit issue. Either WorldEdit isn't copying NBT data correctly (in which case it'd affect all BlockEntities), or that mod is storing data externally where WE cannot access it.

If it's the latter, it's up to the mod to either add support for it or store the data on the block like other mods.
