### ISSUE TITLE
Increase default BlockState count

### ISSUE THREAD

**Issue by wizjany** [EngineHub/WorldEdit#2098]
https://github.com/EngineHub/WorldEdit/blob/3eefaa29ddc1bcf9ff40a68bac80462e8b7560f3/worldedit-core/src/main/java/com/sk89q/worldedit/internal/block/BlockStateIdAccess.java#L35

modern MC has closer to 32k than 16k

**Comment by Justusbr0405** [comment]
Wizjany is an asshole xx

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/WorldEdit/commit/15bd7ff44120ae22448f168f14d1f66ecfbf377d
