### ISSUE TITLE
WorldEdit commands do not work if are runned with '/execute run'

### ISSUE THREAD

**Issue by CosmicAxolotl** [EngineHub/WorldEdit#2100]
### WorldEdit Version

7.2.10

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Consist on that all the WorldEdit commands does not work if are run with `/execute`. Which is inconsistence with the chat autofill.

### Expected Behavior

Using WorldEdit commands with `/execute` arguments runs as other commands works, saving context: executer, position, & rotation.

### Reproduction Steps

1. Write `/execute run we version` in the chat (or using arguments as positioned).
2. Run the command.

**Comment by wizjany** [comment]
this is not a bug. WE commands on forge/fabric(/sponge?) currently only support being run directly by a player.
