### ISSUE TITLE
No World Edit folder created inside config folder

### ISSUE THREAD

**Issue by sprocketaudio** [EngineHub/WorldEdit#2104]
### WorldEdit Version

worldedit-mod-7.2.10.jar

### Platform Version

Forge 40.1.20

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

After loading in once mod is in place, although the mod seesm to work there is no worldedit config folder under config:

![image](https://user-images.githubusercontent.com/13222732/170357001-3f5df514-c242-48ba-8fac-7e84934997fb.png)

### Expected Behavior

A Worldedit folder with the config settings file sahould be created

### Reproduction Steps

1. Add world edit to server
2. Start server

**Comment by octylFractal** [comment]
Provide logs, please.

**Comment by sprocketaudio** [comment]
This has resolveds itself after an ATM pack update
