### ISSUE TITLE
Worldedit sets position (-1,-1,-1)

### ISSUE THREAD

**Issue by PilgetTubeYT** [EngineHub/WorldEdit#2105]
### WorldEdit Version

7.2.5

### Platform Version

1.16.5 Forge 36.2.35

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Worldedit sets a new position (-1,-1,-1) after setting the 1st position on a block with a wooden axe.

### Expected Behavior

Not setting (-1,-1,-1).

### Reproduction Steps

1. Left click with a wooden axe

### Anything Else?

![Screenshot_43](https://user-images.githubusercontent.com/106480112/170874494-ad1b0968-2bcf-4b09-91ed-289384af672b.png)

**Comment by wizjany** [comment]
many time duplicate and even covered on the FAQ on the docs.
