### ISSUE TITLE
Could not pass StartedEngineEvent$Impl to worldedit

### ISSUE THREAD

**Issue by Ragchel** [EngineHub/WorldEdit#2106]
### WorldEdit Version

7.2.9

### Platform Version

SpongeForge v1.16.5-36.2.5-8.1.0-RC1137

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Worldedit throws errors and crashes the server when using commands

### Expected Behavior

Worldedit to load in and function as intended

### Reproduction Steps

1. Install Forge
2. Install SpongeForge
3. Install Worldedit 7.2.9 (stable) (or any newer experimental one)
4. Throws errors
5. Server crashes

### Anything Else?

Clean boot server log: https://tntdestroyr.stackstorage.com/s/b7A9fhbeXhi5poUs

Mods installed: Pixelmon 9.0.0
Forge version: 36.2.33

Got a functional backup file of a VM that has this exact issue if testing is required without much consequences

**Comment by me4502** [comment]
It's currently an extremely large effort to support both SpongeForge and SpongeVanilla, as direct accesses to the MC codebase prevent a plugin from working on both. As the Sponge API is missing many things we need, we currently require direct access. 

For SpongeForge it's likely a better idea to use Forge WorldEdit until either the ability to directly access MC code on both is resolved, or the Sponge API is able to fulfill all of our requirements.

**Comment by Tntdestroyr** [comment]
This issue occurs no matter the version used.

sponge plugin and the forge mod cause the exact same issues.

**Comment by TepelStreeltjeEoA** [comment]
Adding onto this thread, I am also running into this issue. I have tried using WorldEdit forge version 7.2.5 as @me4502 suggested but ran into the following crash: https://pastebin.com/9jvjpHLD

Seems like SpongeForge users are stuck without a working WorldEdit version. I am using spongeforge-1.16.5-36.2.5-8.1.0-RC1152.

**Comment by octylFractal** [comment]
The TLDR is that SpongeFoege has fundamentally different mappings, and we have no ability to build a proper mod release for SF 1.16.5. This will likely not be solved unless someone updates the 1.16.5 branch to build with Java 17. I don't think any of us have time to do that right now.

**Comment by Tntdestroyr** [comment]
> The TLDR is that SpongeFoege has fundamentally different mappings, and we have no ability to build a proper mod release for SF 1.16.5. This will likely not be solved unless someone updates the 1.16.5 branch to build with Java 17. I don't think any of us have time to do that right now.

Totally understandable since SpongeForge just gave some half baked 1.16.5 rewrite and then moved on from it themselves now that its becoming relevant.

Works fine with any other server software

**Comment by nickkeane** [comment]
Can reproduce the same issue - commands not working w/ latest Sponge plugins, and server crash with Curseforge version. Guess there's no way to use WorldEdit on 1.16.5 atm w/ Sponge :(.

**Comment by xinwolfthorn** [comment]
I have the exact same problem, just totally unuseable on 1.16.5.. Typing just //br and not even hitting enter crashes the server, broken!
