### ISSUE TITLE
Worldedit Region with a specific World, not Temp World

### ISSUE THREAD

**Issue by colaman90** [EngineHub/WorldEdit#2119]
### The Problem

Hi Everyone,

we are an 8-year old survival Server and due to the leave / cleanup of players, we need to regenerate pieces of the world. 

Before the 1.18 Update it was no problem, the regenerated world had the same old biome borders like the original one.

Now, after the 1.18 Update, we all know that biomes has changed a lot....

For an example see the attached screenshot. On the left side you see the Original world and on the right side the same place with //regen
![left-normal_right-after-regen](https://user-images.githubusercontent.com/61457390/173342660-cb015ef7-e3e4-4de6-b959-1c3b55f68dac.jpg)

We have implemented a workaround for us that looks like this:
- Generate a Original World in 1.17 with Seed from World
- Generate all Chunks with Chunky, so the whole world is fully generated
- Switch Server Version to 1.18.x
- Generate all new Chunks below 0 with Chunky
-> Now you have a world with the old biomes but with the new negative Things in it. We named it "converted original world"

If we want to regenerate a piece of our world, we go the exact same coordinates in the converted original world and copy / paste the region and now you will see, there isn't any hard border in the bioms, its just the same ;)

![left-normal_right-with-converted-original-world](https://user-images.githubusercontent.com/61457390/173342667-3c44756e-3091-4ddb-90d1-8652b4cc71f4.jpg)

### A Solution

So from our perspective it would be a great feature if we can select a world with UUID in the WorldEdit Config for the regeneration command so the worldedit selection is cut from this world instead of regenerated instead of the regular function with the  worldseed and temp world an new 1.18 biomes.

Do you guys think this would be possible ?

Kind regards
Cola

**Comment by me4502** [comment]
This sounds like you want the snapshots feature, not regen. Regen calls the game's generator, while the snapshots feature restores the selected area to a previously saved world.

**Comment by me4502** [comment]
If you have a world that a UUID can be used for, you have a world that can be used as a snapshot. I'm not exactly understanding what you mean sorry?
