### ISSUE TITLE
//biome reset

### ISSUE THREAD

**Issue by Lolothepro** [EngineHub/WorldEdit#2120]
### The Problem

Once a biome has been modified on a map, it is impossible to restore it to its previous state.

### A Solution

Add a command to reset the biome with the generation seed.

**Comment by wizjany** [comment]
regen

**Comment by Lolothepro** [comment]
La commande /regen ne fait pas que changer le biome, elle ramène le chunk à sa forme originale.

**Comment by octylFractal** [comment]
You can mask regen with gmask like most other commands, allowing you to mask out the blocks using //gmask =0

**Comment by octylFractal** [comment]
You should see //help regen, if you need further support please use the Discord server.
