### ISSUE TITLE
Can´t replace, set (etc)

### ISSUE THREAD

**Issue by firxs1x** [EngineHub/WorldEdit#2123]
### WorldEdit Version

7.2.11-SNAPSHOT.dist

### Platform Version

Bukkit-Official(7.2.11-SNAPSHOT+6192-3433e40)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I want to replace something in my Plot but it says "To bypass your restrictions, use /plot wea" but that plot wea commands doesn´t exist. 

### Expected Behavior

That´ll not Work fine.

### Reproduction Steps

1. Type /plot wea (but it doesn´t exist)

### Anything Else?

Can you release the WorldEdit plugin?

**Comment by me4502** [comment]
Not worldedit related, ask your plot plugin
