### ISSUE TITLE
i downloded the 1.2.10 [the latest verson] and it says that i need the newest verson on my shkockbyet server can someone help

### ISSUE THREAD

**Issue by kupeyy** [EngineHub/WorldEdit#2124]
### WorldEdit Version

1.2.10

### Platform Version

spigot 1.19 auto up-dating

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

it say i need the latist verson and i have the letest verson

### Expected Behavior

its sopost to let me use world edit

### Reproduction Steps

1. ...
2. ...
hello

**Comment by me4502** [comment]
Use 7.2.11 snapshots

**Comment by kupeyy** [comment]
> 

can i get the downlod link i cant find it
