### ISSUE TITLE
Unhandled exception executing tab-completer

### ISSUE THREAD

**Issue by Tencryn** [EngineHub/WorldEdit#2125]
### WorldEdit Version

7.2.11-beta-01

### Platform Version

Paper 1.19-31

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I'm getting a tab-completer error when I'm typing the following command `/brush cyl "oak_slab[waterlogged=true]"`. I first noticed the error on a Purpur fork in 1.18.2 with WE 7.2.10, but proceeded to test on Paper 1.19-31 with WE 7.2.11 Beta 01. 

`org.bukkit.command.CommandException: Unhandled exception executing tab-completer for '/brush cyl "oak_slab[waterlogged=true' in com.sk89q.bukkit.util.DynamicPluginCommand(brush)`

The full error can be found here: https://paste.enginehub.org/DCFGW5MJp

### Expected Behavior

Did not expect to receive an error, but either auto-complete suggestions, or nothing at all.

### Reproduction Steps

1. Type the following `/brush cyl "oak_slab[waterlogged=true`, if the command is complete then move the cursor before the closing `]`
2. See the error in console

**Comment by wizjany** [comment]
will be closed by #2213 since it's not linked yet
