### ISSUE TITLE
Sculk sensor in pasted build not activating

### ISSUE THREAD

**Issue by DoctorJohnSmith** [EngineHub/WorldEdit#2126]
### WorldEdit Version

7.2.11-beta-01

### Platform Version

git-Paper-34 (MC: 1.19)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Sculk sensors pasted from a copied build or loaded from a schematic do not detect any sounds or fire off redstone unless a player directly walks on them. 

### Expected Behavior

pasted sculk sensors should respond to sounds like a generated or hand placed one would

### Reproduction Steps

Create a build using a sculk sensor, either on its own or connected to redstone
select and copy the build
paste the build
walk near the skulk sensor open chests, blow goat horn, etc

**Comment by wizjany** [comment]
probably #1619

**Comment by PiTheGuy** [comment]
I have noticed this. While not ideal, breaking and replacing the sculk sensor seems to fix the issue.
