### ISSUE TITLE
Redstone torches of different types get counted separetly in //distr

### ISSUE THREAD

**Issue by Error1000** [EngineHub/WorldEdit#2127]
### WorldEdit Version

7.2.11-beta-01+6200-0877589

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

`//distr` counts torches in different states as different blocks.
Example output:
```
------------- Block Distribution -------------
Total Block Count: 5
40.000%  2  Grass Block
20.000%  1  Redstone Torch
20.000%  1  Air
20.000%  1  Redstone Torch
```

### Expected Behavior

Just like stairs and other blocks with multiple states, red stone torches get counted together.

### Reproduction Steps

1. Place two torches in different states ( ex. one on the side of a block and one on top )
2. Select the area containing the torches
3. Do `//distr`

**Comment by octylFractal** [comment]
Not a bug, they are two different block types.
