### ISSUE TITLE
Redstone on upside-down pistons doesn't consistently copy

### ISSUE THREAD

**Issue by athompson673** [EngineHub/WorldEdit#2128]
### WorldEdit Version

7.2.11-beta-01+6200-0877589

### Platform Version

fabric-loader-0.14.8-1.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Redstone placed on the back face of an upside-down piston is incorrectly placed. I assume what's going on is that either the piston is placed first, then the redstone is successfully placed, or the redstone is placed first and then pops into an item when the piston is placed.
![ezgif com-optimize](https://user-images.githubusercontent.com/25141140/175792646-f0907fef-6931-4fdb-811c-b8bac9f50c9c.gif)
The issue occurs with `//stack`, `//move`, and `//paste` (likely others that place blocks based on a template as well...)

### Expected Behavior

Place the piston and the redstone without it breaking

### Reproduction Steps

1. place down facing piston
2. place redstone dust on top
3. select region using wand or pos commands
4. duplicate selection using `//stack`

### Anything Else?

I discovered this issue on MC version 1.18.2 Fabric version 0.14.8 WorldEdit verison 7.2.10+1742f98 and created an instance of 1.19 to also test using the most recent beta.

**Comment by me4502** [comment]
This is likely just a case of block updates. Try disabling update and neighbours with `//perf`.
