### ISSUE TITLE
Set entire column with biome brush

### ISSUE THREAD

**Issue by ItzRonaldMLG** [EngineHub/WorldEdit#2132]
### The Problem

I have searched hours but i dont think this is a feature:
I tried to change the biome, but its in 3D, meaning it wont change from top to bottom of the world.
Is there a way to use a brush to both yaxis aswell up and down simultaneously? like ''-100:100''?

### A Solution

something like dividing with ":"

**Comment by octylFractal** [comment]
I'm not really sure what you're asking for, since AFAIK there isn't a biome brush, so there isn't anything to apply this to?

**Comment by octylFractal** [comment]
Apparently I forgot about our biome brush. I don't think we need anything but a `-c` flag to set the whole column with the brush though, unless there is a compelling use-case for only specific y-offsets.

**Comment by ItzRonaldMLG** [comment]
Atm im using ''/brush cylinder $deep_ocean 5 100'', but the 100 will only apply from block to 100 blocks above it, and -100 will of course only do the block and 100 below.
So if you stand in the water you are in biome ''deep ocean'' but if you fly or just even jump around, it will still be the previous biome.

If this explains it better. 
Or maybe use ''vert'' or ''expand-vert'' to apply it from bottom to top?

**Comment by octylFractal** [comment]
That syntax doesn't exist? Are you using a fork despite checking the box saying you aren't?

**Comment by ItzRonaldMLG** [comment]
> That syntax doesn't exist? Are you using a fork despite checking the box saying you aren't?

I cant use it in the command ''/brush cylinder $birch_forest 30 vert'' or expand-vert does not work no

**Comment by octylFractal** [comment]
No, it is not. Please don't describe syntax from other plugins. Leaving this open for the feature of adding columns to the biome brush, but in the future do not create issues when not using WorldEdit.

**Comment by me4502** [comment]
This was closed in https://github.com/EngineHub/WorldEdit/commit/856aaa62670b4cd2f2cc2fbb721bee16e4a49098
