### ISSUE TITLE
Schematic cannot be inserted

### ISSUE THREAD

**Issue by Ziron06** [EngineHub/WorldEdit#2137]
### WorldEdit Version

7.2.10

### Platform Version

Spigot 1.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If I want to load a schematic from the Schematic folder and then insert it into the world of the server, the chat displays this message: 
"Java.lang.NoCllassDetFoundError: Could not initalize class
com.sk89q.worldedit.extent.reorder.MultiStageReorder"
and the message to report this error.
(Please report this error: [See console])

### Expected Behavior

I expected the schematic to be inserted normally.

### Reproduction Steps

1. I copied the schematic in my single player world (//copy) and saved it under a name in the Schematic folder (//schematic save Wolkenstadt2)
2. I copied the schematic file to the Schematic Folder of the Server Plug-in
3. I loaded the Schematic on the server (//schematic load Wolkenstadt2)
4. I wanted to insert the schematic (//paste)

At step 4 the above error occurred

**Comment by JOO200** [comment]
Outdated Worldedit, update your WorldEdit to the beta
