### ISSUE TITLE
worldedit-mod-7.2.11-beta-01 not working on latest version on forge , how do i fix it?

### ISSUE THREAD

**Issue by BabushkaGirl** [EngineHub/WorldEdit#2139]
### WorldEdit Version

worldedit-mod-7.2.11-beta-01

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Every time i try to launch the game with the latest verion of MC+Forge+WorldEdit i get this message and i got no idea how to fix it anymore..

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchFieldError: ENTITIES
Terminationcode: -1

### Expected Behavior

was hoping that the game + WE+FORGE etc would start

### Reproduction Steps

1. ...
2. ...

**Comment by octylFractal** [comment]
Wait, forge made changes we need to update to. No ETA.

Downgrade Forge for now to avoid this.

**Comment by BabushkaGirl** [comment]
> Wait, forge made changes we need to update to. No ETA.
> 
> Downgrade Forge for now to avoid this.

ok to what version of forge?

**Comment by octylFractal** [comment]
41.0.93 or earlier should work.

**Comment by BabushkaGirl** [comment]
ok , thanks , i'll try that one

**Comment by BabushkaGirl** [comment]
Works like a charm , thanks @octylFractal

**Comment by octylFractal** [comment]
Resolved by #2140.
