### ISSUE TITLE
Not supported version? 

### ISSUE THREAD

**Issue by Wypman1** [EngineHub/WorldEdit#2146]
### WorldEdit Version

Bukkit-Official(7.2.10+1742f98

### Platform Version

paper 1.19 and spigot 1.19 (tried both) 

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i try download versions of worldedit for 1.19 (the minehut server version) it says its not supported, even though i made sure to download/use the version for 1.19 so it should work and it is just being annoying at this point 

### Expected Behavior

worldedit working with me reinstalling various 1.19 supported versions of it

### Reproduction Steps

1. get a minehut server
2. add worldedit on the addons page of the website
3. download newer version of worldedit, and replace the older minehut plugin files with new ones to make sure the plugin is up to date

### Anything Else?

minehut says the issue is outside of their expertise, which i find a poor excuse as it is literally their job to help people with server issues, so thats why i went here to report it as bug and hopefully get some help

**Comment by me4502** [comment]
The version you've listed doesn't support 1.19, you need a later one.

This sounds like a MineHut issue, as they're providing the wrong version to you.

**Comment by Wypman1** [comment]
I tried downloading and adding the newer supported version to the plugins
folder in the world folder too, which had worked when i updated from 1.17
to 1.18 so i dont get why it doesnt work anymore?

Op zo 17 jul. 2022 09:47 schreef Maddy Miller ***@***.***>:

**Comment by me4502** [comment]
What I said before hasn't changed. Use a version that supports your MC version. If your host prevents that, it's an issue with your host.

From the information you've provided, you're not using a version that supports your MC version
