### ISSUE TITLE
minecraft crashes when i open a world

### ISSUE THREAD

**Issue by ben5446** [EngineHub/WorldEdit#2147]
### WorldEdit Version

1.19

### Platform Version

Forge 1.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

whenever i open a minecraft world it kicks me with error code

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchFieldError: ENTITIES
Exit Code: -1

i can send more stuff

### Expected Behavior

i expected to be able to join a world

### Reproduction Steps

1. ... open minecraft forge 1.19 with world edit 1.19
2. ... join a world when it hits 100% minecraft crashes

**Comment by octylFractal** [comment]
Use a dev build.

**Comment by ben5446** [comment]
??? whats that

**Comment by ben5446** [comment]
> Use a dev build.

??????????? what is that and how do i use it???????????

**Comment by octylFractal** [comment]
https://builds.enginehub.org/job/worldedit?branch=version/7.2.x, take the Forge one, works just like what you would download from CurseForge.
