### ISSUE TITLE
https://builds.enginehub.org/job/worldedit?branch=version/7.2.x, take the Forge one, works just like what you would download from CurseForge.

### ISSUE THREAD

**Issue by ben5446** [EngineHub/WorldEdit#2148]
https://builds.enginehub.org/job/worldedit?branch=version/7.2.x, take the Forge one, works just like what you would download from CurseForge.

_Originally posted by @octylFractal in https://github.com/EngineHub/WorldEdit/issues/2147#issuecomment-1190596119_

it says to install put in mods folder but its in the mod folder?????????

**Comment by wizjany** [comment]
stop spamming our issue tracker thanks. if you have questions use discord.
