### ISSUE TITLE
World Edit crashes game with exit code -1

### ISSUE THREAD

**Issue by august54742** [EngineHub/WorldEdit#2149]
### WorldEdit Version

7.2.11-beta-01

### Platform Version

Forge 1.19 41.0.105

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[crash-2022-07-21_16.47.31-server.txt](https://github.com/EngineHub/WorldEdit/files/9156897/crash-2022-07-21_16.47.31-server.txt)
The game crashes after loading or creating a world and exits with error java.lang.NoSuchFieldError: ENTITIES. 

### Expected Behavior

The world to load and work without any errors.

### Reproduction Steps

1. Put the mod in the mods folder
2. Attempt to load or create a new world
3. You get the error

**Comment by octylFractal** [comment]
See pinned issues.

**Comment by me4502** [comment]
This is already fixed, Forge made a change that broke mods that were made before that version came out. Update to a newer build of WorldEdit if you want to use that Forge version, noting that it will break on earlier Forge versions.
