### ISSUE TITLE
Command block 2x "/" (1.18.1)

### ISSUE THREAD

**Issue by RybkaPlumPlum** [EngineHub/WorldEdit#2150]
### WorldEdit Version

worldedit-mod-7.2.9.jar

### Platform Version

Fabric 0.14.8

### Confirmations

- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when i write for example this command /execute if block -161 92 -302 minecraft:acacia_button[powered=true] run / **(Here i cant write normal comands like gamemode or difficulty i can write only world edit commands)**

**Comment by wizjany** [comment]
yes? worldedit is probably one of the only things in existence that uses an extra slash in its commands. just drop the extra slash?
