### ISSUE TITLE
b flag working incorrectly on //move

### ISSUE THREAD

**Issue by mattbatwings** [EngineHub/WorldEdit#2154]
### WorldEdit Version

7.2.11

### Platform Version

Fabric 0.14.8

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Executing //move 1 -s b
whilst looking UP or DOWN causes the backwards flag to act as a forwards flag

### Expected Behavior

The selection should move backwards, due to the backwards flag.

### Reproduction Steps

1. Select anything
2. Look up or down
3. Execute //move 1 -s b

**Comment by me4502** [comment]
Added in https://github.com/EngineHub/WorldEdit/commit/54ed9e89d91255def21a53bb2d58c6e219bd6c1b
