### ISSUE TITLE
World edit 1.19 make my minecraft crash

### ISSUE THREAD

**Issue by AkinaTK** [EngineHub/WorldEdit#2156]
### WorldEdit Version

1.19

### Platform Version

Forge 1.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hi!

my minecraft keeps crashing when I add worledit in the mods folder but when it is not in the folder everything is fine! so i don't really understand... when did the bug come from? I deleted the forge 1.19 and the mods, downloaded the forge again, and put the mod in the folder, I did this 3 times and nothing changed. It is because it's a beta version of world edit?

When minecraft crashed, the bug report tells me that it was because of worldedit by the way,

thanks in advance for the help! 

### Expected Behavior

.

### Reproduction Steps

1. ...
2. ...
.

**Comment by me4502** [comment]
Forge made a change that breaks mods built for versions earlier than the one you're on. If you want to use a newer Forge version, you must use a newer version of WorldEdit (dev build). That will break WorldEdit on older Forge versions though
