### ISSUE TITLE
Issues with pasting schematics/replacing blocks

### ISSUE THREAD

**Issue by ThatZayinguy** [EngineHub/WorldEdit#2157]
### WorldEdit Version

worldedit-bukkit-7.2.11

### Platform Version

Paper

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I went to paste a schematic into my world and recived the fallowing error:

An unexpected error while handling a WorldEdit command
25.07 22:07:39 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.extent.reorder.MultiStageReorder
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.EditSession.<init>(EditSession.java:269) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1048) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:249) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at java.util.Optional.map(Optional.java:260) ~[?:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:248) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
25.07 22:07:39 [Server] INFO at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:647) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_replace(RegionCommandsRegistration.java:450) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.10.jar:?]
25.07 22:07:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
25.07 22:07:39 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
25.07 22:07:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2153) ~[?:?]
25.07 22:07:39 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
25.07 22:07:39 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
25.07 22:07:39 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
25.07 22:07:39 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
25.07 22:07:39 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
25.07 22:07:39 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behavior

I expected to have the schematic replaced but was greeted with an in-game message stating: 

java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.extent.reorder.MultiStageReorder

### Reproduction Steps

1. ...
2. ...

### Anything Else?

It's a fresh 1.19 survival server supported by Apex Hosting.

**Comment by JOO200** [comment]
You're using WorldEdit 7.2.10, you need worldedit 7.2.11-beta1
