### ISSUE TITLE
When replacing Blocks especially stairs they always face north and not the direction originally.

### ISSUE THREAD

**Issue by rebelAlliance09** [EngineHub/WorldEdit#2162]
### WorldEdit Version

Fabric 7.2.11-beta

### Platform Version

Fabric 0.14.8

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using //replace or //replacenear for stairs and some other blocks they always are facing north even if the original it is replacing is not facing north.
![weird](https://user-images.githubusercontent.com/45608861/182231216-76e90527-e60e-404b-86ea-0528c4ca9afb.png)
 

### Expected Behavior

Blocks to be placed in the original direction

### Reproduction Steps

1. //replacenear 10 oak_stairs spruce_stairs
2. wait

**Comment by PierreSchwang** [comment]
Utilize the [State Applying Pattern](https://worldedit.enginehub.org/en/latest/usage/general/patterns/#type-or-state-applying-pattern)
