### ISSUE TITLE
Unsupported version 7.2.11 on 1.18.1

### ISSUE THREAD

**Issue by aashaz** [EngineHub/WorldEdit#2163]
### WorldEdit Version

7.2.11

### Platform Version

Spigot 1.18.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

World edit will not work and keeps saying its an unsupported version

### Expected Behavior

world edit to work normally

### Reproduction Steps

1. Add 1.18.1 world edit
2. doesnt work

### Anything Else?

no

**Comment by me4502** [comment]
This is correct, we do not support non-latest patch versions.
