### ISSUE TITLE
no-op-permissions: true The TabComplete doesn't work

### ISSUE THREAD

**Issue by orjacob555** [EngineHub/WorldEdit#2166]
### WorldEdit Version

7.2.12

### Platform Version

paper 1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when no-op-permissions is true players dont have the tabcoplete like //set and then the materials. But when the player is op, the tabcomplete is working.

### Expected Behavior

i had been expected that the tabcomplete will work when the players have all the perms.

### Reproduction Steps

1. no-op-permissions: true
2. give worldedit.*
3. you need to be deop from the first time
4. try //set..

**Comment by me4502** [comment]
I cannot reproduce this issue. It's likely something else on your server
![image](https://user-images.githubusercontent.com/546754/183630620-ac0c960c-c024-4224-b2a0-a6241aded8bd.png)

**Comment by orjacob555** [comment]
its not working to me.
send the config?

**Comment by me4502** [comment]
It's a new config with _only_ the changes you listed in your reproduction steps applied to it.

Try this on a server with only WorldEdit and a permissions plugin (LuckPerms). Otherwise, this seems like not a WE issue.
Also without client mods. Some mods such as Lunar are known to just break tab completion in general, not specific to any plugins

**Comment by orjacob555** [comment]
wait.. try to remove all the players cache and be from the first time without op

**Comment by orjacob555** [comment]
because when i give to me op and then deop it suddenly worked but if i delete the player cache and log in in the first time to the server with the perms it doesnt work

**Comment by me4502** [comment]
It still works for me fine no matter what I do. This very much sounds like an issue with something else on your server.

If you can provide a reproduction of this with only WorldEdit and LuckPerms installed, and no client mods in use, you can re-open this issue.
