### ISSUE TITLE
Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [EngineHub/WorldEdit#2177]
### The Problem

I found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response.

### A Solution

Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time.

### Anything Else?

Worldedit Version: 7.2.12 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

Log: https://logs.apexminecrafthosting.com/pyVNK28

**Comment by wizjany** [comment]
this isn't even worldedit and you don't seem to have any understanding of what's actually going on
