### ISSUE TITLE
Wand /regen

### ISSUE THREAD

**Issue by KobraDad** [EngineHub/WorldEdit#2178]
### WorldEdit Version

WorldEdit version 7.2.12

### Platform Version

Paper version git-Paper-111 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 02831e3)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I use the wand to regenerate a region, especially larger regions, it slows down my server and throws a long list of errors in my server console.  It has kicked me a couple times after freezing the server.  I have already talked to an apex server tech and they looked at everything and said it is a world edit bug and to reach out to y'all.

### Expected Behavior

clean, quick regenerations of a region without throwing several errors or kicking me.

### Reproduction Steps

1. ...Select two points of a large area using the wand
2. ...run command /regen
[latest (8).log](https://github.com/EngineHub/WorldEdit/files/9397830/latest.8.log)

**Comment by octylFractal** [comment]
This is expected behavior. WorldEdit does not work asynchronously, and currently blocks the server thread while processing. Since this isn't crashing your server, there's not much to change. Asynchronous work is already planned as a separate ticket, but is hard to get right so will likely not be implemented any time soon.
