### ISSUE TITLE
Entity Passenger Lost On Move

### ISSUE THREAD

**Issue by RitzKid76** [EngineHub/WorldEdit#2179]
### WorldEdit Version

7.2.13-SNAPSHOT+6244-55e2d3d

### Platform Version

3574-Spigot-450dcaa-cdef8fc

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

placing a passenger inside a minecart and then moving that minecart using the -e flag, causes the passenger to be kicked out of the minecart
(essentially passenger data is lost)

### Expected Behavior

an entity in a minecart should remain in the minecart when moving it with WorldEdit

### Reproduction Steps

1. Place entity in minecart
2. select area around minecart
3. run the command: /move 1 -e
4. examine the bug o-o

**Comment by wizjany** [comment]
on the contrary, i'm finding that i get two entities, one properly as a passenger and one separate. seems to be because getEntities is returning the passengers separately, even though they are copied as a single entity. that seems to be an entirely different issue than what you're seeing though.

**Comment by tjbaker2003** [comment]
thanks stale bot... was hoping that you'd do that

**Comment by RitzKid76** [comment]
thanks stale bot...

**Comment by wizjany** [comment]
you had 6 weeks to say anything beside making sarcastic comments at the bot. as it stands you haven't said anything useful and as I already said I wasn't able to reproduce the bug you reported (i.e. losing data for passengers)

**Comment by RitzKid76** [comment]
if you are unable to recreate a bug report, what else is there for me to say other than: try again?

**Comment by me4502** [comment]
If it can't be reproduced, it means either your instructions were wrong, or it requires something specific about your setup to work.

So either way we need more information

**Comment by RitzKid76** [comment]
I placed an entity in a minecart and found this works with any entity, even boats
selected the region around the cart
ran the command I wrote on the report
and the bug works each time 

also seems to have the same effect with cut/copy then paste
would images help?
