### ISSUE TITLE
Unable to join discord channel https://discord.gg/enginehub

### ISSUE THREAD

**Issue by karlheidar** [EngineHub/WorldEdit#2183]
### WorldEdit Version

n/a

### Platform Version

n/a

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Trying to join the discord channel.
Error message: Unable do accept invite.

### Expected Behavior

Trying to join the discord channel.
Error message: Unable do accept invite.

### Reproduction Steps

1.https://discord.gg/enginehub
2. Error: Unable do accept invite.

**Comment by karlheidar** [comment]
User: Mc_VaDeR#0042

**Comment by octylFractal** [comment]
You were (rightfully) banned. This isn't the place to make a ban appeal, nor would I accept one after review.
