### ISSUE TITLE
//sel extend forgets it was set after arbitrary time

### ISSUE THREAD

**Issue by e-motiv** [EngineHub/WorldEdit#2188]
### WorldEdit Version

7.2.12

### Platform Version
Forge-1.19.2-43.1.25

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

1. I type 
    /tool farwand
    //sel extend
2. Perfect! Selections extend after right clicking
3. After a while, without dc'ing, right clicking doesn't extend anymore, but becomes a normal cuboid selection.

I tried to link this with other commands, but seems arbitrary for now.
This happens like 100 times per hour. Really frustrating, though I do appreciate your work, developers. Just saying.

**Comment by me4502** [comment]
If you’ve disconnected from the server for >5 minutes this will happen. That’s so that worldedit isn’t storing data for potentially limitless players in memory over time

**Comment by wizjany** [comment]
or if this is single player, immediately after leaving the world. either way this likely isn't happening randomly. you can always set your default selector if you want it to persist after the session being dropped. all documented behavior.

**Comment by e-motiv** [comment]
Thanks for the comments both of you, but...

> @me4502: If you’ve disconnected from the server for >5 minutes this will happen. That’s so that worldedit isn’t storing data for potentially limitless players in memory over time

It happens without disconnecting or being AFK. Sometimes even after only 2 minutes actively editing the world.


> @wizjany: or if this is single player, immediately after leaving the world. 

It happens on single player indeed but also on multiplayer (though as an admin and only player online) WITHOUT leaving the world or disconnecting or being afk.


> @wizjany: either way this likely isn't happening randomly. 

Being a developer myself,  I understand this is probably not random, but so far it feels like it and I couldn't figure out when exactly this happens. One does a lot of things when editing the world, but I haven't notice any reproducibility yet.


> @wizjany: you can always set your default selector if you want it to persist after the session being dropped. all documented behavior.

I will try this as a workaround for now.  Which reminds me; I always use a farwand. Maybe that helps to pinpoint it, if this is a matter that concerns you.. I will edit it in my original report here above. Like so:

    /tool farwand
    //sel extend

**Comment by e-motiv** [comment]
Forgive me, but I don't find how to set your default selector.  I've searched to the docs for a half hour, but only find this:

- **[Sessions>Persistent Data](https://worldedit.enginehub.org/en/latest/usage/general/sessions/?highlight=default#persistent-data)**: "Your default selector" but how to set your default selector?
- **[Configuration](https://worldedit.enginehub.org/en/latest/config/?highlight=default)**: A lot of defaults, including default selector item (axe), but nowhere says default selector (being extend for me);

**Comment by octylFractal** [comment]
https://worldedit.enginehub.org/en/latest/commands/?highlight=default%20selector#selection-commands -- `//sel` takes `-d`. Not very well called out though.

**Comment by e-motiv** [comment]
> https://worldedit.enginehub.org/en/latest/commands/?highlight=default%20selector#selection-commands -- `//sel` takes `-d`. Not very well called out though.

O thank you very much. 
Weird that that isn't found by a search of the word "default" in the doc's search engine.
https://worldedit.enginehub.org/en/latest/search/?q=default&check_keywords=yes&area=default

**Comment by octylFractal** [comment]
It is, at the bottom.

**Comment by e-motiv** [comment]
O sh*, you're right, how did I mis this.... Forgive me.... Shame on me...

**Comment by e-motiv** [comment]
Maybe repeat it on the selection page itself? It's not mentioned there.
https://worldedit.enginehub.org/en/latest/usage/regions/selections/#selection-modes

**Comment by e-motiv** [comment]
Shall we delete our last comments to clean the clutter here?

**Comment by octylFractal** [comment]
> It happens without disconnecting or being AFK. Sometimes even after only 2 minutes actively editing the world.

This just... can't happen, unless your system timer is incredibly inaccurate. https://github.com/EngineHub/WorldEdit/blob/version/7.2.x/worldedit-core/src/main/java/com/sk89q/worldedit/session/SessionManager.java#L341-L347 is quite simple; it will only remove after _10 minutes_ has passed. Having your session removed earlier seems incredibly unlikely. Nothing ever calls `SessionManager#remove`, and `SessionManager#clear` is only called when WorldEdit shuts down. You should provide the content of your `logs/latest.log`  after you experience the issue, though I really don't see how this could be possible.

> Shall we delete our last comments to clean the clutter here?

I don't think that's necessary.

**Comment by e-motiv** [comment]
I must have magical powers to induce impossible things. ;-) ;-) ;-)

I'll provide that log next time it happens..

**Comment by octylFractal** [comment]
Are you on an ARM CPU? I suspect there may be a data-race issue that previously went unnoticed on x86 CPUs.

**Comment by TomyLobo** [comment]
@e-motiv are you using //paste -s or //paste -n?

`//chunk` has this code to account for the extending selector:
https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java#L321-L326

`//paste -s/n` does not:
https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java#L194

I created a PR to fix this:
https://github.com/EngineHub/WorldEdit/pull/2289

**Comment by e-motiv** [comment]
> @e-motiv are you using `//paste -s` or `//paste -n`?

All the time! Thanks for the effort.

**Comment by me4502** [comment]
Based on the above discussion this might be fixed in the latest dev build. If you could please verify we can close this issue.

**Comment by me4502** [comment]
https://builds.enginehub.org/job/worldedit

**Comment by e-motiv** [comment]
OK. Checked & seems fixed. Thank you.
(Only tested bukkit version, but it's probably common code.)
