### ISSUE TITLE
Cannot use commands

### ISSUE THREAD

**Issue by lostopkk** [EngineHub/WorldEdit#2190]
### WorldEdit Version

7.2.12

### Platform Version

Fabric 0.14.9

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Cannot use the commands of worldedit

### Expected Behavior

use commands normally

### Reproduction Steps

nothing happens

**Comment by lostopkk** [comment]
Cannot invoke "com.mojang.brigadier.CommandDispatcher.execute(String.Object)" because "net.fabricmc.fabric.impl.command.client.ClientCommandInternals.activeDispatcher" is null

**Comment by octylFractal** [comment]
Please provide your full logs/latest.log.

**Comment by lostopkk** [comment]
https://mclo.gs/jmALUAK

**Comment by octylFractal** [comment]
Try updating Fabric API, if that doesn't fix it I assume it has to be some mod conflict with Fabric API because none of that is WorldEdit related. It's not even using the version of the command api we bundle.

**Comment by lostopkk** [comment]
ok

**Comment by lostopkk** [comment]
not solved, same problem @octylFractal 
https://mclo.gs/1nSRXLO

**Comment by octylFractal** [comment]
Well, it really doesn't seem WorldEdit related. Does it persist if you remove WorldEdit?

**Comment by lostopkk** [comment]
Now that I saw that I can't switch from survival either, I think it's a bug in my modpack as a whole

**Comment by lostopkk** [comment]
I managed to solve it I don't know how actually, but I did it, thanks even though I did this shit 😅
