### ISSUE TITLE
Game Crashes on Start

### ISSUE THREAD

**Issue by Plastisheep** [EngineHub/WorldEdit#2191]
### WorldEdit Version

7.2.11

### Platform Version

Fabric 0.14.9

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Every time I attempt to start the game with WorldEdit enabled, it crashes with error code 1. This is similar to this issue (https://github.com/EngineHub/WorldEdit/issues/2176) but it was resolved without the guy providing the reason that it happened. Ugh. Can someone please help? My crash report is here: https://pastebin.com/N2M5UPFa

### Expected Behavior

That the game would start...

### Reproduction Steps

1. Use Fabric 1.19 with WorldEdit
2. Crash

**Comment by wizjany** [comment]
old patch versions are not supported

**Comment by Plastisheep** [comment]
What do you mean? I'm using the exact same stuff that I said. What do you mean by not the samee version?

**Comment by octylFractal** [comment]
>		worldedit: WorldEdit 7.2.10+1742f98

**Comment by Plastisheep** [comment]
> > ```
> >   worldedit: WorldEdit 7.2.10+1742f98
> > ```

But that's not the- what the heck. I'm not using that version tho....

**Comment by Plastisheep** [comment]
Specifically I'm using 7.2.11+c43a877

**Comment by octylFractal** [comment]
Well, perhaps you should figure out why your logs disagree. Regardless, you are not "using the most recent Minecraft release" (1.19.2), so this is not an issue we provide support with.
