### ISSUE TITLE
Replacing stairs/slabs does not keep orientation

### ISSUE THREAD

**Issue by EldritchGarden** [EngineHub/WorldEdit#2205]
### WorldEdit Version

Bukkit-Official(7.2.12+6240-87f4ae1)

### Platform Version

git-Purpur-1832 (MC: 1.19.2)*

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

`//replace` command on stairs or slabs does not keep rotation of blocks. Slabs are always bottom slabs, and stairs are always upright and facing one direction (north?) regardless of the orientation of the existing block.

example commands tried:
`//replace smooth_quartz_slab polished_deepslate_slab`
`//replace smooth_quartz_stairs polished_deepslate_stairs`

### Expected Behavior

Replacement blocks should keep the same orientation of the original block

### Reproduction Steps

1. Place stairs/slabs in multiple orientations
2. Replace slabs/stairs with other slabs/stairs

**Comment by octylFractal** [comment]
Consider reading the like 10 other closed issues about this, or the docs.
