### ISSUE TITLE
Game crashes when used with other mods (Scroll fo WorldEdit and WorldEdit CUI)

### ISSUE THREAD

**Issue by RomanPro100** [EngineHub/WorldEdit#2206]
### WorldEdit Version

7.2.12

### Platform Version

Fabric 0.14.9

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I do specific things while using [Scroll for WorldEdit](https://modrinth.com/mod/scroll-for-worldedit) or [WorldEdit CUI](https://www.curseforge.com/minecraft/mc-mods/worldeditcui-fabric), the game crashes.

Trying to clear selection using corresponding WorldEdit CUI's key:
[crash-2022-10-28_11.59.54-client.txt](https://github.com/EngineHub/WorldEdit/files/9886866/crash-2022-10-28_11.59.54-client.txt)

Trying to use mouse wheel to move selection using Scroll for WorldEdit:
[crash-2022-10-28_12.10.06-client.txt](https://github.com/EngineHub/WorldEdit/files/9886942/crash-2022-10-28_12.10.06-client.txt)

### Expected Behavior

The game does not crash and mods do what they're supposed to do.

### Reproduction Steps

With WorldEdit CUI:
1. Set "Clear WorldEdit selection" key to any unoccupied key.
2. Select a region and press that key.

With Scroll for WorldEdit:
1. Select a region.
1. Press the "Use selected mode" key (Left Alt by default). "//move" text appears above the crosshair.
2. Scroll mouse forward or back.

**Comment by zml2008** [comment]
Neither of these are worldedit issues - you're just using versions ov those two mods that are incompatible with your minecraft version. Look to see if updates are available.
