### ISSUE TITLE
Add documentation for `/toggleeditwand` command.

### ISSUE THREAD

**Issue by ejm554** [EngineHub/WorldEdit#2207]
### The Problem

I cannot find the `/toggleeditwand` command in the [WorldEdit documentation](https://worldedit.enginehub.org/en/latest/).

![image](https://user-images.githubusercontent.com/26723535/198831956-5a72bcfb-b2bf-4f9a-8ebd-6d4bbfa99d7d.png)

### A Solution

Add documentation for this command.

**Comment by JOO200** [comment]
you just searched for `togglewand` and not `toggleeditwand`:
![grafik](https://user-images.githubusercontent.com/15250323/198832180-0ded7101-5e4d-4678-af97-5aeb72c2429e.png)

**Comment by ejm554** [comment]
My bad! Sorry about that!
