### ISSUE TITLE
Use-Inventory might be bugged

### ISSUE THREAD

**Issue by BoldriniLorenzo** [EngineHub/WorldEdit#2209]
### WorldEdit Version

7.2.12

### Platform Version

[1.19.2] Fabric 0.14.10

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The use-inventory flag doesn't work as intended.
When enabled, with cheat-mode set to true it works but it does not use items from the inventory.
![Screenshot_1](https://user-images.githubusercontent.com/84092873/199128476-e2c81249-f7d5-4753-ac32-8e5c51009a7f.png)
![Screenshot_2](https://user-images.githubusercontent.com/84092873/199128477-d27f5ff8-a1ec-49f7-98f9-db9de3c98d64.png)
When I disable cheat-mode it doesn't let me use World Edit at all unless I enable cheats in my world, use-inventory doesn't work as intended anyway.

### Expected Behavior

Of course use-inventory is expected to use items from your inventory: if I do //set 1, It's expected that the stone from my inventory is going to be used.
This behavior works in Spigot but not in the Fabric version.

### Reproduction Steps

1. Set use-inventory to true
2. In Minecraft: set the positions with the wooden axe
3. In Minecraft: do //set [block]
4. Expect it to place blocks that are not in your inventory.

**Comment by wizjany** [comment]
has never been supported outside of bukkit and isn't even supported there anymore
