### ISSUE TITLE
//restore only restores from the overworld

### ISSUE THREAD

**Issue by ProClifo** [EngineHub/WorldEdit#2214]
### WorldEdit Version

7.2.12

### Platform Version

Fabric 0.14.10

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I use the //restore command in the Nether or the End, it only restores from regions in the overworld.

I'm using this Linux command, recommended in the Worldedit Snapshots Wiki page, to create the world backups:
zip -v backups/`date "+%Y-%m-%d-%H-%M-%S"`.zip -r world
Because this is Fabric, the Nether and End dimensions are stored in the main world folder, in /world/DIM-1/ and /world/DIM1/. So I expected to restore data from those folders while in those dimensions.

### Expected Behavior

I expected the //restore command to restore Nether regions when I'm in the Nether, and End regions when I'm in the End.

### Reproduction Steps

1. Set up a backups folder with a world backup
2. Go to the Nether/End
3. Select two positions and type //restore
4. See how it pastes in terrain from the overworld

**Comment by wizjany** [comment]
#1509
