### ISSUE TITLE
Pasting, Moving action deletes certain types of blocks (sea pickles, paintings, item frames, etc.) 

### ISSUE THREAD

**Issue by BertCreator** [EngineHub/WorldEdit#2215]
### WorldEdit Version

7.2.12

### Platform Version

Fabric 0.11.1 for MC 1.19.2 Java

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When performing //paste or //move certain types of blocks get deleted in the process, which makes copying large sections of a world or building a living nightmare. In the case of sea pickles it doesn't matter if submerged or not. Broken blocks can be seen floating where they were supposed to be.

Blocks I have noticed that get deleted: sea pickles, paintings, carpets

Entities: item frames both types and item inside, armor stands

The issue with entities persists even though I have added -e after the command (including the //copy or //cut command!).

### Expected Behavior

All blocks should be copied properly without anything getting deleted.

### Reproduction Steps

1. //copy -e
2. //paste -e or //move
3. see deleted blocks and/ or entities

### Anything Else?

To me it seems as if the system is copying the blocks in a wrong order. Sea pickles and paintings cannot float for example, so if there is no block supporting them they get removed. This is exactly what happens. Same for carpets.

I hope there is a solution for this. So far I could not find any fix myself and this issue has plagued me greatly. :(

**Comment by me4502** [comment]
This sounds like you just need to turn off updated in //perf
