### ISSUE TITLE
Path is not allowed outside root

### ISSUE THREAD

**Issue by Azrael213** [EngineHub/WorldEdit#2221]
### WorldEdit Version

R. WorldEdit 7.2.12 

### Platform Version

fabric 1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I try to save some schematics from my local save world, to bring it back to a new world, but if i want to save the schematic the following error comes up:

Path is outside allowable root

Select the structure
Enter //copy
Enter //schematic save name

It worked before the change of .minercraft folder, I think i should allow symlinks but i donk know how please help me with the steps 

### Expected Behavior

I expect it to work after allowing Symlinks

### Reproduction Steps

1. Allow Symlinks

**Comment by me4502** [comment]
Enable the allow symlinks option in the WorldEdit configuration, this isn't a bug it's a security feature.
