### ISSUE TITLE
No commands available

### ISSUE THREAD

**Issue by voxymoron** [EngineHub/WorldEdit#2222]
### WorldEdit Version

WorldEdit v7.2.12+6240-87f4ae1

### Platform Version

CraftBukkit version 3608-Spigot-6198b5a-b5aa0be (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WorldEdit ceased working recently after updating my server to the latest version. No commands are available in game. What's odd is that I can type /pl in the server and it lists WE as an available plugin, as if it's running but I just can't use it. Below is what the console has shown upon last start up of the server. [For some reason my server hasn't used the latest.log in months and I'm not really sure why it stopped logging there, so this is all I can provide for now.]

I tried a couple other versions of WE plugin just to see, 7.2.11 and 7.2.13-SNAPSHOT, but neither seemed to change the outcome.

Edit: removed wall of text and put it on pastebin woops https://pastebin.com/Ti5uhTXn

Edit 2: used /reload (I know booo) and this is the result which has more console info that could help! https://pastebin.com/Sw0x6FR1

### Expected Behavior

Expect the plugin to work and allow commands to be used.

### Reproduction Steps

1. Stop server
2. Copy the plugin.jar to my server's plugin folder
3. Start server

### Anything Else?

I know very little about these kinds of things so I'm sorry if the answer is obvious. Explain it to me like I'm 5.

**Comment by octylFractal** [comment]
The relevant info would be in latest.log, so you should figure out what is wrong with logging to that.
