### ISSUE TITLE
WorldEdit and Water

### ISSUE THREAD

**Issue by Donastria** [EngineHub/WorldEdit#2223]
### WorldEdit Version

both versions

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

So fo me it just plain isn't working. but even more concerning is that if for some reason I touch water the whole game goes to pot and I can't break anything or pickup things or fly or even save. I do play modded, but I have gotten the same results even when just wouldedit and fabric are installed. When I try to use worldedit I get a wall of red text and the game closes at best and freezes at worst. I assumed at first that it was another of my mods messing with it, but as I have stated I get similuar results even when it is the only one. And it only happems aftet I touch water, in any way... including rain.

### Expected Behavior

I expected the same greatness I have enjoyed from worldedit for years.

### Reproduction Steps

1. ... start world
2. throw something on the ground because you won't be able to afterwards
3. touch water... go jump in a lake, frolic in a stream, dance in the rain, whatever your jam
4. try to pickup said item without success and have your game go wanky
5. hard restart because there is no saving
6. ...

**Comment by wizjany** [comment]
nothing to do with us. worldedit doesn't touch anything in client code, anything in rendering, etc.

**Comment by Donastria** [comment]
but it is only when YOUR mod is added thus is to do with you

**Comment by Donastria** [comment]
how do I capture that???
because it is ingame

**Comment by Donastria** [comment]
@wizjany its fine if you don't want to admit that your mod is working like a piece of shit right now, but dont just tell me to do something and not tell me how to accomplish said thing! that is pretty shity of you. I would gladly give you logs if there were, but the wall of text is ingame and I don't know how to capture that.  So why don't you tell me, so I can proove you WRONG!
