### ISSUE TITLE
Worldedit 7.2.13 not loading for Paper 1.19.3

### ISSUE THREAD

**Issue by AdminZero** [EngineHub/WorldEdit#2226]
### WorldEdit Version

Worldedit 7.2.13 

### Platform Version

Paper 1.19.3

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

17.12 23:18:05 [Multicraft] Starting server!
17.12 23:18:05 [Multicraft] Loaded config for "Paper 1.19.3 Latest (Locked to 1.19.3 - Build #321)"
17.12 23:18:05 [Multicraft] Updating eula.txt file
17.12 23:18:06 [Server] INFO Starting org.bukkit.craftbukkit.Main
17.12 23:18:06 [Server] INFO *** Warning, you've not updated in a while! ***
17.12 23:18:06 [Server] INFO *** Please download a new build as per instructions from https://papermc.io/downloads ***
17.12 23:18:06 [Server] INFO System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.2+8-86) Host: Linux 4.9.185-xxxx-std-ipv6-64 (amd64)
17.12 23:18:06 [Server] INFO Loading libraries, please wait...
17.12 23:18:07 [Server] INFO 2022-12-17 23:18:07,168 ServerMain WARN Advanced terminal features are not available in this environment
17.12 23:18:10 [Server] INFO Building unoptimized datafixer
17.12 23:18:11 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
17.12 23:18:12 [Server] INFO Loaded 7 recipes
17.12 23:18:13 [Server] INFO Starting minecraft server version 1.19.3
17.12 23:18:13 [Server] INFO Loading properties
17.12 23:18:13 [Server] INFO This server is running Paper version git-Paper-321 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: d8cf30d)
17.12 23:18:13 [Server] INFO Server Ping Player Sample Count: 12
17.12 23:18:13 [Server] INFO Using 4 threads for Netty based IO
17.12 23:18:13 [Server] INFO Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
17.12 23:18:14 [Server] INFO Default game type: SURVIVAL
17.12 23:18:14 [Server] INFO Generating keypair
17.12 23:18:14 [Server] INFO Starting Minecraft server on 54.39.115.228:25635
17.12 23:18:14 [Server] INFO Using epoll channel type
17.12 23:18:14 [Server] INFO Paper: Using libdeflate (Linux x86_64) compression from Velocity.
17.12 23:18:14 [Server] INFO Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
17.12 23:18:14 [Server] ERROR Could not load 'plugins/worldedit-mod-7.2.13.jar' in folder 'plugins'
17.12 23:18:14 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
17.12 23:18:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:179) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
17.12 23:18:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:157) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
17.12 23:18:14 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:436) ~[paper-1.19.3.jar:git-Paper-321]
17.12 23:18:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-321]
17.12 23:18:14 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-321]
17.12 23:18:14 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-321]
17.12 23:18:14 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
17.12 23:18:14 [Server] INFO Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
17.12 23:18:14 [Server] INFO ... 7 more
17.12 23:18:14 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
17.12 23:18:14 [Server] INFO Preparing level "world"

### Expected Behavior

Expect worldedit to load and work on Paper 1.19.3.

### Reproduction Steps

1. Select Paper server 1.19.3
2. Upload Worldedit 7.2.13
3. Start Server

**Comment by octylFractal** [comment]
Use the bukkit plugin, not the mod.

**Comment by AdminZero** [comment]
I'm so stupid... didn't even realize... ha. Thanks!
