### ISSUE TITLE
Incompatible with Chisel&Bits Mod

### ISSUE THREAD

**Issue by mnetwork** [EngineHub/WorldEdit#2227]
### WorldEdit Version

7.2.12 (Forge/Fabric for MC 1.19.2)

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Crush when copy/paste chisel block

### Expected Behavior

-805306369 ERROR CODE

### Reproduction Steps

1. ... Create Chisel block
2. ... Copy with WorldEdit Wand, and then Paste next

**Comment by me4502** [comment]
You’re going to need to provide some error or other issue that this is actually causing, there’s nothing on this report that indicates what’s going wrong
