### ISSUE TITLE
//set wood type

### ISSUE THREAD

**Issue by ItzPokeblox** [EngineHub/WorldEdit#2228]
### The Problem

I know that its possible to replace a selection, brush, etc with just typing a color and it is replaced with wool.

### A Solution

I'm thinking its possible to mimic the same thing done with wool

//set red - replaces selection with red wool
//set oak - replaces selection with oak planks
//set spruce - replaces selection with spruce planks

This is just a small quality of life feature that would probably help with typing and not always wanting spruce buttons in my builds.

**Comment by wizjany** [comment]
legacy patterns like wool colors will be getting removed eventually since there's probably a dozen colored blocks now. absolutely no way we're going to add more ambiguity to patterns now.
