### ISSUE TITLE
WorldEdit Version Unknown

### ISSUE THREAD

**Issue by ItzPokeblox** [EngineHub/WorldEdit#2230]
### WorldEdit Version

unknown

### Platform Version

* Fabric-Official(7.2.11-beta-01+6200-0877589)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

whenever I type /we version (in this version of minecraft 1.19.2 fabric) it says worldedit version unknown

### Expected Behavior

WorldEdit Version (1.19.2) or something

### Reproduction Steps

/we version

**Comment by wizjany** [comment]
unsupported version
