### ISSUE TITLE
Lighting buggy when filling in the celing to a large room

### ISSUE THREAD

**Issue by ItzPokeblox** [EngineHub/WorldEdit#2231]
### WorldEdit Version

WorldEdit version (unknown) https://github.com/EngineHub/WorldEdit/

### Platform Version

* Fabric-Official(7.2.11-beta-01+6200-0877589)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have made a large room of a castle and as soon as I filled in the roof, there are random spots with sunlight and they are annoying to get rid of. I attached a picture below.
https://user-images.githubusercontent.com/121056325/208502905-ad030758-4662-4bb6-98f0-8d23fdf264b3.png

### Expected Behavior

I would fill in the roof and the room would be fully dark

### Reproduction Steps

1. Make a big room (probably //walls)
2. fill in the celing with //set (during day time)
3. random light spots appear probably

**Comment by wizjany** [comment]
WE just calls MC's lighting engine unless you explicitly turn that off. this isn't a bug in WE.
