### ISSUE TITLE
 Set a destination mask when pasting

### ISSUE THREAD

**Issue by mk-pmb** [EngineHub/WorldEdit#2233]
### The Problem

I want to paste my tunnel walls and replace `stone,granite,dirt,grass_block` but preserve ores and other unexpected blocks.

### A Solution

Like #957 (source mask), allow to specify a destination mask of which blocks are acceptable to replace.

### Anything Else?

Thanks for WE! It's very neat.

**Comment by me4502** [comment]
This is how masks work, nothing needs to be added here

**Comment by mk-pmb** [comment]
I just checked the manual before posting and I could only find an option for source mask, not destination mask.

**Comment by mk-pmb** [comment]
Oh, did you mean I have to set `//gmask` before each paste, and reset it after? That's a bit more cumbersome but yeah that works indeed.
