### ISSUE TITLE
worldedit wont allow worlds to load

### ISSUE THREAD

**Issue by King909YT** [EngineHub/WorldEdit#2243]
### WorldEdit Version

 WorldEdit 7.2.10 (Forge/Fabric for MC 1.18.2)

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

whenever worldedit is installed the world will be stuck at 100% but it wont finish loading.

### Expected Behavior

for the world to finish loading so that i can play

### Reproduction Steps

1. put wordedit in the mods folder 
2. try to open a presaved or a new world
3. watch the screen load for eternity

**Comment by me4502** [comment]
There is nowhere near enough information to go on here, given this works for everyone else. This means something else in your setup is the issue.

This is also an old version, you've lied when filling out the issue template.
