### ISSUE TITLE
Unable to Rotate

### ISSUE THREAD

**Issue by CKFA** [EngineHub/WorldEdit#2247]
### WorldEdit Version

7.2.12+6240-87f4ae1

### Platform Version

Fabric 0.14.10-1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

![image](https://user-images.githubusercontent.com/59402813/212523180-569939a6-1084-4583-92d6-77c0691d86eb.png)

As the figure shown, I am unable to do the //rotate 90 after I //copy the area

### Expected Behavior

It should be able to rotate all the object in clipboard, and enable me to paste in different directions.

### Reproduction Steps

1. //copy
2. //rotate 90

**Comment by me4502** [comment]
I cannot reproduce this issue. The error you're seeing also doesn't look like it's coming from WorldEdit, but instead something else overriding the command.

1.19.2 is also not a supported version anymore (hence why you had to lie on the issue template).
