### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Alex81585** [EngineHub/WorldEdit#2252]
### WorldEdit Version

1.19.2

### Platform Version

1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

.

### Expected Behavior

I have a server in pingperfect for minecraft. I have mods in my server, so I place WorldEdit in my mods. The worldedit work perfect in single player. iserver does nothing, I have Op in the game. I have contacted the operators of pingperfect they say that it should work as any other mod.

### Reproduction Steps

1. ...
2. ...
.

### Anything Else?

am attempting to restart the server, I want to get the structures we build to the new server.

**Comment by octylFractal** [comment]
Did you install it on the server?
