### ISSUE TITLE
Maps not working 

### ISSUE THREAD

**Issue by Shortzero9** [EngineHub/WorldEdit#2260]
### WorldEdit Version

1.19.2 and 1.19.3

### Platform Version

Fabric 1.19.2 and 1.19.3

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

In a world where I am actively using worldedit the maps are showing blank where there should be blocks and sometimes show the void (it’s a void world) through blocks. This is for bloacks both placed by hand and worldedit. This started from where I moved the building I was making from around 0 y level to about 70, before I moved it the map rendered just fine.

In a world where worldedit is loaded but not used parts of a map update but not others.

 The photos in creative are for scenario 1 and survival for scenario two
![6D41E462-47A1-4939-9229-7D5DC8776775](https://user-images.githubusercontent.com/125047602/218126751-019fde43-a9ae-40e2-bde2-7bdde3da0926.png)
![F8A3AC52-3B17-48CF-8F96-B1F2A0EE8766](https://user-images.githubusercontent.com/125047602/218126770-93688a79-cfc2-4833-bd3d-4818978cec2c.png)
![C579A04B-5DAF-47D1-8020-43C50316EF3D](https://user-images.githubusercontent.com/125047602/218126777-62c5a4bb-67ca-47d7-972f-38a8e4790cce.png)
![A6D61D93-3E06-452F-B631-4D1C4B2075AC](https://user-images.githubusercontent.com/125047602/218126766-0d468d9b-2c3b-4c35-bb44-ae56a13e7aa9.png)

### Expected Behavior

Maps update as normal

### Reproduction Steps

1.  Build something
2. Open map

**Comment by wizjany** [comment]
> In a world where worldedit is loaded but not used parts of a map update but not others.

worldedit doesn't (and can't) do anything if not used. this might be a concern with certain updates being suppressed if worldedit was in fact being used, but aside from that this sounds like not a worldedit issue.
