### ISSUE TITLE
Block replication

### ISSUE THREAD

**Issue by neila-a** [EngineHub/WorldEdit#2261]
### The Problem

Copy failed due to insufficient heap space during //copy.

### A Solution

Copy in blocks during //copy to prevent insufficient heap space.

**Comment by me4502** [comment]
This request doesn't make sense, what are you actually asking for here?

**Comment by neila-a** [comment]
Copy block by block like Litematica to reduce footprint.

**Comment by me4502** [comment]
That doesn't clarify anything
