### ISSUE TITLE
WorldEdit for 23w07a

### ISSUE THREAD

**Issue by Atten007** [EngineHub/WorldEdit#2266]
### The Problem

Hello,

I want to open a server with the new cherry blossom grove biome. I want to use a Fabric server for it because fabric is much faster than vanilla. But unfortunately, the only files I could find are for 1.19.3 and not for 23w07a.

### A Solution

A possible solution is, that WorldEdit could also be released for 23w07a and other snapshots (Fabric only).

### Alternatives

None

### Anything Else?

None

**Comment by octylFractal** [comment]
We do snapshots if and when we feel like it, you're welcome to do it yourself otherwise.
