### ISSUE TITLE
The server has stopped responding after //Regen

### ISSUE THREAD

**Issue by Revan7even** [EngineHub/WorldEdit#2270]
### WorldEdit Version

7.2.13

### Platform Version

CraftBukkit version 3661-Spigot-19641c7-8434e36 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Using //regen on a village crashed the server and required a restart. Same as #1313, #1484 and #1851 despite issue being marked as fixed and closed.

### Expected Behavior

I expected the server to keep running after executing the command.

### Reproduction Steps

1. `/tool farwand` on stick.
2. Left-click `First position set to -625/85/222 `
3. Right-click `Second position set to -425/63/39 (850632)` 
4. `//regen`
5. Wait 5 seconds
6. `Region regenerated`
7. Wait 60 seconds
8. `Connection timed out`
9. Restart server
10. Load into world
11. Server has reverted to state before regen command.

### Anything Else?

[crash-2023-02-22_21.33.00-server.txt](https://github.com/EngineHub/WorldEdit/files/10834265/crash-2023-02-22_21.33.00-server.txt)
[latest.log](https://github.com/EngineHub/WorldEdit/files/10834276/latest.log)

**Comment by wizjany** [comment]
you're on spigot.

**Comment by Revan7even** [comment]
Cloned the server and switched it to Paper and it works now, but I wouldn't have know if not for your [comment in parentheses](https://github.com/EngineHub/WorldEdit/issues/1313#issuecomment-618785660).

Paper should be more than "recommended" on the WorldEdit for Bukkit page for "[better permormance](https://madelinemiller.dev/blog/paper-vs-spigot/)" if it really means "required for certain features to not crash your world"
