### ISSUE TITLE
for some reason my world edit mod says it is on the wrong version but i am on 1.19.3 and dowloaded the 1.19.3 file from curse forge if anyone can help please  

### ISSUE THREAD

**Issue by KingGibles** [EngineHub/WorldEdit#2271]
### WorldEdit Version

1.19.3

### Platform Version

forge newest version

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

for some reason my world edit mod says it is on the wrong version but i am on 1.19.3 and dowloaded the 1.19.2 file from curse forge if anyone can help please  

### Expected Behavior

n/a

### Reproduction Steps

1. ...N/a
2. ...n/a

**Comment by wizjany** [comment]
a) 1.19.2 is not 1.19.3
b) newest version is not a version
