### ISSUE TITLE
Game crashing when selecting the second position with wand or command

### ISSUE THREAD

**Issue by skTanky** [EngineHub/WorldEdit#2274]
### WorldEdit Version

7.2.13

### Platform Version

* Bukkit-Official(7.2.13+46576cc)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Whenever I select the second position with the wand or the command //pos2, my game freezes then later crashes. I am not sure if it is to do with my end, the plugin end or the server end as there are no error messages in console

### Expected Behavior

I should normally select the point without crashing

### Reproduction Steps

1. Select the first position which is fine
2. Select the second position

### Anything Else?

-

**Comment by me4502** [comment]
You need to provide the platform version, and test this with just WorldEdit installed. It sounds like you have something else that's listening for completed regions that is causing crashing, entirely unrelated to WorldEdit.
