### ISSUE TITLE
WorldEdit does not work on Paper 1.19.4

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#2283]
### WorldEdit Version

WorldEdit version 7.2.14-SNAPSHOT+6358-38d2ff1

### Platform Version

This server is running Paper version git-Paper-459 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 5100822)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[11:46:39 WARN]: 
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

### Expected Behavior

WorldEdit is supposed to work.

### Reproduction Steps

Download Paper, WorldEdit and launch the server.

**Comment by wizjany** [comment]
it cannot be a valid bug report because the current WE release works fine with the current paper build. clearly something else is going on on your end which you should sort out and ask on discord if you need help, not make a bug report for.
