### ISSUE TITLE
Not a bug report, a question, but discord is spazzing out again so I couldn't go there.

### ISSUE THREAD

**Issue by susan3333333** [EngineHub/WorldEdit#2284]
### WorldEdit Version

any

### Platform Version

forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have a 1.16.5 World with the cave & cliffs backport.
there is still no way to update these worlds thru the mod. They were going to make it, and I asked about it, but haven't received a reply.
A friend said Worldedit might work, but maybe not, because the blocks are from a future version to the world, and they weren't sure that world edit could change blocks in a 1.16.5 world to the new ones.

So, is there a way for world edit to map the caves & cliffs blocks to the vanilla ones so I can update the world safely?

### Expected Behavior

Hopefully be able to keep an amazing world that cannot gen in the newer minecraft

### Reproduction Steps

1. Is there anywhere not discord for asking questions?
2. Because it does this alot, I don't use it anymore because of this.

**Comment by me4502** [comment]
Worldedit is not a world converter, and don’t use ableist slurs in issue titles
