### ISSUE TITLE
Use-inventory not working in 1.19.3 Fabric

### ISSUE THREAD

**Issue by LaoNebula** [EngineHub/WorldEdit#2285]
### WorldEdit Version

1.19.3

### Platform Version

fabric 1.19.3

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have enabled `use-inventory` within the config file of worldedit for fabric 1.19.3 but it still does not use my inventory, is there something else that I am required to do?

### Expected Behavior

use my inventory

### Reproduction Steps

1. edit` %appdata%/.minecraft/config/worldedit/worldedit.properties`
2. change `use-inventory=false` to `use-inventory=true`
3. run minecraft

**Comment by wizjany** [comment]
duplicate. unsupported option, esp on that platform.
