### ISSUE TITLE
WorldEdit CUI command not working

### ISSUE THREAD

**Issue by NonSwag** [EngineHub/WorldEdit#2295]
### WorldEdit Version

7.2.14

### Platform Version

Paper 1.19.4

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When running the "/worldedit cui" command, it happens nothing.
No response in form of a message or a console log no error, just nothing.
When looking at the session file, nothing changed. (the option 'useServerCUI' remains false)
CUI is also not working

### Expected Behavior

Something like a response or a change in config, and CUI should work

### Reproduction Steps

1. activate 'server-side-cui' in the worldedit config (if it isn't already)
2. just to be sure that cui was not manually activated, delete all session files
3. restart the server
4. connect to the server and run the command 'worldedit cui'

**Comment by wizjany** [comment]
you seem to be misunderstanding what the command is for. all it does is force a handshake with the CUI, which is totally unnecessary because the CUI already handshakes just fine on its own.
