### ISSUE TITLE
//sel command not clearing server side cui

### ISSUE THREAD

**Issue by NonSwag** [EngineHub/WorldEdit#2296]
### WorldEdit Version

7.2.14

### Platform Version

Paper 1.19.4

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using the //sel command to clear the own selection it does not remove the server side cui

### Expected Behavior

Should remove the CUI

### Reproduction Steps

1. activate 'server-side-cui' in the worldedit config (if not already)
2. set 'useServerCUI' in your session file to 'true'
3. restart the server
4. select a region
5. clear your region selection with the //sel command

**Comment by wizjany** [comment]
can't repro, clearing works just fine.
