### ISSUE TITLE
WE commands not working (java.lang.NoClassDefFoundError: net/minecraft/world/level/WorldGenLevel)

### ISSUE THREAD

**Issue by aloyen07** [EngineHub/WorldEdit#2298]
### WorldEdit Version

Sponge-Official(7.2.11+c43a877)

### Platform Version

SpongeForge: 1.16.5-36.2.5-8.1.0-RC1278

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WE send an error in console when server starts. His commands not working. 
Startup error -> https://gist.github.com/aloyen07/5059a746107b160a4855ea116e4d122d

### Expected Behavior

If I write something command, WE throws an exception in console. 
For example, i write a command //world help (from console) 
Error -> https://gist.github.com/aloyen07/b1b7660065d3f1402dba5de9eb9594d5

### Reproduction Steps

1. Install a Sponge server (API 8.1.0, 1.16.5)
2. Download a WE and install it in your plugins dir. 
3. Start a server. 
4. Write in console //world help. OR Join in the server and try to set homething.

**Comment by me4502** [comment]
Currently the way Sponge is setup, we can't be compatible with both SpongeForge & SpongeVanilla. As we already have a Forge version of the mod, we target SpongeVanilla. 

However, SpongeForge currently has a bug that prevents Forge mods from registering commands - so SpongeForge as a platform is currently broken on their end. There's not much we can really do about this.

**Comment by aloyen07** [comment]
Mod (worldedit-mod-7.2.5-dist.jar) is crashes a server with error `net.minecraftforge.fml.ModLoadingException: Mod §eworldedit§r only supports §3sponge§r §o1.13§r
§7Currently, §3sponge§r§7 is §o8.0.0`
I can send a crash report if you need.

**Comment by me4502** [comment]
You'll have to modify the `META-INF/mods.toml` file to remove the Sponge section; Sponge modified their version system after that version was released

**Comment by aloyen07** [comment]
And how to use WorldEdit without commands? 
I need full WE on my SpongeForge server

**Comment by me4502** [comment]
You’ll need to wait for sponge to fix commands

**Comment by wizjany** [comment]
duplicate issue
