### ISSUE TITLE
Unexpected error when running commands on Spong API 8

### ISSUE THREAD

**Issue by itsAyeC** [EngineHub/WorldEdit#2302]
### WorldEdit Version

7.2.11

### Platform Version

Sponge 8.1.0 

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When running any server commands, it gives me this error: java.lang.NoClassDefFoundError: net/minecraft/network/protocol/Packet 

Happens when running any command and is not a permissions issue.

### Expected Behavior

It should give me the world edit wand when running the //wand command,

### Reproduction Steps

1. Installed worledit 
2. gave permissions to use commands
3. get the error. 
4. 

### Anything Else?

seems to be a compatability problem with sponge api8 and worledit 7.2

**Comment by wizjany** [comment]
dupe

**Comment by itsAyeC** [comment]
is there a solution to this yet?

**Comment by me4502** [comment]
The issue is "the sponge plugin cannot support both sponge vanilla and sponge forge at the same time", the solution is for sponge to allow that. Until they do this is the situation it's in
