### ISSUE TITLE
Server crashes when pasting a schematic

### ISSUE THREAD

**Issue by Kiwicast** [EngineHub/WorldEdit#2303]
### WorldEdit Version

7.2.12

### Platform Version

Forge 43.2.4 (1.19.2)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I paste a schematic that is 584kb in size, the server crashes. The server is a dedicated server i7700k with 32gb ddr4 ram.
The schematic loads but will crash when pasting.

### Expected Behavior

You should be able to load the schematic and then paste it and the schematic appears

### Reproduction Steps

1. ... Loaded schematic in to worldedit schematics folder
2. ...restart server
3.  Load into server
4. Go to location
5. type //schem load (schem file)
6. Wait for it to load
7. type //paste
8. Pauses a while then server crashes

**Comment by octylFractal** [comment]
This sounds like you don't have enough RAM for the schematic. Use the Discord for support.
