### ISSUE TITLE
Add //revolve <amount> [start] [end] [heightDiff] Permissions: worldedit.revolve

### ISSUE THREAD

**Issue by Jettthomas2020** [EngineHub/WorldEdit#2309]
### The Problem

No problem

### A Solution

This would make world edit building so much easier.

**Comment by wizjany** [comment]
use search

**Comment by Jettthomas2020** [comment]
> use search

What am I supposed to do with search?

**Comment by wizjany** [comment]
find the issue you're duplicating.
