### ISSUE TITLE
Make commands consistent

### ISSUE THREAD

**Issue by Blayung** [EngineHub/WorldEdit#2311]
### The Problem

It hurts my brain when half of the worldedit commands start with a single slash and the other half starts with double slashes.

### A Solution

Make all worldedit commands use double slashes.

### Alternatives

Make all worldedit commands use a single slash.

I prefer the solution above over that one, because double slashes make worldedit commands more distinguishable from vanilla commands.

### Anything Else?

nah

**Comment by wizjany** [comment]
duplicate

**Comment by octylFractal** [comment]
#1374
