### ISSUE TITLE
When using convex selection, visualizer stays even after selecting something else  

### ISSUE THREAD

**Issue by itsmorethantech** [EngineHub/WorldEdit#2312]
![2021-09-17_17 56 48](https://user-images.githubusercontent.com/82797019/133746520-c667b1d8-0e96-41ef-80ad-7f156926c211.png)

Version: 1.17.1+01-SNAPSHOT
Minecraft version: 1.17.1 Fabric 0.11.6

Other mods:
AntiGhost
Baritone
Build Guide
Building Wands
Creative One-Punch
Damage Tilt
Dynamic FPS
EasierVillagerTrading
Giselbaers Durability
LambDynamicLights
Light Overlay
Litematica
Lithium
MaLiLib
MiniHUD
Mod Menu
Not Enough Crashes
Ok Zoomer
Sodium
Tweakaroo
While We Wait
WorldEdit (Obviously)

**Comment by zml2008** [comment]
This appears to be a WorldEdit issue -- WE does not fully reset the selection. By copying behavior from the 2dpoly region selector, we should be able to resolve this.

**Comment by me4502** [comment]
Closed by https://github.com/EngineHub/WorldEdit/commit/d320dafc2bcb442a68d9be9b7aac9cfa7fab69ec
