### ISSUE TITLE
//Hollow removing too many blocks

### ISSUE THREAD

**Issue by masterX244** [EngineHub/WorldEdit#2322]
### WorldEdit Version

7.2.14

### Platform Version

git-Paper-538 (MC: 1.19.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hollow not correctly leaving the shell of the shape

### Expected Behavior

WHen having a irregular shape hollow doesnt leave the surface of the shape
Starting shape
![2023-05-23_21 08 56](https://github.com/EngineHub/WorldEdit/assets/1544922/91a81b62-e113-4cbc-85bb-dbb69fa1999e)
Shape after hollow
![2023-05-23_21 08 59](https://github.com/EngineHub/WorldEdit/assets/1544922/186572bd-e702-4bd9-962a-b428c1e48de8)
Expected: the shell of the shape

### Reproduction Steps

1. make a irregular block pattern
2. hollow it

**Comment by wizjany** [comment]
your screenshots don't show it, but i would guess you just need to expand your selection. afaict hollow is working as intended here.
