### ISSUE TITLE
WorldEdit interferes with Aternos servers startup on Forge 1.18.2

### ISSUE THREAD

**Issue by kizuuuuuu** [EngineHub/WorldEdit#2324]
### WorldEdit Version

WorldEdit 7.2.10 (Forge/Fabric for MC 1.18.2)

### Platform Version

Forge (40.2.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Worldedit causing damage to servers on 1.18.2. Server is starting very long, then if im trying to connect it crashes

Log: https://mclo.gs/EpBC6s8

### Expected Behavior

That i will connect to my server without any problems

### Reproduction Steps

1. Started the server
2. Trying to connect
3. Got kicked out, because of too long time to connect
4. After a few seconds, server crashed

**Comment by octylFractal** [comment]
You're not using "a version of WorldEdit compatible with [your] Minecraft version", nor are you using "the most recent Minecraft release". Please don't lie on the checkboxes.

**Comment by kizuuuuuu** [comment]
I'am using 1.18.2 and theres only one worldedit version for 1.18.2, and its broken

**Comment by kizuuuuuu** [comment]
btw. lol. why would i lie about that? its just broken and you are too lazy to fix it

**Comment by octylFractal** [comment]
You're clearly not using 7.2.10, if you read your logs.
