### ISSUE TITLE
WorldEdit Fails to Load

### ISSUE THREAD

**Issue by LieutenantSugar** [EngineHub/WorldEdit#2333]
### WorldEdit Version

worldedit-bukkit-7.2.14.jar

### Platform Version

paper-1.19.4-550.jar

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The title says it all. WorldEdit fails to load upon server launch. When the command `/plugins` is issued, WorldEdit does not show in the list.

### Expected Behavior

I expected WorldEdit to load so that I can use it.

### Reproduction Steps

1. Put the latest WorldEdit JAR file (in this case, version 7.2.14) in the plugins folder.
2. Launch the server
3. Instant error message

### Anything Else?
I have tried the plugin on Spigot as well before I upgraded to Paper. Same issue.
![image](https://github.com/EngineHub/WorldEdit/assets/59771363/75523893-210b-44d2-a4c8-46531f48c2ef)

**Comment by Joo200** [comment]
Your plugin file is corrupted. Replace the existing jar file with a file which is not invalid.

For further support visit the enginehub discord

**Comment by LieutenantSugar** [comment]
I downloaded it from [https://dev.bukkit.org/projects/worldedit/](url), which I believe is the official download site, so I'm too sure how it could be corrupted. If that's not it, then please provide the proper link. Thank you.

**Comment by octylFractal** [comment]
As previously indicated, please use the Discord for support.
