### ISSUE TITLE
Modrinth support

### ISSUE THREAD

**Issue by EAZYBLACK** [EngineHub/WorldEdit#2341]
### The Problem

Modrinth is a new and modern platform for hosting Minecraft mods, which respects both users and authors alike. Modrinth makes it easier than ever to find and download mods thanks to their improved search features, lightning-fast downloads, and purpose-built platform for Minecraft. It also ensures that creators are paid fairly for their work, by giving them 100% of the ad revenue their projects earn -- without making you sit through advertisements to download your favorite mods.

### A Solution

Switch to Modrinth and stop posting on curseforge
Also many launchers support modrinth mods.

### Alternatives

You can also keep curseforge but do modrinth too

**Comment by wizjany** [comment]
duplicate
