### ISSUE TITLE
Modrinth Support? (Repost)

### ISSUE THREAD

**Issue by Brayman30** [EngineHub/WorldEdit#2345]
### The Problem

I, much like the poster of #1985 am not a fan of CurseForge or it's team and much prefer Modrinth. #1985 was locked as spam for some reason so I wanted to re-open it but have no way of commenting under it. 

### A Solution

Publish WorldEdit on [Modrinth](https://modrinth.com/) and/or (Unlock #1985 )

**Comment by me4502** [comment]
If you know it’s a duplicate don’t add another issue
