### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant org.bukkit.DyeColor

### ISSUE THREAD

**Issue by LucidAPs** [EngineHub/WorldEdit#2351]
### WorldEdit Version

7.2.16-SNAPSHOT

### Platform Version

Purpur 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

https://nekobin.com/gurovuseqa

### Expected Behavior

https://nekobin.com/gurovuseqa

### Reproduction Steps

[1. ...
2. ...
](https://nekobin.com/gurovuseqa)

### Anything Else?

read the error

**Comment by octylFractal** [comment]
That's an error in Core Protect, not WorldEdit.
