### ISSUE TITLE
DeInfest command

### ISSUE THREAD

**Issue by XxSIBxX** [EngineHub/WorldEdit#2352]
### The Problem

When I build I sometimes accidentally use infested blocks. I also sometimes find infested blocks in schematics I download online.

### A Solution

A DeInfest command, after selecting an area just by doing //deinfest (or something along those lines) it will automatically turn any infested blocks into their normal versions.

### Alternatives

I could do //replace (infested block) (normal block), but that takes a long time and can get really frustrating to do it for every build I accidentally use infested blocks in or any schematic I find online.

**Comment by octylFractal** [comment]
This is a little too niche to be added as a general command. This can be done after #1813 is added, by doing `//set s/infested_//` (or whatever the syntax ends up being).
