### ISSUE TITLE
minecraft wont load it says error code 1

### ISSUE THREAD

**Issue by xxmoneypandaxx9** [EngineHub/WorldEdit#2353]
### WorldEdit Version

19.4

### Platform Version

forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

minecraft wont load and it says error code 1

### Expected Behavior

it to load

### Reproduction Steps

1. ...
2. ...

**Comment by octylFractal** [comment]
That isn't even a valid WorldEdit version so there's definitely not enough information to help in any capacity. Please provide useful information such as an error log and try to look at the error yourself to see if there's a clear solution.
