### ISSUE TITLE
Loading any schematic throws an exception

### ISSUE THREAD

**Issue by NJDaeger** [EngineHub/WorldEdit#2356]
### WorldEdit Version

Bukkit-Official(7.3.0-SNAPSHOT+6484-6770ada)

### Platform Version

git-Paper-67 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e105354)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I list my schematics on my server and try to load *any* of them, there is an exception, https://paste.enginehub.org/vrG88pAZd . We have tested both MCEDIT_SCHEMATIC and SPONGE_V1_SCHEMATIC formats and yielded the same error.

### Expected Behavior

When I load a schematic, I expect the schematic to load.

### Reproduction Steps

1. //schematic load <any schematic>

### Anything Else?

This also was an issue on 1.19.4.

**Comment by me4502** [comment]
It seems the checks that determined what format was being loaded was failing, so it was assuming it was one of the newest (Sponge v3). So all non-latest formats were having issues.
