### ISSUE TITLE
Sign Text not set - WorldEdit 7.3

### ISSUE THREAD

**Issue by Wolf2323** [EngineHub/WorldEdit#2358]
### WorldEdit Version

7.3.0-SNAPSHOT+6371-df3f7b2

### Platform Version

git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Refering to https://worldedit.enginehub.org/en/latest/usage/general/patterns/#sign-text I tried to execute `//set oak_sign|Line1|Line2` and `//set "oak_wall_sign[facing=north]|Hello world|Second|Third line"` but no sign text is shown.

### Expected Behavior

There should be Text on the Sign

### Reproduction Steps

1. Select a block
2. execute `//set oak_sign|Line1|Line2`

### Anything Else?

I Tested on 7.2 and there it works on 7.3 not
And i also tested on the Latest MC version

**Comment by me4502** [comment]
The build you're using is >4 months old. If you're going to submit bug reports on development snapshots make sure you're using the latest build

**Comment by Wolf2323** [comment]
I also tested it on the latest version and it is still an issue
