### ISSUE TITLE
Some blocks of my mod disappear

### ISSUE THREAD

**Issue by Dotmazy** [EngineHub/WorldEdit#2362]
### WorldEdit Version

7.2.13

### Platform Version

Forge 44.1.23 (1.19.3)

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i try to move, copy/paste, stack or any other action like that my new repeater of my mod disappear.

### Expected Behavior

It's only append when i copy block bellow and i think it's because wordedit place my repeater first but they have to be place after place the block bellow but i don't know how to fix it.

### Reproduction Steps

1. Make a structure with block and my new repeater on top
2. Move, stack, copy/paste the structure

### Anything Else?

It's doesn't happend with my new comparator.

My mod (use jd-gui to decompile if you need): https://drive.google.com/file/d/17hqjjQGGwrV3PFQQDrftJtEs1ygF-3WT/view?pli=1

**Comment by me4502** [comment]
Don't lie on the issue template. It sounds like either:

* You're in the wrong reorder mode (eg, not in `//reorder fast`)
* The mod is storing data in a way that other mods cannot access (eg, in custom files etc rather than NBT/block state properties)

**Comment by Dotmazy** [comment]
I'm not understand what i have to do?
