### ISSUE TITLE
Using //move more than once deletes the selection block by block

### ISSUE THREAD

**Issue by Sammster9000** [EngineHub/WorldEdit#2365]
### WorldEdit Version

7.2.10

### Platform Version

Fabric 0.14.21

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using //move on a selection, after repeating the command another time, the selection will begin to be deleted as it moves farther from the player, 1 layer of blocks at a time. Eventually after repeating the command enough, the whole selection will disappear, and using //move b will not cause it to reappear. 

### Expected Behavior

It's expected that no matter how many times the //move command is repeated, the selection used will remain in tact. 

### Reproduction Steps

1. Use selection tool to make a selection
2. Use //move
3. Repeat step 2. 

### Anything Else?

I am playing on version 1.18.2 to have compatibility with other mods, but I haven't experienced this bug before on later versions of Minecraft and tested this glitch with only worldedit (and fabric api) enabled to make sure that was the problem.

**Comment by octylFractal** [comment]
This is working as intended, if you want your selection to move use `-s`.
