### ISSUE TITLE
Schematics Bug 1.20

### ISSUE THREAD

**Issue by TranDinhDuyyy** [EngineHub/WorldEdit#2369]
### WorldEdit Version

7.2.16

### Platform Version

paper-1.20.1-95

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I save schematics from 1.20 and switch those schematics to 1.19.4 the text in the sign disappears like this:
![image](https://github.com/EngineHub/WorldEdit/assets/105216318/6d39647f-902d-4854-a4eb-e0e5b1ff7502)

### Expected Behavior

.

### Reproduction Steps

1. ...
2. ...

**Comment by wizjany** [comment]
this is expected, mojang changed how nbt works for signs. minecraft data has never pretended to be backwards compatible.
