### ISSUE TITLE
Please add a config option to disable gameplay-related commands (like god/heal)

### ISSUE THREAD

**Issue by itsTyrion** [EngineHub/WorldEdit#2374]
### The Problem

I don't want Worldedit overriding my server-system's commands. 
Generally, I also think that WE isn't the right plugin for something like /heal, but that's just my opinion.

### A Solution

Please add a config option to disable the gameplay-related commands.
![image](https://github.com/EngineHub/WorldEdit/assets/17730120/3407ef33-cf95-4ac6-942f-665935248c19)

**Comment by me4502** [comment]
Not WorldEdit commands, but either way it's up to your server platform to let you choose what plugins have priority for commands, plugins cannot

**Comment by itsTyrion** [comment]
Yes they ARE WorldEdit commands, here's the WE wiki page [https://worldguard.enginehub.org/en/latest/commands](https://worldguard.enginehub.org/en/latest/command)s that confirms it
