### ISSUE TITLE
Allow for setting blocks with nbt data

### ISSUE THREAD

**Issue by BeeFox-sys** [EngineHub/WorldEdit#2375]
### The Problem

At current, it is impossible with world edit to set blocks containing nbt in a command, such as a hopper with items in it, while this is possible with the hand or clipboard options, i feel it should be allowed within the command itself

### A Solution

Allow the ability to use vanillas nbt syntax (eg: `hopper{Items:[{Slot:0b,id:"minecraft:coal_block",Count:64b}]}`) in patterns

### Alternatives

both the patterns `#clipboard` and `hand` do allow for setting nbt, however this does not allow for things like random distributions in patterns. sign, spawner, and heads do have special syntax for allowing some nbt, however they are very much exceptions to the rule and a generic nbt syntax would allow for more to be done (such as setting sign colours, modifying spawner times, etc)

**Comment by octylFractal** [comment]
#2173
