### ISSUE TITLE
Schematics directory issue

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/WorldEdit#2381]
### WorldEdit Version

7.3.0 SNAPSHOT

### Platform Version

Paper Build 111 (Version 1.20.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Schematics directory no longer allows placement outside of working directory,
Example:
`saving:
    dir: "C:\\WorldEditSchematics\\"`
This ruins windows environments using outside directorys to share schematics across several servers.
A major flaw for running multi network environments across windows platforms.

This is not a problem on WG 7.2.x

The error on startup is as follows:
https://pastebin.com/raw/wKwprBpT

### Expected Behavior

To use outside directories [as before].

### Reproduction Steps

1. Launch default worldedit.
2. Use outside directory as schematic folder on windows.
3. Boom?

### Anything Else?

We've been using this schematic system for years, we would highly appreciate this functionality to continue into the future.

**Comment by me4502** [comment]
Closing this as the system you're having issues with there was removed in https://github.com/EngineHub/WorldEdit/commit/7f81aad028f2b8244351764b56d7e9f1e9f3d1ec

**Comment by crumpkatrina** [comment]
@me4502
Are there any plans on returning this system or migrating to a new one?
How else can we use directories outside of the plugin folder?

**Comment by me4502** [comment]
There's nothing stopping you from having a schematics folder outside of the server folder, this issue was unrelated to that

**Comment by crumpkatrina** [comment]
Apologies, misunderstood your comment thus deleted mine above.
Will retest and hope things work. 🙂
