### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Bear228** [EngineHub/WorldEdit#2382]
### WorldEdit Version

7.2.15

### Platform Version

MohistMC 294 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Writes to me to update your plugin even though it is the latest version
![image](https://github.com/EngineHub/WorldEdit/assets/70435982/49536fe3-a951-455c-8e36-e45b9f85df12)

### Expected Behavior

What can I highlight without this error

### Reproduction Steps

1. ...
2. ...

**Comment by octylFractal** [comment]
Mohist is a hybrid. Hybrids are not supported.
