### ISSUE TITLE
World edit not working w/ supplementaries mod

### ISSUE THREAD

**Issue by Niek06** [EngineHub/WorldEdit#2385]
### WorldEdit Version

7.2.15

### Platform Version

Forge 1.20.1 - 47.1.0

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i try to load in a singleplayer world with the mods "worldedit & supplementaries" loaded, it does not word as intended. I get an "invalid player id" error, that i can't fix. If i would only load worldedit it works totally normal. Is there a way to fix this problem?

### Expected Behavior

I expected it to work as intended

### Reproduction Steps

1. 
2.

**Comment by Niek06** [comment]
Here is an latest log of the crash 

[latest.log](https://github.com/EngineHub/WorldEdit/files/12323269/latest.log)

**Comment by octylFractal** [comment]
It doesn't look like WorldEdit is related to this crash, it seems like "moonlight" is causing it. Are you sure this doesn't happen without WorldEdit installed?

**Comment by Niek06** [comment]
Oh yeah you're right! it looks like it is caused by moonlight. thanks! ill try to fix it do you maybe know something?
