### ISSUE TITLE
paste -s doesn't fully select in //sel extend mode

### ISSUE THREAD

**Issue by itsnotjasper** [EngineHub/WorldEdit#2386]
### WorldEdit Version

7.2.15

### Platform Version

git-Purpur-2025; git-Paper-107 (MC 1.20.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The selection only selects 1-block-width when pasting with paste -s in //sel extend mode. 
![2023-08-16_11 31 31](https://github.com/EngineHub/WorldEdit/assets/43426628/67a86eb5-9953-4fc2-9074-296e78d1b422)

### Expected Behavior

paste -s should fully select the region initially copied

### Reproduction Steps

1. copy any region that has more than 1-block-width
2. change selection to //sel extend
3. //paste -s

**Comment by me4502** [comment]
I can't reproduce this issue at all, is there anything else special about your setup or what you're doing? If I do `//paste -s` in extend select mode it'll correctly select the entire area no matter what area shape I copy

**Comment by itsnotjasper** [comment]
Quite strange as the bug is also unreproducible now for me. I've asked a friend who also experienced the same bug if they would be able to recreate it, and hopefully he'll still be able to reproduce the bug.

**Comment by itsnotjasper** [comment]
Closing for now. It seems like I'm also unable to reproduce the issue  and was a possible client-side issue or a bug with WESV. I'll re-open an issue when this occurs again and I'm able to reproduce it reliably.
