### ISSUE TITLE
world keeps getting corrupted

### ISSUE THREAD

**Issue by abielaird** [EngineHub/WorldEdit#2387]
### WorldEdit Version

7.2.15

### Platform Version

forge 1.20

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

i have 10 mods installed and my game keeps getting corrupted, i've narrowed the culprit down to 3 mods: biomes o plenty, journey map, and world edit 1.20 but i dont know how to fix it.

### Expected Behavior

i would like to play these mods without losing my world

### Reproduction Steps

idk if its my computor or the mods but it happened with world edit, journey map, and biomes o plenty installed.

### Anything Else?

i do not know how to provide log files. i really just need to find out how to prevent corruption.

**Comment by me4502** [comment]
Worldedit only does anything while being run, it’s not passively corrupting a world

**Comment by abielaird** [comment]
oh ok, how do i figure out whats corrupting my world?
