### ISSUE TITLE
spawner|entity syntax doesn't work

### ISSUE THREAD

**Issue by calumapplepie** [EngineHub/WorldEdit#2388]
### WorldEdit Version

Bukkit-Official(7.2.15+6463-5ca4dff)

### Platform Version

git-Paper-63 (MC: 1.20.1) (Git: c0936a7) 

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Patterns involving mob spawners don't work (eg, //set spawner|squid).  Instead, an empty spawner is createds

### Expected Behavior

A spawner is created, that creates squid

### Reproduction Steps

1. Select a block
2. Try to make a squid spawner via //set

### Anything Else?

Note: while this is not the latest paper, I can't see any paper changes that would be significant.  If you can't reproduce, i'll try to update my paper build

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/WorldEdit/commit/18cc29a26fb661fdae80fbf26d07ef76b5b37b00
