### ISSUE TITLE
Chisels and Bits compatibility

### ISSUE THREAD

**Issue by Zockerhopper** [EngineHub/WorldEdit#2389]
### The Problem

Whenever I build something with Chisels and bits and then try to copy that area with a Chisels and Bits 'block' with //copy and the //paste it the Chisels and Bits 'block' is completely invisible (not rendering) and when I break the 'block' it playes the breaking sound of stone. Even when I used wood Bits. 

### A Solution

Support for Chisels and Bits 'blocks'.

### Anything Else?

The reason I put block in between two Apostrophies is because Chisels and Bits allows for the use of Bits, that are the size of a single Block pixel to make custom blocks, with custom shapes.

**Comment by me4502** [comment]
This isn’t a feature request, it’s a bug report (one that generally we can’t do anything about as it’s an issue in the mod adding the block).

You need to provide the the information from the bug report template.
