### ISSUE TITLE
Replace randomly a block in a region

### ISSUE THREAD

**Issue by Alvaro203204** [EngineHub/WorldEdit#2392]
### The Problem

It will be very helpful a feature that allows the user to replace a randomly certain of blocks and keep the others, now you can do it with `//replace 10% air` for example an this will replace the 10% of blocks but if you try to make something like `//replace 10%#solid air` isn't going to work properly.

### A Solution

I suggest adding the feature to allow to use tags to replace the 10% of solid blocks for example like I explained in The Problem part. (`//replace 10%#solid air`)

**Comment by me4502** [comment]
Read the docs page on masks, it covers how to combine masks

**Comment by Alvaro203204** [comment]
I tried with maks and combining them but I can't find a solution so I thinked that isn't maked.
