### ISSUE TITLE
sk89q.com

### ISSUE THREAD

**Issue by TheBjoel2** [EngineHub/WorldEdit#2393]
### WorldEdit Version

all of the 1.12.2 branches

### Platform Version

-

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

```
$ ./gradlew build
...
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':worldedit-bukkit:shadowJar'.
> Could not resolve all dependencies for configuration ':worldedit-bukkit:runtime'.
   > Could not resolve com.sk89q:dummypermscompat:1.8.
     Required by:
         project :worldedit-bukkit
      > Could not resolve com.sk89q:dummypermscompat:1.8.
         > Could not get resource 'http://maven.sk89q.com/repo/com/sk89q/dummypermscompat/1.8/dummypermscompat-1.8.pom'.
            > Could not GET 'http://maven.sk89q.com/repo/com/sk89q/dummypermscompat/1.8/dummypermscompat-1.8.pom'. Received status code 522 from server:
```

### Expected Behavior

Build should succeed.

### Reproduction Steps

``./gradlew build``

### Anything Else?

Please update urls since sk89q.com is down

**Comment by octylFractal** [comment]
We do not maintain old versions, if you would like to build them you can figure out the patches yourself.
