### ISSUE TITLE
Limit WorldEdit Usage to Own Region

### ISSUE THREAD

**Issue by Zinnorov** [EngineHub/WorldEdit#2394]
### The Problem

WorldEdit allows users to edit and manipulate blocks across the entire server. This lack of control can be frustrating for server administrators and players who want to ensure that only specific regions are affected by WorldEdit commands.

### A Solution

I suggest implementing a feature in WorldEdit that allows users to limit their WorldEdit commands to only affect their own defined regions or selections. This feature would grant users more control over their edits, reduce the risk of accidental alterations in the world, and enhance the overall experience of using WorldEdit.

**Comment by octylFractal** [comment]
We consider this out-of-scope for WorldEdit. It is designed as an admin-only tool.
