### ISSUE TITLE
Incompatible with Hephaestus mod

### ISSUE THREAD

**Issue by JMackey1** [EngineHub/WorldEdit#2414]
### WorldEdit Version

7.2.15+6463-5ca-4dff

### Platform Version

Fabric 0.14.22

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Worlds will not load when I have both Hephaestus and WorldEdit mods enabled, plus some additional mod(s) which I can't identify. Basically: a world loads if I have Hephaestus enabled, or WorldEdit enabled, but not both when all my other mods are enabled. If I disable all mods other than Hephaestus and WorldEdit, worlds will load.

More details on my Hephaestus ticket: https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/77

### Expected Behavior

Worlds loads with both mods enabled.

### Reproduction Steps

1. Install my mod list (https://pastebin.com/C8vM9qA1)
2. Try to load a world with both Hephaestus and WorldEdit enabled (and all other mods)
3. World gets stuck at loading

### Anything Else?

I don't see a log but if there's a way I can turn some kind of logging on during world loading, or if you want any additional information, please let me know.

**Comment by octylFractal** [comment]
If you could use a process similar to https://madelinemiller.dev/blog/debug-minecraft-server-issues/#finding-the-problem-plugin to narrow down which extra mod it is, that would be nice. There are far too many as-is to really work on this issue.

Alternatively, you could try to dump a stacktrace when it's frozen. I don't know any user-friendly way to do that, the only way I know is using `jstack`. This would likely point directly to the issue.

**Comment by JMackey1** [comment]
[latest.log](https://github.com/EngineHub/WorldEdit/files/12917938/latest.log)

**Comment by me4502** [comment]
Based on the linked tickets it looks like this was a bug in another mod and has since been solved
