### ISSUE TITLE
Multiple coordinates

### ISSUE THREAD

**Issue by Tricnax** [EngineHub/WorldEdit#2421]
### The Problem

I need to create a diagonal tunnel. The //sel poly tool needs to define points by entering coordinates, as is the case with //pos1 and //pos2. The system is missing //pos3, //pos4, etc

### A Solution

I need a way to define multiple coordinates also by typing them in.

### Alternatives

Or how to make diagonal tunnels differently - at different angles and of different thickness?

**Comment by octylFractal** [comment]
This sounds like it is resolved by #1981 which is in the 7.3.0 beta.

**Comment by octylFractal** [comment]
Alternatively, you can just use //pos2 over and over -- that's how the new command works anyway.

**Comment by me4502** [comment]
To clarify pos1 and pos2 act like the left and right clicks of the wand. So pos1 is the primary point, and pos2 depends on how that selection type works. For that type it’s “add additional point”

**Comment by Tricnax** [comment]
Thank you very much for your professional help. I'll try it tonight when I create my world. :)
