### ISSUE TITLE
2 "things" in 7.3.0-beta 2

### ISSUE THREAD

**Issue by Oxicodona** [EngineHub/WorldEdit#2423]
### WorldEdit Version

7.3.0 beta 2

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

1) Applying snow smooth (both commands **//snowsmooth** and **//brush snowsmooth**) with interactions higher than 1 will add the blocks that the terrain had under the new snow blocks

2) Using the mask 0 on snow smooth (both commands **//brush snowsmooth -m 0** and **//snowsmooth -m 0**) will add like a "platform" of snow a few blocks above the selection

### Expected Behavior

1) Expected only snow and snow blocks after using //snowsmooth 

2) Expected using the mask 0 to only put snow in the air blocks above the terrain

### Reproduction Steps

For (1)
1. Select a region with a lot of steep terrain and put //gmask 0 
2. Use //snowsmooth or //brush snowsmooth
3. As you can see in the photos, since the terrain is steep, it will create dirt under the snow

![2023-10-21_14 37 02](https://github.com/EngineHub/WorldEdit/assets/148630103/a5823c9d-be3a-4bd5-82f8-6ad93642d430)
![2023-10-21_14 37 07](https://github.com/EngineHub/WorldEdit/assets/148630103/9b36d9a1-bd28-4f19-8c38-f9d052a442aa)

Also put a photo with trees after using snowsmooth, and, as you can see, the command messes up with the grass

![2023-10-21_14 43 49](https://github.com/EngineHub/WorldEdit/assets/148630103/a66ebd88-0988-4b04-b140-fe8d902e9a4f)
![2023-10-21_14 44 39](https://github.com/EngineHub/WorldEdit/assets/148630103/7b1d3798-a67c-40f3-80a0-70e02db23759)

Applying snow smooth should only add snow and snow blocks instead of adding another blocks (i.e. stone, dirt, grass, etc...), so it doesn't mess with the structure (example snowing terrain with trees)

For (2)
1. Select a region and use //snowsmooth -m 0
2. You will see like a platform above your selection

![2023-10-21_14 30 36](https://github.com/EngineHub/WorldEdit/assets/148630103/ea7ed1d5-4322-4e18-8c43-75889ab81b22)

### Anything Else?

1) Applying snow smooth should only add snow and snow blocks instead of adding another blocks (i.e. stone, dirt, grass, etc...), so it doesn't mess with the structure (example snowing terrain with trees)

**Comment by wizjany** [comment]
#2407 ?

**Comment by Oxicodona** [comment]
yes, it's similar to #2407 but i also added those two new bugs, they are related

the point is that the brush should add only snow and snow blocks

**Comment by wizjany** [comment]
on second look this looks unrelated to the height issue.
for 1: not sure why you think that. filling with the underlying block seems to be intended behavior from what i can see in the code.
for 2: this looks correct as well, if you mask the kernel to air, then the top layer of air is the "ground", which is already flat, so you'll get a flat overlay of snow above it.

**Comment by Joo200** [comment]
Please check the help from `//snowsmooth` with `//help snowsmooth`:

1. Snowsmooth will use existing blocks under the used snow blocks and layers. You can change the amount of snow blocks under the snow layers with the `-l` flag. The behavior is mostly copied from //smooth except the top layers will be replaced by snow.
2. Setting the mask to air with `-m 0` is not the same as using a `//gmask`. From the help text:
   > -m: The mask of blocks to use as height map. Example: '//snowsmooth 1 -m snow_block,snow' would only smooth snow terrain
