### ISSUE TITLE
World crashing when i use //sel

### ISSUE THREAD

**Issue by tadadump** [EngineHub/WorldEdit#2425]
### WorldEdit Version

7.2.3

### Platform Version

forge 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

i just downloaded worldedit today. i want to select a cylinder, but when i do //sel cyl  my world crashes. minecraft stays open, but i’m put back into the main menu.

### Expected Behavior

put in command, select a cylinder

### Reproduction Steps

1. ...put in command //sel cyl
2. ...yea that’s it

**Comment by octylFractal** [comment]
>  I am using a version of WorldEdit compatible with my Minecraft version.
7.2.3 is not compatible with 1.20.1. Please use a version that is compatible.
