### ISSUE TITLE
Shadowed variable is missing in Minecraft 23w43b

### ISSUE THREAD

**Issue by Pixaurora** [EngineHub/WorldEdit#2429]
### WorldEdit Version

7.3.0-SNAPSHOT

### Platform Version

Fabric 0.14.24

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [ ] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Running with the latest build from 7.3.0-SNAPSHOT in Minecraft 23w43b, a couple mixins can't apply properly. The log shows that the intermediary name corresponding with the shadowed variable `MinecraftServer.nextTickTime` has been removed.

[crash log](https://github.com/EngineHub/WorldEdit/files/13193352/latest.log)

### Expected Behavior

The game starts up normally and all of the mixins apply without issue.

### Reproduction Steps

1. Install Fabric loader and the latest snapshot version of Minecraft and the mod.
2. Run the game.

### Anything Else?

This appears to be related to the fact that /tick was added in this snapshot, so Mojang reworked that part of the game.

**Comment by wizjany** [comment]
snapshots are not releases
