### ISSUE TITLE
Placing stairs boots other player's wi-fi.

### ISSUE THREAD

**Issue by NinaCMercer** [EngineHub/WorldEdit#2431]
### WorldEdit Version

7.2.12

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I placed the roof stairs exactly how i wanted, however the server owner got completely booted almost immediately afterwards.

His wi-fi even shutdown, and he presumably had to un-plug and re-plug his router.

### Expected Behavior

The stairs to place without any issue.

### Reproduction Steps

1. Have builder or higher rank on a server, that has at least one other player online.
2. Run "//pos 1", "//pos 2", and "//set quartz_stairs[facing=east,half=bottom]"
3. Wait until you see "[insertplayername] has left the game" in the chat/console.
4. Contact, and ask them what happened on their end.

### Anything Else?

This did NOT occur with other commands, i.e "//set quartz_stairs". It was specifically placing stairs that faced a specific direction.

**Comment by wizjany** [comment]
this is hilarious, but absolutely not a worldedit bug.
