### ISSUE TITLE
//regen crashing problems

### ISSUE THREAD

**Issue by Boredflea** [EngineHub/WorldEdit#2433]
### WorldEdit Version

7.3.0

### Platform Version

spigot 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

whenever I type //regen the server gets overloaded and I time out and cant reconnect until I restart the server

### Expected Behavior

for it to regen the terrain to how it was when the server started

### Reproduction Steps

1. do //regen on any size of regen
2. wait to time out

### Anything Else?

my server is hosted by extra vm

**Comment by me4502** [comment]
Provide your logs and the worldedit version

**Comment by Boredflea** [comment]
It works now that i downloaded an earlier version so I cant pull up the logs

**Comment by octylFractal** [comment]
Hybrids are indeed unsupported.
