### ISSUE TITLE
Using the nav wand while aimed at an armour stand / item frame will break the entity rather than teleport the player.

### ISSUE THREAD

**Issue by accLarson** [EngineHub/WorldEdit#2441]
### WorldEdit Version

7.2.17

### Platform Version

git-purpur-2090

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using the navigation wand, left clicking while aiming at an armour stand / item frame in range of the player will break the entity rather than overriding the click.

### Expected Behavior

The entity does not break and the player teleport either to the block of the entity or teleports to the location where the player is aimed through the entity.

### Reproduction Steps

1. install world edit
2. give yourself a navigation wand (compass by default)
3. stand infront of an armour stand / item frame within range.
4. "punch" (left click) the entity.
5. Observe the reported behaviour (entity breaks / no teleport)

**Comment by me4502** [comment]
This isn't a bug, it's always (intentionally) been the case that hitting entities don't trigger tools. As everything aligns to a block grid it makes the most sense to not have entities trigger tool usages

**Comment by accLarson** [comment]
I see. 
Might be worth considering if some entities like armor stands / item frames should be made an exception to that rule not as a bug fix but for ease of usability.
