### ISSUE TITLE
all the mods 9 world not starting when worldedit installed

### ISSUE THREAD

**Issue by witheredchica** [EngineHub/WorldEdit#2444]
### WorldEdit Version

7.2.15

### Platform Version

Forge 47.2.14

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When WorldEdit is in the mods folder, the game starts normally, then when I open a world it gets stuck on the loading screen. This happens with multiple different worlds, and only happens when WorldEdit is installed

### Expected Behavior

The world to open

### Reproduction Steps

1. Install All the Mods 9 modpack (version 0.2.25)
2. Add WorldEdit to mods folder
3. Either create new singleplayer world or join existing one
4. Game freezes here

### Anything Else?

Game log of error - https://mclo.gs/gacSNWV

**Comment by PrincessRTFM** [comment]
Duplicate of which issue?

**Comment by me4502** [comment]
Duplicate of https://github.com/EngineHub/WorldEdit/issues/2273
