### ISSUE TITLE
Not able to load schematics

### ISSUE THREAD

**Issue by spagettgeeuhraf** [EngineHub/WorldEdit#2445]
### WorldEdit Version

7.3.0-beta-02

### Platform Version

paper

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I am unable to load or paste certain schematics into my server. I am working on a skyblock server, and so the world is an empty void besides the things I have built in it, however I have been trying to paste a schematic of a large cave into the server and it isn't working. I saved the schematic from a separate testing server with the same version and software, and was able to paste it in that server, but it wouldn't work in my main server. It is about 4 million blocks, but it was able to load in my testing server. I've even split the schematic into four smaller sections which each work on the testing server, but I cannot paste them into my main server

### Expected Behavior

I had expected for the schematic to paste and load just the same, but it doesn't and instead gives me an error message saying that the position is not loaded

### Reproduction Steps

1. I saved a schematic of a cave in a testing server on 1.20.1
2. I attempted to load the schematic in my main server with the same software and versions, the only difference being that the world is an empty void for the most part
3. the schematic wouldn't load and gives me an error saying the position is not loaded

**Comment by Joo200** [comment]
* Please make sure you pasted the schematic in the correct schematic directory of the server.
* Can you save and load the saved schematic from the server?

If both doesn't work please join the discord for further questions.

**Comment by wizjany** [comment]
"position is not loaded" doesn't sound like a worldedit error.

**Comment by spagettgeeuhraf** [comment]
It is in the correct place, I can see the schematic in the schematics when listing them on the server. Sorry I don't quite understand the second bullet point. Could you give me an invite? The link for it says expired when I tried

**Comment by spagettgeeuhraf** [comment]
Hey, its been a couple days and I'm still a bit lost. I think I realized what you meant in that second bullet point, and I saved a schematic in my main server and was able to load it perfectly fine. I also have downloaded schematics before and loaded them, only the ones from a separate test server are unable to load. Any help is appreciated

**Comment by me4502** [comment]
As was said the error message doesn't sound like a worldedit one. Provide the actual entire error that shows up when you try to load it

**Comment by spagettgeeuhraf** [comment]
in game it says "Failed to load schematic: unknown error. Please see console" and in the console it just says "[15:50:14 INFO]: 
That position is not loaded" at least 20 times

**Comment by me4502** [comment]
Provide your entire logs on the discord. The error you're providing is not really possible there, the message ingame implies you'll get a stacktrace, and what you're referencing is not a stack trace. It sounds like something else is involved

**Comment by spagettgeeuhraf** [comment]
As said the discord link is expired, could you give me a new one?  I'm not entirely sure what you mean about a stack trace, but the only available errors in the log is just "that position is not loaded" about a hundred times

**Comment by me4502** [comment]
The discord link cannot expire, it’s a public server. http://discord.gg/enginehub
