### ISSUE TITLE
//perf on still won't connect glass pains to adjacent solid blocks.

### ISSUE THREAD

**Issue by DNAmaster10** [EngineHub/WorldEdit#2449]
### WorldEdit Version

7.3.0 beta 2

### Platform Version

Paper-318

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When //set ing or //replace ing for blocks which connect to solid blocks, even with all perf options on, walls, glass panes etc don't connect to bordering solid blocks.

### Expected Behavior

Glass panes, walls etc should connect to solid blocks when set or replaced with all perf settings on.

### Reproduction Steps

Place two blocks at least one block apart, turn perf on, try to set the air block in-between the blocks to glass_pane. It won't connect.

**Comment by me4502** [comment]
You didn't include what Minecraft version you're using

**Comment by me4502** [comment]
From my testing it's behaving the same as it does when I place blocks by hand, so I don't think there's anything wrong here? Yes it's not always connecting to blocks, but panes don't seem to naturally connect to all blocks

**Comment by DNAmaster10** [comment]
> From my testing it's behaving the same as it does when I place blocks by hand, so I don't think there's anything wrong here? Yes it's not always connecting to blocks, but panes don't seem to naturally connect to all blocks

Sorry! We're using 1.20.2 as of now. The issue is happening for all blocks, not just some. Is there any additional information I should provide, such as screenshot attachments?

**Comment by DNAmaster10** [comment]
As a quick update here, testing with [WorldEdit 7.3.0 Beta 4](https://dev.bukkit.org/projects/worldedit/files/5077490) still seems to produce the same issue.

**Comment by MicboxLunchbox** [comment]
Hi I also had this problem. Your having the issue because of a variety of reasons. I found that the best approach is to just replace the pannels by hand, or maybe its possible to edit the .region files of the world somehow. I'm not a developer so sorry if this is not the info you needed.

**Comment by DNAmaster10** [comment]
As an update here, this issue is still persisting in world edit Bukkit-7.3.2.

I'll attach screenshots below.

//Perf is on
![2024-06-03_22 07 07](https://github.com/EngineHub/WorldEdit/assets/44494235/634063e9-8159-4238-9475-59419cd061fc)

Running the following command
![2024-06-03_22 07 18](https://github.com/EngineHub/WorldEdit/assets/44494235/6014d67f-a08a-499d-a87f-775656125920)

Does this
![2024-06-03_22 07 24](https://github.com/EngineHub/WorldEdit/assets/44494235/74c9eb58-4282-493b-b444-5f83acede82f)

However, running //update afterwards
![2024-06-03_22 07 33](https://github.com/EngineHub/WorldEdit/assets/44494235/e1016264-043a-445d-9842-49ec50684a16)

Fixes the issue, here
![2024-06-03_22 07 39](https://github.com/EngineHub/WorldEdit/assets/44494235/4cfe3f74-7881-446a-83b2-885c93d553b8)

The //perf command should be automatically doing this.

The issue isn't unique to just glass panes. Fences and walls have the same issue.
