### ISSUE TITLE
Feature request: Something similar to a //fill command but for 3d areas.

### ISSUE THREAD

**Issue by itsnotjasper** [EngineHub/WorldEdit#2452]
### The Problem

Currently, there is no way to fully fill in 3D areas. The typical solution is to spam //fill for every later, but it'd be much more convenient to use another command to fill in the entirety of an enclosed 3d area.

### A Solution

A new command for filling 3D areas.
Perhaps //fill-3d <pattern> <radius>.

### Alternatives

Spam //fill across every layer. This is extremely tedious for large 3D shapes.

**Comment by me4502** [comment]
Fill is for 3D areas, you're going to need to elaborate on specifically the difference you're referring to here

**Comment by itsnotjasper** [comment]
Not required as I've found an alternative solution that uses //replace instead.
