### ISSUE TITLE
unable to copy and paste structures like I used to be able to

### ISSUE THREAD

**Issue by chameleon222** [EngineHub/WorldEdit#2454]
### WorldEdit Version

LATEST FABRIC RELEASE 1.20.4

### Platform Version

I just don’t know😭

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Ever since I updated to 1.20.4 (i use fabric btw) I haven’t been able to copy and paste structures like I normally do, I can confirm it is not because of the new version and mechanics but I’m almost positive a little bug ive encountered which I depend on for all my building cuz I copy and paste grass and ferns onto blocks that they can’t be placed on normally and stuff and I really take advantage of the mod in that way cuz I use a lot of that type of world edit in my builds but now I have to do it one by one by hand and using the debug stick instead of just /paste -a
I have tried -paste & paste -a and all of the above but no luck, I have to manually copy the grass, stand where I want to copy and paste it each individually and it’s alottt of work now idk I think it’s a small but hopefully it can be fixed love u thx so much for u hard work and have a merry Christmas gurl

### Expected Behavior

When doing /paste -a, everything that you copied will paste like normal ( even blocks that can’t normally be placed on certain blocks ) but now with the latest version I have to do //replace gold block fern on every single tree that I copy and paste since I use ferns on my custom trees ( srry if this is so scattered )

### Reproduction Steps

1. ...
2. ...
I don’t know  but you take your time and enjoy these holidays !!! yasss

### Anything Else?

keep doing u gurl

**Comment by me4502** [comment]
If you’re trying to paste things that cannot naturally go there, it’s always been required to disable neighbours and updates in //perf to stop worldedit triggering updates

**Comment by chameleon222** [comment]
of all the years I’ve used world edit I’m just now discovering this thank you sooo much so much time gonna be saved now😭🙏💯
