### ISSUE TITLE
Depend on specific versions of Minecraft for the Fabric mod

### ISSUE THREAD

**Issue by Poopooracoocoo** [EngineHub/WorldEdit#2455]
### The Problem

Many users somehow get the wrong version of the WorldEdit Fabric mod. Users see a crash that they don't know how to interpret. 

### A Solution

Adding a Minecraft version dependency to the fabric mod json means that Fabric Loader will inform them instead of crashing. 

https://github.com/EngineHub/WorldEdit/blob/master/worldedit-fabric/src/main/resources/fabric.mod.json#L26C7

**Comment by wizjany** [comment]
dupe
