### ISSUE TITLE
WorldEdit for Neoforge (1.20-current)

### ISSUE THREAD

**Issue by Samapoke** [EngineHub/WorldEdit#2458]
### The Problem

I have a Neoforge 1.20.2 server and I want to use WorldEdit, but it not supports Neoforge

### A Solution

Can you make a Neoforge version for the mod? 

### Anything Else?

Thank you!

**Comment by TripleThreeT** [comment]
I agree, but in this case with 1.20.4

**Comment by octylFractal** [comment]
Done for 1.20.5 in #2512 . Will not be backported, as we never do that and it would be a lot of work.
