### ISSUE TITLE
When using //sel command, you will---Internal Excption: Java.lang.NullPointerException

### ISSUE THREAD

**Issue by maboroshiki** [EngineHub/WorldEdit#2464]
### WorldEdit Version

7.2.18-dis/7.3.0-beta-03-dist

### Platform Version

Forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using //sel command, You will instantly drop off the line, any jump to the multiplayer interface.（I am Japanese, my English is very poor, sorry）
And get an error message：Internal Excption: Java.lang.NullPointerException.
This includes //sel and any of them.
My friend is not in this situation, and I am not just related to my macos computer system or not.
<img width="525" alt="817CEF2C-3B71-4B82-8207-573E6A0D031D" src="https://github.com/EngineHub/WorldEdit/assets/158718735/5dbf5010-809a-40a8-b6f3-f3c18c533bb7">

### Expected Behavior

Change selection type.just //sel sphere.

### Reproduction Steps

1. ...//sel
2. ...

**Comment by maboroshiki** [comment]
The same thing happens to me whether I'm playing single-player or multiplayer. But my friend doesn't have this problem, and I think many other people don't have this problem, why only me?
The java version is java17 that came with the boot organ.

**Comment by me4502** [comment]
We'll need significantly more details including specific forge versions, other mods installed, what's installed on the server, and client logs of the actual error.

The only other person who had this issue ended up reproducing it without worldedit installed and found it to be a forge bug, but I don't know what happened when they reported it to Forge.

Forge 1.20.4 is extremely buggy currently (I can't even load the singleplayer world list without it crashing with no mods installed), so it being a forge bug is fairly likely.

**Comment by maboroshiki** [comment]
[latest.log](https://github.com/EngineHub/WorldEdit/files/14150806/latest.log)

Thank you for your reply. I tried to submit the log file.
My version of the game is 1.20.4, I tried to update forge to the latest version and still couldn't fix it, the current version of forge is: 49.0.26.
I first encountered it in single player, and then I tried it on the server, but I had the same problem. My single player game doesn't have any other mods, just worldedit.
I don't know if I have answered all the questions. My English is really not good. I'm sorry.

> We'll need significantly more details including specific forge versions, other mods installed, what's installed on the server, and client logs of the actual error.
> 
> The only other person who had this issue ended up reproducing it without worldedit installed and found it to be a forge bug, but I don't know what happened when they reported it to Forge.
> 
> Forge 1.20.4 is extremely buggy currently (I can't even load the singleplayer world list without it crashing with no mods installed), so it being a forge bug is fairly likely.

**Comment by maboroshiki** [comment]
![image](https://github.com/EngineHub/WorldEdit/assets/158718735/6bf5d6d2-7ce9-4eab-a53a-2420042faa83)
This is a list of plugins on the server, although I first encountered this problem in single player mode.

**Comment by maboroshiki** [comment]
> 我们需要更多的详细信息，包括特定的伪造版本、安装的其他模组、服务器上安装的内容以及实际错误的客户端日志。
> 
> 唯一遇到此问题的人最终在没有安装 worldedit 的情况下重现了该问题，并发现这是一个 Forge 错误，但我不知道当他们向 Forge 报告时发生了什么。
> 
> 目前，Forge 1.20.4 的 bug 非常多（我什至无法加载单人游戏世界列表，而不会在未安装 mod 的情况下崩溃），因此它很可能是一个 Forge 错误。

**Comment by me4502** [comment]
You’re not using worldedit on that server.

**Comment by maboroshiki** [comment]
> You’re not using worldedit on that server.

I'm sorry, the server has the same instructions and the same error... I first encountered it in singleplayer mode...I like to make maps in my archive.

**Comment by octylFractal** [comment]
Forge isn't supported any more so this doesn't matter to us.
