### ISSUE TITLE
[WE API] Clipboard and blocks manipulations

### ISSUE THREAD

**Issue by Quenteez** [EngineHub/WorldEdit#2465]
### WorldEdit Version

7.3.0-beta-03+d6d222e

### Platform Version

Fabric@0.93.1+1.20.4, FabricLoader: 0.15.3

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I ran into a problem, maybe the developers will be able to tell me what I can do to solve it. I use the WorldEdit API to manage schematics. I wrote the following code (**[here](https://paste.md-5.net/afewilexuy.cpp)**), which pastes the schematic "layer by layer", taking into account the direction of the player's gaze. Everything seems to be working correctly, but there are problems with positioning the blocks at the **X** and **Z** coordinates. For some reason, the player's position does not seem to be taken into account. I came to the conclusion that `clipboard.setOrigin()` does not lead to anything. The schematic is simply set diagonally relative to the player.

Video ([here](https://dropmefiles.com/hckfe)).

### Expected Behavior

The blocks will be placed correctly

### Reproduction Steps

nothing there

**Comment by me4502** [comment]
The issue tracker is for reporting bugs _in WorldEdit_, not for help using our API. Use the Discord for API help.
