### ISSUE TITLE
Ideas related to shortcuts

### ISSUE THREAD

**Issue by LLDISK** [EngineHub/WorldEdit#2479]
### The Problem

When installing blocks, using commands to write the block's name or delete copy-paste with commands is annoying and cumbersome.

### A Solution

Hold up the block you want to install and press a shortcut,
I thought it would be nice to have shortcuts for copying, like Ctrl + C, V, etc.

Even if it's not necessarily a shortcut, it would be nice to be able to turn on a command to turn on EasySet, such as holding a block in your left hand or right-clicking on a block to install it.

### Anything Else?

When using stack or move, it's a bit cumbersome to decide where to stop,
I think it would be handy to be able to grab a tool with a stack feature and right-click on a specific location and have it stack or move to that location up to the selection.

Thank you for reading my opinion.

All content is written as a translator.

**Comment by octylFractal** [comment]
This would be more of a request for WorldEdit CUI, as WorldEdit explicitly has minimal client-side interaction and so cannot have keybinds.
