### ISSUE TITLE
schematic in command blocks

### ISSUE THREAD

**Issue by seema84** [EngineHub/WorldEdit#2483]
### WorldEdit Version

v7.3.0-beta-04+c28ebca

### Platform Version

Paper-446 (MC: 1.20.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

https://pastebin.com/PEU63cmZ

### Expected Behavior

it would be nice if you could use worldedit and commandblock to place schematics on certain coordinates

### Reproduction Steps

cb1. /schematic load test cb2. //pos x,y,z cb3. //paste

*cb = commandblock

all 3 command blocks have the same name (because it is probably necessary for them to use the same instance)

**Comment by octylFractal** [comment]
This is already doable with `//placement world`.
