### ISSUE TITLE
//set only partially filling area.

### ISSUE THREAD

**Issue by PolyframeX** [EngineHub/WorldEdit#2485]
### WorldEdit Version

Fabric-Offical(7.2.15+6463-5ca4dff)

### Platform Version

Fabric 0.15.7

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using //set. Only partial areas will be successfully filled.

![image](https://github.com/EngineHub/WorldEdit/assets/80133652/722e50d8-594e-4108-9e4e-3adcb3fa414c)

### Expected Behavior

The area should be fully filled

### Reproduction Steps

1. Create an area to //set
2. Attempt to //set the area

### Anything Else?

Logs: https://pastebin.com/Lw7QEyWE
This issue apparently is related to the specific chipped block I'm using (chipped:ancient_waxed_oxidized_copper)

**Comment by me4502** [comment]
This issue looks unrelated to worldedit, and is instead caused by the mod Adastra blindly trying to set blocks to powered that cannot be powered upon block update

they should check that blocks can actually be powered before trying to set it
