### ISSUE TITLE
Newest release of world edit is being flagged as a trojan by windows defender

### ISSUE THREAD

**Issue by CRxFT** [EngineHub/WorldEdit#2486]
### WorldEdit Version

7.3.0

### Platform Version

Fabric 0.15.7

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Recent release of world edit is flagged as a trojan by windows defender.

### Expected Behavior

No flags from anti virus software.

### Reproduction Steps

1. ...
2. ...

### Anything Else?

![Screenshot 2024-03-12 084245](https://github.com/EngineHub/WorldEdit/assets/153774731/5038b4e6-9109-43e9-9ca4-2a8095d670f1)

**Comment by me4502** [comment]
As long as you downloaded it from a legitimate source, it's not a virus.

Java programs are very frequently falsely flagged by antivirus programs, and they in general are extremely ineffective for actual Minecraft malware. If it's flagging on your machine, just mark it as a false positive assuming you've obtained it from a legitimate source.

**Comment by CRxFT** [comment]
Thanks for the clarification. On Mar 12, 2024, at 9:07 AM, Maddy Miller ***@***.***> wrote:﻿
As long as you downloaded it from a legitimate source, it's not a virus.
Java programs are very frequently falsely flagged by antivirus programs, and they in general are extremely ineffective for actual Minecraft malware. If it's flagging on your machine, just mark it as a false positive assuming you've obtained it from a legitimate source.

**Comment by craftish37** [comment]
Same thing happened here, not much to worry about, Geyser got the same issue some time ago : https://github.com/GeyserMC/Geyser/issues/3662
![image](https://github.com/EngineHub/WorldEdit/assets/63811617/48c99223-4ca4-48d4-9cc6-3bfb59cadb2a)
