### ISSUE TITLE
Why doesn't the //stack command have an "upforward" direction?

### ISSUE THREAD

**Issue by AnEht** [EngineHub/WorldEdit#2491]
### The Problem

When I was using Worldedit to create an underground passage, I found that I couldn't quickly create slanted up and down passages because the stack command didn't have this option, and I didn't understand how the "block vector in form xyz" was used, nor was it written in the end-user documentation.

### A Solution

Add a document description about the "block vector in form xyz" function and add a direction similar to "upforward" to the stack command.

### Anything Else?

It's also possible that I don't have enough knowledge about Worldedit. If there is any solution, I would appreciate it if you could let me know.

**Comment by wizjany** [comment]
the form is "x,y,z". we're not going to add arbitrary names for every possible set of block vectors (i.e. infinite), which is why you can specify your own.
