### ISSUE TITLE
Redstone dust and other components break on all transmute/duplicate commands

### ISSUE THREAD

**Issue by TheMaydayMan** [EngineHub/WorldEdit#2493]
### WorldEdit Version

7.3.0

### Platform Version

Fabric-Official

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Redstone components that require space beneath themselves to be placed (I assume including other things that need ground) will usually break when performing a //paste, //move etc. They don’t break if there was already ground there, A workaround I have found is to paste twice, but it makes lots of items and does not work for move.

### Expected Behavior

It should place all free floating blocks first, and then all non-free floating blocks, probably ground up could result in the lest bugs. I’m not familiar with how WE is coded so I’m not sure exactly how this would be implemented but something along those lines.

### Reproduction Steps

1. Build something with redstone dust and repeaters.
2. Copy it and paste it. It will be broken.

### Anything Else?

Sorry if the versions aren’t detailed enough, I’d rather give little information that wrong information. If the versions are too limited I can find the detailed ones.

**Comment by octylFractal** [comment]
Are you using Carpet? If so this is an expected outcome, as we have conflicts with their block placement modifications.

**Comment by me4502** [comment]
If you have Carpet installed, it breaks WorldEdit's ability to prevent this.

Ideally Fabric would add an API so that it doesn't get broken
