### ISSUE TITLE
Reload command loses references to WE commands

### ISSUE THREAD

**Issue by shrimpwagon** [EngineHub/WorldEdit#2504]
### WorldEdit Version

Forge-Official(7.2.5-57d5ac9)

### Platform Version

Forge-1.16.5

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Sorry I did lie about the confirmations. Yes, I'm using old version only because I'm getting this to work with Pixelmon (Forge 1.16.5). When running the ```/reload``` command all of the WE commands are lost.

### Expected Behavior

After running ```/reload``` the WE commands should remain.

### Reproduction Steps

1. Just do ```/reload``` command

### Anything Else?

Sorry for submitting issue on older version but I was hoping it can be fixed because of integrating with Pixelmon

**Comment by octylFractal** [comment]
No, we do not support old versions in any way.

**Comment by shrimpwagon** [comment]
@octylFractal Understand. Is there a work-around without having to reload game?

**Comment by octylFractal** [comment]
None I'm aware of.
