### ISSUE TITLE
Problems with blockstates in WorldEdit mod

### ISSUE THREAD

**Issue by NathanaelBlystern** [EngineHub/WorldEdit#2506]
### WorldEdit Version

7.2.15

### Platform Version

Forge 47.2.23, Fabric 0.96.11+1.20.4

### Confirmations

- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When trying to paste/move/stack a structure that contains blocks with the blockstates, they don't work correctly. For example, if you use a debug stick on fences or walls, blockstates will not be copied when using the //paste, //move, //clone, etc. commands.

### Expected Behavior

Blockstates should carry over when using the WorldEdit mod.

### Reproduction Steps

1. //copy structure with blockstates
2. //paste

**Comment by NathanaelBlystern** [comment]
PS: 
![image](https://github.com/EngineHub/WorldEdit/assets/60578987/881ea3de-54d8-4945-8b6b-b3a6c230e456)

**Comment by me4502** [comment]
The MC and WorldEdit versions you've listed are not possible to be used together, so something about your report does not add up.

In general though, block states work fine - so it'll be another mod likely hooking into WorldEdit and breaking things. Your report in general doesn't make sense due to conflicting information though so I can't say more

**Comment by NathanaelBlystern** [comment]
![image](https://github.com/EngineHub/WorldEdit/assets/60578987/9fd31058-0280-4cbf-bfe3-d856433059a0)
![image](https://github.com/EngineHub/WorldEdit/assets/60578987/a20d22e0-4e76-42c4-80f7-8322e91b98cc)

Why do you say I can't use it together?

**Comment by octylFractal** [comment]
You stated "Fabric 0.96.11+1.20.4" as well.

**Comment by octylFractal** [comment]
Regardless, it's not really clear what the exact problem is. It would be best if you could show a picture of what you expect to occur.

**Comment by NathanaelBlystern** [comment]
> Regardless, it's not really clear what the exact problem is. It would be best if you could show a picture of what you expect to occur.

The screenshot shows that I tried to copy the bottom section of the sandstone wall and paste it on top, but when I did this, the walls changed their blockstate and joined the blocks behind. Make a video maybe? Or is this problem really happening only to me?

**Comment by octylFractal** [comment]
Okay, that wasn't clear from just the image. That looks like the expected side-effects turned on by default. If you don't want that, turn off "update" and "validation" in `//perf`.
