### ISSUE TITLE
Compass Navigation Feature Not Working

### ISSUE THREAD

**Issue by kimdro** [EngineHub/WorldEdit#2521]
### WorldEdit Version

7.3.0

### Platform Version

paper-1.20.6-36

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Navigation(teleportation) with compass is not working in paper 1.20.6 server. Player doesn't teleport upon right or left clicking compass. 

### Expected Behavior

Upon right or left clicking with compass on hand, player should teleport to where the player's aim is. 

### Reproduction Steps

1. Create a bukkit server with paper-1.20.6-36.jar
2. Put worldedit 7.3.0 in the `plugins` folder
3. Join the server, right or left click with a compass on the hand. 

### Anything Else?

I am aware that paper 1.20.6 is yet an experimental version, however I thought it would be necessary to report this bug for worldedit's future support for 1.20.6.

**Comment by wizjany** [comment]
can you run `//wand -n` and try clicking?

**Comment by me4502** [comment]
I cannot reproduce this on Paper-36 as specified

**Comment by kimdro** [comment]
> can you run `//wand -n` and try clicking?

No changes

**Comment by kimdro** [comment]
> I cannot reproduce this on Paper-36 as specified

Unfortunately, the issue persists for paper-1.20.6-48. However, the issue seemes to be resolved on 7.3.1-SNAPSHOT.
