### ISSUE TITLE
Crashing dedicated server 1.20.1

### ISSUE THREAD

**Issue by PepGames** [EngineHub/WorldEdit#2526]
### WorldEdit Version

7.2.15

### Platform Version

Forge 47.2.32

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

World Edit is crashing my modded 1.20.1 dedicated server. It runs perfectly fine without World Edit, but once it's added, a crash will occur. I am not sure if there is a conflict with another mod? 

Here's the log: https://mclo.gs/f1djCKZ

### Expected Behavior

The server doesn't crash with World Edit.

### Reproduction Steps

1. ... Try with World Edit - Crash
2. ... Try without World Edit - Success!

### Anything Else?

In the 'confirmations' for submitting this ticket you have a box that says "I am using the most recent minecraft version". 

Well. 1.20.1 is the most recent version that is being supported widely by many mods. So in my mind this counts.

**Comment by PepGames** [comment]
*sigh* I had a feeling you guys would ignore this ticket. So let me say again: 

"1.20.1 is the most recent version that is being supported widely by many mods. So in my mind this counts."

No one is playing 1.20.4
No one is playing 1.20.5
No one is playing 1.20.6

But clearly you guys don't care. Good luck with everything.

**Comment by wizjany** [comment]
this is
1) a duplicate
2) caused by other mods misusing block states, something we have better troubleshooting output for in newer versions and
3) actually tons of people are playing newer versions, the fact that modpacks are behind isn't really our concern.
