### ISSUE TITLE
WorldEdit not recognized by Paper Dedicated Server (ApexMC)

### ISSUE THREAD

**Issue by tiilr** [EngineHub/WorldEdit#2527]
### WorldEdit Version

worldedit-bukkit-7.3.1.jar

### Platform Version

git-Paper-496

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I am using the most recent PAPER release (1.20.4) with GeyserMC and Floodgate to allow Bedrock players to join. I have both tried installing WorldEdit through the Plugin List on ApexMC Hosting and manually installing with my FTP Access through the Filezilla App. I have tried installing WorldEdit a few times, but it is the only plugin that will not be recognized by my server. I do have a section of console at launch that reads:

13.05 02:10:46 [Plugin Installation] Removing plugin spigot/107428
13.05 02:10:46 [Plugin Installation] Removing files for plugin spigot/107428
13.05 02:10:46 [Plugin Installation] Removed file worldedit.sk
13.05 02:10:46 [Plugin Installation] Plugin spigot/107428 removed.

This looks like it has something to do with why WorldEdit will not work, but I've never had this problem before and cannot seem to figure it out on my own. 

Any support is appreciated, thank you in advance!

### Expected Behavior

Mod to load through Plugin Folder.

### Reproduction Steps

1. Access FTP Backend of server using FileZilla 3rd party app.
2. Manually install "worldedit-bukkit-7.3.1.jar" to the server's plugins folder.
3. Try using WorldEdit in-game
4. Server doesn't recognize any commands or what WorldEdit is.

**Comment by me4502** [comment]
The section of your logs is entirely unrelated to worldedit at all. Provide your actual full log file, there's nothing we can say or do without it

**Comment by tiilr** [comment]
> The section of your logs is entirely unrelated to worldedit at all. Provide your actual full log file, there's nothing we can say or do without it

Thanks for the quick response. I'm assuming you mean my full launch console? Check the pastebin link [here](https://github.com/EngineHub/WorldEdit/issues).

**Comment by me4502** [comment]
Your logs make no mention of worldedit at all, even if the jar file was corrupt in some way it'd still list the file as invalid. You do not have worldedit installed.

As you're using a host, if it has a plugin install system you'd likely have to ask them for help as the issue would be with that incorrectly listing it as installed when it's not

**Comment by tiilr** [comment]
>As you're using a host, if it has a plugin install system you'd likely have to ask them for help as the issue would be with that incorrectly listing it as installed when it's not

Interesting, other .jar files have allowed me to manually install them using FTP Access, I just assumed WE would work, too. I'll reach out to Apex support in this case. Sorry for wasting your time, thanks for the assist!
