### ISSUE TITLE
worldedit.log is not generated

### ISSUE THREAD

**Issue by hongyulai** [EngineHub/WorldEdit#2530]
### WorldEdit Version

7.3.1

### Platform Version

paper-1.20.4-496

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The generation status of worldedit.log is set to true, but it is not generated

### Expected Behavior

When I remove the block, a worldedit.log should be generated and record the information about the block I removed.

### Reproduction Steps

1.Select the range first
2.//replace minecraft:chest air
3.Find worldedit.log

### Anything Else?

No

**Comment by wizjany** [comment]
Duplicate of #1845
