### ISSUE TITLE
No support for 1.20.6

### ISSUE THREAD

**Issue by Paderman** [EngineHub/WorldEdit#2531]
### WorldEdit Version

7.3.1

### Platform Version

Bukkit 1.20.6

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WorldEdit 7.3.1 not working with Bukkit 1.20.6.

### Expected Behavior

** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

[Server thread/WARN]: CraftBukkit is not a supported Bukkit platform. Please use a supported platform, such as Paper.
[Server thread/INFO]: [WorldEdit] ====================================================
[Server thread/INFO]: [WorldEdit]  WorldEdit works better if you use Paper 
[Server thread/INFO]: [WorldEdit]  as your server software. 
[Server thread/INFO]: [WorldEdit]   
[Server thread/INFO]: [WorldEdit]  Paper offers significant performance improvements,
[Server thread/INFO]: [WorldEdit]  bug fixes, security enhancements and optional
[Server thread/INFO]: [WorldEdit]  features for server owners to enhance their server.
[Server thread/INFO]: [WorldEdit]   
[Server thread/INFO]: [WorldEdit]  Paper includes Timings v2, which is significantly
[Server thread/INFO]: [WorldEdit]  better at diagnosing lag problems over v1.
[Server thread/INFO]: [WorldEdit]   
[Server thread/INFO]: [WorldEdit]  All of your plugins should still work, and the
[Server thread/INFO]: [WorldEdit]  Paper community will gladly help you fix any issues.
[Server thread/INFO]: [WorldEdit]   
[Server thread/INFO]: [WorldEdit]  Join the Paper Community @ https://papermc.io
[Server thread/INFO]: [WorldEdit] ====================================================

### Reproduction Steps

See above.

Can't use walls and many more in game. Plugin is loaded, but not anymore.

Installed openjdk 22 on Debian 12.5 (Trixi)

**Infos:**

_This server is running CraftBukkit version 4149-Bukkit-4e7d749 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT)_

_openjdk 22.0.1 2024-04-16
OpenJDK Runtime Environment (build 22.0.1+8-Debian-1)
OpenJDK 64-Bit Server VM (build 22.0.1+8-Debian-1, mixed mode, sharing)_

**Comment by me4502** [comment]
> CraftBukkit is not a supported Bukkit platform. Please use a supported platform, such as Paper.

This isn't about 1.20.6, this is about using a non-published development jar rather than production server software. You should be using Paper or Spigot, CraftBukkit has not existed for a decade.
