### ISSUE TITLE
Updating Causes Errors

### ISSUE THREAD

**Issue by Epik-B0mber** [EngineHub/WorldEdit#2539]
### WorldEdit Version

7.3.1

### Platform Version

Ketting-1.3.7

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [ ] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [ ] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Greetings. I must disclaim that I lied on the confirmations, and know I'm in the bounds of no support, as I run a Ketting server, but I still wanted to publish this in-case this could help any future developments for the nice people on supported platforms. Thank you.

Anyway I was running V7.2.19 of WE for some time and went to update to the latest for 1.20.1 (7.3.1). Everything works up until issuing commands, that's about it.
If anything could be done, amazing! Otherwise, I won't die, my goal is just to help out maybe, not complain about not getting my way or something. **Thanks in advance** to anyone who reads this, I appreciate it and hope to not be a bother. :-)

[error.log](https://github.com/EngineHub/WorldEdit/files/15439384/error.log)

### Expected Behavior

Utilizing any // command brings forth the given error.

### Reproduction Steps

1. Utilize the wand or run any command
2. Error

### Anything Else?

I just hope this helps fix any future issues or whatever else. I also got J21 to make sure it worked but still had the same results. Thanks again for this golden plugin, it's always been there for me!!! :-)

**Comment by wizjany** [comment]
dont lie on the template
