### ISSUE TITLE
I am an administrator, why am I also restricted?

### ISSUE THREAD

**Issue by Leoparking** [EngineHub/WorldEdit#2547]
### The Problem

I have set in config.yml that ordinary players can only affect 900 blocks by default, while OP should not be restricted
limits:
    max-blocks-changed:
        default: 900
        maximum: -1
However, when an OP uses //set <block> command, they still receive a message saying "Change limit of 900 has been reached"
Even if they have all permissions starting with "worldedit."
![I(N%%KCFLREQ0IJJP`RLO8F_tmb](https://github.com/EngineHub/WorldEdit/assets/141799770/5924c12a-d0a7-4fd4-83ba-48fa2c82ced8)
<img width="354" alt="image" src="https://github.com/EngineHub/WorldEdit/assets/141799770/9822efa1-aef8-4f5e-ab06-775978a930d9">

**Reproduction Steps**
0.Set max-blocks-changed in config.yml to a relatively small value, such as 900
<img width="266" alt="image" src="https://github.com/EngineHub/WorldEdit/assets/141799770/c77ed981-8def-4ee2-bcc6-e09aab2065a9">
1. set a player as OP
2. Ask him to use //pos1,//pos2,//set to fill a large area
3. He will find...
<img width="322" alt="image" src="https://github.com/EngineHub/WorldEdit/assets/141799770/7471ad44-7362-48bc-935f-f2a2363328a4">

### A Solution

Limits should only work for regular players, and OP should not be limited in //set <block> quantity
You can set an "OP judgment"

### Alternatives

Set the default: of max-blocks-changed to infinite (-1), but this will allow everyone, including regular players, to use//setto change the area without restrictions

### Anything Else?

Can you stop being so lazy and just turn off feedback without saying anything? What does that mean
https://github.com/EngineHub/WorldEdit/issues/2545
This is the question I raised yesterday, you made the user very sad💔qwq

**Comment by me4502** [comment]
stop spamming this everywhere. you have already been answered multiple times, but refuse to accept it for some reason. just because you want the answer to be different (even though you won't explain why), doesn't mean it will be.
