### ISSUE TITLE
This file is outside the allowed root directory

### ISSUE THREAD

**Issue by CNSYGZS** [EngineHub/WorldEdit#2548]
### WorldEdit Version

worldedit-bukkit-7.3.3.jar

### Platform Version

leaves-1.20.4.jar

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Prompt for file parsing error when importing schema project: The file is outside the allowed root directory
I have tried deploying a server in a new project that does not contain any other plugins and running it to join. I am also unable to paste my schematic on that server, and all tests have not reported any errors on the console, so I am unable to provide error logs. The plugin only prompts the file [schematic name] on the client side. Parsing error: The path is outside the allowed root directory
I am sure that my schematic file is placed in the correct file path plugins \ WorldEdit \ schematics, and I can also list my schematic list by executing the//schematic list command on my server, but it cannot be loaded into the clipboard

### Expected Behavior

My first step is to execute//schematic list to list the loaded schematic files for inspection
The second part is to load the schematic file I need with the name zc001.schem, so I executed//schematic load zc001
I also tried to execute/chem load zc001.schem

### Reproduction Steps

1. //schematic list
2. //schematic load zc001
3. //schematic load zc001.schem

### Anything Else?

I have reviewed the tutorials and official documents, but it is difficult for me to find the same error message in the tutorial content. Perhaps due to my lack of experience, I can only come here to seek help

**Comment by me4502** [comment]
this just means you’re using a symlink for your schematics folder, without enabling allow symlinks in the config. This isn’t a bug, it’s a security precaution

**Comment by CNSYGZS** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by CNSYGZS** [comment]
> 这仅意味着您正在为 Schematics 文件夹使用符号链接，而没有在配置中启用允许符号链接。这不是错误，而是安全预防措施

Oh, I think it must have been yesterday when I was too tired. According to your prompt, I modified the allow symbolic links and successfully used the schematic I needed. Thank you very much for the answer. This is my first time using GitHub. Thank you again for your clarification
