### ISSUE TITLE
Lodestone Compass Crash

### ISSUE THREAD

**Issue by DerpzGames** [EngineHub/WorldEdit#2555]
### WorldEdit Version

7.3.4

### Platform Version

Fabric (Presumably 0.5.11, the server host doesn't say)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Attempting to use a compass on a Lodestone causes a crash.

### Expected Behavior

It shouldn't crash.

### Reproduction Steps

1. Use a Compass on a Lodestone
2. Watch the magic happen.

**Comment by wizjany** [comment]
no crash log, no repro.
