### ISSUE TITLE
Compatibility with mini-scaled

### ISSUE THREAD

**Issue by ninjaguardian** [EngineHub/WorldEdit#2560]
### The Problem

Can't use worldedit on [mini-scaled](https://modrinth.com/mod/miniscaled) block while in overworld
![2024-06-25_13 15 57](https://github.com/EngineHub/WorldEdit/assets/110734253/485a373a-53e0-4013-ba5d-a95eb40d49da)
running //set dirt does nothing

### A Solution

Maybe make it access the block and set it inside of there

**Comment by wizjany** [comment]
this doesn't seem like a feature request and isn't on the current MC version.
worldedit operates on a minecraft world using minecraft coordinates. that mod appears to be rendering *some other region* into the current world. if you want to edit that other region you'll need to directly select it and manipulate it normally. if the mod doesn't allow for that there's nothing we can do about it.

**Comment by ninjaguardian** [comment]
ok. but i think the reason this happens is because when you click the mini-block in the overworld, it select the corresponding block in the mini world. When you run the command, it doesn't set the block in the mini world even though that is the dimension it is in.

**Comment by wizjany** [comment]
we can't do anything if the mod is redirecting clicks either. use //hpos, //pos with coords, select the area around it, etc if you want to select the "portal block".

**Comment by octylFractal** [comment]
WorldEdit doesn't know that the target click is in a different world, and actually selects in the overworld. I'm not sure why CUI is misrepresenting that though, since the selection is actually in the world the player is in.

**Comment by octylFractal** [comment]
Oh, right, CUI protocol doesn't come with a world -- so it is actually rendered in _both_ places: ![cui rendering twice](https://url.octyl.net/qv690fufxwewq8a2fa7b)

**Comment by octylFractal** [comment]
I think this is a bug with our selection wand. It uses the player world instead of the interact event world. I will take a look and see if it can be fixed; but if so it will only be for newer versions and not 1.20.4.

**Comment by ninjaguardian** [comment]
The CUI is correct. In the over world you can change the world inside of the mini block. The commands just don't change it.
