### ISSUE TITLE
Add a command to offset the selection to the target position at once, this command can accept the x,y,z offset

### ISSUE THREAD

**Issue by mmmpipi** [EngineHub/WorldEdit#2565]
### The Problem

I'm using worldedit to copy special entity types to special coordinates.
Unfortunately, this requires a one-time move to the target location.
If you use the //move command three times, you will lose the entity after the first move
e.g:
Move the Create super glue entity to the valkyrien skie's physical structure

### A Solution

Add a command to offset the selection to the target position at once, this command can accept the x,y,z offset

**Comment by me4502** [comment]
you can use the `//move -s` flag to move the selection alongside the move, or you can use the `//shift` command to shift a selection

**Comment by mmmpipi** [comment]
> 您可以使用标志将所选内容与移动一起移动，也可以使用命令来移动所选内容`//move -s``//shift`

I mean move the selection x,y,z at the same time, instead of moving x,y,z three times respectively, although this looks the same

**Comment by mmmpipi** [comment]
> 您可以使用标志将所选内容与移动一起移动，也可以使用命令来移动所选内容`//move -s``//shift`

What I mean by that is to move the selection and the content x,y,z at the same time, instead of moving x,y,z three times respectively, although this looks the same

**Comment by octylFractal** [comment]
The `//move` command also comes with a `distance` parameter, if that's what you're looking for? https://worldedit.enginehub.org/en/latest/usage/regions/regionops/#moving

**Comment by mmmpipi** [comment]
> 该命令还带有一个参数，如果这就是您要查找的？https://worldedit.enginehub.org/en/latest/usage/regions/regionops/#moving`//move``distance`

Sorry,my English isn't very well,if use //move, i should move it three times,it will be stay in a unknow place,so i want move it to another place by once

**Comment by mmmpipi** [comment]
> > 该命令还带有一个参数，如果这就是您要查找的？[https://worldedit.enginehub.org/en/latest/usage/regions/regionops/#moving`//move``distance`](https://worldedit.enginehub.org/en/latest/usage/regions/regionops/#moving%60//move%60%60distance%60)
> 
> Sorry,my English isn't very well,if use //move, i should move it three times,it will be stay in a unknow place,so i want move it to another place by once



> The `//move` command also comes with a `distance` parameter, if that's what you're looking for? https://worldedit.enginehub.org/en/latest/usage/regions/regionops/#moving

I know your means ,use //move 188 up -es ,but that not i want

**Comment by octylFractal** [comment]
I'm not really sure what you're asking then.

**Comment by mmmpipi** [comment]
> 那我真的不确定你在问什么。

I want a command,it Equal to a //move x east //move y up //move z south ,
but it need a cache space 
![Sprite-0001](https://github.com/EngineHub/WorldEdit/assets/153883613/095a60d7-7008-4a85-bff2-2bb3b97f46d3)

**Comment by mmmpipi** [comment]
> > 那我真的不确定你在问什么。
> 
> I want a command,it Equal to a //move x east //move y up //move z south , but it need a cache space ![Sprite-0001](https://private-user-images.githubusercontent.com/153883613/345327860-095a60d7-7008-4a85-bff2-2bb3b97f46d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTI5NjgsIm5iZiI6MTcxOTk5MjY2OCwicGF0aCI6Ii8xNTM4ODM2MTMvMzQ1MzI3ODYwLTA5NWE2MGQ3LTcwMDgtNGE4NS1iZmYyLTJiYjNiOTdmNDZkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNzQ0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTU3MjY4NjA3Njg1ZjI5MThjY2Q2YWIyODExMjFkZGIyZDNjMDNjNWQyOTdjZWJhMjcwZTJjYzY3MjgyYTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ir3g3cShcyD1l5Y08eR5QAzDGyMTo3AvGuD4rZDLBX8)

The move's peoblem is it need a cache space to move ,because it ,something will broken

**Comment by octylFractal** [comment]
`//move` also takes `x,y,z` if you want, as the offset. See `//help move`.

**Comment by mmmpipi** [comment]
> `//move` also takes `x,y,z` if you want, as the offset. See `//help move`.

Sorry,i cant found,can you give me an example?
![2024-07-03_15 58 53](https://github.com/EngineHub/WorldEdit/assets/153883613/faef4d27-d5b1-44a3-a80e-b33b9d98f866)
