### ISSUE TITLE
1.20.1 Forge  - Cannot load into any world, probably a mod conflict but need help

### ISSUE THREAD

**Issue by katubug** [EngineHub/WorldEdit#2574]
### WorldEdit Version

7.2.15

### Platform Version

Forge 47.3.1

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I attempt to load a singleplayer save with WorldEdit in the mod folder, it loads quickly to 100% and then stays there indefinitely, and I have to force close Minecraft through Task Manager. This issue was originally occuring with my sibling, but now it seems to happen for me, too. It wasn't always the case, but I can not figure out what changed.

Here is my latest.log: https://gist.github.com/katubug/9d3555b3bde17db08c58cbbfff1af8f0

### Expected Behavior

I expect the world to load in.

### Reproduction Steps

1. Attempt to load into a new or existing save

### Anything Else?

I am hoping that y'all can offer me some insight as to what might be the issue. I am fairly confident it's a mod conflict, but I just do not have it in me to do a binary search lately. Any help is appreciated. Thank you.

**Comment by wizjany** [comment]
prob same as #2488, #2522, etc

**Comment by katubug** [comment]
Thank you for the lead! It'll help having an idea where to start. Sorry for the trouble!
