### ISSUE TITLE
//rotate and //flip don't modify block data correctly

### ISSUE THREAD

**Issue by LoliColleen** [EngineHub/WorldEdit#2575]
### WorldEdit Version

Bukkit-Official(7.3.4+6823-6263244)

### Platform Version

Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

//rotate and //flip command can make the block data of the clipboard broken. (When the neighbour block update is DISBALED)
For example, you can copy some rails, then do //rotate 90 and //paste. You can find that the rails are not rotated correctly.
This bug affects "rail", "cobblestone_wall" and so on. (Excluding fences, doors, trapdoors and ... fine i haven't tested all the blocks)
The walls blocks will even be invisible because their block data is broken.

### Expected Behavior

The blocks like rails and cobblestone walls should be correctly rotated or flipped

### Reproduction Steps

1. Do "//perf neighbors off"
2. Select an area with rails and cobblestone walls 
3. Do "//copy"
4. Do "//rotate 90" or "//flip"
5. Do "//paste"

**Comment by LoliColleen** [comment]
Wall blocks will lose Directional data after rotating. But they still have their Wall data

**Comment by brickmonster** [comment]
I've been meaning to report this exact issue.

Same repro steps as OP.
* 7.3.1 on Paper 1.20.4 succeeds
* 7.3.2 on Paper 1.20.4 fails
* 7.3.4 on Paper 1.20.4 fails
* 7.3.1 on Paper 1.20.6 succeeds
* 7.3.2 on Paper 1.20.6 fails
* 7.3.4 on Paper 1.20.6 fails
* 7.3.1 on Paper 1.21 is unsupported
* 7.3.2 on Paper 1.21 is unsupported
* 7.3.4 on Paper 1.21 fails
* FAWE on Paper 1.21 succeeds (but they have updates permanently off, so only a temporary solution)

**Comment by FakkaJohan** [comment]
I have this same issue. I hope it gets fixed soon because copying, flipping and rotating walls properly is essential for me.
