### ISSUE TITLE
Editing on unsupported versions is disabled.

### ISSUE THREAD

**Issue by SneezyOfficial** [EngineHub/WorldEdit#2578]
### WorldEdit Version

7.2.4

### Platform Version

Craftbukkit 1.21

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hello! I hope you're doing good.

Yesterday evening i opened an minecraft server through Kaashosting. As the description says i am running Craftbukkit 1.21. I installed the World Edit plugin (latest version compatible with 1.21) and for some reason the plugin says that my version is unsupported. 

Sorry voor being a noob. First time posting help on a forum :)

Thanks in advance!

### Expected Behavior

WorldEdit running

### Reproduction Steps

1. Opened minecraft craftbukkit server version 1.21
2. Installed WorldEdit 7.2.4
3. Plugin says that edditing is disabled on unsupported versions

**Comment by wizjany** [comment]
https://madelinemiller.dev/blog/stop-using-craftbukkit/
