### ISSUE TITLE
Allow pairing cardinal direction with up/down when stacking

### ISSUE THREAD

**Issue by MegaMinerDL** [EngineHub/WorldEdit#2587]
### The Problem

You can stack a block by typing e.g. north-west, or facing diagonally.

You cannot stack a block by typing e.g. north-west-up (diagonally up).

![github issue](https://github.com/user-attachments/assets/ab36d593-6368-450c-b37c-1434ff24b67f)

### A Solution

Allow pairing cardinal direction with up/down when stacking for extra vertical option.

### Alternatives

.//line may be inconvenient especially when the end-point of a line is unknown, only the start point.

Manual placing and copy pasting takes longer.

**Comment by wizjany** [comment]
pass a vector directly. see //help stack.
