### ISSUE TITLE
//replace functionality

### ISSUE THREAD

**Issue by NikolaiStoilkov** [EngineHub/WorldEdit#2589]
### The Problem

what is the current state of the project and what must be done? I tried to use this plugin on my server and i saw a lot of commands its not supported for latest version.  (for example //replace and many others.) .

### A Solution

Where do you manage your tasks ?

**Comment by octylFractal** [comment]
You are likely using CraftBukkit or the wrong version of something. Please check and if you still need help ask in the Discord.
