### ISSUE TITLE
Crash when selectin position with wand

### ISSUE THREAD

**Issue by Foabi** [EngineHub/WorldEdit#2594]
### WorldEdit Version

7.3.5

### Platform Version

neoforge-21.0.148

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i go into singleplayer/multiplayer, when i get a wand i select the first position and when i want to selected the second it just crashes.
"
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'net.neoforged.neoforge.common.ToolAction net.neoforged.neoforge.event.level.BlockEvent$BlockToolModificationEvent.getToolAction()'
"
### Expected Behavior

Well, to not crash and be able to do something with worldedit.

### Reproduction Steps

1. Left click on a block
2. Right click on another and it crashes

**Comment by octylFractal** [comment]
Please provide the crash report.

**Comment by Foabi** [comment]
> Please provide the crash report.

updated post, or you want the full crash

**Comment by octylFractal** [comment]
The full crash report is preferred, as this isn't really enough information to narrow down the problem.

**Comment by Foabi** [comment]
Hmm, i found out that another mod causes the crash "glitchcore" since i needed it for biomes o plenty
