### ISSUE TITLE
reload problem

### ISSUE THREAD

**Issue by Batman2741** [EngineHub/WorldEdit#2595]
### WorldEdit Version

Forge-Official(7.2.5+57d5ac9)

### Platform Version

forge 1.16.5

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when i do /reload or add a datapack world edit stops until next server restart

### Expected Behavior

world edit still working

### Reproduction Steps

1.load the mod
2. load in and do /reload
3.try to use world edit

**Comment by me4502** [comment]
Forge lacked adequate API to actually deal with this back in 1.16. either way, old versions are not supported, as per the issue template.
