### ISSUE TITLE
worldedit increased memory usage by 1GB

### ISSUE THREAD

**Issue by chengzi-sc** [EngineHub/WorldEdit#2602]
### WorldEdit Version

7.2.15 + 6463-5ca4dff

### Platform Version

Forge 47.2.23

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

After installing WorldEdit, the game's memory usage increased from around 1.4GB to 2.4GB. After removing the mod, it returned to normal.
![image](https://github.com/user-attachments/assets/4f24b8f8-e1a2-4b57-9fee-2240e13fa9e5)
![image](https://github.com/user-attachments/assets/e3469e60-ed97-4046-9522-6fbac9d52c4b)

### Expected Behavior

-

### Reproduction Steps

1. install worldedit

**Comment by octylFractal** [comment]
This is related to having mods with a lot of blockstates, which was partially improved already. But is currently unavoidable without a significant rewrite. Since you're not using latest I'm closing this as we've already made improvements here.
