### ISSUE TITLE
Worldedit 7.3.6 getting flagged as virus

### ISSUE THREAD

**Issue by tilidrop** [EngineHub/WorldEdit#2604]
### WorldEdit Version

7.3.6

### Platform Version

Spigot 1.21.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hello everybody

im trying to download the newest worldedit version but it is getting flagged always as virus in my Brave Browser and also in Edge and Chrome. why is this? im not using any extern virus program.

### Expected Behavior

Im expecting, that i can download the programm and use it on my spigot server

### Reproduction Steps

1. ...open Brave
2. start the newest download of worldedit
3. Programm gets detected from the browser as virus.
4. Programm never gets in my downloads libary

**Comment by me4502** [comment]
If you’re downloading it from an official site, it does not contain a virus. It’s therefore a false positive.

There’s nothing we can do about your computer flagging it, you’d have to mark it as safe on your end. This isn’t anything we have control over
