### ISSUE TITLE
move to modrinth.

### ISSUE THREAD

**Issue by bombaatomowa123456** [EngineHub/WorldEdit#2605]
### The Problem

you are not using modrinth for your mod being downloaded

### A Solution

upload it to modrinth

### Alternatives

anything thats legit and isnt curseforge
the reason this is worse is because modrinth is the best mod website.

### Anything Else?

please just use modrinth.

**Comment by aurorasmiles** [comment]
https://modrinth.com/plugin/worldedit
?
