### ISSUE TITLE
cannot remove worldedit from server

### ISSUE THREAD

**Issue by YLlywelyn** [EngineHub/WorldEdit#2612]
### WorldEdit Version

7.3.6

### Platform Version

spigot

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have removed the worldedit jar from the plugins folder and deleted everything related to worldedit however I still cannot use the wooden axe.  Worldedit has been removed because the commands are gone so why is the selection wand still there?

### Expected Behavior

I expect that when I remove the plugin it is removed, in it's entirety.

### Reproduction Steps

1. have spigot server
2. install worldedit
3. remove worldedit
4. wooden axe is still the selection wand

**Comment by wizjany** [comment]
either you didn't actually remove worldedit, or something else is just providing a selection wand.
