### ISSUE TITLE
When I went through a nether portal, my lodestone compass disappeared.

### ISSUE THREAD

**Issue by FlashDragons** [EngineHub/WorldEdit#2614]
### WorldEdit Version

worldedit-mod-7.3.6

### Platform Version

fabric 1.21

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I went through a nether portal, my lodestone compass disappeared.

### Expected Behavior

Fix this bug.

### Reproduction Steps

There is a bug in 1.21 fabric. When you create a lodestone compass in the nether, you cannot get the corresponding achievement.
You will also be teleported to a place not far ahead when you create it, or the red font in the lower left corner will show "No valid space found in front of you".
At this time, if you put the lodestone compass in the inventory and enter the portal, you will find that the compass is gone after you go to the overworld. There will be no problem if you put it in the backpack. There will be no problem if you put the lodestone compass in the inventory and enter the portal again.
The same effect will occur when you create a lodestone compass in the overworld and enter the nether.

### Anything Else?

I checked dozens of mods this morning, and the bug disappeared after disabling this mod; at the same time, I created a 1.21 fabric 
that only contains fabric api and this mod, and the bug reappeared, and it was determined to be a bug in this mod.

**Comment by wizjany** [comment]
the teleporting (and error about no free space) is just standard navigation wand behavior. you can change the item or unbind the tool if you don't want that.

the lack of achievement and disappearing through the portal have nothing to do with worldedit.
