### ISSUE TITLE
Allow non-int thickness param for //line and //curve

### ISSUE THREAD

**Issue by wizjany** [EngineHub/WorldEdit#2622]
### The Problem

The original implementation (and the existing method in EditSession) took a double param for thickness. In 2014 when migrating commands to "Intake", the param for the commands was changed to an int.

### A Solution

Change the param back to a double.

**Comment by me4502** [comment]
Implemented in https://github.com/EngineHub/WorldEdit/commit/4e7abf56dad67a162a7d86a69b3077e793e3ba9b
