### ISSUE TITLE
Make it possible for #surface to consider different block types as exposed.

### ISSUE THREAD

**Issue by CMarcoo** [EngineHub/WorldEdit#2624]
### The Problem

Suppose you have a field with short grass, tall grass, poppies, dandelions, bushes, etc...
using combined mask replace command, e.g., //replace "#surface !short_grass,tall_grass,poppies,dandelions" stone.
We do not get the blocks below the grass, poppies, dandelions to be considered as surface, therefore they do not get replaced by stone (undesired result).

### A Solution

It would be ideal to have a single command able to indicate which blocks should be skipped by the #surface mask.
This would mean being able to indicate which blocks to go "below" if they represent the surface.

**Comment by wizjany** [comment]
duplicates #2056

internally, this is already doable via api, and the surface mask is essentially an example usage of that api, but adding more complex parsers for multiple blocks, directions, and distances (which is doable via the api) is harder to write with our current mask parsing framework. either way i don't expect the surface mask itself will change, there will just be some nearby/adjacent mask to craft your own.
