### ISSUE TITLE
1.20.1 Quilt: Any version causes very long loading hang.

### ISSUE THREAD

**Issue by jacklollz2** [EngineHub/WorldEdit#2626]
### WorldEdit Version

worldedit-7.2.18-SNAPSHOT6591-9b8eb2c.i0:0/:7.2.18-SNAPSHOT

### Platform Version

Quit 0.26.4-beta.7

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

1.20.1 isn't the latest but it's the latest available for most mods, like Create. I am restricted by 90% of mods.

For all builds, I cannot get 1.20.1 functioning without a very long hang when loading the world.

### Expected Behavior

Loading the world functions normally.

### Reproduction Steps

1. Open the game.
2. Load a world.

**Comment by octylFractal** [comment]
We don't care about other mods, we won't be backporting. Additionally, we never supported Quilt, so any issues with it are not going to be solved either.
