### ISSUE TITLE
Problem with copy and paste

### ISSUE THREAD

**Issue by allaweiq** [EngineHub/WorldEdit#2629]
### WorldEdit Version

1.20.1

### Platform Version

Forge

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I copy anything it says there is an error
![pr](https://github.com/user-attachments/assets/259f645a-6549-4140-8401-62964e214876)

### Expected Behavior

It was working normally on previous updates.

### Reproduction Steps

1. ...I don't know
2. ...I don't know

### Anything Else?

I don't know

**Comment by octylFractal** [comment]
There isn't even an error in your image?
