### ISSUE TITLE
Doesn't remember block metadata while editing.

### ISSUE THREAD

**Issue by Zosya1226** [EngineHub/WorldEdit#2632]
### WorldEdit Version

7.3.6

### Platform Version

paper 1.21.1-52

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

![2024-09-24_07 48 13](https://github.com/user-attachments/assets/c04712bd-485c-403a-bb58-1acd5c48b6ed)

I don't know how to avoid this block destruction when i //move //cut + paste //copy + paste
Sometime cross type of redstone becomes a dot. 

### Expected Behavior

All of redstone components are moving with blocks exactly as it copied or moved from "home" position. I use 7.2.9 WE on my 1.17.1 bukkit server, no common issues.

### Reproduction Steps

1. //copy + paste
2. //cut + paste
3. //move
any plot of redstone

**Comment by octylFractal** [comment]
This is almost certainly #2516
