### ISSUE TITLE
[CRASH] Editing a large region

### ISSUE THREAD

**Issue by AlexMinecraft2012** [EngineHub/WorldEdit#2633]
### WorldEdit Version

7.3.6

### Platform Version

Paper 1.21.1-98-master@9b1ee0d

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Editing a very large region crashes the server.

### Expected Behavior

It will say "Operation completed" and edit the region.

### Reproduction Steps

1. Type //wand.
2. Select a very large region (20000000+ blocks).
3. Type //set 0.

### Anything Else?

Server logs after the crash: [https://mclo.gs/y9oGXPc](https://mclo.gs/y9oGXPc)

**Comment by me4502** [comment]
this looks like an issue with your server, not WorldEdit. it's stalled because you tried to edit a block in a chunk that the server is failing to generate. the same would happen if you just walked there, or if anything caused it to load.

**Comment by AlexMinecraft2012** [comment]
100 blocks is fine.

**Comment by me4502** [comment]
yes, because your 100 block selection is not within the chunk that your server is failing to generate. your logs indicate this is a server issue, not a worldedit one

**Comment by wizjany** [comment]
this is not 20 million blocks but about 90 trillion. also your server was lagging just trying to teleport you to one corner of your selection. it's clearly not going to be able to handle generating and loading 1.5 billion chunks in one go.
