### ISSUE TITLE
Walls don't keep their axes blockstate when copied / flipped / pasted

### ISSUE THREAD

**Issue by xAdrini** [EngineHub/WorldEdit#2639]
### WorldEdit Version

7.3.6

### Platform Version

Fabric 0.16.5-1.21

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If you flip and paste any kind of wall in the latest world edit version 7.3.6 for 1.21, it won't keep its modification of the 4 directions. Only the "up" and "waterlogged" block states are copied.
![Bild_2024-10-04_234436595](https://github.com/user-attachments/assets/a2e5a111-183e-4a89-8398-3b83b71d1452)

My Settings: //perf - everything set to off 

### Expected Behavior

As in previous versions, the specific axes ´/ blockstates should be mirrored when flipping walls.
![Bild_2024-10-04_234741598](https://github.com/user-attachments/assets/47649948-0d73-4d87-ac0b-262d70b80c58)

### Reproduction Steps

1. Modify any axis of any type of wall using the debug stick - disable blockupdates - //perf off
2. Select the wall with the wand
3. copy and flip
4. paste - now only "up" and "waterlogged" are carried along

### Anything Else?

I have tested this with and without axioms blockupdate enabled and disabled. I tried to replicate the bug with stairs, fences, slabs etc, but this bug only occurs with walls.

**Comment by wizjany** [comment]
Duplicates #2575
