### ISSUE TITLE
worldedit inside region

### ISSUE THREAD

**Issue by DrDoofenshmirtz00** [EngineHub/WorldEdit#2641]
### The Problem

i want to give players the opportunity to use some world edit functions but only when they are inside plots they own in towny. 

### A Solution

Implement an option in config to let users only use world edit inside their own claim in towny. Also add permission for admins to bypass this.

### Anything Else?

Please consider adding this feature. i am sure a lot of other people would also like this.

**Comment by octylFractal** [comment]
We don't integrate into other plugins. This would be up to Towny or a third-party plugin.

Additionally, we do not recommend allowing users to use WorldEdit as it is not designed in a secure way beyond permissions.
