### ISSUE TITLE
"editing of unsupported versions is disabled"

### ISSUE THREAD

**Issue by Entoniel** [EngineHub/WorldEdit#2645]
### WorldEdit Version

7.3.7

### Platform Version

Spigot 1.21.1 (4343)

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

My WordEditor stopped working. Before, everything was ok, but the last few days when trying to use it, it says "editing of unsupported versions is disabled". Although I have server version 1.21.1, Spigot kernel, WorldEdit version 7.3.7 (Bukkit for 1.20.2-1.21.1)

What am I doing wrong?!

[Image](https://github.com/user-attachments/assets/e02c0047-f54c-4c65-8692-7246046d830c)

### Expected Behavior

It should work, insert products from the schematic or replace blocks with the SET command, but it does not

### Reproduction Steps

1. instal plugin
2. reload serwer
3. use command //wand to get axe
4. use axe to 2 point (3 bloks)
5. try tu use command //set stone
6. get error messeage

### Anything Else?

![Image](https://github.com/user-attachments/assets/13f10d9f-af91-4b06-a06e-1bd505d995a3)
There is all plugins that iunstalled now

**Comment by octylFractal** [comment]
Already fixed by #2644
