### ISSUE TITLE
crashing on startup with my modpack

### ISSUE THREAD

**Issue by baconbaymax** [EngineHub/WorldEdit#2648]
### WorldEdit Version

WorldEdit 7.2.15 (Forge/Fabric for MC 1.20/1.20.1)

### Platform Version

Modrith app Forgeloader version 47.3.7 game version 1.20.1 

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

darkrolls modpack crashes on startup with world edit installed with 0 crash report i can provide logs if needed though 

### Expected Behavior

it to open

### Reproduction Steps

1. ... download darkrolls modpack on modrith 
2. ... run it with world edit for its version

**Comment by octylFractal** [comment]
As indicated, we don't support old versions.
