### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by KITE2459** [EngineHub/WorldEdit#2649]
### WorldEdit Version

1.21.3-7.3.9 build #6950

### Platform Version

fabric 0.16.9

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Something Permission condition check error?
![Image](https://github.com/user-attachments/assets/71de26f7-ab2b-497d-b5e2-7ad23c340521)

### Expected Behavior

server is booting properly
but if player trying to connect
they are crashed

### Reproduction Steps

1. ...
2. ...

### Anything Else?

always thanks to this mod and devs :)

**Comment by octylFractal** [comment]
That looks like an issue in the lucko perms api, which we don't bundle. You need to update it or file an issue with them.

**Comment by TanCY1** [comment]
I have the same problem, its because of the do a barrel roll mod
