### ISSUE TITLE
Additional ## command arguments

### ISSUE THREAD

**Issue by MegaMinerDL** [EngineHub/WorldEdit#2656]
### The Problem

E.g. I had to replace all glass blocks in a build, but had to do each glass type individually.

### A Solution

It'd be useful if commands in the format of _//replace ##terracottas_ additionally supported:

##glass
##panes
##stripped
##concrete

### Alternatives

E.g. manually replacing each glass block type.

### Anything Else?

Apologies if I am missing something/in the wrong place.

**Comment by me4502** [comment]
These aren’t added by worldedit, they’re just MC tags. if you want more, you can add them via a datapack

it doesn’t make sense for us to add them as it’d impact other things, and also would be opinionated
