### ISSUE TITLE
WorldEdit Crashing

### ISSUE THREAD

**Issue by Goast414** [EngineHub/WorldEdit#2659]
### WorldEdit Version

1.21.3

### Platform Version

NeoForge NEWEST

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Anytime I use the modded version of WorldEdit and i start a world, It crashes and kicks me out of the app.

### Expected Behavior

I expected it to load my world fine, but it just crashed when loading my world.

### Reproduction Steps

1. ...
2. ...

**Comment by wizjany** [comment]
fill out the template properly or at least provide a crash report.
