### ISSUE TITLE
1.20.1 Fabric version

### ISSUE THREAD

**Issue by FASTB1mc** [EngineHub/WorldEdit#2665]
### The Problem

There is no 1.20.1 fabric version of world edit on Modrinth.

### A Solution

Add it please as there is  a 1.20.1 fabric version on Curseforge, But not modrinth.

### Anything Else?

Thank you.

**Comment by wizjany** [comment]
we have no plans on uploading old versions to new distribution platforms.

**Comment by me4502** [comment]
Until Modrinth adds some way to add historic versions this is also very infeasible to do. If we upload old versions now, they’ll show up as the latest versions when they aren’t. This is a blocker for us even considering uploading old versions
