### ISSUE TITLE
Framed Corner Pillar Slope

### ISSUE THREAD

**Issue by Tbird2005** [EngineHub/WorldEdit#2668]
### The Problem

I cannot fill this gap for the life of me, nothing in the mod fits it, and im going to commit 28 billion food warcrimes at the taco bell, if this is not fixed

### A Solution

![Image](https://github.com/user-attachments/assets/ea1acef5-fa5d-4342-9394-89667470a0b4)
Make a block that fits this fricking gap or else >:(

**Comment by wizjany** [comment]
this has nothing to do with worldedit. i can only assume you got lost and are in the wrong repository.
