### ISSUE TITLE
Update for 1.21.4?

### ISSUE THREAD

**Issue by LCSOGthb** [EngineHub/WorldEdit#2670]
### WorldEdit Version

7.3.9

### Platform Version

Fabric 0.16.9

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Plugin Version

### Expected Behavior

Working on Minecraft 1.21.4

### Reproduction Steps

-

**Comment by me4502** [comment]
already done, see https://github.com/EngineHub/WorldEdit/pull/2664
