### ISSUE TITLE
Version incompatibility (bukkit 1.21 with WE v7.3.9)

### ISSUE THREAD

**Issue by WiseFoxy** [EngineHub/WorldEdit#2671]
### WorldEdit Version

7.3.8 or 7.3.9

### Platform Version

CraftBukkit 4226-Bukkit-2889b3a (MC: 1.21)

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

MC v1.21, WE v7.3.9 (tried 7.3.8 as well) that is supposed to be for 1.20.2-1.21.3.
Yet both *.8 and *.9 returns "editing on unsupported versions is disabled".

What am I doing wrong?

### Expected Behavior

WE works

### Reproduction Steps

1. Installed bukkit 1.21
2. Put WE v7.3.9 in plugins

**Comment by octylFractal** [comment]
Don't use CraftBukkit. Use Spigot or Paper.

**Comment by WiseFoxy** [comment]
Awesome response.
Well, I am here since WE claims to work with bukkit.
If it doesn't then the bukkit support should pbbly be removed and not announced, shouldn't it?

**Comment by me4502** [comment]
Bukkit is an API, of which Spigot is the implementation. CraftBukkit does not and has not existed for a decade.

It is only available as an interim dev artefact of Spigot, it's not published. Plugins are not expected to run against software that isn't even published for use. See https://madelinemiller.dev/blog/stop-using-craftbukkit/

**Comment by WiseFoxy** [comment]
Oh my, I guess I was a little outdated at this point. The article is helpful!
Pity we'd have to move to Spigot now. Inevitable tho.

Anyways thank you for such a detailed response, me4502.
