### ISSUE TITLE
Make slabs retain top/bottom orientation

### ISSUE THREAD

**Issue by Maxwellcat09** [EngineHub/WorldEdit#2672]
### The Problem

I'm a casual user of worldedit, i like building houses and such and often use slabs for the roof. Unfortunately a problem i've run in to is that using //replace on slabs (example: //replace dark_prismarine_slab red_nether_brick_slab) causes the slabs to be misaligned, all placed with the bottom orientation instead of retaining their orientation

### A Solution

Im not a programmer, but i don't think it would be impossible to change the //replace code to retain orientation of blocks if the block being replaced can oriented in the same manner (logs would retain orientation of logs, but not slabs)

**Comment by wizjany** [comment]
type applying pattern exists already.
