### ISSUE TITLE
Incompatibility with Do a Barrel Roll mod

### ISSUE THREAD

**Issue by TheWaffleLord37** [EngineHub/WorldEdit#2681]
### WorldEdit Version

7.3.10-beta-01

### Platform Version

Fabric 0.16.9

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When attempting to join a world with both the 3.8.1 version of the [Do a Barrel Roll](https://github.com/enjarai/do-a-barrel-roll) mod (the most recent version as of writing this), and the 7.3.10-beta-01 version of the World Edit mod in the mods folder, the game crashes and displays the error message: "The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_2168 net.minecraft.class_1297.method_5671()'"
Crash log provided below:
[crash-2024-12-22_13.06.15-server.txt](https://github.com/user-attachments/files/18223227/crash-2024-12-22_13.06.15-server.txt)

### Expected Behavior

Both mods to work as normal, and the game not to crash.

### Reproduction Steps

1. Have both mods in the mods folder
2. Join any single player world
3. The game crashes

**Comment by octylFractal** [comment]
That mod is bundling an outdated version of the Lucko Fabric Permissions API, please report this to them.
