### ISSUE TITLE
Load a world, Game crashes.

### ISSUE THREAD

**Issue by DoomShin** [EngineHub/WorldEdit#2682]
### WorldEdit Version

7.3.10-beta-01

### Platform Version

Fabric 0.16.9

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I tried to load the experiment world, It crashed.

### Expected Behavior

The beta version has troubleshooting.

### Reproduction Steps

Fix the crash.

**Comment by octylFractal** [comment]
Please provide the crash report.

**Comment by DoomShin** [comment]
[crash-2024-12-23_16.07.26-server.txt](https://github.com/user-attachments/files/18237639/crash-2024-12-23_16.07.26-server.txt)
Well Here you go.

**Comment by me4502** [comment]
this isn't a WorldEdit issue, you have some other mod including a copy of fabric permissions API for an earlier MC version. You need to get that other mod to fix the issue

**Comment by DoomShin** [comment]
Thanks.
