### ISSUE TITLE
No selection box. (or however it is called)

### ISSUE THREAD

**Issue by NullNobody-MNTop1** [EngineHub/WorldEdit#2688]
### WorldEdit Version

7.3.8

### Platform Version

Fabric 0.16.9

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

There is no box that highlights the selected blocks.

### Expected Behavior

The selection of blocks will result in a highlight box that shows you the selected area.

### Reproduction Steps

1. Use java 1.21.1
2. Give yourself a wooden axe by using /give command and select some blocks.

### Anything Else?

If this is not a bug but a missing feature, then I would like you to add that feature. Also, if it is just an MC ver incompatibility, I would like you to notify me about this.

**Comment by octylFractal** [comment]
There is none by default, you can try the limited version using `//drawsel` or install WorldEdit CUI, when we have releases for it.
