### ISSUE TITLE
[Fabric] Respect Semantic Versioning

### ISSUE THREAD

**Issue by halotroop2288** [EngineHub/WorldEdit#552]
**Is your feature request related to a problem? Please describe.**
Problem: WorldEdit does not respect semver, causing version comparison to be limited in Fabric.

**Describe the solution you'd like**
Switch the semicolon (used for separating the official version from the snapshot version) to a dash or a plus.

**Describe alternatives you've considered**
Omitting the snapshot version entirely would get around the problem, but it would not be a proper solution.

**Additional context**
Fabric loader checks the semantic version of the mod to compare duplicate mods in the list and choose the most up-to-date and appropriate version. With the current naming scheme, the loader cannot understand it and do its job, so the player has to figure it out for themself.
One small change could solve this issue. I don't think it's too much trouble.

Example of an error created by this problem:
``[Info: 2020-02-14 19:22:39.973713136: GameCallbacks.cpp(158)] Game/Fabric|Loader (main) Warn Mod `worldedit` (7.1.0;8e55131) does not respect SemVer - comparison support is limited.``

**Comment by wizjany** [comment]
This is already fixed.
