### ISSUE TITLE
option "no-double-slash" not working

### ISSUE THREAD

**Issue by Fchen48** [EngineHub/WorldEdit#562]
**Describe the bug**

The option `no-double-slash` doesn't affect the commands, regardless of what is set (true or false) all commands have to start with a double slash (`//`)

**To Reproduce**

1. set `no-double-slash` to `true`
2. restart server
3. try commands like `/pos1`, `/set 1`, ...

**Expected behavior**

Commands should work with a single slash.

**Screenshots**

![image](https://user-images.githubusercontent.com/6956592/75710957-d3cd9600-5cc5-11ea-9de5-8a906383cd17.png)

**Additional context**

Nothing more to say.

**Comment by wizjany** [comment]
This is intentional, the setting was removed. Only issue here is that the default configs still ship it.

**Comment by Fchen48** [comment]
Why was this removed? This option was great!

**Comment by wizjany** [comment]
1) you're probably about the only person who used it
2) it was a massive hack, relying on broken platform-dependent redirection
3) we switched to a new command system and saw no reason to re-write the "feature" in.

**Comment by Fchen48** [comment]
Ok, thanks for clarifying.

**Comment by wizjany** [comment]
reopening as reminder to remove the option from configs. feel free to unsubscribe.
