### ISSUE TITLE
Korean language is not showing correctly

### ISSUE THREAD

**Issue by imirochi** [EngineHub/WorldEdit#567]
**Describe the bug**
Korean Lang files has not showing correctly due to Unicode problem.

**To Reproduce**
Just change minecraft language to korean, and type any worldedit commend.
https://imgur.com/a/oDpsIwd
here's screenshot.

**Expected behavior**
Unicode problem. and I fixed https://pastebin.com/ZFRiKdvH

**Screenshots**

https://imgur.com/a/oDpsIwd
https://pastebin.com/ZFRiKdvH

**Additional context**

**Comment by octylFractal** [comment]
Is your fix the same as https://github.com/EngineHub/WorldEdit/commit/624b3a449b5746cee84557992b9b217ac135cf50?

**Comment by imirochi** [comment]
I dunno what that is. I just convert lang files via https://www.branah.com/unicode-converter.
But I think that will works too.

**Comment by imirochi** [comment]
I just downloaded latest build from jenkins, and it fixed!

**Comment by octylFractal** [comment]
I'll consider this fixed then.
